qx.$$packageData['158948264deb']={"resources":{"qx/icon/Tango/16/actions/address-book-new.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/application-exit.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/appointment-new.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/bookmark-new.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/check-spelling.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/contact-new.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/dialog-apply.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/dialog-cancel.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/dialog-close.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/dialog-ok.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/document-new.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/document-open-recent.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/document-open.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/document-print-preview.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/document-print.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/document-properties.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/document-revert.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/document-save-as.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/document-save.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/document-send.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-clear.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-copy.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-cut.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-delete.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-find.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-paste.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-redo.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-select-all.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-undo.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/folder-new.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-indent-less.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-indent-more.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-justify-center.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-justify-fill.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-justify-left.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-justify-right.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-text-bold.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-text-direction-ltr.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-text-direction-rtl.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-text-italic.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-text-strikethrough.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/format-text-underline.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/go-bottom.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/go-down.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/go-first.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/go-home.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/go-last.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/go-next.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/go-previous.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/go-top.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/go-up.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/help-about.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/help-contents.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/help-faq.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/insert-image.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/insert-link.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/insert-text.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/list-add.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/list-remove.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/mail-forward.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/mail-mark-important.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/mail-mark-junk.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/mail-mark-read.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/mail-mark-unread.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/mail-message-new.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/mail-receive.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/mail-reply-all.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/mail-reply-sender.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/mail-send.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/media-eject.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/media-playback-pause.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/media-playback-start.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/media-playback-stop.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/media-record.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/media-seek-backward.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/media-seek-forward.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/media-skip-backward.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/media-skip-forward.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/object-flip-horizontal.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/object-flip-vertical.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/object-rotate-left.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/object-rotate-right.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/process-stop.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/system-log-out.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/system-run.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/system-search.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/system-shutdown.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/view-fullscreen.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/view-refresh.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/view-restore.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/view-sort-ascending.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/view-sort-descending.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/window-close.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/window-new.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/zoom-fit-best.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/zoom-in.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/zoom-original.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/zoom-out.png":[16,16,"png","qx"],"qx/icon/Tango/16/apps/utilities-help.png":[16,16,"png","qx"],"qx/static/blank.html":"qx"}};
(function(){var bd="qx.event.type.Data",bc="Boolean",bb="qx.event.type.Event",ba="display",Y="mousedown",X="none",W="qx.client",V="appear",U="mouseup",T="losecapture",bX="xhtml",bW="_applyUseUndoRedo",bV="focusOut",bU="height",bT="_applyMessengerMode",bS=")",bR="InsertParagraphOnLinebreak",bQ="gecko",bP="repeat",bO="undoRedoState",bk="div",bl="messengerContent",bi="focused",bj="Function",bg="__n",bh="_applyInsertParagraphOnLinebreak",be="PostProcess",bf="width",bo="_applyInsertLinebreakOnCtrlEnter",bp="ContentType",bx="px",bv="url(",bE="DOMNodeRemoved",bz="cursorContext",bK="String",bI="htmlarea",br="ready",bN="loadingError",bM="MessengerMode",bL="zIndex",bq="left",bt="UseUndoRedo",bu="__p",bw="top",by="_applyContentType",bA="qx.ui.embed.HtmlArea",bF="mshtml",bJ="block",bm="position",bn="readyAfterInvalid",bs="InsertLinebreakOnCtrlEnter",bD="contextmenu",bC="set",bB="qx/static/blank.gif",bH="_applyPostProcess",bG="absolute";
qx.Class.define(bA,{extend:qx.ui.core.Widget,construct:function(n,o,p){arguments.callee.base.call(this);
this._setLayout(new qx.ui.layout.Grow);
this.__q();
this.__m={content:n,styleInfo:o,source:p};
qx.event.Registration.addListener(document.body,Y,this.block,this,true);
qx.event.Registration.addListener(document.body,U,this.release,this,true);
qx.event.Registration.addListener(document.body,T,this.release,this,true);
this.__n=this._createBlockerElement();
this.getContainerElement().add(this.__n);
this.__o={};
},events:{"loadingError":bd,"messengerContent":bd,"cursorContext":bd,"ready":bb,"readyAfterInvalid":bb,"focused":bb,"focusOut":bb,"contextmenu":bd,"undoRedoState":bd},statics:{isBlockNode:function(N){return qx.bom.htmlarea.HtmlArea.isBlockNode(N);
},isParagraphParent:function(g){return qx.bom.htmlarea.HtmlArea.isParagraphParent(g);
}},properties:{contentType:{check:bK,init:bX,apply:by},messengerMode:{check:bc,init:false,apply:bT},insertParagraphOnLinebreak:{check:bc,init:true,apply:bh},insertLinebreakOnCtrlEnter:{check:bc,init:true,apply:bo},postProcess:{check:bj,nullable:true,init:null,apply:bH},useUndoRedo:{check:bc,init:true,apply:bW},appearance:{refine:true,init:bI}},members:{__p:null,__o:null,__n:null,__m:null,_applyContentType:function(Q,R){if(this.__p!=null){this.__p.setContentType(Q);
}else{this.__o[bp]=Q;
}},_applyMessengerMode:function(D,E){if(this.__p!=null){this.__p.setMessengerMode(D);
}else{this.__o[bM]=D;
}},_applyInsertParagraphOnLinebreak:function(d,f){if(this.__p!=null){this.__p.setInsertParagraphOnLinebreak(d);
}else{this.__o[bR]=d;
}},_applyInsertLinebreakOnCtrlEnter:function(L,M){if(this.__p!=null){this.__p.setInsertLinebreakOnCtrlEnter(L);
}else{this.__o[bs]=L;
}},_applyPostProcess:function(B,C){if(this.__p!=null){this.__p.setPostProcess(B);
}else{this.__o[be]=B;
}},_applyUseUndoRedo:function(J,K){if(this.__p!=null){this.__p.setUseUndoRedo(J);
}else{this.__o[bt]=J;
}},_createBlockerElement:function(){var P=new qx.html.Element(bk);
P.setStyle(bL,20);
P.setStyle(bm,bG);
P.setStyle(ba,X);
if(qx.core.Variant.isSet(W,bF)){P.setStyles({backgroundImage:bv+qx.util.ResourceManager.getInstance().toUri(bB)+bS,backgroundRepeat:bP});
}return P;
},__q:function(){this.addListenerOnce(V,this.__r);
},__r:function(){var y=this.getContentElement().getDomElement();
this.__p=new qx.bom.htmlarea.HtmlArea(y,this.__m.content,this.__m.styleInfo,this.__m.source);
this.__s();
this.__t();

if(qx.core.Variant.isSet(W,bQ)){this.__w();
}this.addListener(V,this.forceEditable);
},__s:function(){for(var z in this.__o){this.__p[bC+z](this.__o[z]);
}},__t:function(){this.__p.addListener(br,this.__u,this);
this.__p.addListener(bn,this.__u,this);
this.__p.addListener(bi,this.__u,this);
this.__p.addListener(bV,this.__u,this);
this.__p.addListener(bN,this.__v,this);
this.__p.addListener(bz,this.__v,this);
this.__p.addListener(bD,this.__v,this);
this.__p.addListener(bO,this.__v,this);
this.__p.addListener(bl,this.__v,this);
},__u:function(e){var c=e.clone();
this.fireEvent(c.getType());
},__v:function(e){var a=e.clone();
this.fireDataEvent(a.getType(),e.getData());
},__w:function(){var self=this;
var H=this.getContainerElement().getDomElement();
qx.bom.Event.addNativeListener(H,bE,qx.event.GlobalError.observeMethod(function(e){self.__p.invalidateEditor();
}));
},renderLayout:function(q,top,r,s){arguments.callee.base.call(this,q,top,r,s);
var u=bx;
var t=this.getInsets();
this.__n.setStyle(bq,t.left+u);
this.__n.setStyle(bw,t.top+u);
this.__n.setStyle(bf,(r-t.left-t.right)+u);
this.__n.setStyle(bU,(s-t.top-t.bottom)+u);
},getIframeObject:function(){return this.__p!=null?this.__p.getIframeObject():null;
},getCommandManager:function(){return this.__p!=null?this.__p.getCommandManager():null;
},setValue:function(w){if(this.__p!=null){this.__p.setValue(w);
}},getValue:function(){return this.__p!=null?this.__p.getValue():null;
},getComputedValue:function(S){return this.__p!=null?this.__p.getHtml(S):null;
},getCompleteHtml:function(){return this.__p!=null?this.__p.getCompleteHtml():null;
},getContentDocument:function(){return this.__p!=null?this.__p.getContentDocument():null;
},getContentBody:function(){return this.__p!=null?this.__p.getContentBody():null;
},getContentWindow:function(){return this.__p!=null?this.__p.getContentWindow():null;
},getWords:function(m){return this.__p!=null?this.__p.getWords(m):null;
},getWordsWithElement:function(){return this.__p!=null?this.__p.getWordsWithElement():null;
},getTextNodes:function(){return this.__p!=null?this.__p.getTextNodes():null;
},isReady:function(){return this.__p!=null?this.__p.isReady():false;
},forceEditable:function(){if(this.__p!=null){this.__p.forceEditable();
}},isLoaded:function(){return this.__p!=null?this.__p.isLoaded():false;
},setEditable:function(x){if(this.__p!=null){this.__p.setEditable(x);
}},getEditable:function(){return this.__p!=null?this.__p.getEditable():false;
},isEditable:function(){return this.__p!=null?this.__p.isEditable():false;
},insertHtml:function(b){return this.__p!=null?this.__p.insertHtml(b):false;
},removeFormat:function(){return this.__p!=null?this.__p.removeFormat():false;
},setBold:function(){return this.__p!=null?this.__p.setBold():false;
},setItalic:function(){return this.__p!=null?this.__p.setItalic():false;
},setUnderline:function(){return this.__p!=null?this.__p.setUnderline():false;
},setStrikeThrough:function(){return this.__p!=null?this.__p.setStrikeThrough():false;
},setFontSize:function(G){return this.__p!=null?this.__p.setFontSize(G):false;
},setFontFamily:function(O){return this.__p!=null?this.__p.setFontFamily(O):false;
},setTextColor:function(h){return this.__p!=null?this.__p.setTextColor(h):false;
},setTextBackgroundColor:function(l){return this.__p!=null?this.__p.setTextBackgroundColor(l):false;
},setJustifyLeft:function(){return this.__p!=null?this.__p.setJustifyLeft():false;
},setJustifyCenter:function(){return this.__p!=null?this.__p.setJustifyCenter():false;
},setJustifyRight:function(){return this.__p!=null?this.__p.setJustifyRight():false;
},setJustifyFull:function(){return this.__p!=null?this.__p.setJustifyFull():false;
},insertIndent:function(){return this.__p!=null?this.__p.insertIndent():false;
},insertOutdent:function(){return this.__p!=null?this.__p.insertOutdent():false;
},insertOrderedList:function(){return this.__p!=null?this.__p.insertOrderedList():false;
},insertUnorderedList:function(){return this.__p!=null?this.__p.insertUnorderedList():false;
},insertHorizontalRuler:function(){return this.__p!=null?this.__p.insertHorizontalRuler():false;
},insertImage:function(I){return this.__p!=null?this.__p.insertImage(I):false;
},insertHyperLink:function(v){return this.__p!=null?this.__p.insertHyperLink(v):false;
},removeBackgroundColor:function(){return this.__p!=null?this.__p.removeBackgroundColor():false;
},setBackgroundColor:function(A){return this.__p!=null?this.__p.setBackgroundColor(A):false;
},removeBackgroundImage:function(){return this.__p!=null?this.__p.removeBackgroundImage():false;
},setBackgroundImage:function(i,j,k){return this.__p!=null?this.__p.setBackgroundImage(i,j,k):false;
},selectAll:function(){return this.__p!=null?this.__p.selectAll():false;
},undo:function(){return this.__p!=null?this.__p.undo():false;
},redo:function(){return this.__p!=null?this.__p.redo():false;
},resetHtml:function(){if(this.__p!=null){this.__p.resetHtml();
}},getHtml:function(F){return this.__p!=null?this.__p.getHtml(F):null;
},containsOnlyPlaceholder:function(){return this.__p!=null?this.__p.containsOnlyPlaceHolder():false;
},getContextInformation:function(){return this.__p!=null?this.__p.getContextInformation():null;
},getSelection:function(){return this.__p!=null?this.__p.getSelection():null;
},getSelectedText:function(){return this.__p!=null?this.__p.getSelectedText():null;
},getSelectedHtml:function(){return this.__p!=null?this.__p.getSelectedHtml():null;
},clearSelection:function(){if(this.__p!=null){this.__p.clearSelection();
}},getRange:function(){return this.__p.getRange();
},saveRange:function(){this.__p.saveRange();
},getSavedRange:function(){return this.__p.getSavedRange();
},resetSavedRange:function(){this.__p.resetSavedRange();
},getFocusNode:function(){return this.__p!=null?this.__p.getFocusNode():null;
},block:function(){this.__n.setStyle(ba,bJ);
},release:function(){this.__n.setStyle(ba,X);
}},destruct:function(){this._disposeObjects(bg,bu);
this.__o=this.__m=null;
qx.event.Registration.removeListener(document.body,Y,this.block,this,true);
qx.event.Registration.removeListener(document.body,U,this.release,this,true);
qx.event.Registration.removeListener(document.body,T,this.release,this,true);
}});
})();
(function(){var bI="qx.client",bH="Command",bG="mshtml",bF="Custom",bE="Content",bD="Internal",bC="webkit",bB="mousedown",bA="backgroundimage",bz="table",cy="backgroundcolor",cx="td",cw="img",cv="gecko",cu="mouseup",ct="keypress",cs="qx.bom.htmlarea.HtmlArea.debug",cr="on",cq="undo",cp="backgroundColor",bP="undoRedoState",bQ="__x",bN="pageup",bO="b",bL="control",bM="end",bJ="right",bK="insertorderedlist",bT="insertunorderedlist",bU="pagedown",cd="home",cb="backgroundImage",ch="backgroundRepeat",cf="a",cl="y",cj="backgroundPosition",bW="justifyright",co="redo",cn="k",cm="qx.bom.htmlarea.manager.UndoRedo",bV="left",bY="i",ca="u",cc="inserthyperlink",ce="Redo",cg="enter",ci="insertimage",ck="inserthtml",bR="z",bS="down",bX="up";
qx.Class.define(cm,{extend:qx.core.Object,construct:function(cG,cH){arguments.callee.base.call(this);
this.__x=cG;
this.__y=cH;
this.__z=[];
this.__A=[];
this._commands=null;
this.__B=null;
this.__C={};
this.__D={command:true,content:true,custom:true};
this.__bc();
this.__E=qx.lang.Function.bind(this._handleKeyPress,this);
this.__F=qx.lang.Function.bind(this._handleMouseUp,this);

if(qx.core.Variant.isSet(bI,bG)){this.__G=qx.lang.Function.bind(this._handleMouseDown,this);
}},members:{__H:false,__I:false,__J:false,__D:null,__C:null,__x:null,__B:null,__z:null,__A:null,__y:null,__E:null,__F:null,__G:null,__K:null,setContentDocument:function(D){this.__B=D;
this.__x.setContentDocument(D);
qx.event.Registration.addListener(D.body,ct,this.__E,this);
qx.event.Registration.addListener(D.body,cu,this.__F,this);

if(qx.core.Variant.isSet(bI,bG)){qx.event.Registration.addListener(D.body,bB,this.__G,this,true);
}},insertParagraphOnLinebreak:function(){return this.__x.insertParagraphOnLinebreak();
},execute:function(bu,bv){var bw;
bu=bu.toLowerCase();
if(this._commands[bu]){if(this._commands[bu].passthrough){bw=this.__x.execute(bu,bv);
}else{bw=this[bu].call(this);
}}else{if(qx.core.Variant.isSet(bI,bG)||qx.core.Variant.isSet(bI,bC)){this.__bd(bu,bv,this.__x.getCommandObject(bu));
bw=this.__x.execute(bu,bv);
if(!bw){this.__z.pop();
}}else{bw=this.__x.execute(bu,bv);

if(bw){this.__bd(bu,bv,this.__x.getCommandObject(bu));
}}
if(bu==cq&&this.__z.length==0){this.__I=false;
this.__bl();
}else if(bu==co&&this.__A.length==0){this.__H=false;
this.__bl();
}}this.__J=false;
return bw;
},addUndoStep:function(W,X,Y){this.__bd(W,X,Y);
},registerHandler:function(y,z,A,B){this.__C[y]={undo:z,redo:A,context:B};
},isUndoPossible:function(){return this.__I;
},undo:function(){var cE;

if(this.__J){this.__bf();
}if(this.__z.length>0){var cD=this.__z.pop();

if(this.__D[cD.actionType.toLowerCase()]){switch(cD.actionType){case bH:cE=this.__M(cD);
break;
case bE:cE=this.__Q(cD);
break;
case bD:cE=this.__P(cD);
break;
case bF:cE=this.__L(cD);
break;
}}else if(this.__C[cD.actionType]){var cC=this.__C[cD.actionType];
cE=cC.undo.call(cC.context?cC.context:this,cD);
this.__bh(cD);
}else{this.error("actionType "+cD.actionType+" is not managed! Please provide a handler method!");
}this.__H=true;
this.__bl();
return cE;
}},__L:qx.core.Variant.select("qx.client",{"mshtml|webkit":function(bi){var bj=this.__B.body.innerHTML;
var bl=bi.content;
this.__B.body.innerHTML=bl;
var bk=bi;
bk.content=bj;
this.__bh(bk);
return true;
},"default":function(E){var I=E;
var H=qx.bom.element.Style;
switch(E.command){case "backgroundcolor":I.parameter=[H.get(this.__B.body,"backgroundColor")];
break;
case "backgroundimage":I.parameter=[H.get(this.__B.body,"backgroundImage"),H.get(this.__B.body,"backgroundRepeat"),H.get(this.__B.body,"backgroundPosition")];
break;
}this.__bh(I);
if(E.command=="inserthyperlink"){if(qx.core.Variant.isSet("qx.client","gecko")){var G="qx_link"+this.__x.__hyperLinkId;
var F=this.__B.getElementById(G);

if(F){F.parentNode.removeChild(F);
return true;
}else{return false;
}}}else{return this.__x.execute(E.command,E.value);
}}}),__M:qx.core.Variant.select("qx.client",{"mshtml|webkit":function(bd){},"default":function(P){this.__bh(P);

if(qx.core.Variant.isSet("qx.client","gecko")){if(P.command=="inserthtml"&&P.value==qx.bom.htmlarea.HtmlArea.EMPTY_DIV&&this.__N("inserthtml","insertParagraph")){this.__O();
}}return this.__R();
}}),__N:function(p,q){if(this.__z.length>0){var r=this.__z[this.__z.length-1];
return (r.command==p&&r.value==q);
}return false;
},__O:function(){this.__R();

if(this.__z.length>0){var g=this.__z.pop();
this.__bh(g);
}},__P:function(U){this.__bh(U);
return this.__R();
},__Q:qx.core.Variant.select("qx.client",{"gecko":function(ba){this.__bh(ba);

try{return this.__R();
}catch(k){{};
}},"mshtml|webkit":function(C){},"default":function(bm){this.__bh(bm);
return this.__R();
}}),__R:function(){try{return this.__B.execCommand("Undo",false,null);
}catch(e){return false;
}},isRedoPossible:function(){return this.__H;
},redo:function(){if(this.__H){var S;
if(this.__A.length>0){var T=this.__A.pop();

if(this.__D[T.actionType.toLowerCase()]){switch(T.actionType){case bH:S=this.__T(T);
break;
case bE:S=this.__ba(T);
break;
case bD:S=this.__Y(T);
break;
case bF:S=this.__S(T);
break;
}}else if(this.__C[T.actionType]){var R=this.__C[T.actionType];
S=R.redo.call(R.context?R.context:this,T);
this.__bg(T);
}else{this.error("actionType "+T.actionType+" is not managed! Please provide a handler method!");
}this.__I=true;
this.__bl();
}return S;
}},__S:qx.core.Variant.select("qx.client",{"mshtml|webkit":function(bn){var bo=this.__B.body.innerHTML;
var bq=bn.content;
this.__B.body.innerHTML=bq;
var bp=bn;
bp.content=bo;
this.__bg(bp);
return true;
},"default":function(s){this.__bg(s);
return this.__bb();
}}),__T:qx.core.Variant.select("qx.client",{"mshtml|webkit":function(cA){},"default":function(cK){this.__bg(cK);
var cL=this.__bb();

if(qx.core.Variant.isSet("qx.client","gecko")){if(this.__U("inserthtml",qx.bom.htmlarea.HtmlArea.EMPTY_DIV)){var cM=this.__V();
this.__W();

if(cM!=null){this.__X(cM);
}}}return cL;
}}),__U:function(br,bs){if(this.__A.length>0){var bt=this.__A[this.__A.length-1];
return (bt.command==br&&bt.value==bs);
}return false;
},__V:function(){if(this.__y==null){return null;
}var bb=this.__y.getSelection();
var bc=bb?bb.focusNode:null;

if(bc==null){return null;
}
try{while(bc.nodeName.toLowerCase()!="p"){bc=bc.parentNode;

if(!bc||qx.dom.Node.isNodeName(bc,"body")){return null;
}}}catch(h){return null;
}
if(bc!=null&&qx.dom.Node.isNodeName(bc,"p")){return bc;
}else{return null;
}},__W:function(){var cz=this.__A.pop();
this.__bg(cz);
this.__bb();
},__X:qx.core.Variant.select("qx.client",{"gecko":function(be){if(be==this.__y.getContentBody().lastChild){return;
}var bh=be.firstChild;

while(bh.firstChild){bh=bh.firstChild;
}var bf=this.__y.getSelection();
var bg=this.__y.getRange();

if(bf&&bg){bg.selectNode(bh);
bf.addRange(bg);
bg.collapse(true);
}},"default":qx.lang.Function.empty}),__Y:function(f){this.__bg(f);
return this.__bb();
},__ba:qx.core.Variant.select(bI,{"mshtml|webkit":function(l){},"default":function(cB){this.__bg(cB);
return this.__bb();
}}),__bb:function(){try{return this.__B.execCommand(ce,false,null);
}catch(e){return false;
}},__bc:function(){this._commands={undo:{passthrough:false},redo:{passthrough:false}};
this.__x.getCommandObject(cy).customUndo=true;
this.__x.getCommandObject(bA).customUndo=true;

if(qx.core.Variant.isSet(bI,cv)){}},__bd:qx.core.Variant.select(bI,{"mshtml|webkit":function(u,v,w){var x=this.getUndoRedoObject();
x.commandObject=w;
x.command=u;
x.value=v;
x.actionType=bF;
x.content=this.__B.body.innerHTML;
this.__be(x);
},"default":function(J,K,L){if(this.__y==null){return;
}var N=this.getUndoRedoObject();
N.commandObject=L;
N.command=J;
N.value=K;
N.actionType=bF;
var M=this.__y.getSelection();

if(L.customUndo){var O=[];

switch(J){case cy:O.push(qx.bom.element.Style.get(this.__B.body,cp));
break;
case bA:O.push(qx.bom.element.Style.get(this.__B.body,cb),qx.bom.element.Style.get(this.__B.body,ch),qx.bom.element.Style.get(this.__B.body,cj));
break;
case cc:if(M&&!M.isCollapsed){N.actionType=bH;
}break;
}N.parameter=O;
}else{if(qx.core.Variant.isSet(bI,cv)){if(M&&M.isCollapsed){switch(J){case bK:case bT:case bW:case ck:case ci:N.actionType=bH;
break;
default:return;
}}else{N.actionType=bH;
}}else{N.actionType=bH;
}}this.__be(N);
}}),__be:function(V){if(this.__J){this.__bf();
}this.__bg(V);
this.__H=false;
this.__A=[];
this.__bl();
},__bf:function(){var cI=this.__z[this.__z.length-1];

if(cI==null||cI.actionType!=bE){var cJ=this.getUndoRedoObject();
cJ.actionType=bE;

if(qx.core.Variant.isSet(bI,bG)||qx.core.Variant.isSet(bI,bC)){cJ.content=this.__K;
cJ.actionType=bF;
this.__K=null;
}this.__bg(cJ);
this.__J=false;
}},getUndoRedoObject:function(){return {actionType:null,commandObject:null,command:null,value:null,parameter:null,range:null,marker:null,content:null};
},__bg:function(m){if(false&&qx.core.Setting.get(cs)==cr){this.debug("ADD TO UNDO STACK");
this.debug(m.actionType+" "+m.command+" "+m.value);
}this.__z.push(m);
},__bh:function(n){if(false&&qx.core.Setting.get(cs)==cr){this.debug("ADD TO REDO STACK");
this.debug(n.actionType+" "+n.command+" "+n.value);
}this.__A.push(n);
},_handleKeyPress:function(e){var bx=e.getKeyIdentifier().toLowerCase();
var by=e.isCtrlPressed();

switch(bx){case bL:case bV:case bJ:case bX:case bS:case bN:case bU:case cd:case bM:case cg:break;
case cf:case bO:case bY:case ca:case cn:case cl:case bR:if(!by){this.__bi();
}break;
default:this.__H=false;
this.__A=[];
this.__bi();
}},__bi:function(){if(!this.__J){this.__J=true;
this.__I=true;
if(qx.core.Variant.isSet(bI,bG)||qx.core.Variant.isSet(bI,bC)){this.__K=this.__B.body.innerHTML;
}this.__bl();
}},__bj:null,_handleMouseDown:qx.core.Variant.select(bI,{"mshtml":function(e){var t=e.getOriginalTarget();

if(qx.dom.Node.isElement(t)&&(qx.dom.Node.isNodeName(t,cw)||qx.dom.Node.isNodeName(t,bz))){this.__bj={node:t,content:t.outerHTML};
}else{this.__bj=null;
}},"default":function(e){return true;
}}),_handleMouseUp:qx.core.Variant.select(bI,{"gecko":function(e){if(this.__y==null){return;
}var b=this.__y.getSelection();

if(!b){this.__bj=null;
return;
}var a=b.anchorNode;
var c=a.childNodes[b.anchorOffset];
if(qx.dom.Node.isNodeName(c,cw)){if(this.__bj==null){this.__bj=c.cloneNode(true);
}else{if(this.__bj.style.width!=c.style.width||this.__bj.style.height!=c.style.height){this.__bk();
this.__bj=c.cloneNode(true);
}}}else if(qx.dom.Node.isNodeName(a,cx)||qx.dom.Node.isNodeName(a.parentNode,cx)){var d=a.parentNode;

while(qx.dom.Node.isNodeName(d,bz)){d=d.parentNode;
}if(this.__bj==null){this.__bj=d.cloneNode(true);
}else{qx.event.Timer.once(function(){if(d.style.width!=this.__bj.style.width||d.style.height!=this.__bj.style.height||d.innerHTML!=this.__bj.innerHTML){this.__bk();
this.__bj=d.cloneNode(true);
}},this,0);
}}else{this.__bj=null;
}},"default":function(e){var cF=e.srcElement;

if(this.__bj!=null){if(cF.nodeType==1){if(cF==this.__bj.node){if(cF.outerHTML!=this.__bj.content){this.__bj.content=cF.outerHTML;
this.__bk();
}}else{for(var i=0,j=cF.childNodes.length;i<j;i++){if(cF.childNodes[i]==this.__bj.node){if(cF.childNodes[i].outerHTML!=this.__bj.content){this.__bj.content=cF.childNodes[i].outerHTML;
this.__bk();
}}}}}else{this.__bj=null;
}}}}),__bk:qx.core.Variant.select(bI,{"mshtml|webkit":function(){this.__bd(bD,null,null);
},"default":function(){var Q=this.getUndoRedoObject();
Q.actionType=bD;
this.__bg(Q);
}}),__bl:function(){qx.event.Timer.once(function(e){if(this.__y!=null){var o={undo:this.isUndoPossible()?0:-1,redo:this.isRedoPossible()?0:-1};
this.__y.fireDataEvent(bP,o);
}},this,200);
}},destruct:function(){try{qx.event.Registration.removeListener(this.__B.body,ct,this.__E);
qx.event.Registration.removeListener(this.__B,cu,this.__F);

if(qx.core.Variant.isSet(bI,bG)){qx.event.Registration.removeListener(this.__B,bB,this.__G);
}}catch(e){}this._disposeObjects(bQ);
this.__y=this.__z=this.__A=this._commands=this.__B=null;
this.__D=this.__C=null;
}});
})();
(function(){var fv="qx.client",fu="",ft="mshtml",fs="gecko",fr="qx.event.type.Data",fq="enter",fp="qx.event.type.Event",fo=" ",fn='"',fm="left",ed="Boolean",ec="text-align",eb="right",ea="qx.bom.htmlarea.HtmlArea.debug",dY="on",dX="inserthtml",dW="string",dV="italic",dU="body",dT="underline",fC="old_id",fD="b",fA="loadingError",fB="contextmenu",fy="pageup",fz="end",fw="div",fx='On',fE="redo",fF="i",eU="opera",eT="backspace",eW="bold",eV="mouseup",eY="y",eX="down",fb="style",fa="100%",eS='</head>',eR='<head>',ci="k",cj=":",ck='redo',cl='Off',cn="g",co="keypress",cp=";",cq="undo",cr="text-decoration",cs="pagedown",fT="justify",fS="center",fR='</style>',fQ="u",fX="focus",fW="backgroundimage",fV="click",fU='<style type="text/css">',ga="up",fY="blur",di="None",dj="control",dg="delete",dh="'",dm=">",dn='</body></html>',dk="line-through",dl="z",de="keydown",df="keyup",cL="backgroundcolor",cK="focusout",cN="webkit",cM="mshtml|opera",cH="-",cG="backgroundColor",cJ="li",cI='undo',cF="<br class='webkit-block-placeholder' />",cE="textbackgroundcolor",dt="Function",du="fontSize",dv="textcolor",dw="br",dp="home",dq="<",dr="focused",ds="fontFamily",dx="load",dy="setUnderline",cW="backgroundPosition",cV="<!--",cU="transparent",cT='/www.w3.org/1999/xhtml" xml:lang="en" lang="en">',cS="'>",cR='underline',cQ='bold',cP="&copy;",db="ul",da="cursorContext",dz="readyAfterInvalid",dA="styleWithCSS",dB=" />",dC="id",dD="setBold",dE="P",dF="<P>&nbsp;</P>",dG="</",dH="qx/static/blank.html",dI="&gt;",em='="',ek="paddingLeft",ej="X",ei="#",eq="backgroundRepeat",ep="insertimage",eo="a",en="&amp;",et="removeformat",es="marginLeft",eN="ready",eO="<p>&nbsp;</p>",eL='DOCTYPE html PUBLIC "-/',eM="outline",eJ=" html, body {overflow-x: visible; } ",eK='<body>',eH="insertorderedlist",eI='body { font-size:100.01%; font-family:Verdana, Geneva, Arial, Helvetica, sans-serif; background-color:transparent; overflow:visible; background-image:none; margin:0px; padding:5px; } ',eP="font-family",eQ="hideFocus",ff="none",fe='/DTD XHTML 1.0 Transitional/',fh='<html xmlns="http:/',fg="S",fj="fontsize",fi="setItalic",fl="font-style",fk="xhtml",fd="focusOut",fc="justifyleft",fM="paddingTop",fN="marginBottom",fO='<title></title><meta http-equiv="Content-type" content="text/html; charset=UTF-8" />',fP="Control",fI='/W3C/',fJ="placeholder",fK='size',fL="backgroundImage",fG="marginTop",fH="> ",ch=" { ",cg="__bo",cf="font-weight",ce="LI",cd='italic',cc='<!',cb="off",ca="&quot;",bY="marginRight",bX="STYLE",cv="justifyfull",cw="inserthyperlink",ct="<br />",cu='html { margin:0px; padding:0px; } ',cz="<br>",cA='/EN" "http:/',cx="justifycenter",cy="<br /><div id='placeholder'></div>",cC="useCSS",cD="object",eu="strikethrough",er="font-size",eC="indent",ey="text/html",eg="true",ee="1.9",cO=' style="',eh="messengerContent",cY="insertunorderedlist",cX="Text",dL="&lt;",dM="inserthorizontalrule",dN='<br/><div class="placeholder"></div>',dO="selectall",dP="String",dQ=" SCRIPT STYLE DIV SPAN TR TD TBODY TABLE EM STRONG FONT A P B I U STRIKE H1 H2 H3 H4 H5 H6 ",dR="justifyright",dS='/www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">',dJ="ol",dK="//text()[string-length(normalize-space(.))>0]",ef="outdent",eB="fontfamily",eA="<body style='",ez="qx.bom.htmlarea.HtmlArea",eG="paddingBottom",eF="$",eE="-->",eD=" }",ew="paddingRight",ev='html { width:100%; height:100%; margin:0px; padding:0px; overflow-y:auto; overflow-x:auto; } ',cB="Off",dd='p { margin:0px; padding:0px; }',dc='body { font-size: 100.01%; font-family:Verdana, Geneva, Arial, Helvetica, sans-serif; width:100%; height:100%; background-color:transparent; overflow:auto; background-image:none; margin:0px; padding:5px; } ';
qx.Class.define(ez,{extend:qx.core.Object,construct:function(bG,bH,bI,bJ){arguments.callee.base.call(this);
var bL=bJ||qx.util.ResourceManager.getInstance().toUri(dH);
this.__bI(bG);
this.__bJ();
this._createAndAddIframe(bL);
this._addIframeLoadListener();
this.__bm=qx.bom.htmlarea.HtmlArea.__bp(bI);
if(typeof bH===dW){this.__bn=bH;
}if(qx.core.Variant.isSet(fv,eU)){var bK=qx.dom.Node.getWindow(bG);
var bM=qx.event.Registration.getManager(bK).getHandler(qx.event.handler.Keyboard);
bM._keyCodeToIdentifierMap[35]=ei;
bM._keyCodeToIdentifierMap[45]=cH;
bM._keyCodeToIdentifierMap[112]=dE;
bM._keyCodeToIdentifierMap[115]=fg;
bM._keyCodeToIdentifierMap[120]=ej;
}this.__bo=this.__bS();
},events:{"load":fp,"loadingError":fr,"messengerContent":fr,"cursorContext":fr,"ready":fp,"readyAfterInvalid":fp,"focused":fp,"focusOut":fp,"contextmenu":fr,"undoRedoState":fr},statics:{simpleLinebreak:cz,EMPTY_DIV:"<div></div>",GetWordsRegExp:/([^\u0000-\u0040\u005b-\u005f\u007b-\u007f]|['])+/g,CleanupWordsRegExp:/[\u0000-\u0040]/gi,hotkeyInfo:{bold:{method:dD},italic:{method:fi},underline:{method:dy},undo:{method:cq},redo:{method:fE}},__bp:function(V){if(V==null||V==fu){return fu;
}else if(typeof V==cD){var W=fu;

for(var i in V){W+=i+ch+V[i]+eD;
}return W;
}else{return V;
}},__bq:function(bp){var bq={};
var a=bp.split(cp);
var i;

for(i=0;i<a.length;i++){var br=a[i],bs=br.indexOf(cj);

if(bs===-1){continue;
}var name=qx.lang.String.trim(br.substring(0,bs));
var bt=qx.lang.String.trim(br.substring(bs+1,br.length));

if(name&&bt){bq[name]=bt;
}}return bq;
},__br:function(hg,hh,hi,hj){var ho=[];

switch(hg.nodeType){case 1:case 11:var i;
var hm=hg.tagName.toLowerCase();
var hq={};
var hk={};
var closed=(!(hg.hasChildNodes()||qx.bom.htmlarea.HtmlArea.__bs(hg)));

if(hh){if(qx.core.Variant.isSet(fv,ft)){if(hm==fw&&hg.className&&hg.className==fJ){for(i=hg.firstChild;i;i=i.nextSibling){ho.push(qx.bom.htmlarea.HtmlArea.__br(i,true,hi,hj));
}return ho.join(fu);
}}var hp=hg.attributes;
var hn=hp.length;
var a;

for(i=0;i<hn;i++){a=hp[i];
if(!a.specified){continue;
}var name=qx.dom.Node.getName(a);
var hr=a.nodeValue;
if(/(_moz|contenteditable)/.test(name)){continue;
}
if(name!=fb){if(qx.bom.client.Engine.MSHTML){if(name==dC&&hg.getAttribute(fC)){hr=hg.getAttribute(fC);
}else if(!isNaN(hr)){hr=hg.getAttribute(name);
}else{hr=a.nodeValue;
}}else{hr=a.nodeValue;
}}else{hr=hg.style.cssText;
}
if(/(_moz|^$)/.test(hr)){continue;
}if(name==fC){continue;
}if(!hr){continue;
}if(name.charAt(0)===eF){continue;
}hq[name]=hr;
}if(hq.style!==undefined){hk=qx.bom.htmlarea.HtmlArea.__bq(hq.style);
delete hq.style;
}if(hj){var hl={domElement:hg,tag:hm,attributes:hq,styles:hk};
hj(hl);
hl.domElement=null;
hm=hl.tag;
}if(hm){ho.push(dq,hm);
for(var name in hq){var hr=hq[name];
ho.push(fo,name,em,hr.toString().replace(new RegExp(fn,cn),dh),fn);
}if(!qx.lang.Object.isEmpty(hk)){ho.push(cO);

for(var name in hk){var hr=hk[name];
ho.push(name,cj,hr.toString().replace(new RegExp(fn,cn),dh),cp);
}ho.push(fn);
}ho.push(closed?dB:dm);
}}for(i=hg.firstChild;i;i=i.nextSibling){ho.push(qx.bom.htmlarea.HtmlArea.__br(i,true,hi,hj));
}if(hh&&!closed&&hm){ho.push(dG,hm,dm);
}break;
case 3:ho.push(hi?hg.data:qx.bom.htmlarea.HtmlArea.__bt(hg.data));
break;
case 8:ho.push(cV,hg.data,eE);
break;
}return ho.join(fu);
},closingTags:dQ,__bs:function(bS){return (qx.bom.htmlarea.HtmlArea.closingTags.indexOf(fo+bS.tagName+fo)!=-1);
},__bt:function(s){s=s.replace(/&/ig,en);
s=s.replace(/</ig,dL);
s=s.replace(/>/ig,dI);
s=s.replace(/\x22/ig,ca);
s=s.replace(/\xA9/ig,cP);
return s;
},isBlockNode:function(gl){if(!qx.dom.Node.isElement(gl)){return false;
}gl=qx.dom.Node.getName(gl);
return /^(body|form|textarea|fieldset|ul|ol|dl|li|div|p|h[1-6]|quote|pre|table|thead|tbody|tfoot|tr|td|th|iframe|address|blockquote)$/.test(gl);
},isParagraphParent:function(N){if(!qx.dom.Node.isElement(N)){return false;
}N=qx.dom.Node.getName(N);
return /^(body|td|th|caption|fieldset|div)$/.test(N);
}},properties:{contentType:{check:dP,init:fk},messengerMode:{check:ed,init:false},insertParagraphOnLinebreak:{check:ed,init:true},insertLinebreakOnCtrlEnter:{check:ed,init:true},postProcess:{check:dt,nullable:true,init:null},useUndoRedo:{check:ed,init:true}},members:{__bu:null,__bv:false,__bw:false,__bx:false,__by:false,__bz:false,__bo:null,__bA:null,__bB:null,__bC:null,__bD:null,__bm:null,__bE:null,__bF:null,__bG:false,__bH:false,__bI:function(bV){if(qx.dom.Node.isElement(bV)&&qx.dom.Node.isNodeName(bV,fw)){this.__bu=bV;
}},_createAndAddIframe:function(bU){this.__bD=qx.bom.Iframe.create();
qx.bom.Iframe.setSource(this.__bD,bU);
if(qx.core.Variant.isSet(fv,ft)){qx.bom.element.Attribute.set(this.__bD,eQ,eg);
}else{qx.bom.element.Style.set(this.__bD,eM,ff);
}qx.bom.element.Style.setStyles(this.__bD,{width:fa,height:fa});
qx.dom.Element.insertBegin(this.__bD,this.__bu);
},_getIframeDocument:function(){return qx.bom.Iframe.getDocument(this.__bD);
},_getIframeWindow:function(){return qx.bom.Iframe.getWindow(this.__bD);
},_addIframeLoadListener:function(){qx.event.Registration.addListener(this.__bD,dx,this._loaded,this);
},__bJ:function(){this.__bE={"xhtml":{doctype:cc+eL+fI+fe+cA+dS,html:fh+cT,meta:fO,style:qx.core.Variant.select(fv,{"mshtml":cu+dc,"default":ev+eI}),contentStyle:dd,body:eK,footer:dn}};
},__bn:fu,getIframeObject:function(){return this.__bD;
},getCommandManager:function(){return this.__bo;
},setValue:function(gX){if(typeof gX===dW){this.__bn=gX;
var gY=this._getIframeDocument();

if(gY&&gY.body){gY.body.innerHTML=gX;
}}},getValue:function(){return this.__bn;
},getComputedValue:function(bw){return this.getHtml(bw);
},getCompleteHtml:function(){var hw=this.__bE[this.getContentType()];
var hv=hw.html+eR+hw.meta+fU+hw.contentStyle+fR+eS;
hv+=eA+this.__bK()+cS;
hv+=this.getHtml()+dn;
return hv;
},__bK:function(){var G=[cG,fL,eq,cW,ds,du,fG,fN,es,bY,fM,eG,ek,ew];
var F=qx.bom.element.Style;
var E=this.getContentBody();
var J={};
var I,K;
var H=qx.bom.client.Engine.MSHTML?2:1;

for(var i=0,j=G.length;i<j;i++){I=G[i];
K=F.get(E,I,H);

if(K!==undefined&&K!=fu){J[I]=K;
}}return qx.bom.element.Style.compile(J);
},getContentDocument:function(){if(this.__bv){return this._getIframeDocument();
}},getContentBody:function(){if(this.__bv){return this._getIframeDocument().body;
}},getContentWindow:function(){if(this.__bv){return this._getIframeWindow();
}},getWords:function(bN){if(!bN){bN=this.getContentBody();
}
if(!bN){return [];
}var bP=bN.cloneNode(true);
bP.innerHTML=bP.innerHTML.replace(/>/gi,fH);
bP.innerHTML=bP.innerHTML.replace(/\n/gi,fo);
bP.innerHTML=bP.innerHTML.replace(/<!--.*-->/gi,fu);
var bO=qx.core.Variant.isSet(fv,cM)?bP.innerText:bP.textContent;
var bQ=bO.match(qx.bom.htmlarea.HtmlArea.GetWordsRegExp);
return !bQ?[]:bQ;
},getWordsWithElement:function(){var by=this.getTextNodes();
var bC={};
var i,j,bD,bz,bx;

for(var i=0,bB=by.length;i<bB;++i){bz=by[i];
bD=bz.nodeValue.split(fo);

for(var j=0,bA=bD.length;j<bA;++j){bx=this._cleanupWord(bD[j]);

if(bx!=null&&bx.length>1){if(!bC[bx]){bC[bx]=[];
}bC[bx].push(bz);
}}}return bC;
},_cleanupWord:function(gq){if(!gq){return null;
}return gq.replace(qx.bom.htmlarea.HtmlArea.CleanupWordsRegExp,fu);
},getTextNodes:function(){return this._fetchTextNodes(this.getContentBody());
},_fetchTextNodes:function(P){var R=[];
var Q;
if(P.hasChildNodes){for(var i=0;i<P.childNodes.length;i++){Q=this._fetchTextNodes(P.childNodes[i]);
qx.lang.Array.append(R,Q);
}}if(P.nodeType==3){if(P.nodeValue.length>1){R.push(P);
}}return R;
},__bL:0,__bM:function(){var gD=this._getIframeDocument();
if(!gD){this.__bL++;

if(this.__bL>5){this.error('cant load HtmlArea. Document is not available. '+gD);
this.fireDataEvent(fA);
}else{{};
qx.event.Timer.once(function(){this.__bM();
},this,0);
}}else{this.__bL=0;
this._onDocumentIsReady();
}},_loaded:function(e){if(this.__bx){return;
}
if(this.__bw){this.__bN();
return;
}if(qx.core.Variant.isSet(fv,ft)){this.__bM();
}else{this._onDocumentIsReady();
}},isReady:function(){return this.__bv;
},_onDocumentIsReady:function(){var b=new qx.bom.htmlarea.manager.Command(this);

if(this.getUseUndoRedo()){b=new qx.bom.htmlarea.manager.UndoRedo(b,this);
}this.__bx=true;
if(qx.core.Variant.isSet(fv,ft)){this.setEditable(true);
}this.__bQ();
this.__bR();
if(!qx.core.Variant.isSet(fv,ft)){this.setEditable(true);
}this.__bv=true;
this.__bo=b;
b.setContentDocument(this._getIframeDocument());
this.__bT();
this.fireEvent(eN);
},forceEditable:qx.core.Variant.select(fv,{"gecko":function(){var gE=this._getIframeDocument();

if(gE){if(qx.bom.client.Engine.VERSION>=ee){gE.designMode=cB;
gE.body.contentEditable=false;
gE.body.contentEditable=true;
}else{gE.body.contentEditable=true;
this.__bU(true);
}}},"default":qx.lang.Function.empty}),invalidateEditor:qx.core.Variant.select(fv,{"gecko":function(){this.__bx=false;
this.__bv=false;
this.__bw=true;
},"default":function(){}}),__bN:qx.core.Variant.select(fv,{"gecko":function(){this.__bQ();
this.__bR();
this.__bo.setContentDocument(this._getIframeDocument());
this.setEditable(true);
this.forceEditable();
this.__bx=true;
this.__bv=true;
this.__bw=false;
this.fireEvent(dz);
},"default":function(){}}),__bO:function(bd){var bf=fu;

if(!bd){return bf;
}
try{var be=bd.getAttribute(fb);

if(!be){return bf;
}if(qx.core.Variant.isSet(fv,ft)){bf=be.cssText;
}else{bf=be;
}}catch(S){this.error("can't extract style from elem. ");
}return bf;
},__bP:function(bk){var bl=qx.bom.client.Engine.GECKO?eJ:fu;
var bm=this.__bE[this.getContentType()];
var bn=eR+bm.meta+fU+bl+bm.style+bm.contentStyle+this.__bm+fR+eS;
var content=bm.body+bk;
return bm.html+bn+content+bm.footer;
},__bQ:function(){var bF=this.getValue();

if(typeof bF==dW){var bE=this._getIframeDocument();

try{bE.open(ey,true);
bE.write(this.__bP(bF));
bE.close();
}catch(e){this.error("cant open document on source '"+qx.bom.Iframe.queryCurrentUrl(this.__bD)+"'",e);
this.fireDataEvent(fA,e);
}}},__bR:function(){var bj=qx.event.Registration;
var bh=this._getIframeDocument();
bj.addListener(bh.body,co,this._handleKeyPress,this);
bj.addListener(bh.body,df,this._handleKeyUp,this);
bj.addListener(bh.body,de,this._handleKeyDown,this);
var bi=qx.bom.client.Engine.WEBKIT?this._getIframeWindow():bh.body;
bj.addListener(bi,fX,this._handleFocusEvent,this);
bj.addListener(bi,fY,this._handleBlurEvent,this);
bj.addListener(bh,cK,this._handleFocusOutEvent,this);
var bg=qx.bom.client.Engine.MSHTML?fV:eV;
bj.addListener(bh.body,bg,this._handleMouseUpOnBody,this);
bj.addListener(bh.documentElement,bg,this._handleMouseUpOnDocument,this);
bj.addListener(bh.documentElement,fB,this._handleContextMenuEvent,this);
},__bS:function(){if(this.__bA==null){this.__bA={execute:function(gJ,gK){this.stackedCommands=true;
this.commandStack.push({command:gJ,value:gK});
},commandStack:[],stackedCommands:false};
}this.__bA.stackedCommands=false;
return this.__bA;
},__bT:function(){var gm=this.__bA;

if(gm!=null&&gm.stackedCommands){var gn=gm.commandStack;

if(gn!=null){for(var i=0,j=gn.length;i<j;i++){this.__bo.execute(gn[i].command,gn[i].value);
}}}},__bU:function(gF){var gG=this._getIframeDocument();

if(this.__bx&&gG){try{if(qx.core.Variant.isSet(fv,fs)){gG.designMode=(gF!==false)?cl:fx;
}gG.designMode=(gF!==false)?fx:cl;
}catch(e){}}},setEditable:function(T){if(this.__bx){this.__bU(true);
if(qx.core.Variant.isSet(fv,fs)){try{var U=this._getIframeDocument();
U.execCommand(dA,false,true);
}catch(gp){try{var U=this._getIframeDocument();
U.execCommand(cC,false,false);
}catch(gI){if(!this.__bv){this.error("Failed to enable rich edit functionality");
this.fireDataEvent(fA,gI);
}else{throw new Error("Failed to enable rich edit functionality");
}}}}this.__by=T;
}},getEditable:function(){return this.__by;
},isEditable:function(){return this.__by;
},__bV:false,_handleKeyUp:function(e){var gy=e.getKeyIdentifier().toLowerCase();
var gA=e.isCtrlPressed();
this.__bB=e;

if(false&&qx.core.Setting.get(ea)==dY){this.debug(e.getType()+" | "+gy);
}if(qx.core.Variant.isSet(fv,ft)){if(this.__bV){switch(gy){case fq:if(this.getInsertLinebreakOnCtrlEnter()){var gz=this.__ce(this.getSelection());

if(gz){gz.collapse(true);
gz.pasteHTML(dN);
}this.__bY();
}break;
case dj:this.__bV=false;
return;
break;
}}}else if(qx.core.Variant.isSet(fv,fs)){switch(gy){case fm:case eb:case ga:case eX:case fy:case cs:case dg:case fz:case eT:this.__bz=(this.getFocusNode()==this.getContentBody().firstChild);
break;
}}else if(qx.core.Variant.isSet(fv,cN)){if(gA){if(this.getInsertLinebreakOnCtrlEnter()&&gy==fq){this.__bW();
e.preventDefault();
e.stopPropagation();
this.__bY();
}this.__bV=false;
}}},__bW:function(){var gb=this.getSelection();
var gc=fu;
if(gb&&(gb.focusNode.textContent==fu||gb.focusNode.parentElement.tagName==ce)){gc=cF;
}this.__bo.execute(dX,gc+qx.bom.htmlarea.HtmlArea.simpleLinebreak);
},_handleKeyDown:qx.core.Variant.select(fv,{"mshtml|webkit":function(e){var gB=e.getKeyIdentifier().toLowerCase();

if(false&&qx.core.Setting.get(ea)==dY){}if(this.__bV&&(gB==dl||gB==eY||gB==fD||gB==fQ||gB==fF||gB==ci)){e.preventDefault();
e.stopPropagation();
}if(gB==dj){this.__bV=true;
}},"default":function(e){}}),_handleKeyPress:function(e){var gP=this.getContentDocument();
var gL=e.getKeyIdentifier().toLowerCase();
var gN=e.isCtrlPressed();
var gO=e.isShiftPressed();
this.__bB=e;

if(false&&qx.core.Setting.get(ea)==dY){this.debug(e.getType()+" | "+gL);
}if(this.__bG){var gW=!(qx.core.Variant.isSet(fv,ft)&&gL==fq)||!(qx.core.Variant.isSet(fv,fs)&&gL==fq);

if(gW){this.__bY();
this.__bG=false;
}}
switch(gL){case fq:if(!gO&&!gN&&this.getMessengerMode()){e.preventDefault();
e.stopPropagation();
var gU=new qx.event.type.Data(eh,this.getComputedValue());
this.dispatchEvent(gU,true);
this.resetHtml();
}if(gN){if(!this.getInsertLinebreakOnCtrlEnter()){return;
}e.preventDefault();
e.stopPropagation();

if(qx.core.Variant.isSet(fv,fs)){if(this.__cc()){this.insertHtml(ct);
this.__bY();
return;
}this.insertHtml(cy);
}else if(qx.core.Variant.isSet(fv,eU)){var gV=this.getSelection();
var gQ=this.__ce(gV);

if(gV&&gQ){var gR=gP.createElement(dw);
gQ.collapse(true);
gQ.insertNode(gR);
gQ.collapse(true);
gQ.selectNode(gR);
gV.addRange(gQ);
gQ.collapse(true);
}}this.__bY();
}if(qx.core.Variant.isSet(fv,ft)){if(!this.getInsertParagraphOnLinebreak()){if(this.__bo.execute(dX,qx.bom.htmlarea.HtmlArea.simpleLinebreak)){this.__bY();
e.preventDefault();
e.stopPropagation();
}}}else if(qx.core.Variant.isSet(fv,fs)){if(this.getInsertParagraphOnLinebreak()&&!gO&&!gN){var gV=this.getSelection();

if(gV){var gM=gV.focusNode;
if(this.__cc()){this.__bY();
return;
}if(this.__cd()){this.__bY();
return;
}while(!qx.dom.Node.isNodeName(gM,dU)){if(qx.dom.Node.isNodeName(gM,cJ)){this.__bY();
return;
}gM=gM.parentNode;
}}this.__bo.insertParagraphOnLinebreak();
e.preventDefault();
e.stopPropagation();
this.__bY();
this.__bG=true;
}}else if(qx.core.Variant.isSet(fv,cN)){if(this.getInsertParagraphOnLinebreak()&&gO){this.__bW();
e.preventDefault();
e.stopPropagation();
this.__bY();
}}break;
case ga:if(qx.bom.client.Engine.GECKO&&qx.bom.client.Engine.FULLVERSION<1.9&&gO){var gV=this.getSelection();
if(gV&&gV.focusNode==gP.body.firstChild){if(this.__bz){if(gV.focusOffset!=0){gV.extend(gV.focusNode,0);
}}}}this.__bY();
break;
case dp:if(qx.bom.client.Engine.GECKO&&qx.bom.client.Engine.FULLVERSION<1.9){if(gN){var gV=this.getSelection();
if(gO){if(gV&&(gV.focusOffset!=0)||(gV.focusNode!=gP.body.firstChild)){gV.extend(gP.body.firstChild,0);
}}else{var gS=null;
var gT;
if(gP){gS=gP.evaluate(dK,gP.body,null,XPathResult.ANY_TYPE,null);
}
if(gS&&gV){while(gT=gS.iterateNext()){if(gT&&gT.parentNode&&gT.parentNode.tagName!=bX){try{gV.extend(gT,0);

if(!this.isSelectionCollapsed()){gV.collapseToStart();
}}catch(e){}break;
}}}}}}this.__bY();
break;
case fm:case eb:case eX:case fy:case cs:case dg:case fz:case eT:this.__bY();
break;
case fD:if(gN){this.__bX(cQ,true);
}break;
case fF:case ci:if(gN){this.__bX(cd,true);
}break;
case fQ:if(gN){this.__bX(cR,true);
}break;
case dl:if(gN&&!gO){this.__bX(cI,true);
}else if(gN&&gO){this.__bX(ck,true);
}break;
case eY:if(gN){this.__bX(ck,true);
}break;
case eo:if(gN){this.selectAll();
}break;
}this.__bB=null;
},__bX:function(hz,hA){var hC=null;
var hB=qx.bom.htmlarea.HtmlArea.hotkeyInfo;

if(hB[hz]){hC=hB[hz].method;
}
if(hC!=null&&this[hC]){this[hC]();

if(hA){this.__bB.preventDefault();
this.__bB.stopPropagation();
}
if(this.isSelectionCollapsed()){this.__bG=true;
}this.__bY();
}},_handleFocusEvent:function(e){this.__bC=null;
this.fireEvent(dr);
},_handleBlurEvent:function(e){this.__bn=this.getComputedValue();
},_handleFocusOutEvent:function(e){if(this.__bC==null){this.__bC=this.getSelectedHtml();
}this.fireEvent(fd);
},_handleMouseUpOnBody:function(e){if(false&&qx.core.Setting.get(ea)==dY){this.debug("handleMouse "+e.getType());
}this.__bH=true;
this.__bY();
},_handleMouseUpOnDocument:qx.core.Variant.select(fv,{"mshtml":qx.lang.Function.empty,"default":function(e){if(!this.__bH){qx.bom.Element.activate(this.getContentBody());
}this.__bH=false;
}}),_handleContextMenuEvent:function(e){var hd=e.getViewportLeft();
var hc=e.getViewportTop();
var he=qx.bom.element.Location.getLeft(this.__bu)+hd;
var hf=qx.bom.element.Location.getTop(this.__bu)+hc;
var hb={x:he,y:hf,relX:hd,relY:hc,target:e.getTarget()};
e.preventDefault();
e.stopPropagation();
qx.event.Timer.once(function(){this.fireDataEvent(fB,hb);
},this,0);
},isLoaded:function(){return this.__bx;
},insertHtml:function(gd){return this.__bo.execute(dX,gd);
},removeFormat:function(){return this.__bo.execute(et);
},setBold:function(){return this.__bo.execute(eW);
},setItalic:function(){return this.__bo.execute(dV);
},setUnderline:function(){return this.__bo.execute(dT);
},setStrikeThrough:function(){return this.__bo.execute(eu);
},setFontSize:function(bT){return this.__bo.execute(fj,bT);
},setFontFamily:function(O){return this.__bo.execute(eB,O);
},setTextColor:function(hx){return this.__bo.execute(dv,hx);
},setTextBackgroundColor:function(hy){return this.__bo.execute(cE,hy);
},setJustifyLeft:function(){return this.__bo.execute(fc);
},setJustifyCenter:function(){return this.__bo.execute(cx);
},setJustifyRight:function(){return this.__bo.execute(dR);
},setJustifyFull:function(){return this.__bo.execute(cv);
},insertIndent:function(){return this.__bo.execute(eC);
},insertOutdent:function(){return this.__bo.execute(ef);
},insertOrderedList:function(){return this.__bo.execute(eH);
},insertUnorderedList:function(){return this.__bo.execute(cY);
},insertHorizontalRuler:function(){return this.__bo.execute(dM);
},insertImage:function(bR){return this.__bo.execute(ep,bR);
},insertHyperLink:function(bW){return this.__bo.execute(cw,bW);
},removeBackgroundColor:function(){this.__bo.execute(cL,cU);
},setBackgroundColor:function(ha){this.__bo.execute(cL,ha);
},removeBackgroundImage:function(){this.__bo.execute(fW);
},setBackgroundImage:function(gg,gh,gi){return this.__bo.execute(fW,[gg,gh,gi]);
},selectAll:function(){return this.__bo.execute(dO);
},undo:function(){if(this.getUseUndoRedo()){return this.__bo.execute(cq);
}else{return true;
}},redo:function(){if(this.getUseUndoRedo()){return this.__bo.execute(fE);
}else{return true;
}},resetHtml:function(){var X=this._getIframeDocument();
while(X.body.firstChild){X.body.removeChild(X.body.firstChild);
}if(qx.bom.client.Engine.GECKO){X.body.innerHTML=eO;
}else if(qx.bom.client.Engine.WEBKIT){var Y=this.getSelection();
var ba=X.createRange();

if(ba&&Y){Y.addRange(ba);
}}},getHtml:function(gs){var gt=this._getIframeDocument();

if(gt==null){return null;
}return qx.bom.htmlarea.HtmlArea.__br(gt.body,false,gs,this.getPostProcess());
},containsOnlyPlaceholder:qx.core.Variant.select(fv,{"mshtml":function(){var bc=this._getIframeDocument();
return (bc.body.innerHTML==dF);
},"default":qx.lang.Function.returnFalse}),getContextInformation:function(){return this.__ca();
},__bY:function(){qx.event.Timer.once(function(e){var d=this.__ca();
this.fireDataEvent(da,d);
},this,200);
},__ca:function(){if(this._processingExamineCursorContext||this.getEditable()==false){return;
}this._processingExamineCursorContext=true;
var k=this.getFocusNode();

if(k==null){return;
}
if(qx.dom.Node.isText(k)){k=k.parentNode;
}var o=this._getIframeDocument();
var y=qx.core.Variant.isSet(fv,ft)?k.currentStyle:o.defaultView.getComputedStyle(k,null);
var r=false;
var f=false;
var m=false;
var l=false;
var t=false;
var x=false;
var n=false;
var z=false;
var h=false;
var v=false;
var w=null;
var A=null;
var q=null;

if(y!=null){if(qx.core.Variant.isSet(fv,ft)){f=y.fontStyle==dV;
m=y.textDecoration.indexOf(dT)!==-1;
l=y.textDecoration.indexOf(dk)!==-1;
w=y.fontSize;
q=y.fontFamily;
n=y.textAlign==fm;
z=y.textAlign==fS;
h=y.textAlign==eb;
v=y.textAlign==fT;
}else{f=y.getPropertyValue(fl)==dV;
m=y.getPropertyValue(cr).indexOf(dT)!==-1;
l=y.getPropertyValue(cr).indexOf(dk)!==-1;
w=y.getPropertyValue(er);
q=y.getPropertyValue(eP);
n=y.getPropertyValue(ec)==fm;
z=y.getPropertyValue(ec)==fS;
h=y.getPropertyValue(ec)==eb;
v=y.getPropertyValue(ec)==fT;
}
if(qx.core.Variant.isSet(fv,cM)){r=y.fontWeight==700;
}else{r=y.getPropertyValue(cf)==eW||qx.dom.Node.isNodeName(k,fD);
}}var g=k;
if(g!=null&&g.parentNode!=null&&!qx.dom.Node.isDocument(g.parentNode)){while(g!=null&&!qx.dom.Node.isNodeName(g,dU)){var p=qx.dom.Node.getName(g);

if(p==dJ){x=true;
break;
}else if(p==db){t=true;
break;
}
if(A==null||A==fu){A=qx.bom.element.Attribute.get(g,fK);
}g=g.parentNode;
}}var u={bold:r?1:0,italic:f?1:0,underline:m?1:0,strikethrough:l?1:0,fontSize:(A==null)?w:A,fontFamily:q,insertUnorderedList:t?1:0,insertOrderedList:x?1:0,justifyLeft:n?1:0,justifyCenter:z?1:0,justifyRight:h?1:0,justifyFull:v?1:0};
this._processingExamineCursorContext=false;
return u;
},getSelection:qx.core.Variant.select(fv,{"mshtml":function(){return this._getIframeDocument()?this._getIframeDocument().selection:null;
},"default":function(){return this._getIframeWindow()?this._getIframeWindow().getSelection():null;
}}),isSelectionCollapsed:qx.core.Variant.select(fv,{"mshtml":function(){return this.getSelection()&&this.getSelection().type==di;
},"default":function(){return this.getSelection()&&this.getSelection().isCollapsed;
}}),getSelectedText:qx.core.Variant.select(fv,{"mshtml":function(){return this.getRange()?this.getRange().text:fu;
},"default":function(){return this.getRange()?this.getRange().toString():fu;
}}),getSelectedHtml:function(){if(this.__bC!=null){return this.__bC;
}var gC=this.getRange();

if(!gC){return fu;
}else{return this.__cb(gC);
}},__cb:qx.core.Variant.select(fv,{"mshtml":function(bo){if(!bo){return fu;
}return bo.item?bo.item(0).outerHTML:bo.htmlText;
},"default":function(hs){var ht=this._getIframeDocument();

if(ht&&hs){try{var hu=ht.createElement(dU);
hu.appendChild(hs.cloneContents());
return hu.innerHTML;
}catch(c){}return hs+fu;
}return fu;
}}),clearSelection:qx.core.Variant.select(fv,{"mshtml":function(){var gr=this.getSelection();

if(gr){gr.empty();
}},"default":function(){var bb=this.getSelection();

if(bb){bb.collapseToStart();
}}}),__cc:qx.core.Variant.select(fv,{"gecko":function(){var ge=this.getSelection();
var gf=this.getFocusNode();
return ge&&this.isSelectionCollapsed()&&gf!=null&&qx.dom.Node.isText(gf)&&ge.anchorOffset<gf.length;
},"default":function(){return false;
}}),__cd:qx.core.Variant.select(fv,{"gecko":function(){return qx.dom.Node.isElement(this.getFocusNode());
},"default":function(){return false;
}}),getRange:function(){return this.__ce(this.getSelection());
},__ce:qx.core.Variant.select(fv,{"mshtml":function(L){var M=this._getIframeDocument();

if(L){try{return L.createRange();
}catch(gj){return M?M.body.createTextRange():null;
}}else{return M?M.body.createTextRange():null;
}},"default":function(bu){var bv=this._getIframeDocument();

if(bu){try{return bu.getRangeAt(0);
}catch(gH){return bv?bv.createRange():null;
}}else{return bv?bv.createRange():null;
}}}),saveRange:qx.core.Variant.select(fv,{"mshtml":function(){this.__bF=this.getRange();
},"default":function(){}}),getSavedRange:qx.core.Variant.select(fv,{"mshtml":function(){return this.__bF;
},"default":function(){}}),resetSavedRange:qx.core.Variant.select(fv,{"mshtml":function(){this.__bF=null;
},"default":function(){}}),getFocusNode:qx.core.Variant.select(fv,{"mshtml":function(){var B=this.getSelection();
var C;

switch(B.type){case cX:case di:C=this.__ce(B);

if(C){C.collapse(false);
return C.parentElement();
}else{return null;
}break;
case fP:C=this.__ce(B);

if(C){try{C.collapse(false);
}catch(go){}return C.item(0);
}else{return null;
}break;
default:return this._getIframeDocument().body;
}},"default":function(){var D=this.getSelection();

if(D&&D.focusNode){return D.focusNode;
}return this._getIframeDocument().body;
}})},settings:{"qx.bom.htmlarea.HtmlArea.debug":cb},destruct:function(){try{var gv=this._getIframeDocument();
var gx=qx.event.Registration;
gx.removeListener(gv.body,co,this._handleKeyPress,this);
gx.removeListener(gv.body,df,this._handleKeyUp,this);
gx.removeListener(gv.body,de,this._handleKeyDown,this);
var gw=qx.bom.client.Engine.WEBKIT?this._getIframeWindow():gv.body;
gx.removeListener(gw,fX,this._handleFocusEvent);
gx.removeListener(gw,fY,this._handleBlurEvent);
gx.removeListener(gv,cK,this._handleFocusOutEvent);
var gu=qx.bom.client.Engine.MSHTML?fV:eV;
gx.removeListener(gv.body,gu,this._handleMouseUpOnBody,this);
gx.removeListener(gv.body,gu,this._handleMouseUpOnDocument,this);
gx.removeListener(gv.documentElement,fB,this._handleContextMenuEvent,this);
}catch(gk){}this._disposeObjects(cg);
this.__bE=this.__bD=this.__bu=this.__bA=null;
}});
})();
(function(){var cT="qx.client",cS="",cR="legacy-font-size",cQ="mshtml",cP="inserthtml",cO="span",cN='color',cM="text-decoration",cL=';',cK="__cw",bU="transparent",bT='">',bS="child",bR="gecko",bQ="font-family",bP="text-align",bO="BackColor",bN="FontSize",bM='text-decoration',bL="BODY",db="</font>",dc="backgroundPosition",cY="font-size",da="p",cW="underline",cX='|',cU="id",cV="string",dd="background-color",de="backgroundRepeat",ct="font",cs=":",cv="InsertHtml",cu="none",cx=" ",cw=";",cz="px",cy="backgroundImage",cr="Control",cq="__paragraph__",C=':',D="qx.bom.htmlarea.HtmlArea.debug",E="on",F="size",G="__cx",H="textDecoration",I="undefined",J="backgroundColor",K="_moz",L="top",di="/>",dh="formatBlock",dg="insertParagraph",df="li",dm='<span style="',dl="<img ",dk="__cP",dj="no-repeat",dp=' <a href="',dn="__cz",bl="FONT",bm="|top|bottom|center|left|right|right top|left top|left bottom|right bottom|",bj="__placeholder__",bk='font-family:',bp="<p style='",bq="outdent",bn='</a> ',bo="InsertImage",bh="__resetHtml",bi="FontName",T="__cC",S="blockquote",V="style",U="P",P="qx.bom.htmlarea.manager.Command",O="__cB",R="'><br class='webkit-block-placeholder' />",Q="a",N='"',M="<span></span>",bv="type",bw="CreateLink",bx="='",by="__cK",br="qx_link",bs='"></span>',bt="Italic",bu="__cM",bz="InsertUnorderedList",bA="OL",be='text-align:',bd="Bold",bc="ForeColor",bb="url(",ba='" ',Y="repeat repeat-x repeat-y no-repeat",X='</p>',W="<hr />",bg='<font style="',bf="IMG",bB="__cL",bC='<p id="',bD="StrikeThrough",bE="JustifyFull",bF="LI",bG="__getHtml",bH='>',bI='" size="',bJ="Indent",bK="HiliteColor",bY="br",bX="Copy",bW="</span>",bV="Paste",cd="__cO",cc="RemoveFormat",cb="JustifyRight",ca="indent",cf="' ",ce='',cm='style="',cn="JustifyCenter",ck="_moz_dirty",cl="color",ci="JustifyLeft",cj="Underline",cg="SelectAll",ch="Cut",co="line-through",cp="__cN",cD=")",cC="href",cF='<span id="',cE="__cs",cH="UL",cG="__cQ",cJ="Outdent",cI="webkit",cB="selectall",cA="InsertOrderedList";
qx.Class.define(P,{extend:qx.core.Object,construct:function(hi){arguments.callee.base.call(this);
this.__cf=hi;
this.__cg=null;
this._commands=null;
this.__cn();
this.__ch={"Bold":true,"Italic":true,"Underline":true,"StrikeThrough":true};
this.__ci=[10,12,16,18,24,32,48];
this.__cj=0;
},statics:{__ck:bm,__cl:Y},members:{__cg:null,__cf:null,__cm:false,__ch:null,__ci:null,__cj:null,setContentDocument:function(gB){this.__cg=gB;
},getCommandObject:function(fL){if(this._commands[fL]){return this._commands[fL];
}else{return null;
}},__cn:function(){this._commands={bold:{useBuiltin:true,identifier:bd,method:null},italic:{useBuiltin:true,identifier:bt,method:null},underline:{useBuiltin:true,identifier:cj,method:null},strikethrough:{useBuiltin:true,identifier:bD,method:null},fontfamily:{useBuiltin:true,identifier:bi,method:null},fontsize:{useBuiltin:false,identifier:bN,method:by},textcolor:{useBuiltin:true,identifier:bc,method:null},textbackgroundcolor:{useBuiltin:false,identifier:null,method:bB},backgroundcolor:{useBuiltin:false,identifier:null,method:bu},backgroundimage:{useBuiltin:false,identifier:null,method:cp},justifyleft:{useBuiltin:false,identifier:ci,method:cK},justifyright:{useBuiltin:false,identifier:cb,method:cK},justifycenter:{useBuiltin:false,identifier:cn,method:cK},justifyfull:{useBuiltin:false,identifier:bE,method:cK},indent:{useBuiltin:true,identifier:bJ,method:null},outdent:{useBuiltin:true,identifier:cJ,method:null},copy:{useBuiltin:true,identifier:bX,method:null},cut:{useBuiltin:true,identifier:ch,method:null},paste:{useBuiltin:true,identifier:bV,method:null},insertorderedlist:{useBuiltin:false,identifier:cA,method:G},insertunorderedlist:{useBuiltin:false,identifier:bz,method:G},inserthorizontalrule:{useBuiltin:false,identifier:cv,method:T},insertimage:{useBuiltin:false,identifier:bo,method:dn},inserthyperlink:{useBuiltin:false,identifier:bw,method:O},selectall:{useBuiltin:false,identifier:cg,method:cd},selectedtext:{useBuiltin:false,identifier:null,method:dk},selectedhtml:{useBuiltin:false,identifier:null,method:cG},inserthtml:{useBuiltin:false,identifier:cv,method:cE},resethtml:{useBuiltin:false,identifier:null,method:bh},gethtml:{useBuiltin:false,identifier:null,method:bG},removeformat:{useBuiltin:true,identifier:cc,method:null}};
},execute:function(eH,eI){if(!this.__cf.isReady()){this.error("editor not ready! '"+eH+"':'"+eI+"'");
return false;
}eH=eH.toLowerCase();
eI=eI!=null?eI:null;
if(this._commands[eH]){var eJ;
var eK=this._commands[eH];
if(!(qx.bom.client.Engine.WEBKIT&&(eH==ca||eH==bq))){if(this.__co()){this.__cp();
}}if(eK.useBuiltin){eJ=this.__cq(eK.identifier,false,eI);
}else{if(eK.method!=null&&this[eK.method]){eJ=this[eK.method].call(this,eI,eK);
}else{this.error("The method '"+eK.method+"' you calling to execute the command '"+eH+"' is not available!");
}}this.__cf.resetSavedRange();
return eJ;
}else{this.error("Command "+eH+" is currently not supported!");
}},__co:function(){var gO=this.__cf.getFocusNode();
var gR=false;
var gP=false;

if(gO){if(gO.nodeType==3){var gQ=qx.dom.Hierarchy.getAncestors(gO);

for(var i=0,j=gQ.length;i<j;i++){if(gQ[i].tagName==U){gR=true;
break;
}}}else if(gO.nodeType==1&&gO.tagName==bL){gP=true;
}}return gP||!gR;
},__cp:function(){this.__cq(dh,false,da);
},__cq:function(fc,fd,fe){try{var fh=this.__cg;
var ff=false;
var fg=this.__cf.getRange();
this.__cg.body.focus();
if(qx.core.Variant.isSet(cT,cQ)){if(fc!=cB){fg.select();
if(((fg.text)&&(fg.text.length>0))||((fg.length==1)&&(fg.item(0))&&(fg.item(0).tagName==bf))){fh=fg;
}else{fh=this.__cg;
}}if((qx.core.Variant.isSet(cT,cQ))&&(this.__ch[fc])){if(fg.text==cS){ff=true;
}}}var fi=fh.execCommand(fc,fd,fe);

if(ff&&fg.text!=cS){fg.collapse();
}
if(false&&qx.core.Setting.get(D)==E){this.debug("execCommand "+fc+" with value "+fe+" succeded");
}this.__cm=false;
}catch(fK){if(false&&qx.core.Setting.get(D)==E){this.debug("execCommand "+fc+" with value "+fe+" failed");
}return false;
}return fi;
},__cr:qx.core.Variant.select(cT,{"mshtml":function(){var ga=this.__cf;
var fY=ga.getSavedRange()!=null?ga.getSavedRange():ga.getRange();
return fY;
},"default":function(){return this.__cf.getRange();
}}),__cs:qx.core.Variant.select(cT,{"mshtml":function(fv,fw){var fz;
if(fv==qx.bom.htmlarea.HtmlArea.simpleLinebreak){return this.__cv();
}else{this.__cg.body.focus();
var fy=this.__cf.getSelection();
var fx=this.__cr();
if(fx&&fy&&fy.type!=cr){try{fx.pasteHTML(fv);
fx.collapse(false);
fx.select();
fz=true;
}catch(e){}}else{fz=false;
}this.__cf.resetSavedRange();
return fz;
}},"default":function(hg,hh){this.__cg.body.focus();
return this.__cg.execCommand(hh.identifier,false,hg);
}}),insertParagraphOnLinebreak:qx.core.Variant.select(cT,{"gecko":function(){var x=this.__cF();
var B=this.__ct(x);
var t=this.__cD(x);
var y=bj+Date.parse(new Date());
var z=cq+Date.parse(new Date());
var r=ce;
var v=cF+y+bs;
r+=v;
r+=bC+z+ba+B+bH;
r+=t+X;
this.__cf.getCommandManager().addUndoStep(cP,dg,this.getCommandObject(cP));
this.execute(cP,r);
this.__cu();
this.__cg.getElementById(y).removeAttribute(cU);
var w=this.__cg.getElementById(z);

if(w.previousSibling.innerHTML==v){var q=this.__cE();
var u=this.__cg.createElement(bY);
var s=this.__cg.createAttribute(ck);
s.nodeValue=cS;
u.setAttributeNode(s);
var A=this.__cg.createAttribute(bv);
A.nodeValue=K;
u.setAttributeNode(A);
w.previousSibling.appendChild(q);
w.previousSibling.appendChild(u);
}return true;
},"webkit":function(){var gK=this.getCurrentStyles();
var gL=cS;
var gN={"background-color":true,"text-align":true};
for(var gM in gK){if(gN[gM]){gL+=gM+cs+gK[gM]+cw;
}}this.__cf.insertHtml(bp+gL+R);
},"default":qx.lang.Function.empty}),__ct:qx.core.Variant.select(cT,{"gecko":function(fE){var fJ=cm;
var fI=fE.child;
if(fI[bP]){fJ+=be+fI[bP]+cL;
delete fE.child[bP];
}if(fI[bQ]){fJ+=bk+fI[bQ]+cL;
delete fE.child[bQ];
}var fH={"padding-top":true,"padding-bottom":true,"padding-left":true,"padding-right":true};
var fF={"margin-top":true,"margin-bottom":true,"margin-left":true,"margin-right":true};

for(var fG in fI){if(fH[fG]||fF[fG]){fJ+=fG+C+fI[fG]+cL;
delete fE.child[fG];
}}fJ+=N;
return fJ;
},"default":function(){return cS;
}}),__cu:qx.core.Variant.select(cT,{"gecko":function(){var fT=this.__cf.getSelection();

if(!fT||!fT.focusNode){return;
}var fM=fT.focusNode;
var fR=fT.focusNode;

while(!qx.dom.Node.isNodeName(fR,da)){fR=fR.parentNode;
}var fQ=fR.previousSibling.id;
var fU=fR.nextSibling?fR.nextSibling.id:null;

if(qx.lang.String.startsWith(fQ,cq)&&fQ==fU){var fS=fR.nextSibling;
var fO=this.__cf.getRange();
fO.selectNode(fS);
fT.addRange(fO);
var fN=qx.bom.htmlarea.HtmlArea.EMPTY_DIV;
this.__cf.getCommandManager().addUndoStep(cP,fN,this.getCommandObject(cP));
this.execute(cP,fN);
var fP=this.__cf.getRange();

if(fM){while(fM&&fM.firstChild&&qx.dom.Node.isElement(fM.firstChild)){fM=fM.firstChild;
}}fP.selectNode(fM);
fT.addRange(fP);
fP.collapse(true);
}},"default":qx.lang.Function.empty}),__cv:qx.core.Variant.select(cT,{"mshtml":function(){var ep=this.__cf.getRange();
if(ep&&!qx.dom.Node.isNodeName(ep.parentElement(),df)){ep.pasteHTML(qx.bom.htmlarea.HtmlArea.simpleLinebreak);
ep.collapse(false);
ep.select();
return true;
}return false;
},"default":function(){return false;
}}),__cw:function(fV,fW){var fX=qx.core.Variant.isSet(cT,cQ)?this.__cf.getRange():this.__cg;
return fX.execCommand(fW.identifier,false,fV);
},__cx:function(fl,fm){if(qx.core.Variant.isSet(cT,cQ)){var fn=this.__cf.getFocusNode();
this.__cy(fn);
}this.__cg.body.focus();
var fo=this.__cg.execCommand(fm.identifier,false,fl);

if(qx.core.Variant.isSet(cT,cI)){var fn=this.__cf.getFocusNode();
this.__cy(fn.parentNode);
}return fo;
},__cy:function(gE){var gF=[];
var parent=gE.parentNode;

while(qx.dom.Node.isNodeName(parent,S)){gF.push(parent);
parent=parent.parentNode;
}if(gF.length>0){parent.appendChild(gE);
parent.removeChild(gF[gF.length-1]);
}},__cz:qx.core.Variant.select(cT,{"gecko":function(eq,er){if(eq.src){this.__cg.execCommand(er.identifier,false,eq.src);
delete eq.src;
var eF=this.__cf.getSelection();
if(eF){var eE=eF.anchorNode;
var ez=eF.anchorOffset;
var ev=eE.childNodes[ez-1];
var eC;

for(var ey in eq){eC=this.__cg.createAttribute(ey);
eC.nodeValue=eq[ey];
ev.setAttributeNode(eC);
}var ew={"font":true,"span":true};
var et=null;
var eB=true;
if(qx.dom.Node.isElement(ev.previousSibling)&&ew[qx.dom.Node.getName(ev.previousSibling)]){et=ev.previousSibling;
}else if(ew[qx.dom.Node.getName(ev.parentNode)]){et=ev.parentNode;
eB=false;
}var eu=this.__cg.createDocumentFragment();
var eG;

if(eB&&et!=null){var ew=this.__cA(et);
eu.appendChild(ew.root);
eG=ew.inline;
}else{eG=this.__cg.createElement(cO);
eu.appendChild(eG);
}var eD=this.__cg.createTextNode(cS);
eG.appendChild(eD);
var eA=ev.parentNode;
if(ev==eA.lastChild){eA.appendChild(eu);
}else{eA.insertBefore(eu,ev.nextSibling);
}var es=this.__cf.getRange();
es.selectNodeContents(eG);
}return true;
}else{return false;
}},"mshtml":function(gr,gs){var gw=false;
var gx=dl;

for(var gt in gr){gx+=gt+bx+gr[gt]+cf;
}gx+=di;
var gu=this.__cf.getSelection();
var gv=this.__cr();
if(gu&&gu.type!=cr){try{gv.select();
gv.pasteHTML(gx);
gw=true;
}catch(e){}}this.__cf.resetSavedRange();
return gw;
},"default":function(gg,gh){return this.__cg.execCommand(gh.identifier,false,gg.src);
}}),__cA:function(eL){while(eL.firstChild&&eL.firstChild.nodeType==1){eL=eL.firstChild;
}var eP=this.__cF(eL);
var eT,eN,eR;
var eM=cS;
var parent=null;
var eS=null;
var eQ=eP.child;

while(eQ){eS=this.__cg.createElement(eQ[cR]?ct:cO);
eN=this.__cg.createAttribute(V);
eS.setAttributeNode(eN);
for(var eO in eQ){if(eO!=bS&&eO!=cR){eM+=eO+cs+eQ[eO]+cw;
}else if(eO==cR){eR=this.__cg.createAttribute(F);
eR.nodeValue=eQ[eO];
eS.setAttributeNode(eR);
}}eN.nodeValue=eM;

if(parent!=null){parent.appendChild(eS);
}else{eT=eS;
}parent=eS;
eQ=eQ.child;
eM=cS;
}return {root:eT,inline:eS};
},__cB:qx.core.Variant.select(cT,{"gecko|opera":function(a,b){var m=this.__cf.getSelection();
var f=this.__cf.getRange();
if(m.isCollapsed){var d=br+(++this.__cj);
var n=this.__cg.createElement(Q);
var g=this.__cg.createAttribute(cC);
var c=this.__cg.createAttribute(cU);
var h=this.__cg.createTextNode(a);
c.nodeValue=d;
n.setAttributeNode(c);
g.nodeValue=a;
n.setAttributeNode(g);
n.appendChild(h);
f.insertNode(n);
f.selectNode(n);
m.collapseToEnd();
return true;
}else{return this.__cg.execCommand(b.identifier,false,a);
}},"mshtml":function(ek,el){try{var en;
var em=this.__cr();
var eo=this.__cf;
var em=eo.getSavedRange()!=null?eo.getSavedRange():eo.getRange();

if(em!=null&&em.text!=cS){en=em.execCommand(el.identifier,false,ek);
}else{en=this.__cs(dp+ek+bT+ek+bn,el);
}this.__cf.resetSavedRange();
return en;
}catch(e){{};
return false;
}},"default":function(hj,hk){return this.__cg.execCommand(hk.identifier,false,hj);
}}),__cC:function(gy,gz){var gA=W;
if(qx.core.Variant.isSet(cT,bR)){gA+=this.__cD();
}return this.__cs(gA,gz);
},__cD:function(dX){var ec=cS;
var eb=dm;
var ea=[];
var ef=typeof dX!==I?dX:this.__cF();
var ed=ef.child;
var ee=false;
if(qx.lang.Object.isEmpty(ed)){return cS;
}
while(ed){ee=ed[cR]!=null;
ec+=ee?bg:eb;

for(var dY in ed){ec+=(dY!=bS&&dY!=cR)?dY+C+ed[dY]+cL:cS;
}ec+=ee?bI+ed[cR]+bT:bT;
ea.unshift(ee?db:bW);
ed=ed.child;
}if(ea.length==1&&ea[0]==db){ec+=M;
}for(var i=0,j=ea.length;i<j;i++){ec+=ea[i];
}return ec;
},__cE:function(){var gT=this.__cg.createDocumentFragment();
var gY=this.__cF();
var parent=gT;
var gW=gY.child;
var gU;
var gX=false;

while(gW){gX=gW[cR]!=null;
gU=this.__cg.createElement(gX?ct:cO);
parent.appendChild(gU);
for(var gS in gW){if(gS!=bS&&gS!=cR){qx.bom.element.Style.set(gU,gS,gW[gS]);
}}
if(gX){var gV=this.__cg.createAttribute(F);
gV.nodeValue=gW[cR];
gU.setAttributeNode(gV);
}parent=gU;
gW=gW.child;
}return gT;
},__cF:function(gi){var gk={};
var gl=null;
var gm=this.getCurrentStyles(gi);
gl=gk.child={};

for(var gj in gm){if(gj!=cM){gl[gj]=gm[gj];
}}if(gm[cM]){var gn=gm[cM];
for(var i=0,j=gn.length;i<j;i++){if(gl==null){gl=gk.child={};
}else{gl=gl.child={};
}gl[cN]=gn[i][cN];
gl[bM]=gn[i][bM];
}}if(gm[cN]&&gm[bM]){gl=gl.child={};
gl[cN]=gm[cN];
}return gk;
},getCurrentStyles:function(dw){if(dw==null){var dy=this.__cf.getSelection();

if(!dy||dy.focusNode==null){return {};
}dw=(dy.focusNode.nodeType==3)?dy.focusNode.parentNode:dy.focusNode;
}var dz=qx.dom.Hierarchy.getAncestors(dw);
var dB=qx.lang.Array.insertBefore(dz,dw,dz[0]);
var dx=this.__cG(dB);
var dA=this.__cH(dx,dB);
return dA;
},__cG:function(eg){var ej={};
var eh,ei;

for(var i=0,j=eg.length;i<j;i++){ei=eg[i];

for(var k=0,l=ei.style.length;k<l;k++){eh=ei.style[k];

if(eh.length>0&&typeof ej[eh]===I){ej[eh]=ei.style.getPropertyValue(eh);
}}if(ei.tagName.toUpperCase()==bl&&ei.size&&ej[cR]===undefined){ej[cR]=ei.size;
}}if(ej[cR]&&ej[cY]){delete ej[cY];
}return ej;
},__cH:function(dQ,dR){var dW=dR[0];
var dU=this.__cf.getContentWindow().getComputedStyle(dW,null);
var dS;
var dV={};

for(var dT in dQ){if(dT!=cR){dS=dU.getPropertyValue(dT);
}else{dS=dQ[dT];
}if(dT==dd&&dS==bU){dV[dT]=this.__cJ(dR);
}else if(dT==cM){dV[dT]=this.__cI(dR);
}else{dV[dT]=dS;
}}return dV;
},__cI:function(dq){var dt,dv,dr;
var du=[];
var ds=this.__cf.getContentWindow();

for(var i=0,j=dq.length;i<j;i++){dr=ds.getComputedStyle(dq[i],null);
dt=dr.getPropertyValue(cM);
dv=dr.getPropertyValue(cl);
if(dt!=cu){du.push({'text-decoration':dt,'color':dv});
}}return du;
},__cJ:function(fA){var fC,fB,fD;

for(var i=0;i<fA.length;i++){fC=fA[i];
fB=this.__cf.getContentWindow().getComputedStyle(fC,null);
fD=fB.getPropertyValue(dd);
if(fD!=bU){return fD;
}}},__cK:function(dC,dD){var dP=this.__cf.getSelection();
var dK=(qx.core.Variant.isSet(cT,cQ))?this.__cf.getRange():dK=dP.getRangeAt(0);
var dL=[];
var dO;
var dJ=[bA,cH];
var dE,i,j,dM;
dM=(qx.core.Variant.isSet(cT,cQ))?dK.parentElement():dK.commonAncestorContainer;
if(dM.tagName==bL){for(var i=0;i<dJ.length;i++){dE=dM.getElementsByTagName(dJ[i]);

for(var j=0;j<dE.length;j++){if(dE[j]){dL.push(dE[j]);
}}}}else if(qx.lang.Array.contains(dJ,dM.tagName)){dL.push(dM);
}
if(dL.length>0){for(var i=0;i<dL.length;i++){var dG=dL[i];
dO=(qx.core.Variant.isSet(cT,cQ))?
((dG==dM)||(dM.tagName==bL)):
dP.containsNode(dG,false);
for(j=0;j<dG.childNodes.length;j++){var dI=dG.childNodes[j];
if(dO||
(dP.focusNode.nodeValue&&qx.dom.Hierarchy.contains(dI,dP.focusNode)&&(dP.focusOffset==dP.focusNode.nodeValue.length))||
(qx.dom.Hierarchy.contains(dI,dP.anchorNode)&&(dP.anchorOffset==0))||
(dP.containsNode(dI,false))){dI.style.fontSize=(this.__ci[dC]||dC)+cz;
}}}}else{var dH=(qx.core.Variant.isSet(cT,cQ))?dM:dP.focusNode;
var dN=qx.dom.Hierarchy.getAncestors(dH);

for(i=0;i<dN.length;i++){if(dN[i].tagName==bF){if(((qx.core.Variant.isSet(cT,bR))&&
((dP.anchorOffset==0)&&
(dP.focusNode.nodeValue&&(dP.focusOffset==dP.focusNode.nodeValue.length))&&
qx.dom.Hierarchy.contains(dN[i].firstChild,dP.anchorNode)&&
qx.dom.Hierarchy.contains(dN[i].lastChild,dP.focusNode)))||
((qx.core.Variant.isSet(cT,cQ))&&(dK.htmlText==dN[i].innerHTML))){dN[i].style.fontSize=(this.__ci[dC]||dC)+cz;
}break;
}}}if(qx.core.Variant.isSet(cT,cQ)){this.__cg.body.focus();
this.__cf.getRange().select();
return this.__cg.execCommand(bN,false,dC);
}else if(qx.core.Variant.isSet(cT,bR)){var parent=dK.commonAncestorContainer;
if(parent.nodeType===1){var dF=parent.getElementsByTagName(cO);

for(i=0;i<dF.length;i++){if(dF[i].style.fontSize){dF[i].style.fontSize=null;
}}}}return this.__cg.execCommand(bN,false,dC);
},__cL:qx.core.Variant.select(cT,{"mshtml":function(gC,gD){this.__cg.body.focus();
return this.__cg.execCommand(bO,false,gC);
},"gecko|opera":function(o,p){this.__cg.body.focus();
return this.__cg.execCommand(bK,false,o);
},"webkit":function(eU,eV){var eW=this.__cf.getSelection();
var eX=this.__cf.getRange();
if(!eW||!eW.isCollapsed){this.__cg.body.focus();
this.__cg.execCommand(bO,false,eU);
if(eW){eW.collapseToEnd();
}return true;
}else{var fa=eW.anchorOffset;
var fb=eW.anchorOffset;
var eX=eW.getRangeAt(0);
var eY=eW.anchorNode;
while(fb>0){if(eY.nodeValue.charCodeAt(fb)==160||eY.nodeValue.charCodeAt(fb)==32){break;
}else{fb--;
}}while(fa<eY.nodeValue.length){if(eY.nodeValue.charCodeAt(fa)==160||eY.nodeValue.charCodeAt(fa)==32){break;
}else{fa++;
}}eX.setStart(eW.anchorNode,eW.anchorNode.nodeValue.charAt(fb)==cx?fb+1:fb);
eX.setEnd(eW.anchorNode,fa);
eW.addRange(eX);
this.__cg.body.focus();
this.__cg.execCommand(bO,false,eU);
eW.collapseToEnd();
return true;
}}}),__cM:function(gI,gJ){gI=gI!=null&&typeof gI==cV?gI:bU;
qx.bom.element.Style.set(this.__cg.body,J,gI);
return true;
},__cN:function(ha,hb){var hc,he,hd;
var hf=qx.bom.htmlarea.manager.Command;

if(ha==null){hc=null;
}else{hc=ha[0];
he=ha[1];
hd=ha[2];
}if(hc==null||typeof hc!=cV){qx.bom.element.Style.set(this.__cg.body,cy,cS);
qx.bom.element.Style.set(this.__cg.body,de,cS);
qx.bom.element.Style.set(this.__cg.body,dc,cS);
return true;
}else{if(hc.search(/^url.*\(/)==-1){hc=bb+hc+cD;
}}if(he!=null&&!qx.lang.String.contains(hf.__cl,he)){{};
return false;
}else{he=dj;
}
if(hd!=null){if(qx.lang.Type.isString(hd)&&!qx.lang.String.contains(hf.__ck,cX+hd+cX)){{};
return false;
}else{if(qx.lang.Type.isArray(hd)&&hd.length==2){hd=hd[0]+cx+hd[1];
}else{{};
return false;
}}}else{hd=L;
}qx.bom.element.Style.set(this.__cg.body,cy,hc);
qx.bom.element.Style.set(this.__cg.body,de,he);
qx.bom.element.Style.set(this.__cg.body,dc,hd);
return true;
},__cO:qx.core.Variant.select(cT,{"mshtml":function(go,gp){var gq=this.__cg.body.createTextRange();
gq.select();
return true;
},"default":function(fj,fk){return this.__cq(fk.identifier,false,fj);
}}),__cP:function(){return this.__cf.getSelectedText();
},__cQ:function(){return this.__cf.getSelectedHtml();
},__cR:qx.core.Variant.select(cT,{"webkit":function(fp,fq){var fr=this.__cf.getContextInformation();
var ft=this.__cf.getFocusNode();
if(fr.underline){ft.style.textDecoration=cu;
}else{if(fr.strikethrough){var fu=this.__cg.createElement(cO);
qx.bom.element.Style.set(fu,H,cW);
ft.appendChild(fu);
var fs=this.__cf.getSelection();

if(fs){fs.extend(fu,0);

if(!fs.isCollapsed){fs.collapseToEnd();
}}}else{ft.style.textDecoration=cW;
}}return true;
},"default":function(gG,gH){return this.__cq(gH.identifier,false,gG);
}}),__cS:qx.core.Variant.select(cT,{"webkit":function(gb,gc){var ge=this.__cf.getFocusNode();
var gf=this.__cg.createElement(cO);
qx.bom.element.Style.set(gf,H,co);
ge.appendChild(gf);
var gd=this.__cf.getSelection();

if(gd){gd.extend(gf,0);

if(!gd.isCollapsed){gd.collapseToEnd();
}}return true;
},"default":function(hl,hm){return this.__cq(hm.identifier,false,hl);
}})},destruct:function(){this.__cg=this.__cf=this._commands=this.__ch=this.__ci=null;
}});
})();
(function(){var dS="execute",dR="changeValue",dQ="",dP="changeSelection",dO="icon/16/actions/format-justify-fill.png",dN="<tr>",dM="icon/16/actions/format-justify-left.png",dL="icon/16/actions/format-justify-center.png",dK="icon/16/actions/edit-undo.png",dJ="</tr>",cS="#",cR="qooxdoo logo",cQ="icon/16/actions/format-justify-right.png",cP="icon/16/actions/edit-redo.png",cO="icon/16/actions/system-search.png",cN="Online Forum",cM="New",cL="icon/16/actions/edit-cut.png",cK="Search in files",cJ="Georgia",ea="Left aligned",eb="Undo",dX="border-separator",dY="http://",dV="icon/16/actions/document-open.png",dW="Print",dT="Change Font Size",dU="Perl",ec="View",ed="C Dialect",ds="showcase/htmleditor/format-list-unordered.png",dr="BgColor (Hex): ",du="Indent More",dt="Save as...",dw="Show line numbers",dv="icon/16/actions/document-save.png",dy="icon/16/actions/format-text-strikethrough.png",dx="Quickstart",dq="Cut",dp="Ctrl+N",bA="icon/16/actions/edit-paste.png",bB="Align Right",bC="Search",bD="Help",bE="Format Italic",bF="Redo",bG="Show status bar",bH="ANSI to OEM",bI="Editor",bJ="Paragraph",er="OK",eq="Edit",ep="Ctrl+O",eo="icon/16/actions/document-print.png",ev="Comic Sans MS",eu="Tahoma",et="scale",es="icon/16/actions/format-text-italic.png",ex="Show console",ew="Close",cj="showcase.page.htmleditor.Content",ck="<td>First Row, First cell</td>",ch="solid",ci="htmlarea/image/qooxdoo_logo.png",cn="icon/16/actions/document-save-as.png",co="Python",cl="icon/16/apps/utilities-help.png",cm="Search next...",cf="Show tree",cg="Align Justify",bR="Spaces to tabs",bQ="Right aligned",bT="Inserted Unordered List",bS="OEM to ANSI",bN="JavaScript",bM="white",bP="HTML Code:",bO="C",bL="Cancel",bK="<td>Second Row, First cell</td>",ct="Save",cu="</tbody>",cv="Capitals",cw="icon/16/actions/application-exit.png",cp="ASCII table",cq="C Plus Plus",cr="decoration/menu/bar-background.png",cs="Tabs to spaces",cx="Replace in files",cy="Uppercase",cc="Arial Black",cb="Ctrl+P",ca="Topics",bY="Impact",bX="XML",bW="Panes",bV="Justified",bU="C Sharp",ce="Redo Last Undo Step",cd="Ctrl+X",cz="Format Bold",cA="Search previous...",cB="Change Font Family",cC="Show ruler",cD="right",cE="Color (Hex): ",cF="Insert Hyperlink",cG="Copy",cH="icon/16/actions/format-indent-more.png",cI="Paste",cW="Remove Format",cV="Ctrl+C",cU="blank.html",cT="</table>",db="12px ",da="<td>First Row, Second cell</td>",cY="Ctrl+Z",cX="Insert Ordered List",dd="Centered",dc="Ctrl+R",dk="Show macros",dl="Show tags",di="Courier",dj="Courier New",dg="Info...",dh="Format",de="<td>Second Row, Second cell</td>",df="File",dm="Show tabs",dn="icon/16/actions/edit-clear.png",dC='<p>qooxdoo (pronounced [ku:ksdu:]) is a comprehensive and innovative Ajax application framework. Leveraging object-oriented JavaScript allows developers to build impressive cross-browser applications. No HTML, CSS nor DOM knowledge is needed. qooxdoo includes a platform-independent development tool chain, a state-of-the-art GUI toolkit and an advanced client-server communication layer. It is Open Source under an LGPL (GNU Lesser General Public License) / EPL (Eclipse Public License) dual <a href="http://qooxdoo.org/license" class="wikilink1" title="license" target="_blank">license</a>.</p>',dB="Align Left",dE="icon/16/actions/edit-copy.png",dD="Undo Last Change",dG="Search...",dF="<tbody>",dI="Times New Roman",dH="Open",dA="icon/16/actions/format-text-underline.png",dz="Objective C",ek="Align Center",el="Exit",em="Lucida Console",en="Ctrl+S",eg="icon/16/actions/format-indent-less.png",eh="icon/16/actions/format-text-bold.png",ei="Syntax",ej="Arial",ee="Verdana",ef="Indent Less",bz="showcase/htmleditor/format-list-ordered.png",by="Format Strikethrough",bx="Format Underline",bw="icon/16/actions/document-new.png",bv="<table border='1'>",bu="Lowercase",bt="Replace",bs="HTML";
qx.Class.define(cj,{extend:showcase.page.AbstractDesktopContent,construct:function(D){arguments.callee.base.call(this,D);
},members:{__cT:null,__cU:null,_addWindowContent:function(Y){Y.set({layout:new qx.ui.layout.Canvas(),width:540,height:400,caption:bI});
var bb=dC;
this.__cT=new qx.ui.embed.HtmlArea(bb,null,cU);
this.__cT.set({width:540,height:370,margin:5});
var ba=new qx.ui.layout.VBox(0);
var bc=new qx.ui.container.Composite(ba).set({width:540,height:370,backgroundColor:bM});
var bd=this.__dg();
bc.add(bd);
var toolbar=this.__df();
bc.add(toolbar);
bc.add(this.__cT,{flex:1});
Y.add(bc,{edge:0});
},__cV:function(e){var u=window.prompt(cE,cS);
this.setTextColor(u);
},__cW:function(e){var fh=window.prompt(dr,cS);
this.setTextBackgroundColor(fh);
},__cX:function(e){var t={src:qx.util.ResourceManager.getInstance().toUri(ci),border:0,title:cR,alt:cR};
this.insertImage(t);
},__cY:function(e){var C=bv+dF+dN+ck+da+dJ+dN+bK+de+dJ+cu+cT;
this.insertHtml(C);
},__da:function(e){var F=new qx.ui.window.Window(cF);
F.setLayout(new qx.ui.layout.VBox(20));
F.set({width:400,showMaximize:false,showMinimize:false});
var J=new qx.ui.form.TextField(dY);
F.add(J);
var H=new qx.ui.layout.HBox(10);
H.setAlignX(cD);
var I=new qx.ui.container.Composite(H);
var E=new qx.ui.form.Button(er);
E.setWidth(60);
E.addListener(dS,function(e){this.insertHyperLink(J.getValue());
F.close();
},this);
I.add(E);
var G=new qx.ui.form.Button(bL);
G.setWidth(60);
G.addListener(dS,function(e){F.close();
},this);
I.add(G);
F.add(I);
F.center();
F.open();
this.__cU.saveRange();
},__db:function(e){var v=window.prompt(bP,dQ);
this.insertHtml(v);
},__dc:function(){var bk=new qx.ui.form.SelectBox;
bk.set({toolTipText:cB,focusable:false,keepFocus:true,width:120,height:16,margin:[4,0]});
bk.add(new qx.ui.form.ListItem(dQ));
var bl=[eu,ee,dI,ej,cc,dj,di,cJ,bY,ev,em];
var bj;

for(var i=0,j=bl.length;i<j;i++){bj=new qx.ui.form.ListItem(bl[i]);
bj.set({focusable:false,keepFocus:true,font:qx.bom.Font.fromString(db+bl[i])});
bk.add(bj);
}bk.addListener(dP,function(e){var eV=e.getData()[0].getLabel();

if(eV!=dQ){this.setFontFamily(eV);
bk.setSelection([bk.getChildren()[0]]);
}},this.__cT);
return bk;
},__dd:function(){var eX=new qx.ui.form.SelectBox;
eX.set({toolTipText:dT,focusable:false,keepFocus:true,width:50,height:16,margin:[4,0]});
eX.add(new qx.ui.form.ListItem(dQ));
var eW;

for(var i=1;i<=7;i++){eW=new qx.ui.form.ListItem(i+dQ);
eW.set({focusable:false,keepFocus:true});
eX.add(eW);
}eX.addListener(dP,function(e){var P=e.getData()[0].getLabel();

if(P!=dQ){this.setFontSize(P);
eX.setSelection([eX.getChildren()[0]]);
}},this.__cT);
return eX;
},__de:function(){return [{bold:{text:cz,image:eh,action:this.__cT.setBold},italic:{text:bE,image:es,action:this.__cT.setItalic},underline:{text:bx,image:dA,action:this.__cT.setUnderline},strikethrough:{text:by,image:dy,action:this.__cT.setStrikeThrough},removeFormat:{text:cW,image:dn,action:this.__cT.removeFormat}},{alignLeft:{text:dB,image:dM,action:this.__cT.setJustifyLeft},alignCenter:{text:ek,image:dL,action:this.__cT.setJustifyCenter},alignRight:{text:bB,image:cQ,action:this.__cT.setJustifyRight},alignJustify:{text:cg,image:dO,action:this.__cT.setJustifyFull}},{indent:{text:du,image:cH,action:this.__cT.insertIndent},outdent:{text:ef,image:eg,action:this.__cT.insertOutdent}},{ol:{text:cX,image:bz,action:this.__cT.insertOrderedList},ul:{text:bT,image:ds,action:this.__cT.insertUnorderedList}},{undo:{text:dD,image:dK,action:this.__cT.undo},redo:{text:ce,image:cP,action:this.__cT.redo}}];
},__df:function(){var toolbar=new qx.ui.toolbar.ToolBar;
var eQ;
var eR=this.__de();

for(var i=0,j=eR.length;i<j;i++){var eS=new qx.ui.toolbar.Part;
toolbar.add(eS);

for(var eT in eR[i]){var eU=eR[i][eT];

if(eU.custom){eQ=eU.custom.call(this);
}else{eQ=new qx.ui.toolbar.Button(null,eU.image);
eQ.set({focusable:false,keepFocus:true,center:true,toolTipText:eU.text?eU.text:dQ});
eQ.addListener(dS,eU.action,this.__cT);
}eS.add(eQ);
}}return toolbar;
},debugRadio:function(e){alert("This command is not yet implemented!");
},debugCommand:function(e){alert("This command is not yet implemented!");
},debugButton:function(e){alert("This command is not yet implemented!");
},debugCheckBox:function(e){alert("This command is not yet implemented!");
},createCommands:function(){this._newCommand=new qx.ui.core.Command(dp);
this._newCommand.addListener(dS,this.debugCommand);
this._openCommand=new qx.ui.core.Command(ep);
this._openCommand.addListener(dS,this.debugCommand);
this._saveCommand=new qx.ui.core.Command(en);
this._saveCommand.addListener(dS,this.debugCommand);
this._undoCommand=new qx.ui.core.Command(cY);
this._undoCommand.addListener(dS,this.debugCommand);
this._redoCommand=new qx.ui.core.Command(dc);
this._redoCommand.addListener(dS,this.debugCommand);
this._cutCommand=new qx.ui.core.Command(cd);
this._cutCommand.addListener(dS,this.debugCommand);
this._copyCommand=new qx.ui.core.Command(cV);
this._copyCommand.addListener(dS,this.debugCommand);
this._pasteCommand=new qx.ui.core.Command(cb);
this._pasteCommand.addListener(dS,this.debugCommand);
this._pasteCommand.setEnabled(false);
},__dg:function(){this.createCommands();
var menubar=new qx.ui.menubar.MenuBar().set({decorator:new qx.ui.decoration.Single().set({backgroundImage:cr,backgroundRepeat:et,bottom:[1,ch,dX]})});
var x=new qx.ui.menubar.Button(df,null,this.getFileMenu());
var w=new qx.ui.menubar.Button(eq,null,this.getEditMenu());
var z=new qx.ui.menubar.Button(bC,null,this.getSearchMenu());
var y=new qx.ui.menubar.Button(ec,null,this.getViewMenu());
var B=new qx.ui.menubar.Button(dh,null,this.getFormatMenu());
var A=new qx.ui.menubar.Button(bD,null,this.getHelpMenu());
menubar.add(x);
menubar.add(w);
menubar.add(z);
menubar.add(y);
menubar.add(B);
menubar.add(new qx.ui.core.Spacer(),{flex:1});
menubar.add(A);
return menubar;
},getFileMenu:function(){var S=new qx.ui.menu.Menu;
var Q=new qx.ui.menu.Button(cM,bw,this._newCommand);
var U=new qx.ui.menu.Button(dH,dV,this._openCommand);
var T=new qx.ui.menu.Button(ew);
var X=new qx.ui.menu.Button(ct,dv,this._saveCommand);
var W=new qx.ui.menu.Button(dt,cn);
var V=new qx.ui.menu.Button(dW,eo);
var R=new qx.ui.menu.Button(el,cw);
T.addListener(dS,this.debugButton);
W.addListener(dS,this.debugButton);
V.addListener(dS,this.debugButton);
R.addListener(dS,this.debugButton);
S.add(Q);
S.add(U);
S.add(T);
S.add(X);
S.add(W);
S.add(V);
S.add(R);
return S;
},getEditMenu:function(){var bn=new qx.ui.menu.Menu;
var bq=new qx.ui.menu.Button(eb,dK,this._undoCommand);
var bp=new qx.ui.menu.Button(bF,cP,this._redoCommand);
var bm=new qx.ui.menu.Button(dq,cL,this._cutCommand);
var br=new qx.ui.menu.Button(cG,dE,this._copyCommand);
var bo=new qx.ui.menu.Button(cI,bA,this._pasteCommand);
bn.add(bq);
bn.add(bp);
bn.addSeparator();
bn.add(bm);
bn.add(br);
bn.add(bo);
return bn;
},getSearchMenu:function(){var eG=new qx.ui.menu.Menu;
var eE=new qx.ui.menu.Button(dG,cO);
var eJ=new qx.ui.menu.Button(cm);
var eF=new qx.ui.menu.Button(cA);
var eI=new qx.ui.menu.Button(bt);
var eD=new qx.ui.menu.Button(cK,cO);
var eH=new qx.ui.menu.Button(cx);
eF.setEnabled(false);
eE.addListener(dS,this.debugButton);
eJ.addListener(dS,this.debugButton);
eF.addListener(dS,this.debugButton);
eI.addListener(dS,this.debugButton);
eD.addListener(dS,this.debugButton);
eH.addListener(dS,this.debugButton);
eG.add(eE);
eG.add(eJ);
eG.add(eF);
eG.add(eI);
eG.addSeparator();
eG.add(eD);
eG.add(eH);
return eG;
},getViewMenu:function(){var eK=new qx.ui.menu.Menu;
var eM=new qx.ui.menu.Button(bW,null,null,this.getPanesMenu());
var eP=new qx.ui.menu.Button(ei,null,null,this.getSyntaxMenu());
var eO=new qx.ui.menu.CheckBox(cC);
var eN=new qx.ui.menu.CheckBox(dw);
var eL=new qx.ui.menu.Button(cp);
eO.addListener(dR,this.debugCheckBox);
eN.addListener(dR,this.debugCheckBox);
eL.addListener(dS,this.debugButton);
eK.add(eM);
eK.add(eP);
eK.addSeparator();
eK.add(eO);
eK.add(eN);
eK.addSeparator();
eK.add(eL);
return eK;
},getPanesMenu:function(){var n=new qx.ui.menu.Menu;
var p=new qx.ui.menu.CheckBox(dm);
var r=new qx.ui.menu.CheckBox(bG);
var s=new qx.ui.menu.CheckBox(cf);
var o=new qx.ui.menu.CheckBox(dk);
var q=new qx.ui.menu.CheckBox(dl);
var m=new qx.ui.menu.CheckBox(ex);
p.setValue(true);
r.setValue(true);
o.setValue(true);
p.addListener(dR,this.debugCheckBox);
r.addListener(dR,this.debugCheckBox);
s.addListener(dR,this.debugCheckBox);
o.addListener(dR,this.debugCheckBox);
q.addListener(dR,this.debugCheckBox);
m.addListener(dR,this.debugCheckBox);
n.add(r);
n.add(p);
n.addSeparator();
n.add(s);
n.add(o);
n.add(q);
n.add(m);
return n;
},getSyntaxMenu:function(){var fd=new qx.ui.menu.Menu;
var eY=new qx.ui.menu.RadioButton(bs);
var fb=new qx.ui.menu.RadioButton(bX);
var fa=new qx.ui.menu.RadioButton(bN);
var fc=new qx.ui.menu.Button(ed,null,null,this.getSyntaxCMenu());
var fg=new qx.ui.menu.RadioButton(dU);
var fe=new qx.ui.menu.RadioButton(co);
fd.add(eY);
fd.add(fb);
fd.add(fa);
fd.add(fc);
fd.add(fg);
fd.add(fe);
var ff=new qx.ui.form.RadioGroup;
ff.add(eY,fb,fa,fg,fe);
ff.add.apply(ff,fc.getMenu().getChildren());
ff.addListener(dP,this.debugRadio);
return fd;
},getSyntaxCMenu:function(){var bf=new qx.ui.menu.Menu;
var be=new qx.ui.menu.RadioButton(bO);
var bi=new qx.ui.menu.RadioButton(bU);
var bh=new qx.ui.menu.RadioButton(dz);
var bg=new qx.ui.menu.RadioButton(cq);
bf.add(be);
bf.add(bi);
bf.add(bh);
bf.add(bg);
return bf;
},getFormatMenu:function(){var d=new qx.ui.menu.Menu;
var c=new qx.ui.menu.Button(bJ,null,null,this.getParagraphMenu());
var g=new qx.ui.menu.Button(cs);
var h=new qx.ui.menu.Button(bR);
var b=new qx.ui.menu.Button(cy);
var f=new qx.ui.menu.Button(bu);
var a=new qx.ui.menu.Button(cv);
var l=new qx.ui.menu.Button(bS);
var k=new qx.ui.menu.Button(bH);
g.addListener(dS,this.debugButton);
h.addListener(dS,this.debugButton);
b.addListener(dS,this.debugButton);
f.addListener(dS,this.debugButton);
a.addListener(dS,this.debugButton);
l.addListener(dS,this.debugButton);
k.addListener(dS,this.debugButton);
d.add(c);
d.add(g);
d.add(h);
d.addSeparator();
d.add(b);
d.add(f);
d.add(a);
d.addSeparator();
d.add(l);
d.add(k);
return d;
},getParagraphMenu:function(){var K=new qx.ui.menu.Menu;
var N=new qx.ui.menu.Button(ea,dM);
var O=new qx.ui.menu.Button(bQ,cQ);
var L=new qx.ui.menu.Button(dd,dL);
var M=new qx.ui.menu.Button(bV,dO);
N.addListener(dS,this.debugButton);
O.addListener(dS,this.debugButton);
L.addListener(dS,this.debugButton);
M.addListener(dS,this.debugButton);
K.add(N);
K.add(O);
K.add(L);
K.add(M);
return K;
},getHelpMenu:function(){var ey=new qx.ui.menu.Menu;
var eA=new qx.ui.menu.Button(ca,cl);
var eC=new qx.ui.menu.Button(dx);
var eB=new qx.ui.menu.Button(cN);
var ez=new qx.ui.menu.Button(dg);
eA.addListener(dS,this.debugButton);
eC.addListener(dS,this.debugButton);
eB.addListener(dS,this.debugButton);
ez.addListener(dS,this.debugButton);
ey.add(eA);
ey.add(eC);
ey.addSeparator();
ey.add(eB);
ey.addSeparator();
ey.add(ez);
return ey;
}}});
})();
(function(){var b="qx.ui.menubar.MenuBar",a="menubar";
qx.Class.define(b,{extend:qx.ui.toolbar.ToolBar,properties:{appearance:{refine:true,init:a}}});
})();
(function(){var j="qx.dom.Element";
qx.Class.define(j,{statics:{hasChild:function(parent,m){return m.parentNode===parent;
},hasChildren:function(A){return !!A.firstChild;
},hasChildElements:function(u){u=u.firstChild;

while(u){if(u.nodeType===1){return true;
}u=u.nextSibling;
}return false;
},getParentElement:function(q){return q.parentNode;
},isInDom:function(r,s){if(!s){s=window;
}var t=s.document.getElementsByTagName(r.nodeName);

for(var i=0,l=t.length;i<l;i++){if(t[i]===r){return true;
}}return false;
},insertAt:function(v,parent,w){var x=parent.childNodes[w];

if(x){parent.insertBefore(v,x);
}else{parent.appendChild(v);
}return true;
},insertBegin:function(d,parent){if(parent.firstChild){this.insertBefore(d,parent.firstChild);
}else{parent.appendChild(d);
}},insertEnd:function(k,parent){parent.appendChild(k);
},insertBefore:function(g,h){h.parentNode.insertBefore(g,h);
return true;
},insertAfter:function(o,p){var parent=p.parentNode;

if(p==parent.lastChild){parent.appendChild(o);
}else{return this.insertBefore(o,p.nextSibling);
}return true;
},remove:function(B){if(!B.parentNode){return false;
}B.parentNode.removeChild(B);
return true;
},removeChild:function(n,parent){if(n.parentNode!==parent){return false;
}parent.removeChild(n);
return true;
},removeChildAt:function(y,parent){var z=parent.childNodes[y];

if(!z){return false;
}parent.removeChild(z);
return true;
},replaceChild:function(e,f){if(!f.parentNode){return false;
}f.parentNode.replaceChild(e,f);
return true;
},replaceAt:function(a,b,parent){var c=parent.childNodes[b];

if(!c){return false;
}parent.replaceChild(a,c);
return true;
}}});
})();
