qx.$$packageData['abb0d3b5ba3a']={"resources":{}};
(function(){var u="pressed",t="abandoned",s="hovered",r="checked",q="Space",p="Enter",o="mouseup",n="mousedown",m="Boolean",l="_applyValue",f="mouseover",k="mouseout",i="qx.ui.form.ToggleButton",d="keydown",c="changeValue",h="button",g="keyup",j="execute";
qx.Class.define(i,{extend:qx.ui.basic.Atom,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IBooleanForm,qx.ui.form.IExecutable],construct:function(v,w){arguments.callee.base.call(this,v,w);
this.addListener(f,this._onMouseOver);
this.addListener(k,this._onMouseOut);
this.addListener(n,this._onMouseDown);
this.addListener(o,this._onMouseUp);
this.addListener(d,this._onKeyDown);
this.addListener(g,this._onKeyUp);
this.addListener(j,this._onExecute,this);
},properties:{appearance:{refine:true,init:h},focusable:{refine:true,init:true},value:{check:m,nullable:true,event:c,apply:l,init:false}},members:{_applyValue:function(a,b){a?this.addState(r):this.removeState(r);
},_onExecute:function(e){this.toggleValue();
},_onMouseOver:function(e){if(e.getTarget()!==this){return;
}this.addState(s);

if(this.hasState(t)){this.removeState(t);
this.addState(u);
}},_onMouseOut:function(e){if(e.getTarget()!==this){return;
}this.removeState(s);

if(this.hasState(u)){if(!this.getValue()){this.removeState(u);
}this.addState(t);
}},_onMouseDown:function(e){if(!e.isLeftPressed()){return;
}this.capture();
this.removeState(t);
this.addState(u);
e.stopPropagation();
},_onMouseUp:function(e){this.releaseCapture();

if(this.hasState(t)){this.removeState(t);
}else if(this.hasState(u)){this.execute();
}this.removeState(u);
e.stopPropagation();
},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case p:case q:this.removeState(t);
this.addState(u);
e.stopPropagation();
}},_onKeyUp:function(e){if(!this.hasState(u)){return;
}
switch(e.getKeyIdentifier()){case p:case q:this.removeState(t);
this.execute();
this.removeState(u);
e.stopPropagation();
}}}});
})();
(function(){var b="checkbox",a="qx.ui.form.CheckBox";
qx.Class.define(a,{extend:qx.ui.form.ToggleButton,include:[qx.ui.form.MForm,qx.ui.form.MModelProperty],implement:[qx.ui.form.IForm,qx.ui.form.IModel],construct:function(c){{};
arguments.callee.base.call(this,c);
this.setValue(false);
},properties:{appearance:{refine:true,init:b},allowGrowX:{refine:true,init:false}}});
})();
(function(){var e="textarea",d="qx.ui.form.TextArea",c="_applyWrap",b="Boolean";
qx.Class.define(d,{extend:qx.ui.form.AbstractField,construct:function(f){arguments.callee.base.call(this,f);
this.initWrap();
},properties:{wrap:{check:b,init:true,apply:c},appearance:{refine:true,init:e}},members:{_createInputElement:function(){return new qx.html.Input(e);
},_applyWrap:function(g,h){this.getContentElement().setWrap(g);
},_getContentHint:function(){var a=arguments.callee.base.call(this);
a.height=a.height*4;
a.width=this._getTextSize().width*20;
return a;
}}});
})();
(function(){var l="value",k="placeholder",j="Button",h="CheckBox:",g="TextArea:",f="Boolean",e="RepeatButton:",d="execute",c="Website 2",b="Text",U="ToggleButton",T="password",S="RadioButton 3",R="showcase.page.form.Content",Q="Button:",P="ComboBox:",O="ToggleButton:",N="Options",M="RadioButton",L="0",s="MenuButton:",t="PasswordField:",q="SplitButton",r="Buttons",o="",p="RadioButtons:",m="dd.mm.YYYY",n="List:",u="SplitButton:",v="Option",C="RadioButton 1",A="Spinner:",F="Selection",E="DateField:",H="RadioButton 2",G="Number",x="CheckBox",K="SelectBox:",J="Website 3",I="MenuButton",w="Website 1",y="Slider:",z="TextField:",B="Item ",D="RadioButtonGroup:";
qx.Class.define(R,{extend:showcase.AbstractContent,construct:function(X){arguments.callee.base.call(this,X);
this.setView(this._createView());
},members:{_createView:function(){var bo=new qx.ui.layout.Grid(20,5);
bo.setColumnFlex(0,1);
bo.setColumnFlex(1,1);
var by=new qx.ui.container.Composite(bo);
by.setPadding(10);
var bg=1;
var Y=new qx.ui.groupbox.GroupBox(b);
Y.setLayout(new qx.ui.layout.Grid(8,8));
Y.setWidth(290);
by.add(Y,{row:0,column:0});
var bx=new qx.ui.form.TextField();
bx.setPlaceholder(k);
bx.setTabIndex(bg++);
var bi=new qx.ui.basic.Label(z);
bi.setBuddy(bx);
Y.add(bi,{row:0,column:0});
Y.add(bx,{row:0,column:1});
var bf=new qx.ui.form.PasswordField();
bf.setTabIndex(bg++);
bf.setPlaceholder(T);
bi=new qx.ui.basic.Label(t);
bi.setBuddy(bf);
Y.add(bi,{row:1,column:0});
Y.add(bf,{row:1,column:1});
var ba=new qx.ui.form.TextArea();
ba.setTabIndex(bg++);
ba.setPlaceholder(k);
bi=new qx.ui.basic.Label(g);
bi.setBuddy(ba);
Y.add(bi,{row:2,column:0});
Y.add(ba,{row:2,column:1});
var bb=new qx.ui.form.ComboBox();
bb.setTabIndex(bg++);
bb.setPlaceholder(k);
bi=new qx.ui.basic.Label(P);
bi.setBuddy(bb);
Y.add(bi,{row:3,column:0});
Y.add(bb,{row:3,column:1});
this.__ep(bb);
var bq=new qx.ui.form.DateField();
bq.setTabIndex(bg++);
bq.setPlaceholder(m);
bi=new qx.ui.basic.Label(E);
bi.setBuddy(bq);
Y.add(bi,{row:4,column:0});
Y.add(bq,{row:4,column:1});
var bh=new qx.ui.groupbox.GroupBox(F);
bh.setLayout(new qx.ui.layout.Grid(8,8));
bh.setWidth(290);
by.add(bh,{row:1,column:0,rowSpan:2});
var br=new qx.ui.form.SelectBox();
br.setTabIndex(bg++);
bi=new qx.ui.basic.Label(K);
bi.setBuddy(br);
bh.add(bi,{row:0,column:0});
bh.add(br,{row:0,column:1});
this.__ep(br);
var bw=new qx.ui.form.List();
bw.setTabIndex(bg++);
bw.setHeight(60);
bw.setWidth(155);
bi=new qx.ui.basic.Label(n);
bi.setBuddy(bw);
bh.add(bi,{row:1,column:0});
bh.add(bw,{row:1,column:1});
this.__ep(bw);
var bp=new qx.ui.form.RadioButtonGroup();
bp.add(new qx.ui.form.RadioButton(C).set({tabIndex:bg++}));
bp.add(new qx.ui.form.RadioButton(H).set({tabIndex:bg++}));
bp.add(new qx.ui.form.RadioButton(S).set({tabIndex:bg++}));
bi=new qx.ui.basic.Label(D);
bi.setBuddy(bp);
bh.add(bi,{row:2,column:0});
bh.add(bp,{row:2,column:1});
var bu=new qx.ui.groupbox.GroupBox(r);
bu.setLayout(new qx.ui.layout.Grid(8,8));
bu.setWidth(250);
by.add(bu,{row:0,column:1});
var bv=new qx.ui.form.Button(j).set({tabIndex:bg++});
bi=new qx.ui.basic.Label(Q);
bi.setBuddy(bv);
bu.add(bi,{row:0,column:0});
bu.add(bv,{row:0,column:1});
var bd=new qx.ui.form.ToggleButton(U).set({tabIndex:bg++});
bi=new qx.ui.basic.Label(O);
bi.setBuddy(bd);
bu.add(bi,{row:1,column:0});
bu.add(bd,{row:1,column:1});
var bl=new qx.ui.form.RepeatButton(L).set({tabIndex:bg++});
bi=new qx.ui.basic.Label(e);
bi.setBuddy(bl);
bu.add(bi,{row:2,column:0});
bu.add(bl,{row:2,column:1});
var bm=new qx.ui.form.MenuButton(I,null,this.__eq()).set({tabIndex:bg++});
bi=new qx.ui.basic.Label(s);
bi.setBuddy(bm);
bu.add(bi,{row:3,column:0});
bu.add(bm,{row:3,column:1});
var be=new qx.ui.form.SplitButton(q,null,this.__er()).set({tabIndex:bg++});
bi=new qx.ui.basic.Label(u);
bi.setBuddy(be);
bu.add(bi,{row:4,column:0});
bu.add(be,{row:4,column:1});
bl.addListener(d,function(){var a=parseInt(bl.getLabel())+1;
bl.setLabel(a.toString());
});
var bc=new qx.ui.groupbox.GroupBox(f);
bc.setLayout(new qx.ui.layout.Grid(8,8));
bc.setWidth(250);
by.add(bc,{row:1,column:1});
var bs=new qx.ui.form.CheckBox(x).set({tabIndex:bg++});
bi=new qx.ui.basic.Label(h);
bi.setBuddy(bs);
bc.add(bi,{row:0,column:0});
bc.add(bs,{row:0,column:1});
var bk=new qx.ui.form.RadioButton(M).set({tabIndex:bg++});
bc.add(new qx.ui.basic.Label(p),{row:1,column:0});
bc.add(bk,{row:1,column:1});
var bt=new qx.ui.groupbox.GroupBox(G);
bt.setLayout(new qx.ui.layout.Grid(8,8));
bt.setWidth(250);
by.add(bt,{row:2,column:1});
var bj=new qx.ui.form.Spinner(0,50,100).set({tabIndex:bg++});
bi=new qx.ui.basic.Label(A);
bi.setBuddy(bj);
bt.add(bi,{row:0,column:0});
bt.add(bj,{row:0,column:1});
var bn=new qx.ui.form.Slider().set({tabIndex:bg++});
bn.setWidth(130);
bi=new qx.ui.basic.Label(y);
bi.setBuddy(bn);
bt.add(bi,{row:1,column:0});
bt.add(bn,{row:1,column:1});
bn.bind(l,bj,l);
bj.bind(l,bn,l);
return by;
},__ep:function(V){for(var i=0;i<10;i++){var W=new qx.ui.form.ListItem(B+i);
V.add(W);
}},__eq:function(){var bD=new qx.ui.menu.Menu;

for(var i=0;i<3;i++){bD.add(new qx.ui.menu.RadioButton(v+i));
}var bG=new qx.ui.form.RadioGroup;
bG.add.apply(bG,bD.getChildren());
var bF=new qx.ui.menu.Menu();

for(var i=0;i<3;i++){var bH=new qx.ui.menu.Button(j+i);
bF.add(bH);
}var bE=new qx.ui.menu.Button(N,o,null,bD);
bF.addSeparator();
bF.add(bE);
return bF;
},__er:function(){var bz=new qx.ui.menu.Menu;
var bC=new qx.ui.menu.Button(w);
var bA=new qx.ui.menu.Button(c);
var bB=new qx.ui.menu.Button(J);
bz.add(bC);
bz.add(bA);
bz.add(bB);
return bz;
}}});
})();
(function(){var o="button",n="hovered",m="pressed",l="arrow",k="Enter",j="Space",i="abandoned",h="both",g="String",f="changeVisibility",E="splitbutton",D="changeShow",C="mouseout",B="keydown",A="execute",z="_applyMenu",y="icon",x="mouseover",w="keyup",v="qx.ui.menu.Menu",t="_applyIcon",u="label",r="_applyShow",s="changeMenu",p="_applyLabel",q="qx.ui.form.SplitButton";
qx.Class.define(q,{extend:qx.ui.core.Widget,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IExecutable],construct:function(H,I,J,K){arguments.callee.base.call(this);
this._setLayout(new qx.ui.layout.HBox);
this._createChildControl(l);
this.addListener(x,this._onMouseOver,this,true);
this.addListener(C,this._onMouseOut,this,true);
this.addListener(B,this._onKeyDown);
this.addListener(w,this._onKeyUp);
if(H!=null){this.setLabel(H);
}
if(I!=null){this.setIcon(I);
}
if(J!=null){this.setMenu(J);
}
if(K!=null){this.setCommand(K);
}},properties:{appearance:{refine:true,init:E},focusable:{refine:true,init:true},label:{apply:p,nullable:true,check:g},icon:{check:g,apply:t,nullable:true,themeable:true},show:{init:h,check:[h,u,y],themeable:true,inheritable:true,apply:r,event:D},menu:{check:v,nullable:true,apply:z,event:s}},members:{__es:null,_createChildControlImpl:function(a){var b;

switch(a){case o:b=new qx.ui.form.Button;
b.addListener(A,this._onButtonExecute,this);
b.setFocusable(false);
this._addAt(b,0,{flex:1});
break;
case l:b=new qx.ui.form.MenuButton;
b.setFocusable(false);
this._addAt(b,1);
break;
}return b||arguments.callee.base.call(this,a);
},_forwardStates:{hovered:1,focused:1},_applyLabel:function(T,U){var V=this.getChildControl(o);
T==null?V.resetLabel():V.setLabel(T);
},_applyIcon:function(N,O){var P=this.getChildControl(o);
N==null?P.resetIcon():P.setIcon(N);
},_applyMenu:function(Q,R){var S=this.getChildControl(l);

if(Q){S.resetEnabled();
S.setMenu(Q);
Q.setOpener(this);
Q.addListener(f,this._onChangeMenuVisibility,this);
}else{S.setEnabled(false);
S.resetMenu();
}
if(R){R.removeListener(f,this._onChangeMenuVisibility,this);
R.resetOpener();
}},_applyShow:function(F,G){},_onMouseOver:function(e){e.stopPropagation();
this.addState(n);
delete this.__es;
},_onMouseOut:function(e){e.stopPropagation();
if(!this.hasState(n)){return;
}var d=e.getRelatedTarget();

if(qx.ui.core.Widget.contains(this,d)){return;
}var c=this.getMenu();

if(c&&c.isVisible()){this.__es=true;
return;
}this.removeState(n);
},_onKeyDown:function(e){var L=this.getChildControl(o);

switch(e.getKeyIdentifier()){case k:case j:L.removeState(i);
L.addState(m);
}},_onKeyUp:function(e){var M=this.getChildControl(o);

switch(e.getKeyIdentifier()){case k:case j:if(M.hasState(m)){M.removeState(i);
M.removeState(m);
M.execute();
}}},_onButtonExecute:function(e){this.execute();
},_onChangeMenuVisibility:function(e){if(!this.getMenu().isVisible()&&this.__es){this.removeState(n);
}}}});
})();
(function(){var k="textfield",j="",i="downbutton",h="upbutton",g="Number",f="inner",d="PageUp",c="Boolean",b="changeValue",a="Down",H="Up",G="execute",F="PageDown",E="changeLocale",D="qx.dynlocale",C="on",B="_applyEditable",A="_applyWrap",z="keydown",y="\-]",r="mousewheel",s="_applyValue",p="number",q="_applyMinimum",n="qx.util.format.NumberFormat",o="[0-9",l="keyup",m="spinner",t="this._checkValue(value)",u="_applyMaximum",w="changeNumberFormat",v="_applyNumberFormat",x="qx.ui.form.Spinner";
qx.Class.define(x,{extend:qx.ui.core.Widget,implement:[qx.ui.form.INumberForm,qx.ui.form.IRange,qx.ui.form.IForm],include:[qx.ui.core.MContentPadding,qx.ui.form.MForm],construct:function(bo,bp,bq){arguments.callee.base.call(this);
var br=new qx.ui.layout.Grid();
br.setColumnFlex(0,1);
br.setRowFlex(0,1);
br.setRowFlex(1,1);
this._setLayout(br);
this.addListener(z,this._onKeyDown,this);
this.addListener(l,this._onKeyUp,this);
this.addListener(r,this._onMouseWheel,this);

if(qx.core.Variant.isSet(D,C)){qx.locale.Manager.getInstance().addListener(E,this._onChangeLocale,this);
}this._createChildControl(k);
this._createChildControl(h);
this._createChildControl(i);
if(bo!=null){this.setMinimum(bo);
}
if(bq!=null){this.setMaximum(bq);
}
if(bp!==undefined){this.setValue(bp);
}else{this.initValue();
}},properties:{appearance:{refine:true,init:m},focusable:{refine:true,init:true},singleStep:{check:g,init:1},pageStep:{check:g,init:10},minimum:{check:g,apply:q,init:0},value:{check:t,nullable:true,apply:s,init:0,event:b},maximum:{check:g,apply:u,init:100},wrap:{check:c,init:false,apply:A},editable:{check:c,init:true,apply:B},numberFormat:{check:n,apply:v,nullable:true},allowShrinkY:{refine:true,init:false}},members:{__et:null,__eu:false,__ev:false,_createChildControlImpl:function(bh){var bi;

switch(bh){case k:bi=new qx.ui.form.TextField();
bi.setFilter(this._getFilterRegExp());
bi.addState(f);
bi.setWidth(40);
bi.setFocusable(false);
bi.addListener(b,this._onTextChange,this);
this._add(bi,{column:0,row:0,rowSpan:2});
break;
case h:bi=new qx.ui.form.RepeatButton();
bi.addState(f);
bi.setFocusable(false);
bi.addListener(G,this._countUp,this);
this._add(bi,{column:1,row:0});
break;
case i:bi=new qx.ui.form.RepeatButton();
bi.addState(f);
bi.setFocusable(false);
bi.addListener(G,this._countDown,this);
this._add(bi,{column:1,row:1});
break;
}return bi||arguments.callee.base.call(this,bh);
},_getFilterRegExp:function(){var bn=qx.locale.Number.getDecimalSeparator(qx.locale.Manager.getInstance().getLocale());
var bm=qx.locale.Number.getGroupSeparator(qx.locale.Manager.getInstance().getLocale());
var bl=j;
var bj=j;

if(this.getNumberFormat()!==null){bl=this.getNumberFormat().getPrefix()||j;
bj=this.getNumberFormat().getPostfix()||j;
}var bk=new RegExp(o+qx.lang.String.escapeRegexpChars(bn)+qx.lang.String.escapeRegexpChars(bm)+qx.lang.String.escapeRegexpChars(bl)+qx.lang.String.escapeRegexpChars(bj)+y);
return bk;
},_forwardStates:{focused:true,invalid:true},tabFocus:function(){var bg=this.getChildControl(k);
bg.getFocusElement().focus();
bg.selectAllText();
},_applyMinimum:function(U,V){if(this.getMaximum()<U){this.setMaximum(U);
}
if(this.getValue()<U){this.setValue(U);
}else{this._updateButtons();
}},_applyMaximum:function(bA,bB){if(this.getMinimum()>bA){this.setMin(bA);
}
if(this.getValue()>bA){this.setValue(bA);
}else{this._updateButtons();
}},_applyEnabled:function(I,J){arguments.callee.base.call(this,I,J);
this._updateButtons();
},_checkValue:function(K){return typeof K===p&&K>=this.getMinimum()&&K<=this.getMaximum();
},_applyValue:function(L,M){var N=this.getChildControl(k);
this._updateButtons();
this.__et=L;
if(L!==null){if(this.getNumberFormat()){N.setValue(this.getNumberFormat().format(L));
}else{N.setValue(L+j);
}}else{N.setValue(j);
}},_applyEditable:function(bb,bc){var bd=this.getChildControl(k);

if(bd){bd.setReadOnly(!bb);
}},_applyWrap:function(X,Y){this._updateButtons();
},_applyNumberFormat:function(bx,by){var bz=this.getChildControl(k);
bz.setFilter(this._getFilterRegExp());
this.getNumberFormat().addListener(w,this._onChangeNumberFormat,this);
this._applyValue(this.__et,undefined);
},_getContentPaddingTarget:function(){return this.getChildControl(k);
},_updateButtons:function(){var bt=this.getChildControl(h);
var bs=this.getChildControl(i);
var bu=this.getValue();

if(!this.getEnabled()){bt.setEnabled(false);
bs.setEnabled(false);
}else{if(this.getWrap()){bt.setEnabled(true);
bs.setEnabled(true);
}else{if(bu!==null&&bu<this.getMaximum()){bt.setEnabled(true);
}else{bt.setEnabled(false);
}if(bu!==null&&bu>this.getMinimum()){bs.setEnabled(true);
}else{bs.setEnabled(false);
}}}},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case d:this.__eu=true;
case H:this.getChildControl(h).press();
break;
case F:this.__ev=true;
case a:this.getChildControl(i).press();
break;
default:return ;
}e.stopPropagation();
e.preventDefault();
},_onKeyUp:function(e){switch(e.getKeyIdentifier()){case d:this.getChildControl(h).release();
this.__eu=false;
break;
case H:this.getChildControl(h).release();
break;
case F:this.getChildControl(i).release();
this.__ev=false;
break;
case a:this.getChildControl(i).release();
break;
}},_onMouseWheel:function(e){if(e.getWheelDelta()>0){this._countDown();
}else{this._countUp();
}e.stop();
},_onTextChange:function(e){var O=this.getChildControl(k);
var P;
if(this.getNumberFormat()){try{P=this.getNumberFormat().parse(O.getValue());
}catch(ba){}}if(P===undefined){P=parseFloat(O.getValue(),10);
}if(!isNaN(P)){if(P>this.getMaximum()){O.setValue(this.getMaximum()+j);
return;
}else if(P<this.getMinimum()){O.setValue(this.getMinimum()+j);
return;
}this.setValue(P);
}else{this._applyValue(this.__et,undefined);
}},_onChangeLocale:function(S){if(this.getNumberFormat()!==null){this.setNumberFormat(this.getNumberFormat());
var T=this.getChildControl(k);
T.setFilter(this._getFilterRegExp());
T.setValue(this.getNumberFormat().format(this.getValue()));
}},_onChangeNumberFormat:function(be){var bf=this.getChildControl(k);
bf.setFilter(this._getFilterRegExp());
bf.setValue(this.getNumberFormat().format(this.getValue()));
},_countUp:function(){if(this.__eu){var R=this.getValue()+this.getPageStep();
}else{var R=this.getValue()+this.getSingleStep();
}if(this.getWrap()){if(R>this.getMaximum()){var Q=this.getMaximum()-R;
R=this.getMinimum()+Q;
}}this.gotoValue(R);
},_countDown:function(){if(this.__ev){var bw=this.getValue()-this.getPageStep();
}else{var bw=this.getValue()-this.getSingleStep();
}if(this.getWrap()){if(bw<this.getMinimum()){var bv=this.getMinimum()+bw;
bw=this.getMaximum()-bv;
}}this.gotoValue(bw);
},gotoValue:function(W){return this.setValue(Math.min(this.getMaximum(),Math.max(this.getMinimum(),W)));
}},destruct:function(){if(qx.core.Variant.isSet(D,C)){qx.locale.Manager.getInstance().removeListener(E,this._onChangeLocale,this);
}}});
})();
(function(){var c="password",b="qx.ui.form.PasswordField",a="input";
qx.Class.define(b,{extend:qx.ui.form.TextField,members:{_createInputElement:function(){var d=new qx.html.Input(c);
d.addListener(a,this._onHtmlInput,this);
return d;
}}});
})();
