qx.$$packageData['6f1e58388dbe']={"resources":{"qx/icon/Tango/16/actions/edit-clear.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-copy.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-cut.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-delete.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-find.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-paste.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-redo.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-select-all.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-undo.png":[16,16,"png","qx"]}};
(function(){var e="cldr_number_decimal_separator",d="cldr_number_percent_format",c="qx.locale.Number",b="cldr_number_group_separator";
qx.Class.define(c,{statics:{getDecimalSeparator:function(g){return qx.locale.Manager.getInstance().localize(e,[],g);
},getGroupSeparator:function(f){return qx.locale.Manager.getInstance().localize(b,[],f);
},getPercentFormat:function(a){return qx.locale.Manager.getInstance().localize(d,[],a);
}}});
})();
(function(){var a="qx.util.format.IFormat";
qx.Interface.define(a,{members:{format:function(c){},parse:function(b){}}});
})();
(function(){var B="_",A="format",z="thu",y="sat",x="cldr_day_",w="cldr_month_",v="wed",u="fri",t="tue",s="mon",S="sun",R="short",Q="HH:mm",P="HHmmsszz",O="HHmm",N="HHmmss",M="cldr_date_format_",L="HH:mm:ss zz",K="full",J="cldr_pm",H="long",I="medium",F="cldr_am",G="qx.locale.Date",D="cldr_date_time_format_",E="cldr_time_format_",C="HH:mm:ss";
qx.Class.define(G,{statics:{__hq:qx.locale.Manager.getInstance(),getAmMarker:function(W){return this.__hq.localize(F,[],W);
},getPmMarker:function(bh){return this.__hq.localize(J,[],bh);
},getDayNames:function(length,bt,bu){var bu=bu?bu:A;
{};
var bw=[S,s,t,v,z,u,y];
var bx=[];

for(var i=0;i<bw.length;i++){var bv=x+bu+B+length+B+bw[i];
bx.push(this.__hq.localize(bv,[],bt));
}return bx;
},getDayName:function(length,n,o,p){var p=p?p:A;
{};
var r=[S,s,t,v,z,u,y];
var q=x+p+B+length+B+r[n];
return this.__hq.localize(q,[],o);
},getMonthNames:function(length,bp,bq){var bq=bq?bq:A;
{};
var bs=[];

for(var i=0;i<12;i++){var br=w+bq+B+length+B+(i+1);
bs.push(this.__hq.localize(br,[],bp));
}return bs;
},getMonthName:function(length,j,k,l){var l=l?l:A;
{};
var m=w+l+B+length+B+(j+1);
return this.__hq.localize(m,[],k);
},getDateFormat:function(a,b){{};
var c=M+a;
return this.__hq.localize(c,[],b);
},getDateTimeFormat:function(X,Y,ba){var bc=D+X;
var bb=this.__hq.localize(bc,[],ba);

if(bb==bc){bb=Y;
}return bb;
},getTimeFormat:function(bd,be){{};
var bg=E+bd;
var bf=this.__hq.localize(bg,[],be);

if(bf!=bg){return bf;
}
switch(bd){case R:case I:return qx.locale.Date.getDateTimeFormat(O,Q);
case H:return qx.locale.Date.getDateTimeFormat(N,C);
case K:return qx.locale.Date.getDateTimeFormat(P,L);
default:throw new Error("This case should never happen.");
}},getWeekStart:function(bi){var bj={"MV":5,"AE":6,"AF":6,"BH":6,"DJ":6,"DZ":6,"EG":6,"ER":6,"ET":6,"IQ":6,"IR":6,"JO":6,"KE":6,"KW":6,"LB":6,"LY":6,"MA":6,"OM":6,"QA":6,"SA":6,"SD":6,"SO":6,"TN":6,"YE":6,"AS":0,"AU":0,"AZ":0,"BW":0,"CA":0,"CN":0,"FO":0,"GE":0,"GL":0,"GU":0,"HK":0,"IE":0,"IL":0,"IS":0,"JM":0,"JP":0,"KG":0,"KR":0,"LA":0,"MH":0,"MN":0,"MO":0,"MP":0,"MT":0,"NZ":0,"PH":0,"PK":0,"SG":0,"TH":0,"TT":0,"TW":0,"UM":0,"US":0,"UZ":0,"VI":0,"ZA":0,"ZW":0,"MW":0,"NG":0,"TJ":0};
var bk=qx.locale.Date._getTerritory(bi);
return bj[bk]!=null?bj[bk]:1;
},getWeekendStart:function(f){var h={"EG":5,"IL":5,"SY":5,"IN":0,"AE":4,"BH":4,"DZ":4,"IQ":4,"JO":4,"KW":4,"LB":4,"LY":4,"MA":4,"OM":4,"QA":4,"SA":4,"SD":4,"TN":4,"YE":4};
var g=qx.locale.Date._getTerritory(f);
return h[g]!=null?h[g]:6;
},getWeekendEnd:function(T){var U={"AE":5,"BH":5,"DZ":5,"IQ":5,"JO":5,"KW":5,"LB":5,"LY":5,"MA":5,"OM":5,"QA":5,"SA":5,"SD":5,"TN":5,"YE":5,"AF":5,"IR":5,"EG":6,"IL":6,"SY":6};
var V=qx.locale.Date._getTerritory(T);
return U[V]!=null?U[V]:0;
},isWeekend:function(bl,bm){var bo=qx.locale.Date.getWeekendStart(bm);
var bn=qx.locale.Date.getWeekendEnd(bm);

if(bn>bo){return ((bl>=bo)&&(bl<=bn));
}else{return ((bl>=bo)||(bl<=bn));
}},_getTerritory:function(d){if(d){var e=d.split(B)[1]||d;
}else{e=this.__hq.getTerritory()||this.__hq.getLanguage();
}return e.toUpperCase();
}}});
})();
(function(){var bF="(\\d\\d?)",bE="format",bD="",bC="abbreviated",bB="wide",bA="(",bz=")",by="|",bx="stand-alone",bw="wildcard",bl="default",bk="literal",bj="'",bi="hour",bh="(\\d\\d?\\d?)",bg="ms",bf="narrow",be="-",bd="quoted_literal",bc='a',bM="HH:mm:ss",bN="+",bK="HHmmss",bL="long",bI='z',bJ="0",bG="sec",bH="day",bO='Z',bP=" ",bp="min",bo="mm",br="(\\d+)",bq="h",bt="KK",bs='L',bv="Z",bu="(\\d\\d+)",bn="EEEE",bm="^",c=":",d='y',e="K",f="a",g="([\\+\\-]\\d\\d:?\\d\\d)",h="GMT",j="dd",k="qx.util.format.DateFormat",l="yyy",m="H",bT="YYYY",bS="y",bR="HH",bQ="EE",bX='h',bW="S",bV='s',bU='A',ca="yyyyyy",bY="kk",L="ss",M='H',J='S',K="MMMM",P='c',Q="d",N="([a-zA-Z]+)",O='k',H="m",I='Y',u='D',t="yyyyy",w='K',v="hh",q="SSS",p="MM",s="yy",r="(\\d\\d\\d\\d\\d\\d+)",o="yyyy-MM-dd HH:mm:ss",n="(\\d\\d\\d\\d\\d+)",V="short",W='d',X="unkown",Y='m',R="(\\d\\d\\d\\d)",S="(\\d\\d\\d+)",T="k",U='M',ba="(\\d\\d\\d\\d+)",bb="SS",E="MMM",D="s",C="M",B='w',A="EEE",z="$",y="?",x='E',G="z",F="yyyy";
qx.Class.define(k,{extend:qx.core.Object,implement:qx.util.format.IFormat,construct:function(cw,cx){arguments.callee.base.call(this);

if(!cx){this.__hr=qx.locale.Manager.getInstance().getLocale();
}else{this.__hr=cx;
}
if(cw!=null){this.__hs=cw.toString();
}else{this.__hs=qx.locale.Date.getDateFormat(bL,this.__hr)+bP+qx.locale.Date.getDateTimeFormat(bK,bM,this.__hr);
}},statics:{getDateTimeInstance:function(){var cW=qx.util.format.DateFormat;
var cV=qx.locale.Date.getDateFormat(bL)+bP+qx.locale.Date.getDateTimeFormat(bK,bM);

if(cW._dateInstance==null||cW._dateInstance.__hs!=cV){cW._dateTimeInstance=new cW();
}return cW._dateTimeInstance;
},getDateInstance:function(){var dv=qx.util.format.DateFormat;
var du=qx.locale.Date.getDateFormat(V)+bD;

if(dv._dateInstance==null||dv._dateInstance.__hs!=du){dv._dateInstance=new dv(du);
}return dv._dateInstance;
},ASSUME_YEAR_2000_THRESHOLD:30,LOGGING_DATE_TIME__format:o,AM_MARKER:"am",PM_MARKER:"pm",MEDIUM_TIMEZONE_NAMES:["GMT"],FULL_TIMEZONE_NAMES:["Greenwich Mean Time"]},members:{__hr:null,__hs:null,__ht:null,__hu:null,__hv:null,__hw:function(df,dg){var dh=bD+df;

while(dh.length<dg){dh=bJ+dh;
}return dh;
},__hx:function(dr){var ds=new Date(dr.getTime());
var dt=ds.getDate();

while(ds.getMonth()!=0){ds.setDate(-1);
dt+=ds.getDate()+1;
}return dt;
},__hy:function(cy){return new Date(cy.getTime()+(3-((cy.getDay()+6)%7))*86400000);
},__hz:function(cP){var cR=this.__hy(cP);
var cS=cR.getFullYear();
var cQ=this.__hy(new Date(cS,0,4));
return Math.floor(1.5+(cR.getTime()-cQ.getTime())/86400000/7);
},format:function(dw){if(dw==null){return null;
}var dC=qx.util.format.DateFormat;
var dD=this.__hr;
var dN=dw.getFullYear();
var dH=dw.getMonth();
var dP=dw.getDate();
var dx=dw.getDay();
var dI=dw.getHours();
var dE=dw.getMinutes();
var dJ=dw.getSeconds();
var dL=dw.getMilliseconds();
var dO=dw.getTimezoneOffset();
var dA=dO>0?1:-1;
var dy=Math.floor(Math.abs(dO)/60);
var dF=Math.abs(dO)%60;
this.__hA();
var dM=bD;

for(var i=0;i<this.__hv.length;i++){var dK=this.__hv[i];

if(dK.type==bk){dM+=dK.text;
}else{var dB=dK.character;
var dG=dK.size;
var dz=y;

switch(dB){case d:case I:if(dG==2){dz=this.__hw(dN%100,2);
}else{dz=dN+bD;

if(dG>dz.length){for(var i=dz.length;i<dG;i++){dz=bJ+dz;
}}}break;
case u:dz=this.__hw(this.__hx(dw),dG);
break;
case W:dz=this.__hw(dP,dG);
break;
case B:dz=this.__hw(this.__hz(dw),dG);
break;
case x:if(dG==2){dz=qx.locale.Date.getDayName(bf,dx,dD,bE);
}else if(dG==3){dz=qx.locale.Date.getDayName(bC,dx,dD,bE);
}else if(dG==4){dz=qx.locale.Date.getDayName(bB,dx,dD,bE);
}break;
case P:if(dG==2){dz=qx.locale.Date.getDayName(bf,dx,dD,bx);
}else if(dG==3){dz=qx.locale.Date.getDayName(bC,dx,dD,bx);
}else if(dG==4){dz=qx.locale.Date.getDayName(bB,dx,dD,bx);
}break;
case U:if(dG==1||dG==2){dz=this.__hw(dH+1,dG);
}else if(dG==3){dz=qx.locale.Date.getMonthName(bC,dH,dD,bE);
}else if(dG==4){dz=qx.locale.Date.getMonthName(bB,dH,dD,bE);
}break;
case bs:if(dG==1||dG==2){dz=this.__hw(dH+1,dG);
}else if(dG==3){dz=qx.locale.Date.getMonthName(bC,dH,dD,bx);
}else if(dG==4){dz=qx.locale.Date.getMonthName(bB,dH,dD,bx);
}break;
case bc:dz=(dI<12)?qx.locale.Date.getAmMarker(dD):qx.locale.Date.getPmMarker(dD);
break;
case M:dz=this.__hw(dI,dG);
break;
case O:dz=this.__hw((dI==0)?24:dI,dG);
break;
case w:dz=this.__hw(dI%12,dG);
break;
case bX:dz=this.__hw(((dI%12)==0)?12:(dI%12),dG);
break;
case Y:dz=this.__hw(dE,dG);
break;
case bV:dz=this.__hw(dJ,dG);
break;
case J:dz=this.__hw(dL,dG);
break;
case bI:if(dG==1){dz=h+((dA>0)?be:bN)+this.__hw(Math.abs(dy))+c+this.__hw(dF,2);
}else if(dG==2){dz=dC.MEDIUM_TIMEZONE_NAMES[dy];
}else if(dG==3){dz=dC.FULL_TIMEZONE_NAMES[dy];
}break;
case bO:dz=((dA>0)?be:bN)+this.__hw(Math.abs(dy),2)+this.__hw(dF,2);
break;
}dM+=dz;
}}return dM;
},parse:function(cX){this.__hB();
var de=this.__ht.regex.exec(cX);

if(de==null){throw new Error("Date string '"+cX+"' does not match the date format: "+this.__hs);
}var cY={year:1970,month:0,day:1,hour:0,ispm:false,min:0,sec:0,ms:0};
var da=1;

for(var i=0;i<this.__ht.usedRules.length;i++){var dc=this.__ht.usedRules[i];
var db=de[da];

if(dc.field!=null){cY[dc.field]=parseInt(db,10);
}else{dc.manipulator(cY,db);
}da+=(dc.groups==null)?1:dc.groups;
}var dd=new Date(cY.year,cY.month,cY.day,(cY.ispm)?(cY.hour+12):cY.hour,cY.min,cY.sec,cY.ms);

if(cY.month!=dd.getMonth()||cY.year!=dd.getFullYear()){throw new Error("Error parsing date '"+cX+"': the value for day or month is too large");
}return dd;
},__hA:function(){if(this.__hv!=null){return;
}this.__hv=[];
var ea;
var dX=0;
var ec=bD;
var dV=this.__hs;
var dY=bl;
var i=0;

while(i<dV.length){var eb=dV.charAt(i);

switch(dY){case bd:if(eb==bj){if(i+1>=dV.length){i++;
break;
}var dW=dV.charAt(i+1);

if(dW==bj){ec+=eb;
i++;
}else{i++;
dY=X;
}}else{ec+=eb;
i++;
}break;
case bw:if(eb==ea){dX++;
i++;
}else{this.__hv.push({type:bw,character:ea,size:dX});
ea=null;
dX=0;
dY=bl;
}break;
default:if((eb>=bc&&eb<=bI)||(eb>=bU&&eb<=bO)){ea=eb;
dY=bw;
}else if(eb==bj){if(i+1>=dV.length){ec+=eb;
i++;
break;
}var dW=dV.charAt(i+1);

if(dW==bj){ec+=eb;
i++;
}i++;
dY=bd;
}else{dY=bl;
}
if(dY!=bl){if(ec.length>0){this.__hv.push({type:bk,text:ec});
ec=bD;
}}else{ec+=eb;
i++;
}break;
}}if(ea!=null){this.__hv.push({type:bw,character:ea,size:dX});
}else if(ec.length>0){this.__hv.push({type:bk,text:ec});
}},__hB:function(){if(this.__ht!=null){return ;
}var cC=this.__hs;
this.__hC();
this.__hA();
var cI=[];
var cE=bm;

for(var cA=0;cA<this.__hv.length;cA++){var cJ=this.__hv[cA];

if(cJ.type==bk){cE+=qx.lang.String.escapeRegexpChars(cJ.text);
}else{var cB=cJ.character;
var cF=cJ.size;
var cD;

for(var cK=0;cK<this.__hu.length;cK++){var cG=this.__hu[cK];

if(cB==cG.pattern.charAt(0)&&cF==cG.pattern.length){cD=cG;
break;
}}if(cD==null){var cH=bD;

for(var i=0;i<cF;i++){cH+=cB;
}throw new Error("Malformed date format: "+cC+". Wildcard "+cH+" is not supported");
}else{cI.push(cD);
cE+=cD.regex;
}}}cE+=z;
var cz;

try{cz=new RegExp(cE);
}catch(dQ){throw new Error("Malformed date format: "+cC);
}this.__ht={regex:cz,"usedRules":cI,pattern:cE};
},__hC:function(){var ci=qx.util.format.DateFormat;
var co=qx.lang.String;

if(this.__hu!=null){return ;
}var cj=this.__hu=[];
var cv=function(cT,cU){cU=parseInt(cU,10);

if(cU<ci.ASSUME_YEAR_2000_THRESHOLD){cU+=2000;
}else if(cU<100){cU+=1900;
}cT.year=cU;
};
var cp=function(a,b){a.month=parseInt(b,10)-1;
};
var cm=function(dp,dq){dp.ispm=(dq==ci.PM_MARKER);
};
var cl=function(dm,dn){dm.hour=parseInt(dn,10)%24;
};
var ck=function(cb,cc){cb.hour=parseInt(cc,10)%12;
};
var cs=function(cN,cO){return;
};
var cq=qx.locale.Date.getMonthNames(bC,this.__hr,bE);

for(var i=0;i<cq.length;i++){cq[i]=co.escapeRegexpChars(cq[i].toString());
}var cr=function(dR,dS){dS=co.escapeRegexpChars(dS);
dR.month=cq.indexOf(dS);
};
var cf=qx.locale.Date.getMonthNames(bB,this.__hr,bE);

for(var i=0;i<cf.length;i++){cf[i]=co.escapeRegexpChars(cf[i].toString());
}var ce=function(dk,dl){dl=co.escapeRegexpChars(dl);
dk.month=cf.indexOf(dl);
};
var ch=qx.locale.Date.getDayNames(bf,this.__hr,bE);

for(var i=0;i<ch.length;i++){ch[i]=co.escapeRegexpChars(ch[i].toString());
}var cd=function(cL,cM){cM=co.escapeRegexpChars(cM);
cL.month=ch.indexOf(cM);
};
var ct=qx.locale.Date.getDayNames(bC,this.__hr,bE);

for(var i=0;i<ct.length;i++){ct[i]=co.escapeRegexpChars(ct[i].toString());
}var cn=function(di,dj){dj=co.escapeRegexpChars(dj);
di.month=ct.indexOf(dj);
};
var cu=qx.locale.Date.getDayNames(bB,this.__hr,bE);

for(var i=0;i<cu.length;i++){cu[i]=co.escapeRegexpChars(cu[i].toString());
}var cg=function(dT,dU){dU=co.escapeRegexpChars(dU);
dT.month=cu.indexOf(dU);
};
cj.push({pattern:bT,regex:R,manipulator:cv});
cj.push({pattern:bS,regex:br,manipulator:cv});
cj.push({pattern:s,regex:bu,manipulator:cv});
cj.push({pattern:l,regex:S,manipulator:cv});
cj.push({pattern:F,regex:ba,manipulator:cv});
cj.push({pattern:t,regex:n,manipulator:cv});
cj.push({pattern:ca,regex:r,manipulator:cv});
cj.push({pattern:C,regex:bF,manipulator:cp});
cj.push({pattern:p,regex:bF,manipulator:cp});
cj.push({pattern:E,regex:bA+cq.join(by)+bz,manipulator:cr});
cj.push({pattern:K,regex:bA+cf.join(by)+bz,manipulator:ce});
cj.push({pattern:j,regex:bF,field:bH});
cj.push({pattern:Q,regex:bF,field:bH});
cj.push({pattern:bQ,regex:bA+ch.join(by)+bz,manipulator:cd});
cj.push({pattern:A,regex:bA+ct.join(by)+bz,manipulator:cn});
cj.push({pattern:bn,regex:bA+cu.join(by)+bz,manipulator:cg});
cj.push({pattern:f,regex:bA+ci.AM_MARKER+by+ci.PM_MARKER+bz,manipulator:cm});
cj.push({pattern:bR,regex:bF,field:bi});
cj.push({pattern:m,regex:bF,field:bi});
cj.push({pattern:bY,regex:bF,manipulator:cl});
cj.push({pattern:T,regex:bF,manipulator:cl});
cj.push({pattern:bt,regex:bF,field:bi});
cj.push({pattern:e,regex:bF,field:bi});
cj.push({pattern:v,regex:bF,manipulator:ck});
cj.push({pattern:bq,regex:bF,manipulator:ck});
cj.push({pattern:bo,regex:bF,field:bp});
cj.push({pattern:H,regex:bF,field:bp});
cj.push({pattern:L,regex:bF,field:bG});
cj.push({pattern:D,regex:bF,field:bG});
cj.push({pattern:q,regex:bh,field:bg});
cj.push({pattern:bb,regex:bh,field:bg});
cj.push({pattern:bW,regex:bh,field:bg});
cj.push({pattern:bv,regex:g,manipulator:cs});
cj.push({pattern:G,regex:N,manipulator:cs});
}},destruct:function(){this.__hv=this.__ht=this.__hu=null;
}});
})();
(function(){var u="",t="Number",s="-",r="0",q="String",p="changeNumberFormat",o='(',n="g",m="Boolean",l="$",e="NaN",k='([0-9]{1,3}(?:',h='{0,1}[0-9]{3}){0,})',d='\\d+){0,1}',c="qx.util.format.NumberFormat",g="Infinity",f="^",i=".",b="-Infinity",j='([-+]){0,1}';
qx.Class.define(c,{extend:qx.core.Object,implement:qx.util.format.IFormat,construct:function(a){arguments.callee.base.call(this);
this.__ha=a;
},statics:{getIntegerInstance:function(){var v=qx.util.format.NumberFormat;

if(v._integerInstance==null){v._integerInstance=new v();
v._integerInstance.setMaximumFractionDigits(0);
}return v._integerInstance;
},getInstance:function(){if(!this._instance){this._instance=new this;
}return this._instance;
}},properties:{minimumIntegerDigits:{check:t,init:0},maximumIntegerDigits:{check:t,nullable:true},minimumFractionDigits:{check:t,init:0},maximumFractionDigits:{check:t,nullable:true},groupingUsed:{check:m,init:true},prefix:{check:q,init:u,event:p},postfix:{check:q,init:u,event:p}},members:{__ha:null,format:function(F){switch(F){case Infinity:return g;
case -Infinity:return b;
case NaN:return e;
}var J=(F<0);

if(J){F=-F;
}
if(this.getMaximumFractionDigits()!=null){var Q=Math.pow(10,this.getMaximumFractionDigits());
F=Math.round(F*Q)/Q;
}var P=String(Math.floor(F)).length;
var G=u+F;
var M=G.substring(0,P);

while(M.length<this.getMinimumIntegerDigits()){M=r+M;
}
if(this.getMaximumIntegerDigits()!=null&&M.length>this.getMaximumIntegerDigits()){M=M.substring(M.length-this.getMaximumIntegerDigits());
}var L=G.substring(P+1);

while(L.length<this.getMinimumFractionDigits()){L+=r;
}
if(this.getMaximumFractionDigits()!=null&&L.length>this.getMaximumFractionDigits()){L=L.substring(0,this.getMaximumFractionDigits());
}if(this.getGroupingUsed()){var I=M;
M=u;
var O;

for(O=I.length;O>3;O-=3){M=u+qx.locale.Number.getGroupSeparator(this.__ha)+I.substring(O-3,O)+M;
}M=I.substring(0,O)+M;
}var K=this.getPrefix()?this.getPrefix():u;
var H=this.getPostfix()?this.getPostfix():u;
var N=K+(J?s:u)+M;

if(L.length>0){N+=u+qx.locale.Number.getDecimalSeparator(this.__ha)+L;
}N+=H;
return N;
},parse:function(w){var B=qx.lang.String.escapeRegexpChars(qx.locale.Number.getGroupSeparator(this.__ha)+u);
var z=qx.lang.String.escapeRegexpChars(qx.locale.Number.getDecimalSeparator(this.__ha)+u);
var x=new RegExp(f+qx.lang.String.escapeRegexpChars(this.getPrefix())+j+k+B+h+o+z+d+qx.lang.String.escapeRegexpChars(this.getPostfix())+l);
var A=x.exec(w);

if(A==null){throw new Error("Number string '"+w+"' does not match the number format");
}var C=(A[1]==s);
var E=A[2];
var D=A[3];
E=E.replace(new RegExp(B,n),u);
var y=(C?s:u)+E;

if(D!=null&&D.length!=0){D=D.replace(new RegExp(z),u);
y+=i+D;
}return parseFloat(y);
}}});
})();
(function(){var I="short",H="long",G="selection[0]",F="medium",E="Cut",D="Copy",C="language",B="Paste",A="full",z="selection[0].selected",cb="Territory code:",ca="icon/16/actions/edit-find.png",bY="Time format short:",bX="Ctrl+V",bW="icon/16/actions/edit-delete.png",bV="icon/16/actions/edit-cut.png",bU="United States",bT="Date medium:",bS=".png",bR="Date long:",P="DE",Q="en",N="Time format long:",O="Mexico",L="button",M="Locale:",J="AT",K="Undo",X="Date short:",Y="Austria",bs="Format of %1:",bo="Date format short:",bA="changeLocale",bv="Search",bM="MX",bG="center",bh="Ctrl+X",bQ="wide",bO="es",bN="US",bf="middle",bk="Time short:",bm="A date:",bq="name",bt="GB",bw="icon",bC="ES",bI="Germany",R="_",S="Date format medium:",bj="de",bz="F3",by="Date format full:",bx="Week start:",bE="Ctrl+F",bD="icon/16/actions/edit-paste.png",bu="Del",bB="showcase.page.i18n.Content",w="Date format long:",bH="right",T="icon/16/actions/edit-copy.png",U="country",bp="selection[0].countries",x="Spain",y="selection[0].selected.code",be="Locale Information",V="Redo",W="Delete",bd="model",br="Ctrl+C",bK="Date full:",bJ="Ctrl+A",bl="Search Again",bL="Localized ComboBox:",bg="Select All",bF="Ctrl+Z",ba="Time long:",bc="Ctrl+Y",bi="Command Menu (keyboard shortcuts)",bn="showcase/i18n/",bb="Form Elements",bP="Great Britain";
qx.Class.define(bB,{extend:showcase.AbstractContent,include:qx.locale.MTranslation,construct:function(cl){arguments.callee.base.call(this,cl);
this.setView(this._createView());
},members:{__a:null,__b:null,_createView:function(){var ck=new qx.ui.layout.Grid(10,15);
ck.setColumnFlex(0,1);
ck.setColumnFlex(1,1);
var cj=new qx.ui.container.Composite(ck).set({padding:10});
cj.add(this.__c(),{row:0,column:0,colSpan:2});
cj.add(this.__d(),{row:1,column:0});
cj.add(this.__e(),{row:1,column:1});
return cj;
},__c:function(){var cg=new qx.ui.form.RadioButtonGroup(new qx.ui.layout.HBox(10).set({alignX:bG}));
var ch=this.__a=qx.data.marshal.Json.createModel([{language:Q,selected:null,countries:[{code:bN,name:bU},{code:bt,name:bP}]},{language:bO,selected:null,countries:[{code:bC,name:x},{code:bM,name:O}]},{language:bj,selected:null,countries:[{code:P,name:bI},{code:J,name:Y}]}]);

for(var i=0;i<ch.getLength();i++){ch.getItem(i).setSelected(ch.getItem(i).getCountries().getItem(0));
}var cf=new qx.data.controller.List(null,cg,C);
this.__b=cf;
cf.setDelegate({createItem:function(){return new qx.ui.form.RadioButton().set({show:bw,appearance:L});
}});
cf.setIconPath(C);
cf.setIconOptions({converter:function(ci){return bn+ci+bS;
}});
cf.setModel(ch);
cf.getSelection().push(ch.getItem(0));
this.__b.bind(y,this,U);
return cg;
},setCountry:function(u){if(u){var v=this.__b.getSelection().getItem(0).getLanguage();
qx.locale.Manager.getInstance().setLocale(v+R+u);
}},__d:function(){var m=new qx.ui.layout.Grid(10,10);
m.setColumnFlex(0,1);
m.setColumnFlex(1,1);
m.setColumnAlign(0,bH,bf);
var j=new qx.ui.groupbox.GroupBox(this.tr(bb)).set({width:0,minWidth:0});
j.setLayout(m);
j.add(new qx.ui.basic.Label(this.tr(cb)),{row:0,column:0});
var e=new qx.ui.form.SelectBox();
var l=new qx.data.controller.List(null,e,bq);
this.__b.bind(bp,l,bd);
this.__b.bind(z,l,G);
l.bind(G,this.__b,z);
j.add(e,{row:0,column:1});
j.add(new qx.ui.basic.Label(this.tr(bL)),{row:1,column:0});
var a=new qx.ui.form.ComboBox();
a.add(new qx.ui.form.ListItem(this.tr(E)));
a.add(new qx.ui.form.ListItem(this.tr(B)));
a.add(new qx.ui.form.ListItem(this.tr(D)));
j.add(a,{row:1,column:1});
var o=new qx.ui.basic.Label(this.tr(bm));
j.add(o,{row:2,column:0});
var r=new qx.ui.form.DateField();
r.setValue(new Date);
j.add(r,{row:2,column:1});
var h=new qx.ui.control.DateChooser;
j.add(h,{row:3,column:0,colSpan:2});
var g=new qx.ui.core.Command(bF);
var k=new qx.ui.core.Command(bc);
var b=new qx.ui.core.Command(bh);
var f=new qx.ui.core.Command(br);
var s=new qx.ui.core.Command(bX);
var t=new qx.ui.core.Command(bu);
var q=new qx.ui.core.Command(bJ);
var c=new qx.ui.core.Command(bE);
var p=new qx.ui.core.Command(bz);
var d=new qx.ui.menu.Menu;
d.add(new qx.ui.menu.Button(this.tr(K),null,g));
d.add(new qx.ui.menu.Button(this.tr(V),null,k));
d.add(new qx.ui.menu.Separator());
d.add(new qx.ui.menu.Button(this.tr(E),bV,b));
d.add(new qx.ui.menu.Button(this.tr(D),T,f));
d.add(new qx.ui.menu.Button(this.tr(B),bD,s));
d.add(new qx.ui.menu.Button(this.tr(W),bW,t));
d.add(new qx.ui.menu.Button(this.tr(bg),null,q));
d.add(new qx.ui.menu.Separator());
d.add(new qx.ui.menu.Button(this.tr(bv),null,c));
d.add(new qx.ui.menu.Button(this.tr(bl),null,p));
var n=new qx.ui.form.MenuButton(this.tr(bi),null,d);
j.add(n,{row:4,column:0,colSpan:2});
return j;
},__e:function(){var cd=new qx.ui.groupbox.GroupBox(this.tr(be),ca).set({width:0,minWidth:0,allowGrowY:true});
cd.setLayout(new qx.ui.layout.Grow());
var ce=new qx.ui.basic.Label().set({rich:true,allowGrowX:true,allowGrowY:true});
cd.add(ce);
var cc=[];
cc.push("<table id='i18n'><tr><td>");

for(var i=0;i<15;i++){cc.push("");
cc.push("</td><td>");
cc.push("");
cc.push("</td></tr><td>");
}cc.push("");
cc.push("</td><td>");
cc.push("");
cc.push("</td></tr></table>");
this.updateLocaleInformation=function(){var i=0;
cc[(i++*2)+1]=this.tr(M);
cc[(i++*2)+1]=qx.locale.Manager.getInstance().getLocale();
cc[(i++*2)+1]=this.tr(cb);
cc[(i++*2)+1]=qx.locale.Manager.getInstance().getTerritory();
cc[(i++*2)+1]=this.tr(bo);
cc[(i++*2)+1]=qx.locale.Date.getDateFormat(I);
cc[(i++*2)+1]=this.tr(X);
cc[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(I))).format(new Date());
cc[(i++*2)+1]=this.tr(S);
cc[(i++*2)+1]=qx.locale.Date.getDateFormat(F);
cc[(i++*2)+1]=this.tr(bT);
cc[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(F))).format(new Date());
cc[(i++*2)+1]=this.tr(w);
cc[(i++*2)+1]=qx.locale.Date.getDateFormat(H);
cc[(i++*2)+1]=this.tr(bR);
cc[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(H))).format(new Date());
cc[(i++*2)+1]=this.tr(by);
cc[(i++*2)+1]=qx.locale.Date.getDateFormat(A);
cc[(i++*2)+1]=this.tr(bK);
cc[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(A))).format(new Date());
cc[(i++*2)+1]=this.tr(bY);
cc[(i++*2)+1]=qx.locale.Date.getTimeFormat(I);
cc[(i++*2)+1]=this.tr(bk);
cc[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(I))).format(new Date());
cc[(i++*2)+1]=this.tr(N);
cc[(i++*2)+1]=qx.locale.Date.getTimeFormat(H);
cc[(i++*2)+1]=this.tr(ba);
cc[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(H))).format(new Date());
cc[(i++*2)+1]=this.tr(bx);
cc[(i++*2)+1]=qx.locale.Date.getDayName(bQ,qx.locale.Date.getWeekStart());
cc[(i++*2)+1]=this.tr(bs,10000.12);
cc[(i++*2)+1]=qx.util.format.NumberFormat.getInstance().format(10000.12);
ce.setValue(cc.join(""));
};
qx.locale.Manager.getInstance().addListener(bA,this.updateLocaleInformation,this);
this.updateLocaleInformation();
return cd;
}}});
})();
