qx.$$packageData['63150054e271']={"locales":{},"resources":{"qx/icon/Tango/16/actions/edit-clear.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-copy.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-cut.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-delete.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-find.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-paste.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-redo.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-select-all.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-undo.png":[16,16,"png","qx"]},"translations":{"C":{},"de":{"A date:":"Datum:","Command Menu (keyboard shortcuts)":"Command-Menü (Tastenkürzel)","Copy":"Kopieren","Cut":"Aussschneiden","Date format full:":"Vollständiges Datumsformat:","Date format long:":"Langes Datumsformat:","Date format medium:":"Mittellanges Datumsformat:","Date format short:":"kurzes Zeitformat:","Date full:":"Vollständiges Datum:","Date long:":"Langes Datum:","Date medium:":"Mittellanges Datum:","Date short:":"Zeit (kurz):","Delete":"Löschen","Form Elements":"Formular Widgets","Format of %1:":"Format von %1:","Locale Information":"Lokalisierungsinformationen","Locale:":"Sprachkennung:","Localized ComboBox:":"Lokalisierte ComboBox:","Paste":"Einfügen","Redo":"Wiederholen","Search":"Suchen","Search Again":"Weiter suchen","Select All":"Alles auswählen","Territory code:":"Landeskennung:","Time format long:":"Langes Zeitformat:","Time format short:":"kurzes Zeitformat:","Time long:":"Zeit (lang):","Time short:":"Zeit (kurz):","Undo":"Rückgängig","Week start:":"Wochenanfang:","key_full_Alt":"Alt","key_full_Apps":"Kontextmenü","key_full_Backspace":"Rücktaste","key_full_CapsLock":"Feststelltaste","key_full_Control":"Steuerung","key_full_Delete":"Entfernen","key_full_Down":"Pfeil runter","key_full_End":"Ende","key_full_Enter":"Enter","key_full_Escape":"Escape","key_full_Home":"Position 1","key_full_Insert":"Einfügen","key_full_Left":"Pfeil links","key_full_Meta":"Meta","key_full_NumLock":"NumLock","key_full_PageDown":"Bild runter","key_full_PageUp":"Bild hoch","key_full_Pause":"Pause","key_full_PrintScreen":"Drucken","key_full_Right":"Pfeil rechts","key_full_Scroll":"Rollen","key_full_Shift":"Umschalttaste","key_full_Space":"Leertaste","key_full_Tab":"Tabulator","key_full_Up":"Pfeil hoch","key_full_Win":"Windowstaste","key_short_Alt":"Alt","key_short_Apps":"Kontext","key_short_Backspace":"Rück","key_short_CapsLock":"Feststell","key_short_Control":"Strg","key_short_Delete":"Entf","key_short_Down":"Runter","key_short_End":"Ende","key_short_Enter":"Enter","key_short_Escape":"Esc","key_short_Home":"Pos1","key_short_Insert":"Einfg","key_short_Left":"Links","key_short_Meta":"Meta","key_short_NumLock":"Num","key_short_PageDown":"Bild runter","key_short_PageUp":"Bild hoch","key_short_Pause":"Pause","key_short_PrintScreen":"Druck","key_short_Right":"Rechts","key_short_Scroll":"Rollen","key_short_Shift":"Umschalt","key_short_Space":"Leer","key_short_Tab":"Tab","key_short_Up":"Hoch","key_short_Win":"Win"},"de_AT":{},"de_DE":{},"en":{},"en_GB":{},"en_US":{},"es":{"A date:":"Una fecha:","Command Menu (keyboard shortcuts)":"Menú de comando (claves del teclado)","Copy":"Copiar","Cut":"Cortar","Date format full:":"Formato de fecha completo:","Date format long:":"Formato de fecha largo:","Date format medium:":"Formato de fecha mediano:","Date format short:":"Formato de hora corto:","Date full:":"Fecha completo:","Date long:":"Fecha largo:","Date medium:":"Fecha mediano:","Date short:":"Hora corto:","Delete":"Borrar","Format of %1:":"Formato de %1:","Locale Information":"Información de la localisación","Locale:":"Localisación:","Localized ComboBox:":"ComboBox:","Paste":"Pegar","Redo":"Rehacer","Search":"Búsqueda","Search Again":"Buscar otra vez","Select All":"Seleccionar todo","Territory code:":"Código regional:","Time format long:":"Formato de hora largo:","Time format short:":"Formato de hora corto:","Time long:":"Hora largo:","Time short:":"Hora corto:","Undo":"Deshacer","Week start:":"Inicio de semana:","key_full_Alt":"Alt","key_full_Apps":"Aplicaciones","key_full_Backspace":"Retroceso","key_full_CapsLock":"Bloqueo Mayúsculas","key_full_Control":"Control","key_full_Delete":"Suprimir","key_full_Down":"Flecha abajo","key_full_End":"Fin","key_full_Enter":"Intro","key_full_Escape":"Escape","key_full_Home":"Inicio","key_full_Insert":"Insertar","key_full_Left":"Flecha izquierda","key_full_Meta":"Meta","key_full_NumLock":"Bloqueo Numérico","key_full_PageDown":"Avanzar Página","key_full_PageUp":"Retroceder Página","key_full_Pause":"Pausa","key_full_PrintScreen":"Imprimir Pantalla","key_full_Right":"Flecha derecha","key_full_Scroll":"Bloq. Despl.","key_full_Shift":"Mayúscula","key_full_Space":"Espacio","key_full_Tab":"Tabulador","key_full_Up":"Flecha arriba","key_full_Win":"Windows","key_short_Alt":"Alt","key_short_Apps":"Aplic","key_short_Backspace":"Retroceso","key_short_CapsLock":"BloqMayús","key_short_Control":"Ctrl","key_short_Delete":"Supr","key_short_Down":"Abajo","key_short_End":"Fin","key_short_Enter":"Intro","key_short_Escape":"Esc","key_short_Home":"Inicio","key_short_Insert":"Insert","key_short_Left":"Izquierda","key_short_Meta":"Meta","key_short_NumLock":"BloqNum","key_short_PageDown":"AvPág","key_short_PageUp":"RePág","key_short_Pause":"Pausa","key_short_PrintScreen":"ImprPant","key_short_Right":"Derecha","key_short_Scroll":"BloqDespl","key_short_Shift":"Mayús","key_short_Space":"Espacio","key_short_Tab":"Tab","key_short_Up":"Arriba","key_short_Win":"Win"},"es_ES":{},"es_MX":{},"ro":{"A date:":"O dată:","Command Menu (keyboard shortcuts)":"Meniu de comandă (scurtături de tastatură)","Copy":"Copiază","Cut":"Taie","Date format full:":"Format dată întreg:","Date format long:":"Format dată lung:","Date format medium:":"Format dată mediu:","Date format short:":"Format dată scurt:","Date full:":"Dată întreagă:","Date long:":"Dată lungă:","Date medium:":"Dată medie:","Date short:":"Dată scurtă:","Delete":"Şterge","Form Elements":"Elemente de formular","Format of %1:":"Formatul %1:","Locale Information":"Informație despre localizare","Locale:":"Localizare:","Localized ComboBox:":"ComboBox localizată:","Paste":"Lipește","Redo":"Refă","Search":"Caută","Search Again":"Caută din nou","Select All":"Selectează tot","Territory code:":"Cod postal:","Time format long:":"Format oră lung:","Time format short:":"Format oră curt:","Time long:":"Oră lungă:","Time short:":"Oră scurtă:","Undo":"Desfă","Week start:":"Începutul săptămânii:"},"ro_RO":{},"sv":{"A date:":"Ett datum:","Command Menu (keyboard shortcuts)":"Kommandomeny (kortkommandon)","Copy":"Kopiera","Cut":"Klipp ut","Date format full:":"Fullängdsdatumformat","Date format long:":"Långt datumformat","Date format medium:":"Medellångt datumformat","Date format short:":"Kort datumformat","Date full:":"Fullängdsdatum:","Date long:":"Långt datum","Date medium:":"Medellångt datum","Date short:":"Kort datum","Delete":"Radera","Form Elements":"Formulärelement","Format of %1:":"Format av %1:","Locale Information":"Lokalinformation","Locale:":"Lokal:","Localized ComboBox:":"Lokaliserad rullgardin","Paste":"Klistra in","Redo":"Återgöra","Search":"Sök","Search Again":"Sök igen","Select All":"Välj alla","Territory code:":"Territoriekod","Time format long:":"Långt tidsformat:","Time format short:":"Kort tidsformat:","Time long:":"Lång tid:","Time short:":"Kort tid:","Undo":"Ångra","Week start:":"Veckostart:","key_full_Alt":"Alt","key_full_Apps":"Apps","key_full_Backspace":"Backspace","key_full_CapsLock":"CapsLock","key_full_Control":"Control","key_full_Delete":"Delete","key_full_Down":"Ner","key_full_End":"End","key_full_Enter":"Enter","key_full_Escape":"Escape","key_full_Home":"Home","key_full_Insert":"Insert","key_full_Left":"Vänster","key_full_Meta":"Meta","key_full_NumLock":"NumLock","key_full_PageDown":"PageDown","key_full_PageUp":"PageUp","key_full_Pause":"Pause","key_full_PrintScreen":"PrintScreen","key_full_Right":"Höger","key_full_Scroll":"Scroll","key_full_Shift":"Shift","key_full_Space":"Blanksteg","key_full_Tab":"Tab","key_full_Up":"Upp","key_full_Win":"Win","key_short_Alt":"Alt","key_short_Apps":"Apps","key_short_Backspace":"BS","key_short_CapsLock":"Caps","key_short_Control":"Ctrl","key_short_Delete":"Del","key_short_Down":"Ner","key_short_End":"End","key_short_Enter":"Enter","key_short_Escape":"Esc","key_short_Home":"Home","key_short_Insert":"Ins","key_short_Left":"Vänster","key_short_Meta":"Meta","key_short_NumLock":"Num","key_short_PageDown":"PgDn","key_short_PageUp":"PgUp","key_short_Pause":"Pause","key_short_PrintScreen":"PrnScn","key_short_Right":"Höger","key_short_Scroll":"Scroll","key_short_Shift":"Shift","key_short_Space":"Space","key_short_Tab":"Tab","key_short_Up":"Upp","key_short_Win":"Win"},"sv_SE":{}}};

qx.Part.$$notifyLoad("63150054e271", function() {
(function(){var o="String",n="execute",m="qx.ui.menu.Menu",l="_shortcut",k="changeEnabled",j="changeToolTipText",i="Boolean",h="qx.ui.core.Command",g="changeLabel",f="changeMenu",c="changeIcon",e="changeValue",d="_applyShortcut",b="_applyEnabled",a="qx.event.type.Data";
qx.Class.define(h,{extend:qx.core.Object,construct:function(p){qx.core.Object.call(this);
this._shortcut=new qx.bom.Shortcut(p);
this._shortcut.addListener(n,this.execute,this);
},events:{"execute":a},properties:{enabled:{init:true,check:i,event:k,apply:b},shortcut:{check:o,apply:d,nullable:true},label:{check:o,nullable:true,event:g},icon:{check:o,nullable:true,event:c},toolTipText:{check:o,nullable:true,event:j},value:{nullable:true,event:e},menu:{check:m,nullable:true,event:f}},members:{_shortcut:null,_applyEnabled:function(q){this._shortcut.setEnabled(q);
},_applyShortcut:function(r){this._shortcut.setShortcut(r);
},execute:function(s){this.fireDataEvent(n,s);
},toString:function(){return this._shortcut.toString();
}},destruct:function(){this._disposeObjects(l);
this.removeListener(n,this.execute,this);
}});
})();
(function(){var m="Unidentified",l="Boolean",k="+",j="short",h="keydown",g="",f="Control",d="keypress",c="-",b="PageUp",S="Escape",R="qx.event.type.Data",Q="_applyShortcut",P="PrintScreen",O="NumLock",N="5",M="8",L="execute",K="Meta",J="0",t="2",u="Shift",r="You can only specify one non modifier key!",s="3",p="/",q="Delete",n="String",o="changeEnabled",v="*",w="qx.bom.Shortcut",B="6",A="4",D="1",C="Alt",F="Not a valid key name for a shortcut: ",E="PageDown",y="Whitespaces are not allowed within shortcuts",I="_applyEnabled",H="7",G="a",x="z",z="9";
qx.Class.define(w,{extend:qx.core.Object,construct:function(T){qx.core.Object.call(this);
this.__xO={};
this.__xP=null;

if(T!=null){this.setShortcut(T);
}this.initEnabled();
},events:{"execute":R},properties:{enabled:{init:true,check:l,event:o,apply:I},shortcut:{check:n,apply:Q,nullable:true},autoRepeat:{check:l,init:false}},members:{__xO:g,__xP:g,execute:function(U){this.fireDataEvent(L,U);
},__xQ:function(event){if(this.getEnabled()&&this.__xS(event)){if(!this.isAutoRepeat()){this.execute(event.getTarget());
}event.stop();
}},__xR:function(event){if(this.getEnabled()&&this.__xS(event)){if(this.isAutoRepeat()){this.execute(event.getTarget());
}event.stop();
}},_applyEnabled:function(V,W){if(V){qx.event.Registration.addListener(document.documentElement,h,this.__xQ,this);
qx.event.Registration.addListener(document.documentElement,d,this.__xR,this);
}else{qx.event.Registration.removeListener(document.documentElement,h,this.__xQ,this);
qx.event.Registration.removeListener(document.documentElement,d,this.__xR,this);
}},_applyShortcut:function(X,Y){if(X){if(X.search(/[\s]+/)!=-1){var bc=y;
this.error(bc);
throw new Error(bc);
}this.__xO={"Control":false,"Shift":false,"Meta":false,"Alt":false};
this.__xP=null;
var ba;
var a=[];

while(X.length>0&&ba!=-1){ba=X.search(/[-+]+/);
a.push((X.length==1||ba==-1)?X:X.substring(0,ba));
X=X.substring(ba+1);
}var bb=a.length;

for(var i=0;i<bb;i++){var bd=this.__xU(a[i]);

switch(bd){case f:case u:case K:case C:this.__xO[bd]=true;
break;
case m:var bc=F+a[i];
this.error(bc);
throw bc;
default:if(this.__xP){var bc=r;
this.error(bc);
throw bc;
}this.__xP=bd;
}}}return true;
},__xS:function(e){var be=this.__xP;

if(!be){return ;
}if((!this.__xO.Shift&&e.isShiftPressed())||(this.__xO.Shift&&!e.isShiftPressed())||(!this.__xO.Control&&e.isCtrlPressed())||(this.__xO.Control&&!e.isCtrlPressed())||(!this.__xO.Meta&&e.isMetaPressed())||(this.__xO.Meta&&!e.isMetaPressed())||(!this.__xO.Alt&&e.isAltPressed())||(this.__xO.Alt&&!e.isAltPressed())){return false;
}
if(be==e.getKeyIdentifier()){return true;
}return false;
},__xT:{esc:S,ctrl:f,print:P,del:q,pageup:b,pagedown:E,numlock:O,numpad_0:J,numpad_1:D,numpad_2:t,numpad_3:s,numpad_4:A,numpad_5:N,numpad_6:B,numpad_7:H,numpad_8:M,numpad_9:z,numpad_divide:p,numpad_multiply:v,numpad_minus:c,numpad_plus:k},__xU:function(bf){var bg=qx.event.handler.Keyboard;
var bh=m;

if(bg.isValidKeyIdentifier(bf)){return bf;
}
if(bf.length==1&&bf>=G&&bf<=x){return bf.toUpperCase();
}bf=bf.toLowerCase();
var bh=this.__xT[bf]||qx.lang.String.firstUp(bf);

if(bg.isValidKeyIdentifier(bh)){return bh;
}else{return m;
}},toString:function(){var bk=this.__xP;
var bj=[];

for(var bi in this.__xO){if(this.__xO[bi]){bj.push(qx.locale.Key.getKeyName(j,bi));
}}
if(bk){bj.push(qx.locale.Key.getKeyName(j,bk));
}return bj.join(k);
}},destruct:function(){this.setEnabled(false);
this.__xO=this.__xP=null;
}});
})();
(function(){var by="Control",bx="Left",bw="Meta",bv="Pause",bu="End",bt="Down",bs="Ctrl",br="Home",bq="Apps",bp="Win",be="Right",bd="Backspace",bc="Space",bb="Up",ba="Shift",Y="Enter",X="Scroll",W="Alt",V="Escape",U="key_full_Meta",bF="PrintScreen",bG="NumLock",bD="key_short_Alt",bE="key_short_Control_Mac",bB="key_short_Insert",bC="Del",bz="key_full_Enter",bA="key_full_Control",bH="qx.locale.Key",bI="Tabulator",bi="key_full_Space",bh="key_short_Meta",bk="key_short_PageUp",bj="key_short_Pause",bm="key_full_Down",bl="key_short_Apps",bo="key_short_Win",bn="key_full_Right",bg="os.name",bf="key_short_Up",a="key_full_PageDown",b="key_full_Alt",c="PgDn",d="Esc",e="key_full_Insert",f="osx",g="key_short_Space",h="key_short_Backspace",i="key_short_Home",j="key_short_Down",bM="PgUp",bL="_Mac",bK="key_short_CapsLock",bJ="PageUp",bQ="key_full_Up",bP="key_full_Home",bO="key_full_Backspace",bN="PageDown",bS="CapsLock",bR="Ins",E="key_short_PrintScreen",F="Tab",C="key_full_Apps",D="key_short_Tab",I="key_short_End",J="_",G="Caps",H="key_short_NumLock",A="Num",B="key_full_Scroll",r="key_short_Left",q="key_short_Scroll",t="key_",s="key_full_Pause",n="key_short_Right",m="key_full_PrintScreen",p="key_full_Win",o="key_full_Control_Mac",l="key_short_Shift",k="key_short_PageDown",O="key_short_Enter",P="key_short_Control",Q="Insert",R="key_short_Escape",K="key_full_Tab",L="Print",M="Delete",N="key_full_CapsLock",S="key_full_Escape",T="key_short_Delete",z="key_full_PageUp",y="key_full_Shift",x="key_full_NumLock",w="key_full_Delete",v="key_full_End",u="key_full_Left";
qx.Class.define(bH,{statics:{getKeyName:function(bT,bU,bV){var bX=t+bT+J+bU;
if(qx.core.Environment.get(bg)==f&&bU==by){bX+=bL;
}var bW=qx.locale.Manager.getInstance().translate(bX,[],bV);

if(bW==bX){return qx.locale.Key._keyNames[bX]||bU;
}else{return bW;
}}},defer:function(bY){var cb={};
var ca=qx.locale.Manager;
cb[ca.marktr(h)]=bd;
cb[ca.marktr(D)]=F;
cb[ca.marktr(g)]=bc;
cb[ca.marktr(O)]=Y;
cb[ca.marktr(l)]=ba;
cb[ca.marktr(P)]=bs;
cb[ca.marktr(bE)]=bs;
cb[ca.marktr(bD)]=W;
cb[ca.marktr(bK)]=G;
cb[ca.marktr(bh)]=bw;
cb[ca.marktr(R)]=d;
cb[ca.marktr(r)]=bx;
cb[ca.marktr(bf)]=bb;
cb[ca.marktr(n)]=be;
cb[ca.marktr(j)]=bt;
cb[ca.marktr(bk)]=bM;
cb[ca.marktr(k)]=c;
cb[ca.marktr(I)]=bu;
cb[ca.marktr(i)]=br;
cb[ca.marktr(bB)]=bR;
cb[ca.marktr(T)]=bC;
cb[ca.marktr(H)]=A;
cb[ca.marktr(E)]=L;
cb[ca.marktr(q)]=X;
cb[ca.marktr(bj)]=bv;
cb[ca.marktr(bo)]=bp;
cb[ca.marktr(bl)]=bq;
cb[ca.marktr(bO)]=bd;
cb[ca.marktr(K)]=bI;
cb[ca.marktr(bi)]=bc;
cb[ca.marktr(bz)]=Y;
cb[ca.marktr(y)]=ba;
cb[ca.marktr(bA)]=by;
cb[ca.marktr(o)]=by;
cb[ca.marktr(b)]=W;
cb[ca.marktr(N)]=bS;
cb[ca.marktr(U)]=bw;
cb[ca.marktr(S)]=V;
cb[ca.marktr(u)]=bx;
cb[ca.marktr(bQ)]=bb;
cb[ca.marktr(bn)]=be;
cb[ca.marktr(bm)]=bt;
cb[ca.marktr(z)]=bJ;
cb[ca.marktr(a)]=bN;
cb[ca.marktr(v)]=bu;
cb[ca.marktr(bP)]=br;
cb[ca.marktr(e)]=Q;
cb[ca.marktr(w)]=M;
cb[ca.marktr(x)]=bG;
cb[ca.marktr(m)]=bF;
cb[ca.marktr(B)]=X;
cb[ca.marktr(s)]=bv;
cb[ca.marktr(p)]=bp;
cb[ca.marktr(C)]=bq;
bY._keyNames=cb;
}});
})();
(function(){var br="long",bq="short",bp="selection[0]",bo="Cut",bn="medium",bm="full",bl="language",bk="Territory code:",bj="Copy",bi="Paste",W="selection[0].selected",V="icon/16/actions/edit-cut.png",U="DE",T="Time format long:",S="ro",R="Undo",Q="Time long:",P="es",O="Romania",N="GB",by="ES",bz="Date format full:",bw="Ctrl+F",bx="icon/16/actions/edit-paste.png",bu="icon/16/actions/edit-delete.png",bv="Sweden",bs="Search",bt="Spain",bA="Redo",bB="model",bb="Ctrl+V",ba="Mexico",bd="Locale:",bc="Time format short:",bf="Austria",be="Date format short:",bh="wide",bg="selection[0].selected.code",Y="middle",X="AT",a="icon",b="Germany",c="de",d="showcase.page.i18n.Content",e="Date format long:",f="Date long:",g="Week start:",h="SE",j="showcase/i18n/",k="sv",bF="United States",bE="Date medium:",bD=".png",bC="en",bJ="Format of %1:",bI="button",bH="F3",bG="MX",bL="center",bK="Ctrl+X",z="US",A="Select All",x="name",y="icon/16/actions/edit-find.png",D="Date format medium:",E="_",B="Date full:",C="Del",v="right",w="Locale Information",s="Time short:",r="Ctrl+A",u="Search Again",t="Ctrl+Y",o="Form Elements",n="Ctrl+Z",q="RO",p="Date short:",m="changeLocale",l="icon/16/actions/edit-copy.png",J="Delete",K="A date:",L="country",M="selection[0].countries",F="Ctrl+C",G="Localized ComboBox:",H="Command Menu (keyboard shortcuts)",I="Great Britain";
qx.Class.define(d,{extend:showcase.AbstractContent,include:qx.locale.MTranslation,construct:function(bM){showcase.AbstractContent.call(this,bM);
this.setView(this._createView());
},members:{__xV:null,__xW:null,_createView:function(){var bO=new qx.ui.layout.Grid(10,15);
bO.setColumnFlex(0,1);
bO.setColumnFlex(1,1);
var bN=new qx.ui.container.Composite(bO).set({padding:10});
bN.add(this.__xX(),{row:0,column:0,colSpan:2});
bN.add(this.__xY(),{row:1,column:0});
bN.add(this.__ya(),{row:1,column:1});
return bN;
},__xX:function(){var bQ=new qx.ui.form.RadioButtonGroup(new qx.ui.layout.HBox(10).set({alignX:bL}));
var bR=this.__xV=qx.data.marshal.Json.createModel([{language:bC,selected:null,countries:[{code:z,name:bF},{code:N,name:I}]},{language:P,selected:null,countries:[{code:by,name:bt},{code:bG,name:ba}]},{language:c,selected:null,countries:[{code:U,name:b},{code:X,name:bf}]},{language:k,selected:null,countries:[{code:h,name:bv}]},{language:S,selected:null,countries:[{code:q,name:O}]}]);

for(var i=0;i<bR.getLength();i++){bR.getItem(i).setSelected(bR.getItem(i).getCountries().getItem(0));
}var bP=new qx.data.controller.List(null,bQ,bl);
this.__xW=bP;
bP.setDelegate({createItem:function(){return new qx.ui.form.RadioButton().set({show:a,appearance:bI});
}});
bP.setIconPath(bl);
bP.setIconOptions({converter:function(bS){return j+bS+bD;
}});
bP.setModel(bR);
bP.getSelection().push(bR.getItem(0));
this.__xW.bind(bg,this,L);
return bQ;
},setCountry:function(bT){if(bT){var bU=this.__xW.getSelection().getItem(0);
var bX=bU.getCountries();
var bV=false;

for(var i=0;i<bX.getLength();i++){if(bX.getItem(i).getCode()==bT){bV=true;
break;
}}
if(!bV){return;
}var bW=bU.getLanguage();
qx.locale.Manager.getInstance().setLocale(bW+E+bT);
}},__xY:function(){var ck=new qx.ui.layout.Grid(10,10);
ck.setColumnFlex(0,1);
ck.setColumnFlex(1,1);
ck.setColumnAlign(0,v,Y);
var ch=new qx.ui.groupbox.GroupBox(this.tr(o)).set({width:0,minWidth:0});
ch.setLayout(ck);
ch.add(new qx.ui.basic.Label(this.tr(bk)),{row:0,column:0});
var cd=new qx.ui.form.SelectBox();
var cj=new qx.data.controller.List(null,cd,x);
this.__xW.bind(M,cj,bB);
this.__xW.bind(W,cj,bp);
cj.bind(bp,this.__xW,W);
ch.add(cd,{row:0,column:1});
ch.add(new qx.ui.basic.Label(this.tr(G)),{row:1,column:0});
var bY=new qx.ui.form.ComboBox();
bY.add(new qx.ui.form.ListItem(this.tr(bo)));
bY.add(new qx.ui.form.ListItem(this.tr(bi)));
bY.add(new qx.ui.form.ListItem(this.tr(bj)));
ch.add(bY,{row:1,column:1});
var cm=new qx.ui.basic.Label(this.tr(K));
ch.add(cm,{row:2,column:0});
var cp=new qx.ui.form.DateField();
cp.setValue(new Date);
ch.add(cp,{row:2,column:1});
var cg=new qx.ui.control.DateChooser;
ch.add(cg,{row:3,column:0,colSpan:2});
var cf=new qx.ui.core.Command(n);
var ci=new qx.ui.core.Command(t);
var ca=new qx.ui.core.Command(bK);
var ce=new qx.ui.core.Command(F);
var cq=new qx.ui.core.Command(bb);
var cr=new qx.ui.core.Command(C);
var co=new qx.ui.core.Command(r);
var cb=new qx.ui.core.Command(bw);
var cn=new qx.ui.core.Command(bH);
var cc=new qx.ui.menu.Menu;
cc.add(new qx.ui.menu.Button(this.tr(R),null,cf));
cc.add(new qx.ui.menu.Button(this.tr(bA),null,ci));
cc.add(new qx.ui.menu.Separator());
cc.add(new qx.ui.menu.Button(this.tr(bo),V,ca));
cc.add(new qx.ui.menu.Button(this.tr(bj),l,ce));
cc.add(new qx.ui.menu.Button(this.tr(bi),bx,cq));
cc.add(new qx.ui.menu.Button(this.tr(J),bu,cr));
cc.add(new qx.ui.menu.Button(this.tr(A),null,co));
cc.add(new qx.ui.menu.Separator());
cc.add(new qx.ui.menu.Button(this.tr(bs),null,cb));
cc.add(new qx.ui.menu.Button(this.tr(u),null,cn));
var cl=new qx.ui.form.MenuButton(this.tr(H),null,cc);
ch.add(cl,{row:4,column:0,colSpan:2});
return ch;
},__ya:function(){var ct=new qx.ui.groupbox.GroupBox(this.tr(w),y).set({width:0,minWidth:0,allowGrowY:true});
ct.setLayout(new qx.ui.layout.Grow());
var cu=new qx.ui.basic.Label().set({rich:true,allowGrowX:true,allowGrowY:true});
ct.add(cu);
var cs=[];
cs.push("<table id='i18n'><tr><td>");

for(var i=0;i<15;i++){cs.push("");
cs.push("</td><td>");
cs.push("");
cs.push("</td></tr><td>");
}cs.push("");
cs.push("</td><td>");
cs.push("");
cs.push("</td></tr></table>");
this.updateLocaleInformation=function(){var i=0;
cs[(i++*2)+1]=this.tr(bd);
cs[(i++*2)+1]=qx.locale.Manager.getInstance().getLocale();
cs[(i++*2)+1]=this.tr(bk);
cs[(i++*2)+1]=qx.locale.Manager.getInstance().getTerritory();
cs[(i++*2)+1]=this.tr(be);
cs[(i++*2)+1]=qx.locale.Date.getDateFormat(bq);
cs[(i++*2)+1]=this.tr(p);
cs[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(bq))).format(new Date());
cs[(i++*2)+1]=this.tr(D);
cs[(i++*2)+1]=qx.locale.Date.getDateFormat(bn);
cs[(i++*2)+1]=this.tr(bE);
cs[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(bn))).format(new Date());
cs[(i++*2)+1]=this.tr(e);
cs[(i++*2)+1]=qx.locale.Date.getDateFormat(br);
cs[(i++*2)+1]=this.tr(f);
cs[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(br))).format(new Date());
cs[(i++*2)+1]=this.tr(bz);
cs[(i++*2)+1]=qx.locale.Date.getDateFormat(bm);
cs[(i++*2)+1]=this.tr(B);
cs[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(bm))).format(new Date());
cs[(i++*2)+1]=this.tr(bc);
cs[(i++*2)+1]=qx.locale.Date.getTimeFormat(bq);
cs[(i++*2)+1]=this.tr(s);
cs[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(bq))).format(new Date());
cs[(i++*2)+1]=this.tr(T);
cs[(i++*2)+1]=qx.locale.Date.getTimeFormat(br);
cs[(i++*2)+1]=this.tr(Q);
cs[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(br))).format(new Date());
cs[(i++*2)+1]=this.tr(g);
cs[(i++*2)+1]=qx.locale.Date.getDayName(bh,qx.locale.Date.getWeekStart());
cs[(i++*2)+1]=this.tr(bJ,10000.12);
cs[(i++*2)+1]=(new qx.util.format.NumberFormat()).format(10000.12);
cu.setValue(cs.join(""));
};
qx.locale.Manager.getInstance().addListener(m,this.updateLocaleInformation,this);
this.updateLocaleInformation();
return ct;
}}});
})();

});