qx.$$packageData['e173f003f5ba']={"locales":{"C":{"alternateQuotationEnd":"’","alternateQuotationStart":"‘","cldr_am":"AM","cldr_date_format_full":"EEEE, MMMM d, y","cldr_date_format_long":"MMMM d, y","cldr_date_format_medium":"MMM d, y","cldr_date_format_short":"M/d/yy","cldr_date_time_format_EEEd":"d EEE","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_Hms":"H:mm:ss","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, M/d","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E, MMM d","cldr_date_time_format_MMMMEd":"E, MMMM d","cldr_date_time_format_MMMMd":"MMMM d","cldr_date_time_format_MMMd":"MMM d","cldr_date_time_format_Md":"M/d","cldr_date_time_format_d":"d","cldr_date_time_format_hm":"h:mm a","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"M/yyyy","cldr_date_time_format_yMEd":"EEE, M/d/yyyy","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, MMM d, y","cldr_date_time_format_yMMMM":"MMMM y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ y","cldr_day_format_abbreviated_fri":"Fri","cldr_day_format_abbreviated_mon":"Mon","cldr_day_format_abbreviated_sat":"Sat","cldr_day_format_abbreviated_sun":"Sun","cldr_day_format_abbreviated_thu":"Thu","cldr_day_format_abbreviated_tue":"Tue","cldr_day_format_abbreviated_wed":"Wed","cldr_day_format_narrow_fri":"F","cldr_day_format_narrow_mon":"M","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"S","cldr_day_format_narrow_thu":"T","cldr_day_format_narrow_tue":"T","cldr_day_format_narrow_wed":"W","cldr_day_format_wide_fri":"Friday","cldr_day_format_wide_mon":"Monday","cldr_day_format_wide_sat":"Saturday","cldr_day_format_wide_sun":"Sunday","cldr_day_format_wide_thu":"Thursday","cldr_day_format_wide_tue":"Tuesday","cldr_day_format_wide_wed":"Wednesday","cldr_day_stand-alone_abbreviated_fri":"Fri","cldr_day_stand-alone_abbreviated_mon":"Mon","cldr_day_stand-alone_abbreviated_sat":"Sat","cldr_day_stand-alone_abbreviated_sun":"Sun","cldr_day_stand-alone_abbreviated_thu":"Thu","cldr_day_stand-alone_abbreviated_tue":"Tue","cldr_day_stand-alone_abbreviated_wed":"Wed","cldr_day_stand-alone_narrow_fri":"F","cldr_day_stand-alone_narrow_mon":"M","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"S","cldr_day_stand-alone_narrow_thu":"T","cldr_day_stand-alone_narrow_tue":"T","cldr_day_stand-alone_narrow_wed":"W","cldr_day_stand-alone_wide_fri":"Friday","cldr_day_stand-alone_wide_mon":"Monday","cldr_day_stand-alone_wide_sat":"Saturday","cldr_day_stand-alone_wide_sun":"Sunday","cldr_day_stand-alone_wide_thu":"Thursday","cldr_day_stand-alone_wide_tue":"Tuesday","cldr_day_stand-alone_wide_wed":"Wednesday","cldr_month_format_abbreviated_1":"Jan","cldr_month_format_abbreviated_10":"Oct","cldr_month_format_abbreviated_11":"Nov","cldr_month_format_abbreviated_12":"Dec","cldr_month_format_abbreviated_2":"Feb","cldr_month_format_abbreviated_3":"Mar","cldr_month_format_abbreviated_4":"Apr","cldr_month_format_abbreviated_5":"May","cldr_month_format_abbreviated_6":"Jun","cldr_month_format_abbreviated_7":"Jul","cldr_month_format_abbreviated_8":"Aug","cldr_month_format_abbreviated_9":"Sep","cldr_month_format_wide_1":"January","cldr_month_format_wide_10":"October","cldr_month_format_wide_11":"November","cldr_month_format_wide_12":"December","cldr_month_format_wide_2":"February","cldr_month_format_wide_3":"March","cldr_month_format_wide_4":"April","cldr_month_format_wide_5":"May","cldr_month_format_wide_6":"June","cldr_month_format_wide_7":"July","cldr_month_format_wide_8":"August","cldr_month_format_wide_9":"September","cldr_month_stand-alone_narrow_1":"J","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":".","cldr_number_group_separator":",","cldr_number_percent_format":"#,##0%","cldr_pm":"PM","cldr_time_format_full":"h:mm:ss a zzzz","cldr_time_format_long":"h:mm:ss a z","cldr_time_format_medium":"h:mm:ss a","cldr_time_format_short":"h:mm a","quotationEnd":"”","quotationStart":"“"},"de":{"alternateQuotationEnd":"‘","alternateQuotationStart":"‚","cldr_am":"vorm.","cldr_date_format_full":"EEEE, d. MMMM y","cldr_date_format_long":"d. MMMM y","cldr_date_format_medium":"dd.MM.yyyy","cldr_date_format_short":"dd.MM.yy","cldr_date_time_format_EEEd":"d. EEE","cldr_date_time_format_Ed":"E d.","cldr_date_time_format_H":"H","cldr_date_time_format_HHmm":"HH:mm","cldr_date_time_format_HHmmss":"HH:mm:ss","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, d.M.","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E d. MMM","cldr_date_time_format_MMMMEd":"E d. MMMM","cldr_date_time_format_MMMMd":"d. MMMM","cldr_date_time_format_MMMMdd":"dd. MMMM","cldr_date_time_format_MMMd":"d. MMM","cldr_date_time_format_MMd":"d.MM.","cldr_date_time_format_MMdd":"dd.MM.","cldr_date_time_format_Md":"d.M.","cldr_date_time_format_d":"d","cldr_date_time_format_mmss":"mm:ss","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"yyyy-M","cldr_date_time_format_yMEd":"EEE, yyyy-M-d","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, d. MMM y","cldr_date_time_format_yMMMM":"MMMM y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ y","cldr_date_time_format_yyMM":"MM.yy","cldr_date_time_format_yyMMM":"MMM yy","cldr_date_time_format_yyMMdd":"dd.MM.yy","cldr_date_time_format_yyQ":"Q yy","cldr_date_time_format_yyQQQQ":"QQQQ yy","cldr_date_time_format_yyyy":"y","cldr_date_time_format_yyyyMMMM":"MMMM y","cldr_day_format_abbreviated_fri":"Fr.","cldr_day_format_abbreviated_mon":"Mo.","cldr_day_format_abbreviated_sat":"Sa.","cldr_day_format_abbreviated_sun":"So.","cldr_day_format_abbreviated_thu":"Do.","cldr_day_format_abbreviated_tue":"Di.","cldr_day_format_abbreviated_wed":"Mi.","cldr_day_format_narrow_fri":"F","cldr_day_format_narrow_mon":"M","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"S","cldr_day_format_narrow_thu":"D","cldr_day_format_narrow_tue":"D","cldr_day_format_narrow_wed":"M","cldr_day_format_wide_fri":"Freitag","cldr_day_format_wide_mon":"Montag","cldr_day_format_wide_sat":"Samstag","cldr_day_format_wide_sun":"Sonntag","cldr_day_format_wide_thu":"Donnerstag","cldr_day_format_wide_tue":"Dienstag","cldr_day_format_wide_wed":"Mittwoch","cldr_day_stand-alone_abbreviated_fri":"Fr.","cldr_day_stand-alone_abbreviated_mon":"Mo.","cldr_day_stand-alone_abbreviated_sat":"Sa.","cldr_day_stand-alone_abbreviated_sun":"So.","cldr_day_stand-alone_abbreviated_thu":"Do.","cldr_day_stand-alone_abbreviated_tue":"Di.","cldr_day_stand-alone_abbreviated_wed":"Mi.","cldr_day_stand-alone_narrow_fri":"F","cldr_day_stand-alone_narrow_mon":"M","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"S","cldr_day_stand-alone_narrow_thu":"D","cldr_day_stand-alone_narrow_tue":"D","cldr_day_stand-alone_narrow_wed":"M","cldr_day_stand-alone_wide_fri":"Freitag","cldr_day_stand-alone_wide_mon":"Montag","cldr_day_stand-alone_wide_sat":"Samstag","cldr_day_stand-alone_wide_sun":"Sonntag","cldr_day_stand-alone_wide_thu":"Donnerstag","cldr_day_stand-alone_wide_tue":"Dienstag","cldr_day_stand-alone_wide_wed":"Mittwoch","cldr_month_format_abbreviated_1":"Jan","cldr_month_format_abbreviated_10":"Okt","cldr_month_format_abbreviated_11":"Nov","cldr_month_format_abbreviated_12":"Dez","cldr_month_format_abbreviated_2":"Feb","cldr_month_format_abbreviated_3":"Mär","cldr_month_format_abbreviated_4":"Apr","cldr_month_format_abbreviated_5":"Mai","cldr_month_format_abbreviated_6":"Jun","cldr_month_format_abbreviated_7":"Jul","cldr_month_format_abbreviated_8":"Aug","cldr_month_format_abbreviated_9":"Sep","cldr_month_format_wide_1":"Januar","cldr_month_format_wide_10":"Oktober","cldr_month_format_wide_11":"November","cldr_month_format_wide_12":"Dezember","cldr_month_format_wide_2":"Februar","cldr_month_format_wide_3":"März","cldr_month_format_wide_4":"April","cldr_month_format_wide_5":"Mai","cldr_month_format_wide_6":"Juni","cldr_month_format_wide_7":"Juli","cldr_month_format_wide_8":"August","cldr_month_format_wide_9":"September","cldr_month_stand-alone_abbreviated_10":"Okt","cldr_month_stand-alone_abbreviated_11":"Nov","cldr_month_stand-alone_abbreviated_12":"Dez","cldr_month_stand-alone_abbreviated_3":"Mär","cldr_month_stand-alone_abbreviated_7":"Jul","cldr_month_stand-alone_abbreviated_8":"Aug","cldr_month_stand-alone_abbreviated_9":"Sep","cldr_month_stand-alone_narrow_1":"J","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":",","cldr_number_group_separator":".","cldr_number_percent_format":"#,##0 %","cldr_pm":"nachm.","cldr_time_format_full":"HH:mm:ss zzzz","cldr_time_format_long":"HH:mm:ss z","cldr_time_format_medium":"HH:mm:ss","cldr_time_format_short":"HH:mm","quotationEnd":"“","quotationStart":"„"},"de_AT":{"cldr_date_format_full":"EEEE, dd. MMMM y","cldr_date_format_long":"dd. MMMM y","cldr_month_format_abbreviated_1":"Jän","cldr_month_format_wide_1":"Jänner"},"de_DE":{},"en":{"alternateQuotationEnd":"’","alternateQuotationStart":"‘","cldr_am":"AM","cldr_date_format_full":"EEEE, MMMM d, y","cldr_date_format_long":"MMMM d, y","cldr_date_format_medium":"MMM d, y","cldr_date_format_short":"M/d/yy","cldr_date_time_format_EEEd":"d EEE","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_Hms":"H:mm:ss","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, M/d","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E, MMM d","cldr_date_time_format_MMMMEd":"E, MMMM d","cldr_date_time_format_MMMMd":"MMMM d","cldr_date_time_format_MMMd":"MMM d","cldr_date_time_format_Md":"M/d","cldr_date_time_format_d":"d","cldr_date_time_format_hm":"h:mm a","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"M/yyyy","cldr_date_time_format_yMEd":"EEE, M/d/yyyy","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, MMM d, y","cldr_date_time_format_yMMMM":"MMMM y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ y","cldr_day_format_abbreviated_fri":"Fri","cldr_day_format_abbreviated_mon":"Mon","cldr_day_format_abbreviated_sat":"Sat","cldr_day_format_abbreviated_sun":"Sun","cldr_day_format_abbreviated_thu":"Thu","cldr_day_format_abbreviated_tue":"Tue","cldr_day_format_abbreviated_wed":"Wed","cldr_day_format_narrow_fri":"F","cldr_day_format_narrow_mon":"M","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"S","cldr_day_format_narrow_thu":"T","cldr_day_format_narrow_tue":"T","cldr_day_format_narrow_wed":"W","cldr_day_format_wide_fri":"Friday","cldr_day_format_wide_mon":"Monday","cldr_day_format_wide_sat":"Saturday","cldr_day_format_wide_sun":"Sunday","cldr_day_format_wide_thu":"Thursday","cldr_day_format_wide_tue":"Tuesday","cldr_day_format_wide_wed":"Wednesday","cldr_day_stand-alone_abbreviated_fri":"Fri","cldr_day_stand-alone_abbreviated_mon":"Mon","cldr_day_stand-alone_abbreviated_sat":"Sat","cldr_day_stand-alone_abbreviated_sun":"Sun","cldr_day_stand-alone_abbreviated_thu":"Thu","cldr_day_stand-alone_abbreviated_tue":"Tue","cldr_day_stand-alone_abbreviated_wed":"Wed","cldr_day_stand-alone_narrow_fri":"F","cldr_day_stand-alone_narrow_mon":"M","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"S","cldr_day_stand-alone_narrow_thu":"T","cldr_day_stand-alone_narrow_tue":"T","cldr_day_stand-alone_narrow_wed":"W","cldr_day_stand-alone_wide_fri":"Friday","cldr_day_stand-alone_wide_mon":"Monday","cldr_day_stand-alone_wide_sat":"Saturday","cldr_day_stand-alone_wide_sun":"Sunday","cldr_day_stand-alone_wide_thu":"Thursday","cldr_day_stand-alone_wide_tue":"Tuesday","cldr_day_stand-alone_wide_wed":"Wednesday","cldr_month_format_abbreviated_1":"Jan","cldr_month_format_abbreviated_10":"Oct","cldr_month_format_abbreviated_11":"Nov","cldr_month_format_abbreviated_12":"Dec","cldr_month_format_abbreviated_2":"Feb","cldr_month_format_abbreviated_3":"Mar","cldr_month_format_abbreviated_4":"Apr","cldr_month_format_abbreviated_5":"May","cldr_month_format_abbreviated_6":"Jun","cldr_month_format_abbreviated_7":"Jul","cldr_month_format_abbreviated_8":"Aug","cldr_month_format_abbreviated_9":"Sep","cldr_month_format_wide_1":"January","cldr_month_format_wide_10":"October","cldr_month_format_wide_11":"November","cldr_month_format_wide_12":"December","cldr_month_format_wide_2":"February","cldr_month_format_wide_3":"March","cldr_month_format_wide_4":"April","cldr_month_format_wide_5":"May","cldr_month_format_wide_6":"June","cldr_month_format_wide_7":"July","cldr_month_format_wide_8":"August","cldr_month_format_wide_9":"September","cldr_month_stand-alone_narrow_1":"J","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":".","cldr_number_group_separator":",","cldr_number_percent_format":"#,##0%","cldr_pm":"PM","cldr_time_format_full":"h:mm:ss a zzzz","cldr_time_format_long":"h:mm:ss a z","cldr_time_format_medium":"h:mm:ss a","cldr_time_format_short":"h:mm a","quotationEnd":"”","quotationStart":"“"},"en_GB":{"alternateQuotationEnd":"”","alternateQuotationStart":"“","cldr_date_format_full":"EEEE, d MMMM y","cldr_date_format_long":"d MMMM y","cldr_date_format_medium":"d MMM y","cldr_date_format_short":"dd/MM/yyyy","cldr_date_time_format_MEd":"E, d/M","cldr_date_time_format_MMMEd":"E d MMM","cldr_date_time_format_MMMMd":"d MMMM","cldr_date_time_format_MMdd":"dd/MM","cldr_date_time_format_Md":"d/M","cldr_date_time_format_yMEd":"EEE, d/M/yyyy","cldr_date_time_format_yyMMM":"MMM yy","cldr_date_time_format_yyyyMM":"MM/yyyy","cldr_date_time_format_yyyyMMMM":"MMMM y","cldr_time_format_full":"HH:mm:ss zzzz","cldr_time_format_long":"HH:mm:ss z","cldr_time_format_medium":"HH:mm:ss","cldr_time_format_short":"HH:mm","quotationEnd":"’","quotationStart":"‘"},"en_US":{},"es":{"alternateQuotationEnd":"”","alternateQuotationStart":"“","cldr_am":"a.m.","cldr_date_format_full":"EEEE d 'de' MMMM 'de' y","cldr_date_format_long":"d 'de' MMMM 'de' y","cldr_date_format_medium":"dd/MM/yyyy","cldr_date_format_short":"dd/MM/yy","cldr_date_time_format_EEEd":"EEE d","cldr_date_time_format_HHmm":"HH:mm","cldr_date_time_format_HHmmss":"HH:mm:ss","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, d-M","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E d MMM","cldr_date_time_format_MMMMEd":"E d MMMM","cldr_date_time_format_MMMMd":"d 'de' MMMM","cldr_date_time_format_MMMd":"d MMM","cldr_date_time_format_MMMdd":"dd-MMM","cldr_date_time_format_MMd":"d/MM","cldr_date_time_format_MMdd":"MM/dd","cldr_date_time_format_Md":"d/M","cldr_date_time_format_d":"d","cldr_date_time_format_hhmm":"hh:mm a","cldr_date_time_format_hhmmss":"hh:mm:ss a","cldr_date_time_format_mmss":"mm:ss","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"M/yyyy","cldr_date_time_format_yMEd":"EEE d/M/yyyy","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, d MMM y","cldr_date_time_format_yMMMM":"MMMM 'de' y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ yyyy","cldr_date_time_format_yyMM":"MM/yy","cldr_date_time_format_yyMMM":"MMM-yy","cldr_date_time_format_yyQ":"Q yy","cldr_date_time_format_yyQQQQ":"QQQQ 'de' yy","cldr_date_time_format_yyyyMM":"MM/yyyy","cldr_day_format_abbreviated_fri":"vie","cldr_day_format_abbreviated_mon":"lun","cldr_day_format_abbreviated_sat":"sáb","cldr_day_format_abbreviated_sun":"dom","cldr_day_format_abbreviated_thu":"jue","cldr_day_format_abbreviated_tue":"mar","cldr_day_format_abbreviated_wed":"mié","cldr_day_format_narrow_fri":"V","cldr_day_format_narrow_mon":"L","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"D","cldr_day_format_narrow_thu":"J","cldr_day_format_narrow_tue":"M","cldr_day_format_narrow_wed":"M","cldr_day_format_wide_fri":"viernes","cldr_day_format_wide_mon":"lunes","cldr_day_format_wide_sat":"sábado","cldr_day_format_wide_sun":"domingo","cldr_day_format_wide_thu":"jueves","cldr_day_format_wide_tue":"martes","cldr_day_format_wide_wed":"miércoles","cldr_day_stand-alone_abbreviated_fri":"vie","cldr_day_stand-alone_abbreviated_mon":"lun","cldr_day_stand-alone_abbreviated_sat":"sáb","cldr_day_stand-alone_abbreviated_sun":"dom","cldr_day_stand-alone_abbreviated_thu":"jue","cldr_day_stand-alone_abbreviated_tue":"mar","cldr_day_stand-alone_abbreviated_wed":"mié","cldr_day_stand-alone_narrow_fri":"V","cldr_day_stand-alone_narrow_mon":"L","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"D","cldr_day_stand-alone_narrow_thu":"J","cldr_day_stand-alone_narrow_tue":"M","cldr_day_stand-alone_narrow_wed":"M","cldr_day_stand-alone_wide_fri":"viernes","cldr_day_stand-alone_wide_mon":"lunes","cldr_day_stand-alone_wide_sat":"sábado","cldr_day_stand-alone_wide_sun":"domingo","cldr_day_stand-alone_wide_thu":"jueves","cldr_day_stand-alone_wide_tue":"martes","cldr_day_stand-alone_wide_wed":"miércoles","cldr_month_format_abbreviated_1":"ene","cldr_month_format_abbreviated_10":"oct","cldr_month_format_abbreviated_11":"nov","cldr_month_format_abbreviated_12":"dic","cldr_month_format_abbreviated_2":"feb","cldr_month_format_abbreviated_3":"mar","cldr_month_format_abbreviated_4":"abr","cldr_month_format_abbreviated_5":"may","cldr_month_format_abbreviated_6":"jun","cldr_month_format_abbreviated_7":"jul","cldr_month_format_abbreviated_8":"ago","cldr_month_format_abbreviated_9":"sep","cldr_month_format_wide_1":"enero","cldr_month_format_wide_10":"octubre","cldr_month_format_wide_11":"noviembre","cldr_month_format_wide_12":"diciembre","cldr_month_format_wide_2":"febrero","cldr_month_format_wide_3":"marzo","cldr_month_format_wide_4":"abril","cldr_month_format_wide_5":"mayo","cldr_month_format_wide_6":"junio","cldr_month_format_wide_7":"julio","cldr_month_format_wide_8":"agosto","cldr_month_format_wide_9":"septiembre","cldr_month_stand-alone_narrow_1":"E","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":",","cldr_number_group_separator":".","cldr_number_percent_format":"#,##0%","cldr_pm":"p.m.","cldr_time_format_full":"HH:mm:ss zzzz","cldr_time_format_long":"HH:mm:ss z","cldr_time_format_medium":"HH:mm:ss","cldr_time_format_short":"HH:mm","quotationEnd":"’","quotationStart":"‘"},"es_ES":{},"es_MX":{"cldr_number_decimal_separator":".","cldr_number_group_separator":","}},"resources":{},"translations":{}};

qx.Part.$$notifyLoad("e173f003f5ba", function() {
(function(){var m="move",l="Boolean",k="mouseup",j="mousedown",i="losecapture",h="__x",g="qx.ui.core.MMovable",f="__y",d="mousemove",c="maximized";
qx.Mixin.define(g,{properties:{movable:{check:l,init:true},useMoveFrame:{check:l,init:false}},members:{__x:null,__y:null,__z:null,__A:null,__B:null,__C:null,__D:null,__E:false,__F:null,__G:0,_activateMoveHandle:function(y){if(this.__x){throw new Error("The move handle could not be redefined!");
}this.__x=y;
y.addListener(j,this._onMoveMouseDown,this);
y.addListener(k,this._onMoveMouseUp,this);
y.addListener(d,this._onMoveMouseMove,this);
y.addListener(i,this.__K,this);
},__H:function(){var x=this.__y;

if(!x){x=this.__y=new qx.ui.core.Widget();
x.setAppearance("move-frame");
x.exclude();
qx.core.Init.getApplication().getRoot().add(x);
}return x;
},__I:function(){var location=this.getContainerLocation();
var b=this.getBounds();
var a=this.__H();
a.setUserBounds(location.left,location.top,b.width,b.height);
a.show();
a.setZIndex(this.getZIndex()+1);
},__J:function(e){var s=this.__z;
var v=Math.max(s.left,Math.min(s.right,e.getDocumentLeft()));
var u=Math.max(s.top,Math.min(s.bottom,e.getDocumentTop()));
var r=this.__A+v;
var t=this.__B+u;
return {viewportLeft:r,viewportTop:t,parentLeft:r-this.__C,parentTop:t-this.__D};
},_onMoveMouseDown:function(e){if(!this.getMovable()||this.hasState(c)){return;
}var parent=this.getLayoutParent();
var p=parent.getContentLocation();
var q=parent.getBounds();
if(qx.Class.implementsInterface(parent,qx.ui.window.IDesktop)){if(!parent.isContentBlocked()){this.__E=true;
this.__F=parent.getBlockerColor();
this.__G=parent.getBlockerOpacity();
parent.setBlockerColor(null);
parent.setBlockerOpacity(1);
parent.blockContent(this.getZIndex()-1);
}}this.__z={left:p.left,top:p.top,right:p.left+q.width,bottom:p.top+q.height};
var o=this.getContainerLocation();
this.__C=p.left;
this.__D=p.top;
this.__A=o.left-e.getDocumentLeft();
this.__B=o.top-e.getDocumentTop();
this.addState(m);
this.__x.capture();
if(this.getUseMoveFrame()){this.__I();
}e.stop();
},_onMoveMouseMove:function(e){if(!this.hasState(m)){return;
}var n=this.__J(e);

if(this.getUseMoveFrame()){this.__H().setDomPosition(n.viewportLeft,n.viewportTop);
}else{this.setDomPosition(n.parentLeft,n.parentTop);
}e.stopPropagation();
},_onMoveMouseUp:function(e){if(!this.hasState(m)){return;
}this.removeState(m);
var parent=this.getLayoutParent();

if(qx.Class.implementsInterface(parent,qx.ui.window.IDesktop)){if(this.__E){parent.unblockContent();
parent.setBlockerColor(this.__F);
parent.setBlockerOpacity(this.__G);
this.__F=null;
this.__G=0;
}}this.__x.releaseCapture();
var w=this.__J(e);
this.setLayoutProperties({left:w.parentLeft,top:w.parentTop});
if(this.getUseMoveFrame()){this.__H().exclude();
}e.stopPropagation();
},__K:function(e){if(!this.hasState("move")){return;
}this.removeState("move");
if(this.getUseMoveFrame()){this.__H().exclude();
}}},destruct:function(){this._disposeObjects(f,h);
this.__z=null;
}});
})();
(function(){var q="resize",p="Boolean",o="mouseup",n="mousedown",m="losecapture",l="resizableBottom",k="mouseout",j="resizableRight",i="resizableLeft",h="mousemove",c="move",g="shorthand",f="maximized",b="resizableTop",a="Integer",d="qx.ui.core.MResizable";
qx.Mixin.define(d,{construct:function(){this.addListener(n,this.__bb,this,true);
this.addListener(o,this.__bc,this);
this.addListener(h,this.__be,this);
this.addListener(k,this.__bf,this);
this.addListener(m,this.__bd,this);
var C=this.getContainerElement().getDomElement();

if(C==null){C=window;
}this.__O=qx.event.Registration.getManager(C).getHandler(qx.event.handler.DragDrop);
},properties:{resizableTop:{check:p,init:true},resizableRight:{check:p,init:true},resizableBottom:{check:p,init:true},resizableLeft:{check:p,init:true},resizable:{group:[b,j,l,i],mode:g},resizeSensitivity:{check:a,init:5},useResizeFrame:{check:p,init:true}},members:{__O:null,__P:null,__Q:null,__R:null,__S:null,__T:null,__U:null,RESIZE_TOP:1,RESIZE_BOTTOM:2,RESIZE_LEFT:4,RESIZE_RIGHT:8,__V:function(){var L=this.__P;

if(!L){L=this.__P=new qx.ui.core.Widget();
L.setAppearance("resize-frame");
L.exclude();
qx.core.Init.getApplication().getRoot().add(L);
}return L;
},__W:function(){var x=this.__T;
var w=this.__V();
w.setUserBounds(x.left,x.top,x.width,x.height);
w.show();
w.setZIndex(this.getZIndex()+1);
},__X:function(e){var E=this.__Q;
var F=this.getSizeHint();
var I=this.__U;
var H=this.__T;
var D=H.width;
var G=H.height;
var K=H.left;
var top=H.top;
var J;

if((E&this.RESIZE_TOP)||(E&this.RESIZE_BOTTOM)){J=Math.max(I.top,Math.min(I.bottom,e.getDocumentTop()))-this.__S;

if(E&this.RESIZE_TOP){G-=J;
}else{G+=J;
}
if(G<F.minHeight){G=F.minHeight;
}else if(G>F.maxHeight){G=F.maxHeight;
}
if(E&this.RESIZE_TOP){top+=H.height-G;
}}
if((E&this.RESIZE_LEFT)||(E&this.RESIZE_RIGHT)){J=Math.max(I.left,Math.min(I.right,e.getDocumentLeft()))-this.__R;

if(E&this.RESIZE_LEFT){D-=J;
}else{D+=J;
}
if(D<F.minWidth){D=F.minWidth;
}else if(D>F.maxWidth){D=F.maxWidth;
}
if(E&this.RESIZE_LEFT){K+=H.width-D;
}}return {viewportLeft:K,viewportTop:top,parentLeft:H.bounds.left+K-H.left,parentTop:H.bounds.top+top-H.top,width:D,height:G};
},__Y:{1:"n-resize",2:"s-resize",4:"w-resize",8:"e-resize",5:"nw-resize",6:"sw-resize",9:"ne-resize",10:"se-resize"},__ba:function(e){var O=this.getContentLocation();
var M=this.getResizeSensitivity();
var Q=e.getDocumentLeft();
var P=e.getDocumentTop();
var N=0;

if(this.getResizableTop()&&Math.abs(O.top-P)<M){N+=this.RESIZE_TOP;
}else if(this.getResizableBottom()&&Math.abs(O.bottom-P)<M){N+=this.RESIZE_BOTTOM;
}
if(this.getResizableLeft()&&Math.abs(O.left-Q)<M){N+=this.RESIZE_LEFT;
}else if(this.getResizableRight()&&Math.abs(O.right-Q)<M){N+=this.RESIZE_RIGHT;
}this.__Q=N;
},__bb:function(e){if(!this.__Q){return;
}this.addState(q);
this.__R=e.getDocumentLeft();
this.__S=e.getDocumentTop();
var location=this.getContainerLocation();
var A=this.getBounds();
this.__T={top:location.top,left:location.left,width:A.width,height:A.height,bounds:qx.lang.Object.clone(A)};
var parent=this.getLayoutParent();
var y=parent.getContentLocation();
var z=parent.getBounds();
this.__U={left:y.left,top:y.top,right:y.left+z.width,bottom:y.top+z.height};
if(this.getUseResizeFrame()){this.__W();
}this.capture();
e.stop();
},__bc:function(e){if(!this.hasState(q)){return;
}if(this.getUseResizeFrame()){this.__V().exclude();
}var B=this.__X(e);
this.setWidth(B.width);
this.setHeight(B.height);
if(this.getResizableLeft()||this.getResizableTop()){this.setLayoutProperties({left:B.parentLeft,top:B.parentTop});
}this.__Q=0;
this.removeState(q);
this.resetCursor();
this.getApplicationRoot().resetGlobalCursor();
this.releaseCapture();
e.stopPropagation();
},__bd:function(e){if(!this.__Q){return;
}this.resetCursor();
this.getApplicationRoot().resetGlobalCursor();
this.removeState(c);
if(this.getUseResizeFrame()){this.__V().exclude();
}},__be:function(e){if(this.hasState(q)){var u=this.__X(e);
if(this.getUseResizeFrame()){var s=this.__V();
s.setUserBounds(u.viewportLeft,u.viewportTop,u.width,u.height);
}else{this.setWidth(u.width);
this.setHeight(u.height);
if(this.getResizableLeft()||this.getResizableTop()){this.setLayoutProperties({left:u.parentLeft,top:u.parentTop});
}}e.stopPropagation();
}else if(!this.hasState(f)&&!this.__O.isSessionActive()){this.__ba(e);
var v=this.__Q;
var t=this.getApplicationRoot();

if(v){var r=this.__Y[v];
this.setCursor(r);
t.setGlobalCursor(r);
}else if(this.getCursor()){this.resetCursor();
t.resetGlobalCursor();
}}},__bf:function(e){if(this.getCursor()&&!this.hasState(q)){this.resetCursor();
this.getApplicationRoot().resetGlobalCursor();
}}},destruct:function(){if(this.__P!=null&&!qx.core.ObjectRegistry.inShutDown){this.__P.destroy();
this.__P=null;
}this.__O=null;
}});
})();
(function(){var a="qx.ui.window.IWindowManager";
qx.Interface.define(a,{members:{setDesktop:function(f){this.assertInterface(f,qx.ui.window.IDesktop);
},changeActiveWindow:function(b,c){},updateStack:function(){},bringToFront:function(d){this.assertInstance(d,qx.ui.window.Window);
},sendToBack:function(e){this.assertInstance(e,qx.ui.window.Window);
}}});
})();
(function(){var b="__N",a="qx.ui.window.Manager";
qx.Class.define(a,{extend:qx.core.Object,implement:qx.ui.window.IWindowManager,members:{__N:null,setDesktop:function(e){this.__N=e;
this.updateStack();
},getDesktop:function(){return this.__N;
},changeActiveWindow:function(c,d){if(c){this.bringToFront(c);
}},_minZIndex:1e5,updateStack:function(){qx.ui.core.queue.Widget.add(this);
},syncWidget:function(){this.__N.forceUnblockContent();
var k=this.__N.getWindows();
var o=this._minZIndex-1;
var n=false;
var m,j=null;

for(var i=0,l=k.length;i<l;i++){m=k[i];

if(!m.isVisible()){continue;
}o+=2;
m.setZIndex(o);
if(m.getModal()){this.__N.blockContent(o-1);
}n=n||m.isActive();
j=m;
}
if(!n){this.__N.setActiveWindow(j);
}},bringToFront:function(f){var g=this.__N.getWindows();
var h=qx.lang.Array.remove(g,f);

if(h){g.push(f);
this.updateStack();
}},sendToBack:function(p){var q=this.__N.getWindows();
var r=qx.lang.Array.remove(q,p);

if(r){q.unshift(p);
this.updateStack();
}}},destruct:function(){this._disposeObjects(b);
}});
})();
(function(){var o="Boolean",n="qx.event.type.Event",m="captionbar",l="_applyCaptionBarChange",k="maximize-button",j="restore-button",i="minimize-button",h="close-button",g="title",f="icon",T="maximized",S="execute",R="pane",Q="statusbar-text",P="statusbar",O="String",N="normal",M="active",L="beforeClose",K="beforeMinimize",v="mousedown",w="changeStatus",t="changeIcon",u="excluded",r="dblclick",s="_applyActive",p="beforeRestore",q="minimize",x="changeModal",y="_applyShowStatusbar",C="_applyStatus",B="qx.ui.window.Window",E="changeCaption",D="focusout",G="beforeMaximize",F="maximize",A="restore",J="window",I="close",H="changeActive",z="minimized";
qx.Class.define(B,{extend:qx.ui.core.Widget,include:[qx.ui.core.MRemoteChildrenHandling,qx.ui.core.MRemoteLayoutHandling,qx.ui.core.MResizable,qx.ui.core.MMovable,qx.ui.core.MContentPadding],construct:function(W,X){qx.ui.core.Widget.call(this);
this._setLayout(new qx.ui.layout.VBox());
this._createChildControl(m);
this._createChildControl(R);
if(X!=null){this.setIcon(X);
}
if(W!=null){this.setCaption(W);
}this._updateCaptionBar();
this.addListener(v,this._onWindowMouseDown,this,true);
this.addListener(D,this._onWindowFocusOut,this);
qx.core.Init.getApplication().getRoot().add(this);
this.initVisibility();
qx.ui.core.FocusHandler.getInstance().addRoot(this);
{};
},statics:{DEFAULT_MANAGER_CLASS:qx.ui.window.Manager},events:{"beforeClose":n,"close":n,"beforeMinimize":n,"minimize":n,"beforeMaximize":n,"maximize":n,"beforeRestore":n,"restore":n},properties:{appearance:{refine:true,init:J},visibility:{refine:true,init:u},focusable:{refine:true,init:true},active:{check:o,init:false,apply:s,event:H},modal:{check:o,init:false,event:x},caption:{apply:l,event:E,nullable:true},icon:{check:O,nullable:true,apply:l,event:t,themeable:true},status:{check:O,nullable:true,apply:C,event:w},showClose:{check:o,init:true,apply:l,themeable:true},showMaximize:{check:o,init:true,apply:l,themeable:true},showMinimize:{check:o,init:true,apply:l,themeable:true},allowClose:{check:o,init:true,apply:l},allowMaximize:{check:o,init:true,apply:l},allowMinimize:{check:o,init:true,apply:l},showStatusbar:{check:o,init:false,apply:y}},members:{__L:null,__M:null,getChildrenContainer:function(){return this.getChildControl(R);
},_forwardStates:{active:true,maximized:true},setLayoutParent:function(parent){{};
qx.ui.core.Widget.prototype.setLayoutParent.call(this,parent);
},_createChildControlImpl:function(bo){var bp;

switch(bo){case P:bp=new qx.ui.container.Composite(new qx.ui.layout.HBox());
this._add(bp);
bp.add(this.getChildControl(Q));
break;
case Q:bp=new qx.ui.basic.Label();
bp.setValue(this.getStatus());
break;
case R:bp=new qx.ui.container.Composite();
this._add(bp,{flex:1});
break;
case m:var br=new qx.ui.layout.Grid();
br.setRowFlex(0,1);
br.setColumnFlex(1,1);
bp=new qx.ui.container.Composite(br);
this._add(bp);
bp.addListener(r,this._onCaptionMouseDblClick,this);
this._activateMoveHandle(bp);
break;
case f:bp=new qx.ui.basic.Image(this.getIcon());
this.getChildControl(m).add(bp,{row:0,column:0});
break;
case g:bp=new qx.ui.basic.Label(this.getCaption());
bp.setWidth(0);
bp.setAllowGrowX(true);
var bq=this.getChildControl(m);
bq.add(bp,{row:0,column:1});
break;
case i:bp=new qx.ui.form.Button();
bp.setFocusable(false);
bp.addListener(S,this._onMinimizeButtonClick,this);
this.getChildControl(m).add(bp,{row:0,column:2});
break;
case j:bp=new qx.ui.form.Button();
bp.setFocusable(false);
bp.addListener(S,this._onRestoreButtonClick,this);
this.getChildControl(m).add(bp,{row:0,column:3});
break;
case k:bp=new qx.ui.form.Button();
bp.setFocusable(false);
bp.addListener(S,this._onMaximizeButtonClick,this);
this.getChildControl(m).add(bp,{row:0,column:4});
break;
case h:bp=new qx.ui.form.Button();
bp.setFocusable(false);
bp.addListener(S,this._onCloseButtonClick,this);
this.getChildControl(m).add(bp,{row:0,column:6});
break;
}return bp||qx.ui.core.Widget.prototype._createChildControlImpl.call(this,bo);
},_updateCaptionBar:function(){var ba;
var bb=this.getIcon();

if(bb){this.getChildControl(f).setSource(bb);
this._showChildControl(f);
}else{this._excludeChildControl(f);
}var Y=this.getCaption();

if(Y){this.getChildControl(g).setValue(Y);
this._showChildControl(g);
}else{this._excludeChildControl(g);
}
if(this.getShowMinimize()){this._showChildControl(i);
ba=this.getChildControl(i);
this.getAllowMinimize()?ba.resetEnabled():ba.setEnabled(false);
}else{this._excludeChildControl(i);
}
if(this.getShowMaximize()){if(this.isMaximized()){this._showChildControl(j);
this._excludeChildControl(k);
}else{this._showChildControl(k);
this._excludeChildControl(j);
}ba=this.getChildControl(k);
this.getAllowMaximize()?ba.resetEnabled():ba.setEnabled(false);
}else{this._excludeChildControl(k);
this._excludeChildControl(j);
}
if(this.getShowClose()){this._showChildControl(h);
ba=this.getChildControl(h);
this.getAllowClose()?ba.resetEnabled():ba.setEnabled(false);
}else{this._excludeChildControl(h);
}},close:function(){if(!this.isVisible()){return;
}
if(this.fireNonBubblingEvent(L,qx.event.type.Event,[false,true])){this.hide();
this.fireEvent(I);
}},open:function(){this.show();
this.setActive(true);
this.focus();
},center:function(){var parent=this.getLayoutParent();

if(parent){var bk=parent.getBounds();

if(bk){var bl=this.getSizeHint();
var bj=Math.round((bk.width-bl.width)/2);
var top=Math.round((bk.height-bl.height)/2);

if(top<0){top=0;
}this.moveTo(bj,top);
return;
}}{};
},maximize:function(){if(this.isMaximized()){return;
}var parent=this.getLayoutParent();

if(parent!=null&&parent.supportsMaximize()){if(this.fireNonBubblingEvent(G,qx.event.type.Event,[false,true])){if(!this.isVisible()){this.open();
}var c=this.getLayoutProperties();
this.__M=c.left===undefined?0:c.left;
this.__L=c.top===undefined?0:c.top;
this.setLayoutProperties({left:null,top:null,edge:0});
this.addState(T);
this._updateCaptionBar();
this.fireEvent(F);
}}},minimize:function(){if(!this.isVisible()){return;
}
if(this.fireNonBubblingEvent(K,qx.event.type.Event,[false,true])){var bc=this.getLayoutProperties();
this.__M=bc.left===undefined?0:bc.left;
this.__L=bc.top===undefined?0:bc.top;
this.removeState(T);
this.hide();
this.fireEvent(q);
}},restore:function(){if(this.getMode()===N){return;
}
if(this.fireNonBubblingEvent(p,qx.event.type.Event,[false,true])){if(!this.isVisible()){this.open();
}var bi=this.__M;
var top=this.__L;
this.setLayoutProperties({edge:null,left:bi,top:top});
this.removeState(T);
this._updateCaptionBar();
this.fireEvent(A);
}},moveTo:function(d,top){if(this.isMaximized()){return;
}this.setLayoutProperties({left:d,top:top});
},isMaximized:function(){return this.hasState(T);
},getMode:function(){if(!this.isVisible()){return z;
}else{if(this.isMaximized()){return T;
}else{return N;
}}},_applyActive:function(bd,be){if(be){this.removeState(M);
}else{this.addState(M);
}},_getContentPaddingTarget:function(){return this.getChildControl(R);
},_applyShowStatusbar:function(bg,bh){if(bg){this._showChildControl(P);
}else{this._excludeChildControl(P);
}},_applyCaptionBarChange:function(U,V){this._updateCaptionBar();
},_applyStatus:function(bs,bt){var bu=this.getChildControl(Q,true);

if(bu){bu.setValue(bs);
}},_applyCaption:function(bm,bn){{};
this.getChildControl(g).setValue(bm);
},_applyIcon:function(a,b){{};
this.getChildControl(f).setSource(a);
},_onWindowEventStop:function(e){e.stopPropagation();
},_onWindowMouseDown:function(e){this.setActive(true);
},_onWindowFocusOut:function(e){if(this.getModal()){return;
}var bf=e.getRelatedTarget();

if(bf!=null&&!qx.ui.core.Widget.contains(this,bf)){this.setActive(false);
}},_onCaptionMouseDblClick:function(e){if(this.getAllowMaximize()){this.isMaximized()?this.restore():this.maximize();
}},_onMinimizeButtonClick:function(e){this.minimize();
this.getChildControl(i).reset();
},_onRestoreButtonClick:function(e){this.restore();
this.getChildControl(j).reset();
},_onMaximizeButtonClick:function(e){this.maximize();
this.getChildControl(k).reset();
},_onCloseButtonClick:function(e){this.close();
this.getChildControl(h).reset();
}}});
})();
(function(){var a="qx.ui.window.IDesktop";
qx.Interface.define(a,{members:{setWindowManager:function(b){this.assertInterface(b,qx.ui.window.IWindowManager);
},getWindows:function(){},supportsMaximize:function(){},blockContent:function(c){this.assertInteger(c);
},unblockContent:function(){},isContentBlocked:function(){}}});
})();
(function(){var a="qx.ui.window.Desktop";
qx.Class.define(a,{extend:qx.ui.core.Widget,include:[qx.ui.core.MChildrenHandling,qx.ui.window.MDesktop,qx.ui.core.MBlocker],implement:qx.ui.window.IDesktop,construct:function(b){qx.ui.core.Widget.call(this);
this.getContentElement().disableScrolling();
this._setLayout(new qx.ui.layout.Canvas());
this.setWindowManager(b);
}});
})();
(function(){var a="showcase.page.AbstractDesktopContent";
qx.Class.define(a,{extend:showcase.AbstractContent,construct:function(c){showcase.AbstractContent.call(this,c);
this.setView(this._createView());
},members:{_createView:function(){var e=new qx.ui.window.Desktop(new qx.ui.window.Manager());
var d=new qx.ui.window.Window();
d.set({showClose:false,showMinimize:false,contentPadding:0});
this._addWindowContent(d);
e.add(d);
d.moveTo(30,20);
d.open();
return e;
},_addWindowContent:function(b){throw new Error("Abstract method call!");
}}});
})();
(function(){var h="checked",g="menu-checkbox",f="Boolean",d="_applyValue",c="changeValue",b="qx.ui.menu.CheckBox",a="execute";
qx.Class.define(b,{extend:qx.ui.menu.AbstractButton,implement:[qx.ui.form.IBooleanForm],construct:function(k,l){qx.ui.menu.AbstractButton.call(this);
if(k!=null){if(k.translate){this.setLabel(k.translate());
}else{this.setLabel(k);
}}
if(l!=null){this.setMenu(l);
}this.addListener(a,this._onExecute,this);
},properties:{appearance:{refine:true,init:g},value:{check:f,init:false,apply:d,event:c,nullable:true}},members:{_applyValue:function(i,j){i?this.addState(h):this.removeState(h);
},_onExecute:function(e){this.toggleValue();
},_onMouseUp:function(e){if(e.isLeftPressed()){this.execute();
}qx.ui.menu.Manager.getInstance().hideAll();
},_onKeyPress:function(e){this.execute();
}}});
})();

});