qx.$$packageData['dc24c9b35a48']={"resources":{}};
(function(){var s="pressed",r="abandoned",q="hovered",p="checked",o="Space",n="Enter",m="mouseup",l="mousedown",k="Boolean",j="_applyValue",c="mouseover",i="mouseout",g="qx.ui.form.ToggleButton",b="keydown",a="changeValue",f="button",d="keyup",h="execute";
qx.Class.define(g,{extend:qx.ui.basic.Atom,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IBooleanForm,qx.ui.form.IExecutable],construct:function(v,w){arguments.callee.base.call(this,v,w);
this.addListener(c,this._onMouseOver);
this.addListener(i,this._onMouseOut);
this.addListener(l,this._onMouseDown);
this.addListener(m,this._onMouseUp);
this.addListener(b,this._onKeyDown);
this.addListener(d,this._onKeyUp);
this.addListener(h,this._onExecute,this);
},properties:{appearance:{refine:true,init:f},focusable:{refine:true,init:true},value:{check:k,nullable:true,event:a,apply:j,init:false}},members:{_applyValue:function(t,u){t?this.addState(p):this.removeState(p);
},_onExecute:function(e){this.toggleValue();
},_onMouseOver:function(e){if(e.getTarget()!==this){return;
}this.addState(q);

if(this.hasState(r)){this.removeState(r);
this.addState(s);
}},_onMouseOut:function(e){if(e.getTarget()!==this){return;
}this.removeState(q);

if(this.hasState(s)){if(!this.getValue()){this.removeState(s);
}this.addState(r);
}},_onMouseDown:function(e){if(!e.isLeftPressed()){return;
}this.capture();
this.removeState(r);
this.addState(s);
e.stopPropagation();
},_onMouseUp:function(e){this.releaseCapture();

if(this.hasState(r)){this.removeState(r);
}else if(this.hasState(s)){this.execute();
}this.removeState(s);
e.stopPropagation();
},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case n:case o:this.removeState(r);
this.addState(s);
e.stopPropagation();
}},_onKeyUp:function(e){if(!this.hasState(s)){return;
}
switch(e.getKeyIdentifier()){case n:case o:this.removeState(r);
this.execute();
this.removeState(s);
e.stopPropagation();
}}}});
})();
(function(){var b="checkbox",a="qx.ui.form.CheckBox";
qx.Class.define(a,{extend:qx.ui.form.ToggleButton,include:[qx.ui.form.MForm,qx.ui.form.MModelProperty],implement:[qx.ui.form.IForm,qx.ui.form.IModel],construct:function(c){{};
arguments.callee.base.call(this,c);
this.setValue(false);
},properties:{appearance:{refine:true,init:b},allowGrowX:{refine:true,init:false}}});
})();
(function(){var e="textarea",d="qx.ui.form.TextArea",c="_applyWrap",b="Boolean";
qx.Class.define(d,{extend:qx.ui.form.AbstractField,construct:function(h){arguments.callee.base.call(this,h);
this.initWrap();
},properties:{wrap:{check:b,init:true,apply:c},appearance:{refine:true,init:e}},members:{_createInputElement:function(){return new qx.html.Input(e);
},_applyWrap:function(f,g){this.getContentElement().setWrap(f);
},_getContentHint:function(){var a=arguments.callee.base.call(this);
a.height=a.height*4;
a.width=this._getTextSize().width*20;
return a;
}}});
})();
(function(){var p="value",o="placeholder",n="Button",m="CheckBox:",l="TextArea:",k="Boolean",j="RepeatButton:",h="execute",g="Website 2",f="Text",Y="ToggleButton",X="password",W="RadioButton 3",V="showcase.page.form.Content",U="Button:",T="ComboBox:",S="ToggleButton:",R="Options",Q="RadioButton",P="0",w="MenuButton:",x="PasswordField:",u="SplitButton",v="Buttons",s="",t="RadioButtons:",q="dd.mm.YYYY",r="List:",y="SplitButton:",z="Option",G="RadioButton 1",E="Spinner:",J="Selection",I="DateField:",L="RadioButton 2",K="Number",B="CheckBox",O="SelectBox:",N="Website 3",M="MenuButton",A="Website 1",C="Slider:",D="TextField:",F="Item ",H="RadioButtonGroup:";
qx.Class.define(V,{extend:showcase.AbstractContent,construct:function(bH){arguments.callee.base.call(this,bH);
this.setView(this._createView());
},members:{_createView:function(){var bt=new qx.ui.layout.Grid(20,5);
bt.setColumnFlex(0,1);
bt.setColumnFlex(1,1);
var bD=new qx.ui.container.Composite(bt);
bD.setPadding(10);
var bl=1;
var be=new qx.ui.groupbox.GroupBox(f);
be.setLayout(new qx.ui.layout.Grid(8,8));
be.setWidth(290);
bD.add(be,{row:0,column:0});
var bC=new qx.ui.form.TextField();
bC.setPlaceholder(o);
bC.setTabIndex(bl++);
var bn=new qx.ui.basic.Label(D);
bn.setBuddy(bC);
be.add(bn,{row:0,column:0});
be.add(bC,{row:0,column:1});
var bk=new qx.ui.form.PasswordField();
bk.setTabIndex(bl++);
bk.setPlaceholder(X);
bn=new qx.ui.basic.Label(x);
bn.setBuddy(bk);
be.add(bn,{row:1,column:0});
be.add(bk,{row:1,column:1});
var bf=new qx.ui.form.TextArea();
bf.setTabIndex(bl++);
bf.setPlaceholder(o);
bn=new qx.ui.basic.Label(l);
bn.setBuddy(bf);
be.add(bn,{row:2,column:0});
be.add(bf,{row:2,column:1});
var bg=new qx.ui.form.ComboBox();
bg.setTabIndex(bl++);
bg.setPlaceholder(o);
bn=new qx.ui.basic.Label(T);
bn.setBuddy(bg);
be.add(bn,{row:3,column:0});
be.add(bg,{row:3,column:1});
this.__vw(bg);
var bv=new qx.ui.form.DateField();
bv.setTabIndex(bl++);
bv.setPlaceholder(q);
bn=new qx.ui.basic.Label(I);
bn.setBuddy(bv);
be.add(bn,{row:4,column:0});
be.add(bv,{row:4,column:1});
var bm=new qx.ui.groupbox.GroupBox(J);
bm.setLayout(new qx.ui.layout.Grid(8,8));
bm.setWidth(290);
bD.add(bm,{row:1,column:0,rowSpan:2});
var bw=new qx.ui.form.SelectBox();
bw.setTabIndex(bl++);
bn=new qx.ui.basic.Label(O);
bn.setBuddy(bw);
bm.add(bn,{row:0,column:0});
bm.add(bw,{row:0,column:1});
this.__vw(bw);
var bB=new qx.ui.form.List();
bB.setTabIndex(bl++);
bB.setHeight(60);
bB.setWidth(155);
bn=new qx.ui.basic.Label(r);
bn.setBuddy(bB);
bm.add(bn,{row:1,column:0});
bm.add(bB,{row:1,column:1});
this.__vw(bB);
var bu=new qx.ui.form.RadioButtonGroup();
bu.add(new qx.ui.form.RadioButton(G).set({tabIndex:bl++}));
bu.add(new qx.ui.form.RadioButton(L).set({tabIndex:bl++}));
bu.add(new qx.ui.form.RadioButton(W).set({tabIndex:bl++}));
bn=new qx.ui.basic.Label(H);
bn.setBuddy(bu);
bm.add(bn,{row:2,column:0});
bm.add(bu,{row:2,column:1});
var bz=new qx.ui.groupbox.GroupBox(v);
bz.setLayout(new qx.ui.layout.Grid(8,8));
bz.setWidth(250);
bD.add(bz,{row:0,column:1});
var bA=new qx.ui.form.Button(n).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(U);
bn.setBuddy(bA);
bz.add(bn,{row:0,column:0});
bz.add(bA,{row:0,column:1});
var bi=new qx.ui.form.ToggleButton(Y).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(S);
bn.setBuddy(bi);
bz.add(bn,{row:1,column:0});
bz.add(bi,{row:1,column:1});
var bq=new qx.ui.form.RepeatButton(P).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(j);
bn.setBuddy(bq);
bz.add(bn,{row:2,column:0});
bz.add(bq,{row:2,column:1});
var br=new qx.ui.form.MenuButton(M,null,this.__vx()).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(w);
bn.setBuddy(br);
bz.add(bn,{row:3,column:0});
bz.add(br,{row:3,column:1});
var bj=new qx.ui.form.SplitButton(u,null,this.__vy()).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(y);
bn.setBuddy(bj);
bz.add(bn,{row:4,column:0});
bz.add(bj,{row:4,column:1});
bq.addListener(h,function(){var bG=parseInt(bq.getLabel())+1;
bq.setLabel(bG.toString());
});
var bh=new qx.ui.groupbox.GroupBox(k);
bh.setLayout(new qx.ui.layout.Grid(8,8));
bh.setWidth(250);
bD.add(bh,{row:1,column:1});
var bx=new qx.ui.form.CheckBox(B).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(m);
bn.setBuddy(bx);
bh.add(bn,{row:0,column:0});
bh.add(bx,{row:0,column:1});
var bp=new qx.ui.form.RadioButton(Q).set({tabIndex:bl++});
bh.add(new qx.ui.basic.Label(t),{row:1,column:0});
bh.add(bp,{row:1,column:1});
var by=new qx.ui.groupbox.GroupBox(K);
by.setLayout(new qx.ui.layout.Grid(8,8));
by.setWidth(250);
bD.add(by,{row:2,column:1});
var bo=new qx.ui.form.Spinner(0,50,100).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(E);
bn.setBuddy(bo);
by.add(bn,{row:0,column:0});
by.add(bo,{row:0,column:1});
var bs=new qx.ui.form.Slider().set({tabIndex:bl++});
bs.setWidth(130);
bn=new qx.ui.basic.Label(C);
bn.setBuddy(bs);
by.add(bn,{row:1,column:0});
by.add(bs,{row:1,column:1});
bs.bind(p,bo,p);
bo.bind(p,bs,p);
return bD;
},__vw:function(bE){for(var i=0;i<10;i++){var bF=new qx.ui.form.ListItem(F+i);
bE.add(bF);
}},__vx:function(){var a=new qx.ui.menu.Menu;

for(var i=0;i<3;i++){a.add(new qx.ui.menu.RadioButton(z+i));
}var d=new qx.ui.form.RadioGroup;
d.add.apply(d,a.getChildren());
var c=new qx.ui.menu.Menu();

for(var i=0;i<3;i++){var e=new qx.ui.menu.Button(n+i);
c.add(e);
}var b=new qx.ui.menu.Button(R,s,null,a);
c.addSeparator();
c.add(b);
return c;
},__vy:function(){var ba=new qx.ui.menu.Menu;
var bd=new qx.ui.menu.Button(A);
var bb=new qx.ui.menu.Button(g);
var bc=new qx.ui.menu.Button(N);
ba.add(bd);
ba.add(bb);
ba.add(bc);
return ba;
}}});
})();
(function(){var n="button",m="hovered",l="pressed",k="arrow",j="Enter",i="Space",h="abandoned",g="both",f="String",d="changeVisibility",D="splitbutton",C="changeShow",B="mouseout",A="keydown",z="execute",y="_applyMenu",x="icon",w="mouseover",v="keyup",u="qx.ui.menu.Menu",s="_applyIcon",t="label",q="_applyShow",r="changeMenu",o="_applyLabel",p="qx.ui.form.SplitButton";
qx.Class.define(p,{extend:qx.ui.core.Widget,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IExecutable],construct:function(J,K,L,M){arguments.callee.base.call(this);
this._setLayout(new qx.ui.layout.HBox);
this._createChildControl(k);
this.addListener(w,this._onMouseOver,this,true);
this.addListener(B,this._onMouseOut,this,true);
this.addListener(A,this._onKeyDown);
this.addListener(v,this._onKeyUp);
if(J!=null){this.setLabel(J);
}
if(K!=null){this.setIcon(K);
}
if(L!=null){this.setMenu(L);
}
if(M!=null){this.setCommand(M);
}},properties:{appearance:{refine:true,init:D},focusable:{refine:true,init:true},label:{apply:o,nullable:true,check:f},icon:{check:f,apply:s,nullable:true,themeable:true},show:{init:g,check:[g,t,x],themeable:true,inheritable:true,apply:q,event:C},menu:{check:u,nullable:true,apply:y,event:r}},members:{__vz:null,_createChildControlImpl:function(N){var O;

switch(N){case n:O=new qx.ui.form.Button;
O.addListener(z,this._onButtonExecute,this);
O.setFocusable(false);
this._addAt(O,0,{flex:1});
break;
case k:O=new qx.ui.form.MenuButton;
O.setFocusable(false);
this._addAt(O,1);
break;
}return O||arguments.callee.base.call(this,N);
},_forwardStates:{hovered:1,focused:1},_applyLabel:function(P,Q){var R=this.getChildControl(n);
P==null?R.resetLabel():R.setLabel(P);
},_applyIcon:function(S,T){var U=this.getChildControl(n);
S==null?U.resetIcon():U.setIcon(S);
},_applyMenu:function(a,b){var c=this.getChildControl(k);

if(a){c.resetEnabled();
c.setMenu(a);
a.setOpener(this);
a.addListener(d,this._onChangeMenuVisibility,this);
}else{c.setEnabled(false);
c.resetMenu();
}
if(b){b.removeListener(d,this._onChangeMenuVisibility,this);
b.resetOpener();
}},_applyShow:function(E,F){},_onMouseOver:function(e){e.stopPropagation();
this.addState(m);
delete this.__vz;
},_onMouseOut:function(e){e.stopPropagation();
if(!this.hasState(m)){return;
}var I=e.getRelatedTarget();

if(qx.ui.core.Widget.contains(this,I)){return;
}var H=this.getMenu();

if(H&&H.isVisible()){this.__vz=true;
return;
}this.removeState(m);
},_onKeyDown:function(e){var V=this.getChildControl(n);

switch(e.getKeyIdentifier()){case j:case i:V.removeState(h);
V.addState(l);
}},_onKeyUp:function(e){var G=this.getChildControl(n);

switch(e.getKeyIdentifier()){case j:case i:if(G.hasState(l)){G.removeState(h);
G.removeState(l);
G.execute();
}}},_onButtonExecute:function(e){this.execute();
},_onChangeMenuVisibility:function(e){if(!this.getMenu().isVisible()&&this.__vz){this.removeState(m);
}}}});
})();
(function(){var p="textfield",o="",n="downbutton",m="upbutton",l="Number",k="inner",j="PageUp",i="Boolean",h="changeValue",g="Down",M="Up",L="execute",K="PageDown",J="changeLocale",I="qx.dynlocale",H="on",G="_applyEditable",F="_applyWrap",E="keydown",D="\-]",w="mousewheel",x="_applyValue",u="number",v="_applyMinimum",s="qx.util.format.NumberFormat",t="[0-9",q="keyup",r="spinner",y="this._checkValue(value)",z="_applyMaximum",B="changeNumberFormat",A="_applyNumberFormat",C="qx.ui.form.Spinner";
qx.Class.define(C,{extend:qx.ui.core.Widget,implement:[qx.ui.form.INumberForm,qx.ui.form.IRange,qx.ui.form.IForm],include:[qx.ui.core.MContentPadding,qx.ui.form.MForm],construct:function(U,V,W){arguments.callee.base.call(this);
var X=new qx.ui.layout.Grid();
X.setColumnFlex(0,1);
X.setRowFlex(0,1);
X.setRowFlex(1,1);
this._setLayout(X);
this.addListener(E,this._onKeyDown,this);
this.addListener(q,this._onKeyUp,this);
this.addListener(w,this._onMouseWheel,this);

if(qx.core.Variant.isSet(I,H)){qx.locale.Manager.getInstance().addListener(J,this._onChangeLocale,this);
}this._createChildControl(p);
this._createChildControl(m);
this._createChildControl(n);
if(U!=null){this.setMinimum(U);
}
if(W!=null){this.setMaximum(W);
}
if(V!==undefined){this.setValue(V);
}else{this.initValue();
}},properties:{appearance:{refine:true,init:r},focusable:{refine:true,init:true},singleStep:{check:l,init:1},pageStep:{check:l,init:10},minimum:{check:l,apply:v,init:0},value:{check:y,nullable:true,apply:x,init:0,event:h},maximum:{check:l,apply:z,init:100},wrap:{check:i,init:false,apply:F},editable:{check:i,init:true,apply:G},numberFormat:{check:s,apply:A,nullable:true},allowShrinkY:{refine:true,init:false}},members:{__vA:null,__vB:false,__vC:false,_createChildControlImpl:function(S){var T;

switch(S){case p:T=new qx.ui.form.TextField();
T.setFilter(this._getFilterRegExp());
T.addState(k);
T.setWidth(40);
T.setFocusable(false);
T.addListener(h,this._onTextChange,this);
this._add(T,{column:0,row:0,rowSpan:2});
break;
case m:T=new qx.ui.form.RepeatButton();
T.addState(k);
T.setFocusable(false);
T.addListener(L,this._countUp,this);
this._add(T,{column:1,row:0});
break;
case n:T=new qx.ui.form.RepeatButton();
T.addState(k);
T.setFocusable(false);
T.addListener(L,this._countDown,this);
this._add(T,{column:1,row:1});
break;
}return T||arguments.callee.base.call(this,S);
},_getFilterRegExp:function(){var bp=qx.locale.Number.getDecimalSeparator(qx.locale.Manager.getInstance().getLocale());
var bo=qx.locale.Number.getGroupSeparator(qx.locale.Manager.getInstance().getLocale());
var bn=o;
var bl=o;

if(this.getNumberFormat()!==null){bn=this.getNumberFormat().getPrefix()||o;
bl=this.getNumberFormat().getPostfix()||o;
}var bm=new RegExp(t+qx.lang.String.escapeRegexpChars(bp)+qx.lang.String.escapeRegexpChars(bo)+qx.lang.String.escapeRegexpChars(bn)+qx.lang.String.escapeRegexpChars(bl)+D);
return bm;
},_forwardStates:{focused:true,invalid:true},tabFocus:function(){var bh=this.getChildControl(p);
bh.getFocusElement().focus();
bh.selectAllText();
},_applyMinimum:function(Y,ba){if(this.getMaximum()<Y){this.setMaximum(Y);
}
if(this.getValue()<Y){this.setValue(Y);
}else{this._updateButtons();
}},_applyMaximum:function(d,f){if(this.getMinimum()>d){this.setMin(d);
}
if(this.getValue()>d){this.setValue(d);
}else{this._updateButtons();
}},_applyEnabled:function(Q,R){arguments.callee.base.call(this,Q,R);
this._updateButtons();
},_checkValue:function(bb){return typeof bb===u&&bb>=this.getMinimum()&&bb<=this.getMaximum();
},_applyValue:function(bq,br){var bs=this.getChildControl(p);
this._updateButtons();
this.__vA=bq;
if(bq!==null){if(this.getNumberFormat()){bs.setValue(this.getNumberFormat().format(bq));
}else{bs.setValue(bq+o);
}}else{bs.setValue(o);
}},_applyEditable:function(bv,bw){var bx=this.getChildControl(p);

if(bx){bx.setReadOnly(!bv);
}},_applyWrap:function(bt,bu){this._updateButtons();
},_applyNumberFormat:function(bi,bj){var bk=this.getChildControl(p);
bk.setFilter(this._getFilterRegExp());
this.getNumberFormat().addListener(B,this._onChangeNumberFormat,this);
this._applyValue(this.__vA,undefined);
},_getContentPaddingTarget:function(){return this.getChildControl(p);
},_updateButtons:function(){var bf=this.getChildControl(m);
var be=this.getChildControl(n);
var bg=this.getValue();

if(!this.getEnabled()){bf.setEnabled(false);
be.setEnabled(false);
}else{if(this.getWrap()){bf.setEnabled(true);
be.setEnabled(true);
}else{if(bg!==null&&bg<this.getMaximum()){bf.setEnabled(true);
}else{bf.setEnabled(false);
}if(bg!==null&&bg>this.getMinimum()){be.setEnabled(true);
}else{be.setEnabled(false);
}}}},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case j:this.__vB=true;
case M:this.getChildControl(m).press();
break;
case K:this.__vC=true;
case g:this.getChildControl(n).press();
break;
default:return ;
}e.stopPropagation();
e.preventDefault();
},_onKeyUp:function(e){switch(e.getKeyIdentifier()){case j:this.getChildControl(m).release();
this.__vB=false;
break;
case M:this.getChildControl(m).release();
break;
case K:this.getChildControl(n).release();
this.__vC=false;
break;
case g:this.getChildControl(n).release();
break;
}},_onMouseWheel:function(e){if(e.getWheelDelta()>0){this._countDown();
}else{this._countUp();
}e.stop();
},_onTextChange:function(e){var bc=this.getChildControl(p);
var bd;
if(this.getNumberFormat()){try{bd=this.getNumberFormat().parse(bc.getValue());
}catch(N){}}if(bd===undefined){bd=parseFloat(bc.getValue(),10);
}if(!isNaN(bd)){if(bd>this.getMaximum()){bc.setValue(this.getMaximum()+o);
return;
}else if(bd<this.getMinimum()){bc.setValue(this.getMinimum()+o);
return;
}this.setValue(bd);
}else{this._applyValue(this.__vA,undefined);
}},_onChangeLocale:function(by){if(this.getNumberFormat()!==null){this.setNumberFormat(this.getNumberFormat());
var bz=this.getChildControl(p);
bz.setFilter(this._getFilterRegExp());
bz.setValue(this.getNumberFormat().format(this.getValue()));
}},_onChangeNumberFormat:function(O){var P=this.getChildControl(p);
P.setFilter(this._getFilterRegExp());
P.setValue(this.getNumberFormat().format(this.getValue()));
},_countUp:function(){if(this.__vB){var bB=this.getValue()+this.getPageStep();
}else{var bB=this.getValue()+this.getSingleStep();
}if(this.getWrap()){if(bB>this.getMaximum()){var bA=this.getMaximum()-bB;
bB=this.getMinimum()+bA;
}}this.gotoValue(bB);
},_countDown:function(){if(this.__vC){var b=this.getValue()-this.getPageStep();
}else{var b=this.getValue()-this.getSingleStep();
}if(this.getWrap()){if(b<this.getMinimum()){var a=this.getMinimum()+b;
b=this.getMaximum()-a;
}}this.gotoValue(b);
},gotoValue:function(c){return this.setValue(Math.min(this.getMaximum(),Math.max(this.getMinimum(),c)));
}},destruct:function(){if(qx.core.Variant.isSet(I,H)){qx.locale.Manager.getInstance().removeListener(J,this._onChangeLocale,this);
}}});
})();
(function(){var c="password",b="qx.ui.form.PasswordField",a="input";
qx.Class.define(b,{extend:qx.ui.form.TextField,members:{_createInputElement:function(){var d=new qx.html.Input(c);
d.addListener(a,this._onHtmlInput,this);
return d;
}}});
})();
