qx.$$packageData['e80126cd24a4']={"locales":{},"resources":{"qx/icon/Tango/16/actions/edit-clear.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-copy.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-cut.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-delete.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-find.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-paste.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-redo.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-select-all.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-undo.png":[16,16,"png","qx"]},"translations":{"C":{},"de":{"A date:":"Datum:","Command Menu (keyboard shortcuts)":"Command-Menü (Tastenkürzel)","Copy":"Kopieren","Cut":"Aussschneiden","Date format full:":"Vollständiges Datumsformat:","Date format long:":"Langes Datumsformat:","Date format medium:":"Mittellanges Datumsformat:","Date format short:":"kurzes Zeitformat:","Date full:":"Vollständiges Datum:","Date long:":"Langes Datum:","Date medium:":"Mittellanges Datum:","Date short:":"Zeit (kurz):","Delete":"Löschen","Form Elements":"Formular Widgets","Format of %1:":"Format von %1:","Locale Information":"Lokalisierungsinformationen","Locale:":"Sprachkennung:","Localized ComboBox:":"Lokalisierte ComboBox:","Paste":"Einfügen","Redo":"Wiederholen","Search":"Suchen","Search Again":"Weiter suchen","Select All":"Alles auswählen","Territory code:":"Landeskennung:","Time format long:":"Langes Zeitformat:","Time format short:":"kurzes Zeitformat:","Time long:":"Zeit (lang):","Time short:":"Zeit (kurz):","Undo":"Rückgängig","Week start:":"Wochenanfang:","key_full_Alt":"Alt","key_full_Apps":"Kontextmenü","key_full_Backspace":"Rücktaste","key_full_CapsLock":"Feststelltaste","key_full_Control":"Steuerung","key_full_Delete":"Entfernen","key_full_Down":"Pfeil runter","key_full_End":"Ende","key_full_Enter":"Enter","key_full_Escape":"Escape","key_full_Home":"Position 1","key_full_Insert":"Einfügen","key_full_Left":"Pfeil links","key_full_Meta":"Meta","key_full_NumLock":"NumLock","key_full_PageDown":"Bild runter","key_full_PageUp":"Bild hoch","key_full_Pause":"Pause","key_full_PrintScreen":"Drucken","key_full_Right":"Pfeil rechts","key_full_Scroll":"Rollen","key_full_Shift":"Umschalttaste","key_full_Space":"Leertaste","key_full_Tab":"Tabulator","key_full_Up":"Pfeil hoch","key_full_Win":"Windowstaste","key_short_Alt":"Alt","key_short_Apps":"Kontext","key_short_Backspace":"Rück","key_short_CapsLock":"Feststell","key_short_Control":"Strg","key_short_Delete":"Entf","key_short_Down":"Runter","key_short_End":"Ende","key_short_Enter":"Enter","key_short_Escape":"Esc","key_short_Home":"Pos1","key_short_Insert":"Einfg","key_short_Left":"Links","key_short_Meta":"Meta","key_short_NumLock":"Num","key_short_PageDown":"Bild runter","key_short_PageUp":"Bild hoch","key_short_Pause":"Pause","key_short_PrintScreen":"Druck","key_short_Right":"Rechts","key_short_Scroll":"Rollen","key_short_Shift":"Umschalt","key_short_Space":"Leer","key_short_Tab":"Tab","key_short_Up":"Hoch","key_short_Win":"Win"},"de_AT":{},"de_DE":{},"en":{},"en_GB":{},"en_US":{},"es":{"A date:":"Una fecha:","Command Menu (keyboard shortcuts)":"Menú de comando (claves del teclado)","Copy":"Copiar","Cut":"Cortar","Date format full:":"Formato de fecha completo:","Date format long:":"Formato de fecha largo:","Date format medium:":"Formato de fecha mediano:","Date format short:":"Formato de hora corto:","Date full:":"Fecha completo:","Date long:":"Fecha largo:","Date medium:":"Fecha mediano:","Date short:":"Hora corto:","Delete":"Borrar","Format of %1:":"Formato de %1:","Locale Information":"Información de la localisación","Locale:":"Localisación:","Localized ComboBox:":"ComboBox:","Paste":"Pegar","Redo":"Rehacer","Search":"Búsqueda","Search Again":"Buscar otra vez","Select All":"Seleccionar todo","Territory code:":"Código regional:","Time format long:":"Formato de hora largo:","Time format short:":"Formato de hora corto:","Time long:":"Hora largo:","Time short:":"Hora corto:","Undo":"Deshacer","Week start:":"Inicio de semana:","key_full_Alt":"Alt","key_full_Apps":"Aplicaciones","key_full_Backspace":"Retroceso","key_full_CapsLock":"Bloqueo Mayúsculas","key_full_Control":"Control","key_full_Delete":"Suprimir","key_full_Down":"Flecha abajo","key_full_End":"Fin","key_full_Enter":"Intro","key_full_Escape":"Escape","key_full_Home":"Inicio","key_full_Insert":"Insertar","key_full_Left":"Flecha izquierda","key_full_Meta":"Meta","key_full_NumLock":"Bloqueo Numérico","key_full_PageDown":"Avanzar Página","key_full_PageUp":"Retroceder Página","key_full_Pause":"Pausa","key_full_PrintScreen":"Imprimir Pantalla","key_full_Right":"Flecha derecha","key_full_Scroll":"Bloq. Despl.","key_full_Shift":"Mayúscula","key_full_Space":"Espacio","key_full_Tab":"Tabulador","key_full_Up":"Flecha arriba","key_full_Win":"Windows","key_short_Alt":"Alt","key_short_Apps":"Aplic","key_short_Backspace":"Retroceso","key_short_CapsLock":"BloqMayús","key_short_Control":"Ctrl","key_short_Control_Mac":"Ctrl","key_short_Delete":"Supr","key_short_Down":"Abajo","key_short_End":"Fin","key_short_Enter":"Intro","key_short_Escape":"Esc","key_short_Home":"Inicio","key_short_Insert":"Insert","key_short_Left":"Izquierda","key_short_Meta":"Meta","key_short_NumLock":"BloqNum","key_short_PageDown":"AvPág","key_short_PageUp":"RePág","key_short_Pause":"Pausa","key_short_PrintScreen":"ImprPant","key_short_Right":"Derecha","key_short_Scroll":"BloqDespl","key_short_Shift":"Mayús","key_short_Space":"Espacio","key_short_Tab":"Tab","key_short_Up":"Arriba","key_short_Win":"Win"},"es_ES":{},"es_MX":{},"ro":{"A date:":"O dată:","Command Menu (keyboard shortcuts)":"Meniu de comandă (scurtături de tastatură)","Copy":"Copiază","Cut":"Taie","Date format full:":"Format dată întreg:","Date format long:":"Format dată lung:","Date format medium:":"Format dată mediu:","Date format short:":"Format dată scurt:","Date full:":"Dată întreagă:","Date long:":"Dată lungă:","Date medium:":"Dată medie:","Date short:":"Dată scurtă:","Delete":"Şterge","Form Elements":"Elemente de formular","Format of %1:":"Formatul %1:","Locale Information":"Informație despre localizare","Locale:":"Localizare:","Localized ComboBox:":"ComboBox localizată:","Paste":"Lipește","Redo":"Refă","Search":"Caută","Search Again":"Caută din nou","Select All":"Selectează tot","Territory code:":"Cod postal:","Time format long:":"Format oră lung:","Time format short:":"Format oră curt:","Time long:":"Oră lungă:","Time short:":"Oră scurtă:","Undo":"Desfă","Week start:":"Începutul săptămânii:"}}};

qx.Part.$$notifyLoad("e80126cd24a4", function() {
(function(){var o="String",n="execute",m="qx.ui.menu.Menu",l="_shortcut",k="changeEnabled",j="changeToolTipText",i="Boolean",h="qx.ui.core.Command",g="changeLabel",f="changeMenu",c="changeIcon",e="changeValue",d="_applyShortcut",b="_applyEnabled",a="qx.event.type.Data";
qx.Class.define(h,{extend:qx.core.Object,construct:function(p){qx.core.Object.call(this);
this._shortcut=new qx.bom.Shortcut(p);
this._shortcut.addListener(n,this.execute,this);
},events:{"execute":a},properties:{enabled:{init:true,check:i,event:k,apply:b},shortcut:{check:o,apply:d,nullable:true},label:{check:o,nullable:true,event:g},icon:{check:o,nullable:true,event:c},toolTipText:{check:o,nullable:true,event:j},value:{nullable:true,event:e},menu:{check:m,nullable:true,event:f}},members:{_shortcut:null,_applyEnabled:function(q){this._shortcut.setEnabled(q);
},_applyShortcut:function(r){this._shortcut.setShortcut(r);
},execute:function(s){this.fireDataEvent(n,s);
},toString:function(){return this._shortcut.toString();
}},destruct:function(){this._disposeObjects(l);
}});
})();
(function(){var m="Unidentified",l="Boolean",k="+",j="short",h="keydown",g="",f="Control",d="keypress",c="-",b="PageUp",S="Escape",R="qx.event.type.Data",Q="_applyShortcut",P="PrintScreen",O="NumLock",N="5",M="8",L="execute",K="Meta",J="0",t="2",u="Shift",r="You can only specify one non modifier key!",s="3",p="/",q="Delete",n="String",o="changeEnabled",v="*",w="qx.bom.Shortcut",B="6",A="4",D="1",C="Alt",F="Not a valid key name for a shortcut: ",E="PageDown",y="Whitespaces are not allowed within shortcuts",I="_applyEnabled",H="7",G="a",x="z",z="9";
qx.Class.define(w,{extend:qx.core.Object,construct:function(T){qx.core.Object.call(this);
this.__yc={};
this.__yd=null;

if(T!=null){this.setShortcut(T);
}this.initEnabled();
},events:{"execute":R},properties:{enabled:{init:true,check:l,event:o,apply:I},shortcut:{check:n,apply:Q,nullable:true},autoRepeat:{check:l,init:false}},members:{__yc:g,__yd:g,execute:function(U){this.fireDataEvent(L,U);
},__ye:function(event){if(this.getEnabled()&&this.__yg(event)){if(!this.isAutoRepeat()){this.execute(event.getTarget());
}event.stop();
}},__yf:function(event){if(this.getEnabled()&&this.__yg(event)){if(this.isAutoRepeat()){this.execute(event.getTarget());
}event.stop();
}},_applyEnabled:function(V,W){if(V){qx.event.Registration.addListener(document.documentElement,h,this.__ye,this);
qx.event.Registration.addListener(document.documentElement,d,this.__yf,this);
}else{qx.event.Registration.removeListener(document.documentElement,h,this.__ye,this);
qx.event.Registration.removeListener(document.documentElement,d,this.__yf,this);
}},_applyShortcut:function(X,Y){if(X){if(X.search(/[\s]+/)!=-1){var bc=y;
this.error(bc);
throw new Error(bc);
}this.__yc={"Control":false,"Shift":false,"Meta":false,"Alt":false};
this.__yd=null;
var ba;
var a=[];

while(X.length>0&&ba!=-1){ba=X.search(/[-+]+/);
a.push((X.length==1||ba==-1)?X:X.substring(0,ba));
X=X.substring(ba+1);
}var bb=a.length;

for(var i=0;i<bb;i++){var bd=this.__yi(a[i]);

switch(bd){case f:case u:case K:case C:this.__yc[bd]=true;
break;
case m:var bc=F+a[i];
this.error(bc);
throw bc;
default:if(this.__yd){var bc=r;
this.error(bc);
throw bc;
}this.__yd=bd;
}}}return true;
},__yg:function(e){var be=this.__yd;

if(!be){return ;
}if((!this.__yc.Shift&&e.isShiftPressed())||(this.__yc.Shift&&!e.isShiftPressed())||(!this.__yc.Control&&e.isCtrlPressed())||(this.__yc.Control&&!e.isCtrlPressed())||(!this.__yc.Meta&&e.isMetaPressed())||(this.__yc.Meta&&!e.isMetaPressed())||(!this.__yc.Alt&&e.isAltPressed())||(this.__yc.Alt&&!e.isAltPressed())){return false;
}
if(be==e.getKeyIdentifier()){return true;
}return false;
},__yh:{esc:S,ctrl:f,print:P,del:q,pageup:b,pagedown:E,numlock:O,numpad_0:J,numpad_1:D,numpad_2:t,numpad_3:s,numpad_4:A,numpad_5:N,numpad_6:B,numpad_7:H,numpad_8:M,numpad_9:z,numpad_divide:p,numpad_multiply:v,numpad_minus:c,numpad_plus:k},__yi:function(bf){var bg=qx.event.handler.Keyboard;
var bh=m;

if(bg.isValidKeyIdentifier(bf)){return bf;
}
if(bf.length==1&&bf>=G&&bf<=x){return bf.toUpperCase();
}bf=bf.toLowerCase();
var bh=this.__yh[bf]||qx.lang.String.firstUp(bf);

if(bg.isValidKeyIdentifier(bh)){return bh;
}else{return m;
}},toString:function(){var bk=this.__yd;
var bj=[];

for(var bi in this.__yc){if(this.__yc[bi]){bj.push(qx.locale.Key.getKeyName(j,bi));
}}
if(bk){bj.push(qx.locale.Key.getKeyName(j,bk));
}return bj.join(k);
}},destruct:function(){this.setEnabled(false);
this.__yc=this.__yd=null;
}});
})();
(function(){var bw="Control",bv="Left",bu="Meta",bt="Pause",bs="End",br="Down",bq="Ctrl",bp="Home",bo="Apps",bn="Win",bc="Right",bb="Backspace",ba="Space",Y="Up",X="Shift",W="Enter",V="Scroll",U="Alt",T="Escape",S="key_full_Meta",bD="PrintScreen",bE="NumLock",bB="key_short_Alt",bC="key_short_Control_Mac",bz="key_short_Insert",bA="Del",bx="key_full_Enter",by="key_full_Control",bF="qx.locale.Key",bG="Tabulator",bg="key_full_Space",bf="key_short_Meta",bi="key_short_PageUp",bh="key_short_Pause",bk="key_full_Down",bj="key_short_Apps",bm="key_short_Win",bl="key_full_Right",be="key_short_Up",bd="key_full_PageDown",a="key_full_Alt",b="PgDn",c="Esc",d="key_full_Insert",e="key_short_Space",f="key_short_Backspace",g="key_short_Home",h="key_short_Down",i="PgUp",j="_Mac",bK="key_short_CapsLock",bJ="PageUp",bI="key_full_Up",bH="key_full_Home",bO="key_full_Backspace",bN="PageDown",bM="CapsLock",bL="Ins",bQ="key_short_PrintScreen",bP="Tab",C="key_full_Apps",D="key_short_Tab",A="key_short_End",B="_",G="Caps",H="key_short_NumLock",E="Num",F="key_full_Scroll",y="key_short_Left",z="key_short_Scroll",r="key_",q="key_full_Pause",t="key_short_Right",s="key_full_PrintScreen",n="key_full_Win",m="key_full_Control_Mac",p="key_short_Shift",o="key_short_PageDown",l="key_short_Enter",k="key_short_Control",M="Insert",N="key_short_Escape",O="key_full_Tab",P="Print",I="Delete",J="key_full_CapsLock",K="key_full_Escape",L="key_short_Delete",Q="key_full_PageUp",R="key_full_Shift",x="key_full_NumLock",w="key_full_Delete",v="key_full_End",u="key_full_Left";
qx.Class.define(bF,{statics:{getKeyName:function(bR,bS,bT){{};
var bV=r+bR+B+bS;
if(qx.bom.client.Platform.MAC&&bS==bw){bV+=j;
}var bU=qx.locale.Manager.getInstance().translate(bV,[],bT);

if(bU==bV){return qx.locale.Key._keyNames[bV]||bS;
}else{return bU;
}}},defer:function(bW){var bY={};
var bX=qx.locale.Manager;
bY[bX.marktr(f)]=bb;
bY[bX.marktr(D)]=bP;
bY[bX.marktr(e)]=ba;
bY[bX.marktr(l)]=W;
bY[bX.marktr(p)]=X;
bY[bX.marktr(k)]=bq;
bY[bX.marktr(bC)]=bq;
bY[bX.marktr(bB)]=U;
bY[bX.marktr(bK)]=G;
bY[bX.marktr(bf)]=bu;
bY[bX.marktr(N)]=c;
bY[bX.marktr(y)]=bv;
bY[bX.marktr(be)]=Y;
bY[bX.marktr(t)]=bc;
bY[bX.marktr(h)]=br;
bY[bX.marktr(bi)]=i;
bY[bX.marktr(o)]=b;
bY[bX.marktr(A)]=bs;
bY[bX.marktr(g)]=bp;
bY[bX.marktr(bz)]=bL;
bY[bX.marktr(L)]=bA;
bY[bX.marktr(H)]=E;
bY[bX.marktr(bQ)]=P;
bY[bX.marktr(z)]=V;
bY[bX.marktr(bh)]=bt;
bY[bX.marktr(bm)]=bn;
bY[bX.marktr(bj)]=bo;
bY[bX.marktr(bO)]=bb;
bY[bX.marktr(O)]=bG;
bY[bX.marktr(bg)]=ba;
bY[bX.marktr(bx)]=W;
bY[bX.marktr(R)]=X;
bY[bX.marktr(by)]=bw;
bY[bX.marktr(m)]=bw;
bY[bX.marktr(a)]=U;
bY[bX.marktr(J)]=bM;
bY[bX.marktr(S)]=bu;
bY[bX.marktr(K)]=T;
bY[bX.marktr(u)]=bv;
bY[bX.marktr(bI)]=Y;
bY[bX.marktr(bl)]=bc;
bY[bX.marktr(bk)]=br;
bY[bX.marktr(Q)]=bJ;
bY[bX.marktr(bd)]=bN;
bY[bX.marktr(v)]=bs;
bY[bX.marktr(bH)]=bp;
bY[bX.marktr(d)]=M;
bY[bX.marktr(w)]=I;
bY[bX.marktr(x)]=bE;
bY[bX.marktr(s)]=bD;
bY[bX.marktr(F)]=V;
bY[bX.marktr(q)]=bt;
bY[bX.marktr(n)]=bn;
bY[bX.marktr(C)]=bo;
bW._keyNames=bY;
}});
})();
(function(){var o="short",n="long",m="selection[0]",l="medium",k="Cut",j="Copy",h="language",g="Paste",f="full",e="selection[0].selected",bF="Territory code:",bE="icon/16/actions/edit-find.png",bD="Time format short:",bC="Ctrl+V",bB="icon/16/actions/edit-delete.png",bA="icon/16/actions/edit-cut.png",bz="United States",by="Date medium:",bx=".png",bw="Date long:",v="DE",w="en",t="Time format long:",u="Mexico",r="button",s="Locale:",p="AT",q="Undo",D="Date short:",E="Austria",W="Format of %1:",S="Date format short:",bf="changeLocale",ba="Search",br="MX",bl="center",L="Ctrl+X",bv="wide",bt="es",bs="US",J="middle",O="Time short:",Q="A date:",U="name",X="GB",bb="icon",bh="ES",bn="Germany",x="_",y="Date format medium:",N="de",be="F3",bd="Date format full:",bc="Week start:",bj="Ctrl+F",bi="icon/16/actions/edit-paste.png",Y="Del",bg="showcase.page.i18n.Content",a="Date format long:",bm="right",z="icon/16/actions/edit-copy.png",A="country",T="selection[0].countries",b="Spain",d="selection[0].selected.code",I="Locale Information",B="Redo",C="Delete",G="model",V="Ctrl+C",bp="Date full:",bo="Ctrl+A",P="Search Again",bq="Localized ComboBox:",K="Select All",bk="Ctrl+Z",F="Time long:",H="Ctrl+Y",c="Command Menu (keyboard shortcuts)",R="showcase/i18n/",M="Form Elements",bu="Great Britain";
qx.Class.define(bg,{extend:showcase.AbstractContent,include:qx.locale.MTranslation,construct:function(bG){showcase.AbstractContent.call(this,bG);
this.setView(this._createView());
},members:{__tW:null,__tX:null,_createView:function(){var bI=new qx.ui.layout.Grid(10,15);
bI.setColumnFlex(0,1);
bI.setColumnFlex(1,1);
var bH=new qx.ui.container.Composite(bI).set({padding:10});
bH.add(this.__tY(),{row:0,column:0,colSpan:2});
bH.add(this.__ua(),{row:1,column:0});
bH.add(this.__ub(),{row:1,column:1});
return bH;
},__tY:function(){var bK=new qx.ui.form.RadioButtonGroup(new qx.ui.layout.HBox(10).set({alignX:bl}));
var bL=this.__tW=qx.data.marshal.Json.createModel([{language:w,selected:null,countries:[{code:bs,name:bz},{code:X,name:bu}]},{language:bt,selected:null,countries:[{code:bh,name:b},{code:br,name:u}]},{language:N,selected:null,countries:[{code:v,name:bn},{code:p,name:E}]}]);

for(var i=0;i<bL.getLength();i++){bL.getItem(i).setSelected(bL.getItem(i).getCountries().getItem(0));
}var bJ=new qx.data.controller.List(null,bK,h);
this.__tX=bJ;
bJ.setDelegate({createItem:function(){return new qx.ui.form.RadioButton().set({show:bb,appearance:r});
}});
bJ.setIconPath(h);
bJ.setIconOptions({converter:function(bM){return R+bM+bx;
}});
bJ.setModel(bL);
bJ.getSelection().push(bL.getItem(0));
this.__tX.bind(d,this,A);
return bK;
},setCountry:function(bN){if(bN){var bO=this.__tX.getSelection().getItem(0).getLanguage();
qx.locale.Manager.getInstance().setLocale(bO+x+bN);
}},__ua:function(){var cb=new qx.ui.layout.Grid(10,10);
cb.setColumnFlex(0,1);
cb.setColumnFlex(1,1);
cb.setColumnAlign(0,bm,J);
var bX=new qx.ui.groupbox.GroupBox(this.tr(M)).set({width:0,minWidth:0});
bX.setLayout(cb);
bX.add(new qx.ui.basic.Label(this.tr(bF)),{row:0,column:0});
var bT=new qx.ui.form.SelectBox();
var ca=new qx.data.controller.List(null,bT,U);
this.__tX.bind(T,ca,G);
this.__tX.bind(e,ca,m);
ca.bind(m,this.__tX,e);
bX.add(bT,{row:0,column:1});
bX.add(new qx.ui.basic.Label(this.tr(bq)),{row:1,column:0});
var bP=new qx.ui.form.ComboBox();
bP.add(new qx.ui.form.ListItem(this.tr(k)));
bP.add(new qx.ui.form.ListItem(this.tr(g)));
bP.add(new qx.ui.form.ListItem(this.tr(j)));
bX.add(bP,{row:1,column:1});
var cd=new qx.ui.basic.Label(this.tr(Q));
bX.add(cd,{row:2,column:0});
var cg=new qx.ui.form.DateField();
cg.setValue(new Date);
bX.add(cg,{row:2,column:1});
var bW=new qx.ui.control.DateChooser;
bX.add(bW,{row:3,column:0,colSpan:2});
var bV=new qx.ui.core.Command(bk);
var bY=new qx.ui.core.Command(H);
var bQ=new qx.ui.core.Command(L);
var bU=new qx.ui.core.Command(V);
var ch=new qx.ui.core.Command(bC);
var ci=new qx.ui.core.Command(Y);
var cf=new qx.ui.core.Command(bo);
var bR=new qx.ui.core.Command(bj);
var ce=new qx.ui.core.Command(be);
var bS=new qx.ui.menu.Menu;
bS.add(new qx.ui.menu.Button(this.tr(q),null,bV));
bS.add(new qx.ui.menu.Button(this.tr(B),null,bY));
bS.add(new qx.ui.menu.Separator());
bS.add(new qx.ui.menu.Button(this.tr(k),bA,bQ));
bS.add(new qx.ui.menu.Button(this.tr(j),z,bU));
bS.add(new qx.ui.menu.Button(this.tr(g),bi,ch));
bS.add(new qx.ui.menu.Button(this.tr(C),bB,ci));
bS.add(new qx.ui.menu.Button(this.tr(K),null,cf));
bS.add(new qx.ui.menu.Separator());
bS.add(new qx.ui.menu.Button(this.tr(ba),null,bR));
bS.add(new qx.ui.menu.Button(this.tr(P),null,ce));
var cc=new qx.ui.form.MenuButton(this.tr(c),null,bS);
bX.add(cc,{row:4,column:0,colSpan:2});
return bX;
},__ub:function(){var ck=new qx.ui.groupbox.GroupBox(this.tr(I),bE).set({width:0,minWidth:0,allowGrowY:true});
ck.setLayout(new qx.ui.layout.Grow());
var cl=new qx.ui.basic.Label().set({rich:true,allowGrowX:true,allowGrowY:true});
ck.add(cl);
var cj=[];
cj.push("<table id='i18n'><tr><td>");

for(var i=0;i<15;i++){cj.push("");
cj.push("</td><td>");
cj.push("");
cj.push("</td></tr><td>");
}cj.push("");
cj.push("</td><td>");
cj.push("");
cj.push("</td></tr></table>");
this.updateLocaleInformation=function(){var i=0;
cj[(i++*2)+1]=this.tr(s);
cj[(i++*2)+1]=qx.locale.Manager.getInstance().getLocale();
cj[(i++*2)+1]=this.tr(bF);
cj[(i++*2)+1]=qx.locale.Manager.getInstance().getTerritory();
cj[(i++*2)+1]=this.tr(S);
cj[(i++*2)+1]=qx.locale.Date.getDateFormat(o);
cj[(i++*2)+1]=this.tr(D);
cj[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(o))).format(new Date());
cj[(i++*2)+1]=this.tr(y);
cj[(i++*2)+1]=qx.locale.Date.getDateFormat(l);
cj[(i++*2)+1]=this.tr(by);
cj[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(l))).format(new Date());
cj[(i++*2)+1]=this.tr(a);
cj[(i++*2)+1]=qx.locale.Date.getDateFormat(n);
cj[(i++*2)+1]=this.tr(bw);
cj[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(n))).format(new Date());
cj[(i++*2)+1]=this.tr(bd);
cj[(i++*2)+1]=qx.locale.Date.getDateFormat(f);
cj[(i++*2)+1]=this.tr(bp);
cj[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(f))).format(new Date());
cj[(i++*2)+1]=this.tr(bD);
cj[(i++*2)+1]=qx.locale.Date.getTimeFormat(o);
cj[(i++*2)+1]=this.tr(O);
cj[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(o))).format(new Date());
cj[(i++*2)+1]=this.tr(t);
cj[(i++*2)+1]=qx.locale.Date.getTimeFormat(n);
cj[(i++*2)+1]=this.tr(F);
cj[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(n))).format(new Date());
cj[(i++*2)+1]=this.tr(bc);
cj[(i++*2)+1]=qx.locale.Date.getDayName(bv,qx.locale.Date.getWeekStart());
cj[(i++*2)+1]=this.tr(W,10000.12);
cj[(i++*2)+1]=qx.util.format.NumberFormat.getInstance().format(10000.12);
cl.setValue(cj.join(""));
};
qx.locale.Manager.getInstance().addListener(bf,this.updateLocaleInformation,this);
this.updateLocaleInformation();
return ck;
}}});
})();

});