qx.$$packageData['a1b6899e5b82']={"locales":{},"resources":{},"translations":{}};

qx.Part.$$notifyLoad("a1b6899e5b82", function() {
(function(){var s="pressed",r="abandoned",q="hovered",p="checked",o="Space",n="Enter",m="mouseup",l="mousedown",k="Boolean",j="_applyValue",c="mouseover",i="mouseout",g="qx.ui.form.ToggleButton",b="keydown",a="changeValue",f="button",d="keyup",h="execute";
qx.Class.define(g,{extend:qx.ui.basic.Atom,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IBooleanForm,qx.ui.form.IExecutable],construct:function(t,u){qx.ui.basic.Atom.call(this,t,u);
this.addListener(c,this._onMouseOver);
this.addListener(i,this._onMouseOut);
this.addListener(l,this._onMouseDown);
this.addListener(m,this._onMouseUp);
this.addListener(b,this._onKeyDown);
this.addListener(d,this._onKeyUp);
this.addListener(h,this._onExecute,this);
},properties:{appearance:{refine:true,init:f},focusable:{refine:true,init:true},value:{check:k,nullable:true,event:a,apply:j,init:false}},members:{_applyValue:function(v,w){v?this.addState(p):this.removeState(p);
},_onExecute:function(e){this.toggleValue();
},_onMouseOver:function(e){if(e.getTarget()!==this){return;
}this.addState(q);

if(this.hasState(r)){this.removeState(r);
this.addState(s);
}},_onMouseOut:function(e){if(e.getTarget()!==this){return;
}this.removeState(q);

if(this.hasState(s)){if(!this.getValue()){this.removeState(s);
}this.addState(r);
}},_onMouseDown:function(e){if(!e.isLeftPressed()){return;
}this.capture();
this.removeState(r);
this.addState(s);
e.stopPropagation();
},_onMouseUp:function(e){this.releaseCapture();

if(this.hasState(r)){this.removeState(r);
}else if(this.hasState(s)){this.execute();
}this.removeState(s);
e.stopPropagation();
},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case n:case o:this.removeState(r);
this.addState(s);
e.stopPropagation();
}},_onKeyUp:function(e){if(!this.hasState(s)){return;
}
switch(e.getKeyIdentifier()){case n:case o:this.removeState(r);
this.execute();
this.removeState(s);
e.stopPropagation();
}}}});
})();
(function(){var b="checkbox",a="qx.ui.form.CheckBox";
qx.Class.define(a,{extend:qx.ui.form.ToggleButton,include:[qx.ui.form.MForm,qx.ui.form.MModelProperty],implement:[qx.ui.form.IForm,qx.ui.form.IModel],construct:function(c){{};
qx.ui.form.ToggleButton.call(this,c);
this.setValue(false);
},properties:{appearance:{refine:true,init:b},allowGrowX:{refine:true,init:false}}});
})();
(function(){var h="auto",g="textarea",f="Boolean",d="qx.ui.form.TextArea",c="_applyWrap",b="Integer",a="mousewheel";
qx.Class.define(d,{extend:qx.ui.form.AbstractField,construct:function(l){qx.ui.form.AbstractField.call(this,l);
this.initWrap();
this.addListener(a,this._onMousewheel,this);
},properties:{wrap:{check:f,init:true,apply:c},appearance:{refine:true,init:g},singleStep:{check:b,init:20}},members:{_onMousewheel:function(e){var m=this.getContentElement();
var scrollY=m.getScrollY();
m.scrollToY(scrollY+e.getWheelDelta()*this.getSingleStep());
var n=m.getScrollY();

if(n!=scrollY){e.stop();
}},_createInputElement:function(){return new qx.html.Input(g,{overflowX:h,overflowY:h});
},_applyWrap:function(i,j){this.getContentElement().setWrap(i);
},_getContentHint:function(){var k=qx.ui.form.AbstractField.prototype._getContentHint.call(this);
k.height=k.height*4;
k.width=this._getTextSize().width*20;
return k;
}}});
})();
(function(){var k="value",j="placeholder",h="Button",g="CheckBox:",f="TextArea:",e="Boolean",d="RepeatButton:",c="execute",b="Website 2",a="Text",T="ToggleButton",S="password",R="RadioButton 3",Q="showcase.page.form.Content",P="Button:",O="ComboBox:",N="ToggleButton:",M="Options",L="RadioButton",K="0",r="MenuButton:",s="PasswordField:",p="SplitButton",q="Buttons",n="",o="RadioButtons:",l="dd.mm.YYYY",m="List:",t="SplitButton:",u="Option",B="RadioButton 1",z="Spinner:",E="Selection",D="DateField:",G="RadioButton 2",F="Number",w="CheckBox",J="SelectBox:",I="Website 3",H="MenuButton",v="Website 1",x="Slider:",y="TextField:",A="Item ",C="RadioButtonGroup:";
qx.Class.define(Q,{extend:showcase.AbstractContent,construct:function(bE){showcase.AbstractContent.call(this,bE);
this.setView(this._createView());
},members:{_createView:function(){var bt=new qx.ui.layout.Grid(20,5);
bt.setColumnFlex(0,1);
bt.setColumnFlex(1,1);
var bD=new qx.ui.container.Composite(bt);
bD.setPadding(10);
var bl=1;
var be=new qx.ui.groupbox.GroupBox(a);
be.setLayout(new qx.ui.layout.Grid(8,8));
be.setWidth(290);
bD.add(be,{row:0,column:0});
var bC=new qx.ui.form.TextField();
bC.setPlaceholder(j);
bC.setTabIndex(bl++);
var bn=new qx.ui.basic.Label(y);
bn.setBuddy(bC);
be.add(bn,{row:0,column:0});
be.add(bC,{row:0,column:1});
var bk=new qx.ui.form.PasswordField();
bk.setTabIndex(bl++);
bk.setPlaceholder(S);
bn=new qx.ui.basic.Label(s);
bn.setBuddy(bk);
be.add(bn,{row:1,column:0});
be.add(bk,{row:1,column:1});
var bf=new qx.ui.form.TextArea();
bf.setTabIndex(bl++);
bf.setPlaceholder(j);
bn=new qx.ui.basic.Label(f);
bn.setBuddy(bf);
be.add(bn,{row:2,column:0});
be.add(bf,{row:2,column:1});
var bg=new qx.ui.form.ComboBox();
bg.setTabIndex(bl++);
bg.setPlaceholder(j);
bn=new qx.ui.basic.Label(O);
bn.setBuddy(bg);
be.add(bn,{row:3,column:0});
be.add(bg,{row:3,column:1});
this.__Jp(bg);
var bv=new qx.ui.form.DateField();
bv.setTabIndex(bl++);
bv.setPlaceholder(l);
bn=new qx.ui.basic.Label(D);
bn.setBuddy(bv);
be.add(bn,{row:4,column:0});
be.add(bv,{row:4,column:1});
var bm=new qx.ui.groupbox.GroupBox(E);
bm.setLayout(new qx.ui.layout.Grid(8,8));
bm.setWidth(290);
bD.add(bm,{row:1,column:0,rowSpan:2});
var bw=new qx.ui.form.SelectBox();
bw.setTabIndex(bl++);
bn=new qx.ui.basic.Label(J);
bn.setBuddy(bw);
bm.add(bn,{row:0,column:0});
bm.add(bw,{row:0,column:1});
this.__Jp(bw);
var bB=new qx.ui.form.List();
bB.setTabIndex(bl++);
bB.setHeight(60);
bB.setWidth(155);
bn=new qx.ui.basic.Label(m);
bn.setBuddy(bB);
bm.add(bn,{row:1,column:0});
bm.add(bB,{row:1,column:1});
this.__Jp(bB);
var bu=new qx.ui.form.RadioButtonGroup();
bu.add(new qx.ui.form.RadioButton(B).set({tabIndex:bl++}));
bu.add(new qx.ui.form.RadioButton(G).set({tabIndex:bl++}));
bu.add(new qx.ui.form.RadioButton(R).set({tabIndex:bl++}));
bn=new qx.ui.basic.Label(C);
bn.setBuddy(bu);
bm.add(bn,{row:2,column:0});
bm.add(bu,{row:2,column:1});
var bz=new qx.ui.groupbox.GroupBox(q);
bz.setLayout(new qx.ui.layout.Grid(8,8));
bz.setWidth(250);
bD.add(bz,{row:0,column:1});
var bA=new qx.ui.form.Button(h).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(P);
bn.setBuddy(bA);
bz.add(bn,{row:0,column:0});
bz.add(bA,{row:0,column:1});
var bi=new qx.ui.form.ToggleButton(T).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(N);
bn.setBuddy(bi);
bz.add(bn,{row:1,column:0});
bz.add(bi,{row:1,column:1});
var bq=new qx.ui.form.RepeatButton(K).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(d);
bn.setBuddy(bq);
bz.add(bn,{row:2,column:0});
bz.add(bq,{row:2,column:1});
var br=new qx.ui.form.MenuButton(H,null,this.__Jq()).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(r);
bn.setBuddy(br);
bz.add(bn,{row:3,column:0});
bz.add(br,{row:3,column:1});
var bj=new qx.ui.form.SplitButton(p,null,this.__Jr()).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(t);
bn.setBuddy(bj);
bz.add(bn,{row:4,column:0});
bz.add(bj,{row:4,column:1});
bq.addListener(c,function(){var bH=parseInt(bq.getLabel())+1;
bq.setLabel(bH.toString());
});
var bh=new qx.ui.groupbox.GroupBox(e);
bh.setLayout(new qx.ui.layout.Grid(8,8));
bh.setWidth(250);
bD.add(bh,{row:1,column:1});
var bx=new qx.ui.form.CheckBox(w).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(g);
bn.setBuddy(bx);
bh.add(bn,{row:0,column:0});
bh.add(bx,{row:0,column:1});
var bp=new qx.ui.form.RadioButton(L).set({tabIndex:bl++});
bh.add(new qx.ui.basic.Label(o),{row:1,column:0});
bh.add(bp,{row:1,column:1});
var by=new qx.ui.groupbox.GroupBox(F);
by.setLayout(new qx.ui.layout.Grid(8,8));
by.setWidth(250);
bD.add(by,{row:2,column:1});
var bo=new qx.ui.form.Spinner(0,50,100).set({tabIndex:bl++});
bn=new qx.ui.basic.Label(z);
bn.setBuddy(bo);
by.add(bn,{row:0,column:0});
by.add(bo,{row:0,column:1});
var bs=new qx.ui.form.Slider().set({tabIndex:bl++});
bs.setWidth(130);
bn=new qx.ui.basic.Label(x);
bn.setBuddy(bs);
by.add(bn,{row:1,column:0});
by.add(bs,{row:1,column:1});
bs.bind(k,bo,k);
bo.bind(k,bs,k);
return bD;
},__Jp:function(bF){for(var i=0;i<10;i++){var bG=new qx.ui.form.ListItem(A+i);
bF.add(bG);
}},__Jq:function(){var U=new qx.ui.menu.Menu;

for(var i=0;i<3;i++){U.add(new qx.ui.menu.RadioButton(u+i));
}var X=new qx.ui.form.RadioGroup;
X.add.apply(X,U.getChildren());
var W=new qx.ui.menu.Menu();

for(var i=0;i<3;i++){var Y=new qx.ui.menu.Button(h+i);
W.add(Y);
}var V=new qx.ui.menu.Button(M,n,null,U);
W.addSeparator();
W.add(V);
return W;
},__Jr:function(){var ba=new qx.ui.menu.Menu;
var bd=new qx.ui.menu.Button(v);
var bb=new qx.ui.menu.Button(b);
var bc=new qx.ui.menu.Button(I);
ba.add(bd);
ba.add(bb);
ba.add(bc);
return ba;
}}});
})();
(function(){var k="button",j="hovered",i="pressed",h="arrow",g="Enter",f="Space",d="abandoned",c="both",b="String",a="changeVisibility",A="splitbutton",z="changeShow",y="mouseout",x="keydown",w="execute",v="_applyMenu",u="icon",t="mouseover",s="keyup",r="qx.ui.menu.Menu",p="_applyIcon",q="label",n="_applyShow",o="changeMenu",l="_applyLabel",m="qx.ui.form.SplitButton";
qx.Class.define(m,{extend:qx.ui.core.Widget,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IExecutable],construct:function(F,G,H,I){qx.ui.core.Widget.call(this);
this._setLayout(new qx.ui.layout.HBox);
this._createChildControl(h);
this.addListener(t,this._onMouseOver,this,true);
this.addListener(y,this._onMouseOut,this,true);
this.addListener(x,this._onKeyDown);
this.addListener(s,this._onKeyUp);
if(F!=null){this.setLabel(F);
}
if(G!=null){this.setIcon(G);
}
if(H!=null){this.setMenu(H);
}
if(I!=null){this.setCommand(I);
}},properties:{appearance:{refine:true,init:A},focusable:{refine:true,init:true},label:{apply:l,nullable:true,check:b},icon:{check:b,apply:p,nullable:true,themeable:true},show:{init:c,check:[c,q,u],themeable:true,inheritable:true,apply:n,event:z},menu:{check:r,nullable:true,apply:v,event:o}},members:{__zr:null,_createChildControlImpl:function(J){var K;

switch(J){case k:K=new qx.ui.form.Button;
K.addListener(w,this._onButtonExecute,this);
K.setFocusable(false);
this._addAt(K,0,{flex:1});
break;
case h:K=new qx.ui.form.MenuButton;
K.setFocusable(false);
this._addAt(K,1);
break;
}return K||qx.ui.core.Widget.prototype._createChildControlImpl.call(this,J);
},_forwardStates:{hovered:1,focused:1},_applyLabel:function(C,D){var E=this.getChildControl(k);
C==null?E.resetLabel():E.setLabel(C);
},_applyIcon:function(O,P){var Q=this.getChildControl(k);
O==null?Q.resetIcon():Q.setIcon(O);
},_applyMenu:function(L,M){var N=this.getChildControl(h);

if(L){N.resetEnabled();
N.setMenu(L);
L.setOpener(this);
L.addListener(a,this._onChangeMenuVisibility,this);
}else{N.setEnabled(false);
N.resetMenu();
}
if(M){M.removeListener(a,this._onChangeMenuVisibility,this);
M.resetOpener();
}},_applyShow:function(R,S){},_onMouseOver:function(e){e.stopPropagation();
this.addState(j);
delete this.__zr;
},_onMouseOut:function(e){e.stopPropagation();
if(!this.hasState(j)){return;
}var U=e.getRelatedTarget();

if(qx.ui.core.Widget.contains(this,U)){return;
}var T=this.getMenu();

if(T&&T.isVisible()){this.__zr=true;
return;
}this.removeState(j);
},_onKeyDown:function(e){var B=this.getChildControl(k);

switch(e.getKeyIdentifier()){case g:case f:B.removeState(d);
B.addState(i);
}},_onKeyUp:function(e){var V=this.getChildControl(k);

switch(e.getKeyIdentifier()){case g:case f:if(V.hasState(i)){V.removeState(d);
V.removeState(i);
V.execute();
}}},_onButtonExecute:function(e){this.execute();
},_onChangeMenuVisibility:function(e){if(!this.getMenu().isVisible()&&this.__zr){this.removeState(j);
}}}});
})();
(function(){var l="textfield",k="",j="downbutton",i="upbutton",h="Number",g="inner",f="PageUp",d="Boolean",c="changeValue",b="Down",K="Up",J="execute",I="PageDown",H="changeLocale",G="qx.dynlocale",F="on",E="_applyEditable",D="_applyWrap",C="keydown",B="\-]",s="mousewheel",t="_applyValue",q="number",r="_applyMinimum",o="qx.util.format.NumberFormat",p="[0-9",m="keyup",n="spinner",u="this._checkValue(value)",v="_applyMaximum",x="changeNumberFormat",w="changeMaximum",z="changeMinimum",y="_applyNumberFormat",A="qx.ui.form.Spinner";
qx.Class.define(A,{extend:qx.ui.core.Widget,implement:[qx.ui.form.INumberForm,qx.ui.form.IRange,qx.ui.form.IForm],include:[qx.ui.core.MContentPadding,qx.ui.form.MForm],construct:function(bv,bw,bx){qx.ui.core.Widget.call(this);
var by=new qx.ui.layout.Grid();
by.setColumnFlex(0,1);
by.setRowFlex(0,1);
by.setRowFlex(1,1);
this._setLayout(by);
this.addListener(C,this._onKeyDown,this);
this.addListener(m,this._onKeyUp,this);
this.addListener(s,this._onMouseWheel,this);

if(qx.core.Variant.isSet(G,F)){qx.locale.Manager.getInstance().addListener(H,this._onChangeLocale,this);
}this._createChildControl(l);
this._createChildControl(i);
this._createChildControl(j);
if(bv!=null){this.setMinimum(bv);
}
if(bx!=null){this.setMaximum(bx);
}
if(bw!==undefined){this.setValue(bw);
}else{this.initValue();
}},properties:{appearance:{refine:true,init:n},focusable:{refine:true,init:true},singleStep:{check:h,init:1},pageStep:{check:h,init:10},minimum:{check:h,apply:r,init:0,event:z},value:{check:u,nullable:true,apply:t,init:0,event:c},maximum:{check:h,apply:v,init:100,event:w},wrap:{check:d,init:false,apply:D},editable:{check:d,init:true,apply:E},numberFormat:{check:o,apply:y,nullable:true},allowShrinkY:{refine:true,init:false}},members:{__yC:null,__yD:false,__yE:false,_createChildControlImpl:function(S){var T;

switch(S){case l:T=new qx.ui.form.TextField();
T.setFilter(this._getFilterRegExp());
T.addState(g);
T.setWidth(40);
T.setFocusable(false);
T.addListener(c,this._onTextChange,this);
this._add(T,{column:0,row:0,rowSpan:2});
break;
case i:T=new qx.ui.form.RepeatButton();
T.addState(g);
T.setFocusable(false);
T.addListener(J,this._countUp,this);
this._add(T,{column:1,row:0});
break;
case j:T=new qx.ui.form.RepeatButton();
T.addState(g);
T.setFocusable(false);
T.addListener(J,this._countDown,this);
this._add(T,{column:1,row:1});
break;
}return T||qx.ui.core.Widget.prototype._createChildControlImpl.call(this,S);
},_getFilterRegExp:function(){var bp=qx.locale.Number.getDecimalSeparator(qx.locale.Manager.getInstance().getLocale());
var bo=qx.locale.Number.getGroupSeparator(qx.locale.Manager.getInstance().getLocale());
var bn=k;
var bl=k;

if(this.getNumberFormat()!==null){bn=this.getNumberFormat().getPrefix()||k;
bl=this.getNumberFormat().getPostfix()||k;
}var bm=new RegExp(p+qx.lang.String.escapeRegexpChars(bp)+qx.lang.String.escapeRegexpChars(bo)+qx.lang.String.escapeRegexpChars(bn)+qx.lang.String.escapeRegexpChars(bl)+B);
return bm;
},_forwardStates:{focused:true,invalid:true},tabFocus:function(){var P=this.getChildControl(l);
P.getFocusElement().focus();
P.selectAllText();
},_applyMinimum:function(bb,bc){if(this.getMaximum()<bb){this.setMaximum(bb);
}
if(this.getValue()<bb){this.setValue(bb);
}else{this._updateButtons();
}},_applyMaximum:function(bd,be){if(this.getMinimum()>bd){this.setMinimum(bd);
}
if(this.getValue()>bd){this.setValue(bd);
}else{this._updateButtons();
}},_applyEnabled:function(bj,bk){qx.ui.core.Widget.prototype._applyEnabled.call(this,bj,bk);
this._updateButtons();
},_checkValue:function(bz){return typeof bz===q&&bz>=this.getMinimum()&&bz<=this.getMaximum();
},_applyValue:function(U,V){var W=this.getChildControl(l);
this._updateButtons();
this.__yC=U;
if(U!==null){if(this.getNumberFormat()){W.setValue(this.getNumberFormat().format(U));
}else{W.setValue(U+k);
}}else{W.setValue(k);
}},_applyEditable:function(bs,bt){var bu=this.getChildControl(l);

if(bu){bu.setReadOnly(!bs);
}},_applyWrap:function(Q,R){this._updateButtons();
},_applyNumberFormat:function(X,Y){var ba=this.getChildControl(l);
ba.setFilter(this._getFilterRegExp());
this.getNumberFormat().addListener(x,this._onChangeNumberFormat,this);
this._applyValue(this.__yC,undefined);
},_getContentPaddingTarget:function(){return this.getChildControl(l);
},_updateButtons:function(){var bh=this.getChildControl(i);
var bg=this.getChildControl(j);
var bi=this.getValue();

if(!this.getEnabled()){bh.setEnabled(false);
bg.setEnabled(false);
}else{if(this.getWrap()){bh.setEnabled(true);
bg.setEnabled(true);
}else{if(bi!==null&&bi<this.getMaximum()){bh.setEnabled(true);
}else{bh.setEnabled(false);
}if(bi!==null&&bi>this.getMinimum()){bg.setEnabled(true);
}else{bg.setEnabled(false);
}}}},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case f:this.__yD=true;
case K:this.getChildControl(i).press();
break;
case I:this.__yE=true;
case b:this.getChildControl(j).press();
break;
default:return ;
}e.stopPropagation();
e.preventDefault();
},_onKeyUp:function(e){switch(e.getKeyIdentifier()){case f:this.getChildControl(i).release();
this.__yD=false;
break;
case K:this.getChildControl(i).release();
break;
case I:this.getChildControl(j).release();
this.__yE=false;
break;
case b:this.getChildControl(j).release();
break;
}},_onMouseWheel:function(e){if(e.getWheelDelta()>0){this._countDown();
}else{this._countUp();
}e.stop();
},_onTextChange:function(e){var bC=this.getChildControl(l);
var bD;
if(this.getNumberFormat()){try{bD=this.getNumberFormat().parse(bC.getValue());
}catch(a){}}if(bD===undefined){bD=parseFloat(bC.getValue(),10);
}if(!isNaN(bD)){if(bD>this.getMaximum()){bC.setValue(this.getMaximum()+k);
return;
}else if(bD<this.getMinimum()){bC.setValue(this.getMinimum()+k);
return;
}this.setValue(bD);
}else{this._applyValue(this.__yC,undefined);
}},_onChangeLocale:function(N){if(this.getNumberFormat()!==null){this.setNumberFormat(this.getNumberFormat());
var O=this.getChildControl(l);
O.setFilter(this._getFilterRegExp());
O.setValue(this.getNumberFormat().format(this.getValue()));
}},_onChangeNumberFormat:function(L){var M=this.getChildControl(l);
M.setFilter(this._getFilterRegExp());
M.setValue(this.getNumberFormat().format(this.getValue()));
},_countUp:function(){if(this.__yD){var bB=this.getValue()+this.getPageStep();
}else{var bB=this.getValue()+this.getSingleStep();
}if(this.getWrap()){if(bB>this.getMaximum()){var bA=this.getMaximum()-bB;
bB=this.getMinimum()+bA;
}}this.gotoValue(bB);
},_countDown:function(){if(this.__yE){var br=this.getValue()-this.getPageStep();
}else{var br=this.getValue()-this.getSingleStep();
}if(this.getWrap()){if(br<this.getMinimum()){var bq=this.getMinimum()+br;
br=this.getMaximum()-bq;
}}this.gotoValue(br);
},gotoValue:function(bf){return this.setValue(Math.min(this.getMaximum(),Math.max(this.getMinimum(),bf)));
}},destruct:function(){if(qx.core.Variant.isSet(G,F)){qx.locale.Manager.getInstance().removeListener(H,this._onChangeLocale,this);
}}});
})();
(function(){var c="password",b="qx.ui.form.PasswordField",a="input";
qx.Class.define(b,{extend:qx.ui.form.TextField,members:{_createInputElement:function(){var d=new qx.html.Input(c);
d.addListener(a,this._onHtmlInput,this);
return d;
}}});
})();

});