qx.$$packageData['0170e5d0f168']={"locales":{},"resources":{},"translations":{}};

qx.Part.$$notifyLoad("0170e5d0f168", function() {
(function(){var k="pressed",j="abandoned",i="hovered",h="Boolean",g="Space",f="undetermined",d="Enter",c="checked",b="mousedown",a="_applyTriState",w="mouseout",v="changeValue",u="keydown",t="_applyGroup",s="button",r="execute",q="qx.ui.form.RadioGroup",p="_applyValue",o="qx.ui.form.ToggleButton",n="mouseover",l="keyup",m="mouseup";
qx.Class.define(o,{extend:qx.ui.basic.Atom,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IBooleanForm,qx.ui.form.IExecutable,qx.ui.form.IRadioItem],construct:function(x,y){qx.ui.basic.Atom.call(this,x,y);
this.addListener(n,this._onMouseOver);
this.addListener(w,this._onMouseOut);
this.addListener(b,this._onMouseDown);
this.addListener(m,this._onMouseUp);
this.addListener(u,this._onKeyDown);
this.addListener(l,this._onKeyUp);
this.addListener(r,this._onExecute,this);
},properties:{appearance:{refine:true,init:s},focusable:{refine:true,init:true},value:{check:h,nullable:true,event:v,apply:p,init:false},group:{check:q,nullable:true,apply:t},triState:{check:h,apply:a,nullable:true,init:null}},members:{_applyGroup:function(z,A){if(A){A.remove(this);
}
if(z){z.add(this);
}},_applyValue:function(B,C){B?this.addState(c):this.removeState(c);

if(this.isTriState()){if(B===null){this.addState(f);
}else if(C===null){this.removeState(f);
}}},_applyTriState:function(D,E){this._applyValue(this.getValue());
},_onExecute:function(e){this.toggleValue();
},_onMouseOver:function(e){if(e.getTarget()!==this){return;
}this.addState(i);

if(this.hasState(j)){this.removeState(j);
this.addState(k);
}},_onMouseOut:function(e){if(e.getTarget()!==this){return;
}this.removeState(i);

if(this.hasState(k)){if(!this.getValue()){this.removeState(k);
}this.addState(j);
}},_onMouseDown:function(e){if(!e.isLeftPressed()){return;
}this.capture();
this.removeState(j);
this.addState(k);
e.stopPropagation();
},_onMouseUp:function(e){this.releaseCapture();

if(this.hasState(j)){this.removeState(j);
}else if(this.hasState(k)){this.execute();
}this.removeState(k);
e.stopPropagation();
},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case d:case g:this.removeState(j);
this.addState(k);
e.stopPropagation();
}},_onKeyUp:function(e){if(!this.hasState(k)){return;
}
switch(e.getKeyIdentifier()){case d:case g:this.removeState(j);
this.execute();
this.removeState(k);
e.stopPropagation();
}}}});
})();
(function(){var f="mshtml",e="engine.name",d="pop.push.reverse.shift.sort.splice.unshift.join.slice",c="number",b="qx.type.BaseArray",a=".";
qx.Class.define(b,{extend:Array,construct:function(g){},members:{toArray:null,valueOf:null,pop:null,push:null,reverse:null,shift:null,sort:null,splice:null,unshift:null,concat:null,join:null,slice:null,toString:null,indexOf:null,lastIndexOf:null,forEach:null,filter:null,map:null,some:null,every:null}});
(function(){function k(l){if((qx.core.Environment.get(e)==f)){j.prototype={length:0,$$isArray:true};
var o=d.split(a);

for(var length=o.length;length;){j.prototype[o[--length]]=Array.prototype[o[length]];
}}var p=Array.prototype.slice;
j.prototype.concat=function(){var r=this.slice(0);

for(var i=0,length=arguments.length;i<length;i++){var q;

if(arguments[i] instanceof j){q=p.call(arguments[i],0);
}else if(arguments[i] instanceof Array){q=arguments[i];
}else{q=[arguments[i]];
}r.push.apply(r,q);
}return r;
};
j.prototype.toString=function(){return p.call(this,0).toString();
};
j.prototype.toLocaleString=function(){return p.call(this,0).toLocaleString();
};
j.prototype.constructor=j;
j.prototype.indexOf=qx.lang.Core.arrayIndexOf;
j.prototype.lastIndexOf=qx.lang.Core.arrayLastIndexOf;
j.prototype.forEach=qx.lang.Core.arrayForEach;
j.prototype.some=qx.lang.Core.arraySome;
j.prototype.every=qx.lang.Core.arrayEvery;
var m=qx.lang.Core.arrayFilter;
var n=qx.lang.Core.arrayMap;
j.prototype.filter=function(){var s=new this.constructor;
s.push.apply(s,m.apply(this,arguments));
return s;
};
j.prototype.map=function(){var t=new this.constructor;
t.push.apply(t,n.apply(this,arguments));
return t;
};
j.prototype.slice=function(){var u=new this.constructor;
u.push.apply(u,Array.prototype.slice.apply(this,arguments));
return u;
};
j.prototype.splice=function(){var v=new this.constructor;
v.push.apply(v,Array.prototype.splice.apply(this,arguments));
return v;
};
j.prototype.toArray=function(){return Array.prototype.slice.call(this,0);
};
j.prototype.valueOf=function(){return this.length;
};
return j;
}function j(length){if(arguments.length===1&&typeof length===c){this.length=-1<length&&length===length>>.5?length:this.push(length);
}else if(arguments.length){this.push.apply(this,arguments);
}}function h(){}h.prototype=[];
j.prototype=new h;
j.prototype.length=0;
qx.type.BaseArray=k(j);
})();
})();
(function(){var s="html.classlist",r="default",q="native",p="",o=" ",n='',m="(^|\\s)",k="(\\s|$)",j="\\b",h="g",c='function',g="\\b|\\b",f="qx.bom.element.Class",b='SVGAnimatedString',a='object',e="$2",d='undefined';
qx.Class.define(f,{statics:{__ym:/\s+/g,__yn:/^\s+|\s+$/g,add:qx.lang.Object.select(qx.core.Environment.get(s)?q:r,{"native":function(t,name){t.classList.add(name);
return name;
},"default":function(u,name){if(!this.has(u,name)){u.className+=(u.className?o:p)+name;
}return name;
}}),addClasses:qx.lang.Object.select(qx.core.Environment.get(s)?q:r,{"native":function(v,w){for(var i=0;i<w.length;i++){v.classList.add(w[i]);
}return v.className;
},"default":function(x,y){var z={};
var B;
var A=x.className;

if(A){B=A.split(this.__ym);

for(var i=0,l=B.length;i<l;i++){z[B[i]]=true;
}
for(var i=0,l=y.length;i<l;i++){if(!z[y[i]]){B.push(y[i]);
}}}else{B=y;
}return x.className=B.join(o);
}}),get:function(C){var D=C.className;

if(typeof D.split!==c){if(typeof D===a){if(qx.Bootstrap.getClass(D)==b){D=D.baseVal;
}else{D=n;
}}
if(typeof D===d){D=n;
}}return D;
},has:qx.lang.Object.select(qx.core.Environment.get(s)?q:r,{"native":function(E,name){return E.classList.contains(name);
},"default":function(F,name){var G=new RegExp(m+name+k);
return G.test(F.className);
}}),remove:qx.lang.Object.select(qx.core.Environment.get(s)?q:r,{"native":function(H,name){H.classList.remove(name);
return name;
},"default":function(I,name){var J=new RegExp(m+name+k);
I.className=I.className.replace(J,e);
return name;
}}),removeClasses:qx.lang.Object.select(qx.core.Environment.get(s)?q:r,{"native":function(K,L){for(var i=0;i<L.length;i++){K.classList.remove(L[i]);
}return K.className;
},"default":function(M,N){var O=new RegExp(j+N.join(g)+j,h);
return M.className=M.className.replace(O,p).replace(this.__yn,p).replace(this.__ym,o);
}}),replace:function(P,Q,R){this.remove(P,Q);
return this.add(P,R);
},toggle:qx.lang.Object.select(qx.core.Environment.get(s)?q:r,{"native":function(S,name,T){if(T===undefined){S.classList.toggle(name);
}else{T?this.add(S,name):this.remove(S,name);
}return name;
},"default":function(U,name,V){if(V==null){V=!this.has(U,name);
}V?this.add(U,name):this.remove(U,name);
return name;
}})}});
})();
(function(){var m="string",k="script",h="<table>",g="engine.name",f="<fieldset>",e="<select multiple='multiple'>",d="</div>",c="</select>",b="</tr></tbody></table>",a="<col",J="div",I="<table><tbody><tr>",H=">",G="<table><tbody></tbody><colgroup>",F="<th",E="</tbody></table>",D="<td",C="</colgroup></table>",B="<opt",A="text/javascript",t="",u="</fieldset>",r="<table><tbody>",s="div<div>",p="<table",q="mshtml",n="qx.bom.Html",o="<leg",v="tbody",w="<tr",y="</table>",x="undefined",z="></";
qx.Class.define(n,{statics:{__yo:function(K,L,M){return M.match(/^(abbr|br|col|img|input|link|meta|param|hr|area|embed)$/i)?K:L+z+M+H;
},__yp:{opt:[1,e,c],leg:[1,f,u],table:[1,h,y],tr:[2,r,E],td:[3,I,b],col:[2,G,C],def:qx.core.Environment.select(g,{"mshtml":[1,s,d],"default":null})},__yq:function(N,O){var U=O.createElement(J);
N=N.replace(/(<(\w+)[^>]*?)\/>/g,this.__yo);
var Q=N.replace(/^\s+/,t).substring(0,5).toLowerCase();
var T,P=this.__yp;

if(!Q.indexOf(B)){T=P.opt;
}else if(!Q.indexOf(o)){T=P.leg;
}else if(Q.match(/^<(thead|tbody|tfoot|colg|cap)/)){T=P.table;
}else if(!Q.indexOf(w)){T=P.tr;
}else if(!Q.indexOf(D)||!Q.indexOf(F)){T=P.td;
}else if(!Q.indexOf(a)){T=P.col;
}else{T=P.def;
}if(T){U.innerHTML=T[1]+N+T[2];
var S=T[0];

while(S--){U=U.lastChild;
}}else{U.innerHTML=N;
}if((qx.core.Environment.get(g)==q)){var V=/<tbody/i.test(N);
var R=!Q.indexOf(p)&&!V?U.firstChild&&U.firstChild.childNodes:T[1]==h&&!V?U.childNodes:[];

for(var j=R.length-1;j>=0;--j){if(R[j].tagName.toLowerCase()===v&&!R[j].childNodes.length){R[j].parentNode.removeChild(R[j]);
}}if(/^\s/.test(N)){U.insertBefore(O.createTextNode(N.match(/^\s*/)[0]),U.firstChild);
}}return qx.lang.Array.fromCollection(U.childNodes);
},clean:function(W,X,Y){X=X||document;
if(typeof X.createElement===x){X=X.ownerDocument||X[0]&&X[0].ownerDocument||document;
}if(!Y&&W.length===1&&typeof W[0]===m){var bg=/^<(\w+)\s*\/?>$/.exec(W[0]);

if(bg){return [X.createElement(bg[1])];
}}var ba,bc=[];

for(var i=0,l=W.length;i<l;i++){ba=W[i];
if(typeof ba===m){ba=this.__yq(ba,X);
}if(ba.nodeType){bc.push(ba);
}else if(ba instanceof qx.type.BaseArray){bc.push.apply(bc,Array.prototype.slice.call(ba,0));
}else if(ba.toElement){bc.push(ba.toElement());
}else{bc.push.apply(bc,ba);
}}if(Y){var bf=[],be=qx.lang.Array,bd,bb;

for(var i=0;bc[i];i++){bd=bc[i];

if(bd.nodeType==1&&bd.tagName.toLowerCase()===k&&(!bd.type||bd.type.toLowerCase()===A)){if(bd.parentNode){bd.parentNode.removeChild(bc[i]);
}bf.push(bd);
}else{if(bd.nodeType===1){bb=be.fromCollection(bd.getElementsByTagName(k));
bc.splice.apply(bc,[i+1,0].concat(bb));
}Y.appendChild(bd);
}}return bf;
}return bc;
}}});
})();
(function(){var g="label",f="checkbox",e="qx.ui.form.CheckBox",d="value",c="toolTipText",b="enabled",a="menu";
qx.Class.define(e,{extend:qx.ui.form.ToggleButton,include:[qx.ui.form.MForm,qx.ui.form.MModelProperty],implement:[qx.ui.form.IForm,qx.ui.form.IModel],construct:function(h){qx.ui.form.ToggleButton.call(this,h);
this.setValue(false);
},properties:{appearance:{refine:true,init:f},allowGrowX:{refine:true,init:false}},members:{_forwardStates:{invalid:true,focused:true,undetermined:true,checked:true,hovered:true},_bindableProperties:[b,g,c,d,a]}});
})();
(function(){var m="get",k="set",h="reset",g=":not(",f="getValue",e="append",d=")",c="getPreviousSiblings",b="#",a="qx.bom.Collection",K="setValue",J="prepend",I="string",H="getAncestors",G="getOffsetParent",F="remove",E=">*",D="add",C="*",B="",t="addListener",u="has",r="toggle",s="getSiblings",p="replace",q="after",n="replaceWith",o="setCss",v="setStyles",w="before",y="getNextSiblings",x="getPosition",A="getCss",z="removeListener";
(function(){var M=function(N,O){return function(P,Q,R,S,T,U){var length=this.length;

if(length>0){var V=N[O];

for(var i=0;i<length;i++){if(this[i].nodeType===1){V.call(N,this[i],P,Q,R,S,T,U);
}}}return this;
};
};
var L=function(W,X){return function(Y,ba,bb,bc,bd,be){if(this.length>0){var bf=this[0].nodeType===1?W[X](this[0],Y,ba,bb,bc,bd,be):null;

if(bf&&bf.nodeType){return this.__yv([bf]);
}else{return bf;
}}return null;
};
};
qx.Class.define(a,{extend:qx.type.BaseArray,construct:function(bg){qx.type.BaseArray.apply(this,arguments);
},statics:{query:function(bh,bi){var bj=qx.bom.Selector.query(bh,bi);
return qx.lang.Array.cast(bj,qx.bom.Collection);
},id:function(bk){var bl=document.getElementById(bk);
if(bl&&bl.id!=bk){return qx.bom.Collection.query(b+bk);
}if(bl){return new qx.bom.Collection(bl);
}else{return new qx.bom.Collection();
}},html:function(bm,bn){var bo=qx.bom.Html.clean([bm],bn);
return qx.lang.Array.cast(bo,qx.bom.Collection);
},__yr:/^[^<]*(<(.|\s)+>)[^>]*$|^#([\w-]+)$/,create:function(bp,bq){var bs=qx.bom.Collection;
if(bp.nodeType){return new bs(bp);
}else if(typeof bp===I){var br=bs.__yr.exec(bp);

if(br){return br[1]?bs.html(br[1],bq):bs.id(br[3].substring(1));
}else{return bs.query(bp,bq);
}}else{return qx.lang.Array.cast(bp,qx.bom.Collection);
}}},members:{__ys:null,setAttribute:M(qx.bom.element.Attribute,k),resetAttribute:M(qx.bom.element.Attribute,h),getAttribute:L(qx.bom.element.Attribute,m),addClass:M(qx.bom.element.Class,D),getClass:L(qx.bom.element.Class,m),hasClass:L(qx.bom.element.Class,u),removeClass:M(qx.bom.element.Class,F),replaceClass:M(qx.bom.element.Class,p),toggleClass:M(qx.bom.element.Class,r),setValue:M(qx.bom.Input,K),getValue:L(qx.bom.Input,f),setStyle:M(qx.bom.element.Style,k),setStyles:M(qx.bom.element.Style,v),resetStyle:M(qx.bom.element.Style,h),getStyle:L(qx.bom.element.Style,m),setCss:M(qx.bom.element.Style,o),getCss:M(qx.bom.element.Style,A),getOffset:L(qx.bom.element.Location,m),getPosition:L(qx.bom.element.Location,x),getOffsetParent:L(qx.bom.element.Location,G),setScrollLeft:function(bt){var Node=qx.dom.Node;

for(var i=0,l=this.length,bu;i<l;i++){bu=this[i];

if(Node.isElement(bu)){bu.scrollLeft=bt;
}else if(Node.isWindow(bu)){bu.scrollTo(bt,this.getScrollTop(bu));
}else if(Node.isDocument(bu)){Node.getWindow(bu).scrollTo(bt,this.getScrollTop(bu));
}}return this;
},setScrollTop:function(bv){var Node=qx.dom.Node;

for(var i=0,l=this.length,bw;i<l;i++){bw=this[i];

if(Node.isElement(bw)){bw.scrollTop=bv;
}else if(Node.isWindow(bw)){bw.scrollTo(this.getScrollLeft(bw),bv);
}else if(Node.isDocument(bw)){Node.getWindow(bw).scrollTo(this.getScrollLeft(bw),bv);
}}return this;
},getScrollLeft:function(){var bx=this[0];

if(!bx){return null;
}var Node=qx.dom.Node;

if(Node.isWindow(bx)||Node.isDocument(bx)){return qx.bom.Viewport.getScrollLeft();
}return bx.scrollLeft;
},getScrollTop:function(){var by=this[0];

if(!by){return null;
}var Node=qx.dom.Node;

if(Node.isWindow(by)||Node.isDocument(by)){return qx.bom.Viewport.getScrollTop();
}return by.scrollTop;
},getWidth:function(){var bz=this[0];
var Node=qx.dom.Node;

if(bz){if(Node.isElement(bz)){return qx.bom.element.Dimension.getWidth(bz);
}else if(Node.isDocument(bz)){return qx.bom.Document.getWidth(Node.getWindow(bz));
}else if(Node.isWindow(bz)){return qx.bom.Viewport.getWidth(bz);
}}return null;
},getContentWidth:function(){var bA=this[0];

if(qx.dom.Node.isElement(bA)){return qx.bom.element.Dimension.getContentWidth(bA);
}return null;
},getHeight:function(){var bB=this[0];
var Node=qx.dom.Node;

if(bB){if(Node.isElement(bB)){return qx.bom.element.Dimension.getHeight(bB);
}else if(Node.isDocument(bB)){return qx.bom.Document.getHeight(Node.getWindow(bB));
}else if(Node.isWindow(bB)){return qx.bom.Viewport.getHeight(bB);
}}return null;
},getContentHeight:function(){var bC=this[0];

if(qx.dom.Node.isElement(bC)){return qx.bom.element.Dimension.getContentHeight(bC);
}return null;
},addListener:M(qx.bom.Element,t),removeListener:M(qx.bom.Element,z),eq:function(bD){return this.slice(bD,+bD+1);
},filter:function(bE,bF){var bG;

if(qx.lang.Type.isFunction(bE)){bG=qx.type.BaseArray.prototype.filter.call(this,bE,bF);
}else{bG=qx.bom.Selector.matches(bE,this);
}return this.__yv(bG);
},is:function(bH){return !!bH&&qx.bom.Selector.matches(bH,this).length>0;
},__yt:/^.[^:#\[\.,]*$/,not:function(bI){if(this.__yt.test(bI)){var bJ=qx.bom.Selector.matches(g+bI+d,this);
return this.__yv(bJ);
}var bJ=qx.bom.Selector.matches(bI,this);
return this.filter(function(bK){return bJ.indexOf(bK)===-1;
});
},add:function(bL,bM){var bN=qx.bom.Selector.query(bL,bM);
var bO=qx.lang.Array.unique(this.concat(bN));
return this.__yv(bO);
},children:function(bP){var bQ=[];

for(var i=0,l=this.length;i<l;i++){bQ.push.apply(bQ,qx.dom.Hierarchy.getChildElements(this[i]));
}
if(bP){bQ=qx.bom.Selector.matches(bP,bQ);
}return this.__yv(bQ);
},closest:function(bR){var bS=new qx.bom.Collection(1);
var bU=qx.bom.Selector;
var bT=this.map(function(bV){while(bV&&bV.ownerDocument){bS[0]=bV;

if(bU.matches(bR,bS).length>0){return bV;
}bV=bV.parentNode;
}});
return this.__yv(qx.lang.Array.unique(bT));
},contents:function(){var bX=[];
var bW=qx.lang.Array;

for(var i=0,l=this.length;i<l;i++){bX.push.apply(bX,bW.fromCollection(this[i].childNodes));
}return this.__yv(bX);
},find:function(bY){var cb=qx.bom.Selector;
if(this.length===1){return this.__yv(cb.query(bY,this[0]));
}else{var ca=[];

for(var i=0,l=this.length;i<l;i++){ca.push.apply(ca,cb.query(bY,this[i]));
}return this.__yv(qx.lang.Array.unique(ca));
}},next:function(cc){var cd=qx.dom.Hierarchy;
var ce=this.map(cd.getNextElementSibling,cd);
if(cc){ce=qx.bom.Selector.matches(cc,ce);
}return this.__yv(ce);
},nextAll:function(cf){return this.__yu(y,cf);
},prev:function(cg){var ch=qx.dom.Hierarchy;
var ci=this.map(ch.getPreviousElementSibling,ch);
if(cg){ci=qx.bom.Selector.matches(cg,ci);
}return this.__yv(ci);
},prevAll:function(cj){return this.__yu(c,cj);
},parent:function(ck){var Element=qx.dom.Element;
var cl=qx.lang.Array.unique(this.map(Element.getParentElement,Element));
if(ck){cl=qx.bom.Selector.matches(ck,cl);
}return this.__yv(cl);
},parents:function(cm){return this.__yu(H,cm);
},siblings:function(cn){return this.__yu(s,cn);
},__yu:function(co,cp){var cr=[];
var cq=qx.dom.Hierarchy;

for(var i=0,l=this.length;i<l;i++){cr.push.apply(cr,cq[co](this[i]));
}var cs=qx.lang.Array.unique(cr);
if(cp){cs=qx.bom.Selector.matches(cp,cs);
}return this.__yv(cs);
},__yv:function(ct){var cu=new qx.bom.Collection;
cu.__ys=this;
ct=Array.prototype.slice.call(ct,0);
cu.push.apply(cu,ct);
return cu;
},andSelf:function(){return this.add(this.__ys);
},end:function(){return this.__ys||new qx.bom.Collection();
},__yw:function(cv,cw){var cB=this[0];
var cA=cB.ownerDocument||cB;
var cz=cA.createDocumentFragment();
var cD=qx.bom.Html.clean(cv,cA,cz);
var cF=cz.firstChild;
if(cF){var cx=this.length-1;

for(var i=0,l=cx;i<l;i++){cw.call(this,this[i],cz.cloneNode(true));
}cw.call(this,this[cx],cz);
}if(cD){var cy;
var cE=qx.io.ScriptLoader;
var cC=qx.lang.Function;

for(var i=0,l=cD.length;i<l;i++){cy=cD[i];
if(cy.src){cE.get().load(cy.src);
}else{cC.globalEval(cy.text||cy.textContent||cy.innerHTML||B);
}if(cy.parentNode){cy.parentNode.removeChild(cy);
}}}return this;
},__yx:function(cG,cH){var cJ=qx.bom.Selector;
var cI=qx.lang.Array;
var cL=[];

for(var i=0,l=cG.length;i<l;i++){cL.push.apply(cL,cJ.query(cG[i]));
}cL=cI.cast(cI.unique(cL),qx.bom.Collection);
for(var i=0,cK=this.length;i<cK;i++){cL[cH](this[i]);
}return this;
},append:function(cM){return this.__yw(arguments,this.__yy);
},prepend:function(cN){return this.__yw(arguments,this.__yz);
},__yy:function(cO,cP){cO.appendChild(cP);
},__yz:function(cQ,cR){cQ.insertBefore(cR,cQ.firstChild);
},appendTo:function(cS){return this.__yx(arguments,e);
},prependTo:function(cT){return this.__yx(arguments,J);
},before:function(cU){return this.__yw(arguments,this.__yA);
},after:function(cV){return this.__yw(arguments,this.__yB);
},__yA:function(cW,cX){cW.parentNode.insertBefore(cX,cW);
},__yB:function(cY,da){cY.parentNode.insertBefore(da,cY.nextSibling);
},insertBefore:function(db){return this.__yx(arguments,w);
},insertAfter:function(dc){return this.__yx(arguments,q);
},wrapAll:function(content){var de=this[0];

if(de){var dd=qx.bom.Collection.create(content,de.ownerDocument).clone();
if(de.parentNode){de.parentNode.insertBefore(dd[0],de);
}dd.map(this.__yC).append(this);
}return this;
},__yC:function(df){while(df.firstChild){df=df.firstChild;
}return df;
},wrapInner:function(content){var dg=new qx.bom.Collection(1);

for(var i=0,l=this.length;i<l;i++){dg[0]=this[i];
dg.contents().wrapAll(content);
}return this;
},wrap:function(content){var dh=new qx.bom.Collection(1);
for(var i=0,l=this.length;i<l;i++){dh[0]=this[i];
dh.wrapAll(content);
}return this;
},replaceWith:function(content){return this.after(content).remove();
},replaceAll:function(di){return this.__yx(arguments,n);
},remove:function(dj){var dl=this;

if(dj){dl=this.filter(dj);

if(dl.length==0){return this;
}}for(var i=0,dm=dl.length,dk;i<dm;i++){dk=dl[i];

if(dk.parentNode){dk.parentNode.removeChild(dk);
}}return dl;
},destroy:function(dn){if(this.length==0){return this;
}var dq=qx.bom.Selector;
var dt=this;

if(dn){dt=this.filter(dn);

if(dt.length==0){return this;
}}var ds=qx.event.Registration.getManager(this[0]);

for(var i=0,l=dt.length,dr,du;i<l;i++){dr=dt[i];
ds.removeAllListeners(dr);
du=dq.query(C,dr);

for(var j=0,dp=du.length;j<dp;j++){ds.removeAllListeners(du[j]);
}if(dr.parentNode){dr.parentNode.removeChild(dr);
}}if(dn){dt.end();
qx.lang.Array.exclude(this,dt);
}else{this.length=0;
}return this;
},empty:function(){var dv=qx.bom.Collection;

for(var i=0,l=this.length;i<l;i++){dv.query(E,this[i]).destroy();
while(this.firstChild){this.removeChild(this.firstChild);
}}return this;
},clone:function(dw){var Element=qx.bom.Element;
return dw?
this.map(function(dx){return Element.clone(dx,true);
}):this.map(Element.clone,Element);
}},defer:function(dy){if(window.$==null){window.$=dy.create;
}}});
})();
})();
(function(){var k="overflowY",j="engine.name",i="hidden",h="auto",g="textarea",f="width",d="webkit",c="Boolean",b="Integer",a="input",y="",x="appear",w="mshtml",v="px",u="_applyWrap",t="-1",s="_applyMinimalLineHeight",r="mousewheel",q="_applyAutoSize",p="tabIndex",n='name',o="qx.ui.form.TextArea",l='id',m="absolute";
qx.Class.define(o,{extend:qx.ui.form.AbstractField,construct:function(z){qx.ui.form.AbstractField.call(this,z);
this.initWrap();
this.addListener(r,this._onMousewheel,this);
},properties:{wrap:{check:c,init:true,apply:u},appearance:{refine:true,init:g},singleStep:{check:b,init:20},minimalLineHeight:{check:b,apply:s,init:4},autoSize:{check:c,apply:q,init:false}},members:{__yD:null,__yE:null,__yF:null,setValue:function(A){A=qx.ui.form.AbstractField.prototype.setValue.call(this,A);
this.__yG();
return A;
},_onMousewheel:function(e){var B=this.getContentElement();
var scrollY=B.getScrollY();
B.scrollToY(scrollY+e.getWheelDelta()*this.getSingleStep());
var C=B.getScrollY();

if(C!=scrollY){e.stop();
}},__yG:function(){if(this.isAutoSize()){var F=this.__yH();

if(F){this.__yF=this.__yF||this._getAreaHeight();
var H=this._getScrolledAreaHeight();
if(this.getMaxHeight()){var D=this.getInsets();
var E=-D.top+this.getMaxHeight()-D.bottom;

if(H>E){this.getContentElement().setStyle(k,h);
}else{this.getContentElement().setStyle(k,i);
}}var G=Math.max(H,this.__yF);
this._setAreaHeight(G);
}else{this.addListenerOnce(x,function(){if(qx.core.Environment.get(j)==d){var J=this.getContentElement();
var I=this.getValue();
J.setStyle(k,i,true);
this.setValue(y);
this.setValue(I);
}this.__yG();
},this);
}}},_getAreaHeight:function(){return this.getInnerSize().height;
},_setAreaHeight:function(K){if(this._getAreaHeight()!==K){this.__yE=K;
qx.ui.core.queue.Layout.add(this);
qx.ui.core.queue.Manager.flush();
this.__yK();
}},_getScrolledAreaHeight:function(){var M=this.__yH();
var L=M.getDomElement();

if(L){if(!L.parentNode){qx.html.Element.flush();
return this._getScrolledAreaHeight();
}if(qx.core.Environment.get(j)===d){M.setWrap(!this.getWrap(),true);
}M.setWrap(this.getWrap(),true);
if(qx.core.Environment.get(j)==d){L.style.overflow=i;
}if(qx.core.Environment.get(j)==w){L.style.overflow=y;
}M.setValue(this.getValue());
this.__yJ(M);

if(qx.core.Environment.get(j)==w){if(!L.scrollTop){qx.html.Element.flush();
}return L.scrollTop+this._getTextSize().height;
}return L.scrollTop;
}},__yH:function(){this.__yD=this.__yD||this.__yI();
return this.__yD;
},__yI:function(){var Q,O,N,P;
Q=this.getContentElement();
if(!Q.getDomElement()){return;
}N=qx.bom.Collection.create(Q.getDomElement()).clone()[0];
P=new qx.html.Input(g);
P.useElement(N);
O=P;
O.setStyles({position:m,top:0,left:-9999,height:0,overflow:i},true);
O.removeAttribute(l);
O.removeAttribute(n);
O.setAttribute(p,t);
O.setValue(Q.getValue());
O.insertBefore(Q);
this.__yJ(O);
return O;
},__yJ:function(R){R=R.getDomElement();

if(R){R.scrollTop=10000;
}},_createInputElement:function(){return new qx.html.Input(g,{overflowX:h,overflowY:h});
},_applyWrap:function(S,T){this.getContentElement().setWrap(S);
this.__yG();
},_applyMinimalLineHeight:function(){qx.ui.core.queue.Layout.add(this);
},_applyAutoSize:function(U,V){if(U){this.__yG();
this.addListener(a,this.__yG,this);
this.addListenerOnce(x,function(){this.getContentElement().setStyle(k,i);
});
}else{this.removeListener(a,this.__yG);
this.getContentElement().setStyle(k,h);
}},_applyDimension:function(W){qx.ui.form.AbstractField.prototype._applyDimension.call(this);

if(W===this.getMaxHeight()){this.__yG();
}},__yK:function(){var content=this.getContentElement();
var Y=content.getDomElement();
var X=content.getStyle(f);
content.setStyle(f,parseInt(X,10)+1000+v,true);
if(Y){qx.bom.element.Dimension.getWidth(Y);
}content.setStyle(f,X,true);
},__yL:function(){if(this.isAutoSize()&&this.getHeight()){this.warn("autoSize is ignored when the height property is set. "+"If you want to set an initial height, use the minHeight "+"property instead.");
}},_getContentHint:function(){var ba=qx.ui.form.AbstractField.prototype._getContentHint.call(this);
ba.height=ba.height*this.getMinimalLineHeight();
ba.width=this._getTextSize().width*20;

if(this.isAutoSize()){ba.height=this.__yE||ba.height;
}return ba;
}}});
})();
(function(){var k="value",j="placeholder",h="Button",g="CheckBox:",f="TextArea:",e="Boolean",d="RepeatButton:",c="execute",b="Website 2",a="Text",V="ToggleButton",U="password",T="RadioButton 3",S="showcase.page.form.Content",R="Button:",Q="ComboBox:",P="ToggleButton:",O="Options",N="RadioButton",M="0",r="MenuButton:",s="Tri-State CheckBox:",p="PasswordField:",q="SplitButton",n="Buttons",o="",l="RadioButtons:",m="dd.mm.YYYY",t="List:",u="SplitButton:",B="Option",z="RadioButton 1",F="Spinner:",D="Selection",I="DateField:",H="RadioButton 2",w="Tri-State CheckBox",L="Number",K="CheckBox",J="SelectBox:",v="Website 3",x="MenuButton",y="Website 1",A="Slider:",C="TextField:",E="Item ",G="RadioButtonGroup:";
qx.Class.define(S,{extend:showcase.AbstractContent,construct:function(W){showcase.AbstractContent.call(this,W);
this.setView(this._createView());
},members:{_createView:function(){var bn=new qx.ui.layout.Grid(20,5);
bn.setColumnFlex(0,1);
bn.setColumnFlex(1,1);
var by=new qx.ui.container.Composite(bn);
by.setPadding(10);
var bf=1;
var X=new qx.ui.groupbox.GroupBox(a);
X.setLayout(new qx.ui.layout.Grid(8,8));
X.setWidth(290);
by.add(X,{row:0,column:0});
var bw=new qx.ui.form.TextField();
bw.setPlaceholder(j);
bw.setTabIndex(bf++);
var bh=new qx.ui.basic.Label(C);
bh.setBuddy(bw);
X.add(bh,{row:0,column:0});
X.add(bw,{row:0,column:1});
var be=new qx.ui.form.PasswordField();
be.setTabIndex(bf++);
be.setPlaceholder(U);
bh=new qx.ui.basic.Label(p);
bh.setBuddy(be);
X.add(bh,{row:1,column:0});
X.add(be,{row:1,column:1});
var Y=new qx.ui.form.TextArea();
Y.setTabIndex(bf++);
Y.setPlaceholder(j);
bh=new qx.ui.basic.Label(f);
bh.setBuddy(Y);
X.add(bh,{row:2,column:0});
X.add(Y,{row:2,column:1});
var ba=new qx.ui.form.ComboBox();
ba.setTabIndex(bf++);
ba.setPlaceholder(j);
bh=new qx.ui.basic.Label(Q);
bh.setBuddy(ba);
X.add(bh,{row:3,column:0});
X.add(ba,{row:3,column:1});
this.__yM(ba);
var bp=new qx.ui.form.DateField();
bp.setTabIndex(bf++);
bp.setPlaceholder(m);
bh=new qx.ui.basic.Label(I);
bh.setBuddy(bp);
X.add(bh,{row:4,column:0});
X.add(bp,{row:4,column:1});
var bg=new qx.ui.groupbox.GroupBox(D);
bg.setLayout(new qx.ui.layout.Grid(8,8));
bg.setWidth(290);
by.add(bg,{row:1,column:0,rowSpan:2});
var bq=new qx.ui.form.SelectBox();
bq.setTabIndex(bf++);
bh=new qx.ui.basic.Label(J);
bh.setBuddy(bq);
bg.add(bh,{row:0,column:0});
bg.add(bq,{row:0,column:1});
this.__yM(bq);
var bv=new qx.ui.form.List();
bv.setTabIndex(bf++);
bv.setHeight(60);
bv.setWidth(155);
bh=new qx.ui.basic.Label(t);
bh.setBuddy(bv);
bg.add(bh,{row:1,column:0});
bg.add(bv,{row:1,column:1});
this.__yM(bv);
var bo=new qx.ui.form.RadioButtonGroup();
bo.add(new qx.ui.form.RadioButton(z).set({tabIndex:bf++}));
bo.add(new qx.ui.form.RadioButton(H).set({tabIndex:bf++}));
bo.add(new qx.ui.form.RadioButton(T).set({tabIndex:bf++}));
bh=new qx.ui.basic.Label(G);
bh.setBuddy(bo);
bg.add(bh,{row:2,column:0});
bg.add(bo,{row:2,column:1});
var bt=new qx.ui.groupbox.GroupBox(n);
bt.setLayout(new qx.ui.layout.Grid(8,8));
bt.setWidth(250);
by.add(bt,{row:0,column:1});
var bu=new qx.ui.form.Button(h).set({tabIndex:bf++});
bh=new qx.ui.basic.Label(R);
bh.setBuddy(bu);
bt.add(bh,{row:0,column:0});
bt.add(bu,{row:0,column:1});
var bc=new qx.ui.form.ToggleButton(V).set({tabIndex:bf++});
bh=new qx.ui.basic.Label(P);
bh.setBuddy(bc);
bt.add(bh,{row:1,column:0});
bt.add(bc,{row:1,column:1});
var bk=new qx.ui.form.RepeatButton(M).set({tabIndex:bf++});
bh=new qx.ui.basic.Label(d);
bh.setBuddy(bk);
bt.add(bh,{row:2,column:0});
bt.add(bk,{row:2,column:1});
var bl=new qx.ui.form.MenuButton(x,null,this.__yN()).set({tabIndex:bf++});
bh=new qx.ui.basic.Label(r);
bh.setBuddy(bl);
bt.add(bh,{row:3,column:0});
bt.add(bl,{row:3,column:1});
var bd=new qx.ui.form.SplitButton(q,null,this.__yO()).set({tabIndex:bf++});
bh=new qx.ui.basic.Label(u);
bh.setBuddy(bd);
bt.add(bh,{row:4,column:0});
bt.add(bd,{row:4,column:1});
bk.addListener(c,function(){var bz=parseInt(bk.getLabel())+1;
bk.setLabel(bz.toString());
});
var bb=new qx.ui.groupbox.GroupBox(e);
bb.setLayout(new qx.ui.layout.Grid(8,8));
bb.setWidth(250);
by.add(bb,{row:1,column:1});
var br=new qx.ui.form.CheckBox(K).set({tabIndex:bf++});
bh=new qx.ui.basic.Label(g);
bh.setBuddy(br);
bb.add(bh,{row:0,column:0});
bb.add(br,{row:0,column:1});
var bx=new qx.ui.form.CheckBox(w).set({triState:true,value:null});
bh=new qx.ui.basic.Label(s);
bh.setBuddy(bx);
bb.add(bh,{row:1,column:0});
bb.add(bx,{row:1,column:1});
var bj=new qx.ui.form.RadioButton(N).set({tabIndex:bf++});
bb.add(new qx.ui.basic.Label(l),{row:2,column:0});
bb.add(bj,{row:2,column:1});
var bs=new qx.ui.groupbox.GroupBox(L);
bs.setLayout(new qx.ui.layout.Grid(8,8));
bs.setWidth(250);
by.add(bs,{row:2,column:1});
var bi=new qx.ui.form.Spinner(0,50,100).set({tabIndex:bf++});
bh=new qx.ui.basic.Label(F);
bh.setBuddy(bi);
bs.add(bh,{row:0,column:0});
bs.add(bi,{row:0,column:1});
var bm=new qx.ui.form.Slider().set({tabIndex:bf++});
bm.setWidth(130);
bh=new qx.ui.basic.Label(A);
bh.setBuddy(bm);
bs.add(bh,{row:1,column:0});
bs.add(bm,{row:1,column:1});
bm.bind(k,bi,k);
bi.bind(k,bm,k);
return by;
},__yM:function(bA){for(var i=0;i<10;i++){var bB=new qx.ui.form.ListItem(E+i);
bA.add(bB);
}},__yN:function(){var bC=new qx.ui.menu.Menu;

for(var i=0;i<3;i++){bC.add(new qx.ui.menu.RadioButton(B+i));
}var bF=new qx.ui.form.RadioGroup;
bF.add.apply(bF,bC.getChildren());
var bE=new qx.ui.menu.Menu();

for(var i=0;i<3;i++){var bG=new qx.ui.menu.Button(h+i);
bE.add(bG);
}var bD=new qx.ui.menu.Button(O,o,null,bC);
bE.addSeparator();
bE.add(bD);
return bE;
},__yO:function(){var bH=new qx.ui.menu.Menu;
var bK=new qx.ui.menu.Button(y);
var bI=new qx.ui.menu.Button(b);
var bJ=new qx.ui.menu.Button(v);
bH.add(bK);
bH.add(bI);
bH.add(bJ);
return bH;
}}});
})();
(function(){var k="button",j="hovered",i="pressed",h="arrow",g="Enter",f="Space",d="abandoned",c="both",b="String",a="changeVisibility",A="splitbutton",z="changeShow",y="mouseout",x="keydown",w="execute",v="_applyMenu",u="icon",t="mouseover",s="keyup",r="qx.ui.menu.Menu",p="_applyIcon",q="label",n="_applyShow",o="changeMenu",l="_applyLabel",m="qx.ui.form.SplitButton";
qx.Class.define(m,{extend:qx.ui.core.Widget,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IExecutable],construct:function(B,C,D,E){qx.ui.core.Widget.call(this);
this._setLayout(new qx.ui.layout.HBox);
this._createChildControl(h);
this.addListener(t,this._onMouseOver,this,true);
this.addListener(y,this._onMouseOut,this,true);
this.addListener(x,this._onKeyDown);
this.addListener(s,this._onKeyUp);
if(B!=null){this.setLabel(B);
}
if(C!=null){this.setIcon(C);
}
if(D!=null){this.setMenu(D);
}
if(E!=null){this.setCommand(E);
}},properties:{appearance:{refine:true,init:A},focusable:{refine:true,init:true},label:{apply:l,nullable:true,check:b},icon:{check:b,apply:p,nullable:true,themeable:true},show:{init:c,check:[c,q,u],themeable:true,inheritable:true,apply:n,event:z},menu:{check:r,nullable:true,apply:v,event:o}},members:{__yP:null,_createChildControlImpl:function(F,G){var H;

switch(F){case k:H=new qx.ui.form.Button;
H.addListener(w,this._onButtonExecute,this);
H.setFocusable(false);
this._addAt(H,0,{flex:1});
break;
case h:H=new qx.ui.form.MenuButton;
H.setFocusable(false);
this._addAt(H,1);
break;
}return H||qx.ui.core.Widget.prototype._createChildControlImpl.call(this,F);
},_forwardStates:{hovered:1,focused:1},_applyLabel:function(I,J){var K=this.getChildControl(k);
I==null?K.resetLabel():K.setLabel(I);
},_applyIcon:function(L,M){var N=this.getChildControl(k);
L==null?N.resetIcon():N.setIcon(L);
},_applyMenu:function(O,P){var Q=this.getChildControl(h);

if(O){Q.resetEnabled();
Q.setMenu(O);
O.setOpener(this);
O.addListener(a,this._onChangeMenuVisibility,this);
}else{Q.setEnabled(false);
Q.resetMenu();
}
if(P){P.removeListener(a,this._onChangeMenuVisibility,this);
P.resetOpener();
}},_applyShow:function(R,S){},_onMouseOver:function(e){e.stopPropagation();
this.addState(j);
delete this.__yP;
},_onMouseOut:function(e){e.stopPropagation();
if(!this.hasState(j)){return;
}var U=e.getRelatedTarget();

if(qx.ui.core.Widget.contains(this,U)){return;
}var T=this.getMenu();

if(T&&T.isVisible()){this.__yP=true;
return;
}this.removeState(j);
},_onKeyDown:function(e){var V=this.getChildControl(k);

switch(e.getKeyIdentifier()){case g:case f:V.removeState(d);
V.addState(i);
}},_onKeyUp:function(e){var W=this.getChildControl(k);

switch(e.getKeyIdentifier()){case g:case f:if(W.hasState(i)){W.removeState(d);
W.removeState(i);
W.execute();
}}},_onButtonExecute:function(e){this.execute();
},_onChangeMenuVisibility:function(e){if(!this.getMenu().isVisible()&&this.__yP){this.removeState(j);
}}}});
})();
(function(){var k="textfield",j="",i="downbutton",h="upbutton",g="Number",f="inner",d="PageUp",c="Boolean",b="changeValue",a="Down",I="Up",H="execute",G="PageDown",F="changeLocale",E="qx.dynlocale",D="_applyEditable",C="_applyWrap",B="keydown",A="\-]",z="mousewheel",r="_applyValue",s="number",p="_applyMinimum",q="qx.util.format.NumberFormat",n="[0-9",o="keyup",l="spinner",m="this._checkValue(value)",t="_applyMaximum",u="changeNumberFormat",w="changeMaximum",v="changeMinimum",y="_applyNumberFormat",x="qx.ui.form.Spinner";
qx.Class.define(x,{extend:qx.ui.core.Widget,implement:[qx.ui.form.INumberForm,qx.ui.form.IRange,qx.ui.form.IForm],include:[qx.ui.core.MContentPadding,qx.ui.form.MForm],construct:function(J,K,L){qx.ui.core.Widget.call(this);
var M=new qx.ui.layout.Grid();
M.setColumnFlex(0,1);
M.setRowFlex(0,1);
M.setRowFlex(1,1);
this._setLayout(M);
this.addListener(B,this._onKeyDown,this);
this.addListener(o,this._onKeyUp,this);
this.addListener(z,this._onMouseWheel,this);

if(qx.core.Environment.get(E)){qx.locale.Manager.getInstance().addListener(F,this._onChangeLocale,this);
}this._createChildControl(k);
this._createChildControl(h);
this._createChildControl(i);
if(J!=null){this.setMinimum(J);
}
if(L!=null){this.setMaximum(L);
}
if(K!==undefined){this.setValue(K);
}else{this.initValue();
}},properties:{appearance:{refine:true,init:l},focusable:{refine:true,init:true},singleStep:{check:g,init:1},pageStep:{check:g,init:10},minimum:{check:g,apply:p,init:0,event:v},value:{check:m,nullable:true,apply:r,init:0,event:b},maximum:{check:g,apply:t,init:100,event:w},wrap:{check:c,init:false,apply:C},editable:{check:c,init:true,apply:D},numberFormat:{check:q,apply:y,nullable:true},allowShrinkY:{refine:true,init:false}},members:{__yQ:null,__yR:false,__yS:false,_createChildControlImpl:function(N,O){var P;

switch(N){case k:P=new qx.ui.form.TextField();
P.setFilter(this._getFilterRegExp());
P.addState(f);
P.setWidth(40);
P.setFocusable(false);
P.addListener(b,this._onTextChange,this);
this._add(P,{column:0,row:0,rowSpan:2});
break;
case h:P=new qx.ui.form.RepeatButton();
P.addState(f);
P.setFocusable(false);
P.addListener(H,this._countUp,this);
this._add(P,{column:1,row:0});
break;
case i:P=new qx.ui.form.RepeatButton();
P.addState(f);
P.setFocusable(false);
P.addListener(H,this._countDown,this);
this._add(P,{column:1,row:1});
break;
}return P||qx.ui.core.Widget.prototype._createChildControlImpl.call(this,N);
},_getFilterRegExp:function(){var U=qx.locale.Number.getDecimalSeparator(qx.locale.Manager.getInstance().getLocale());
var T=qx.locale.Number.getGroupSeparator(qx.locale.Manager.getInstance().getLocale());
var S=j;
var Q=j;

if(this.getNumberFormat()!==null){S=this.getNumberFormat().getPrefix()||j;
Q=this.getNumberFormat().getPostfix()||j;
}var R=new RegExp(n+qx.lang.String.escapeRegexpChars(U)+qx.lang.String.escapeRegexpChars(T)+qx.lang.String.escapeRegexpChars(S)+qx.lang.String.escapeRegexpChars(Q)+A);
return R;
},_forwardStates:{focused:true,invalid:true},tabFocus:function(){var V=this.getChildControl(k);
V.getFocusElement().focus();
V.selectAllText();
},_applyMinimum:function(W,X){if(this.getMaximum()<W){this.setMaximum(W);
}
if(this.getValue()<W){this.setValue(W);
}else{this._updateButtons();
}},_applyMaximum:function(Y,ba){if(this.getMinimum()>Y){this.setMinimum(Y);
}
if(this.getValue()>Y){this.setValue(Y);
}else{this._updateButtons();
}},_applyEnabled:function(bb,bc){qx.ui.core.Widget.prototype._applyEnabled.call(this,bb,bc);
this._updateButtons();
},_checkValue:function(bd){return typeof bd===s&&bd>=this.getMinimum()&&bd<=this.getMaximum();
},_applyValue:function(be,bf){var bg=this.getChildControl(k);
this._updateButtons();
this.__yQ=be;
if(be!==null){if(this.getNumberFormat()){bg.setValue(this.getNumberFormat().format(be));
}else{bg.setValue(be+j);
}}else{bg.setValue(j);
}},_applyEditable:function(bh,bi){var bj=this.getChildControl(k);

if(bj){bj.setReadOnly(!bh);
}},_applyWrap:function(bk,bl){this._updateButtons();
},_applyNumberFormat:function(bm,bn){var bo=this.getChildControl(k);
bo.setFilter(this._getFilterRegExp());
this.getNumberFormat().addListener(u,this._onChangeNumberFormat,this);
this._applyValue(this.__yQ,undefined);
},_getContentPaddingTarget:function(){return this.getChildControl(k);
},_updateButtons:function(){var bq=this.getChildControl(h);
var bp=this.getChildControl(i);
var br=this.getValue();

if(!this.getEnabled()){bq.setEnabled(false);
bp.setEnabled(false);
}else{if(this.getWrap()){bq.setEnabled(true);
bp.setEnabled(true);
}else{if(br!==null&&br<this.getMaximum()){bq.setEnabled(true);
}else{bq.setEnabled(false);
}if(br!==null&&br>this.getMinimum()){bp.setEnabled(true);
}else{bp.setEnabled(false);
}}}},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case d:this.__yR=true;
case I:this.getChildControl(h).press();
break;
case G:this.__yS=true;
case a:this.getChildControl(i).press();
break;
default:return ;
}e.stopPropagation();
e.preventDefault();
},_onKeyUp:function(e){switch(e.getKeyIdentifier()){case d:this.getChildControl(h).release();
this.__yR=false;
break;
case I:this.getChildControl(h).release();
break;
case G:this.getChildControl(i).release();
this.__yS=false;
break;
case a:this.getChildControl(i).release();
break;
}},_onMouseWheel:function(e){if(e.getWheelDelta()>0){this._countDown();
}else{this._countUp();
}e.stop();
},_onTextChange:function(e){var bs=this.getChildControl(k);
var bt;
if(this.getNumberFormat()){try{bt=this.getNumberFormat().parse(bs.getValue());
}catch(bu){}}if(bt===undefined){bt=parseFloat(bs.getValue());
}if(!isNaN(bt)){if(bt>this.getMaximum()){bs.setValue(this.getMaximum()+j);
return;
}else if(bt<this.getMinimum()){bs.setValue(this.getMinimum()+j);
return;
}this.setValue(bt);
}else{this._applyValue(this.__yQ,undefined);
}},_onChangeLocale:function(bv){if(this.getNumberFormat()!==null){this.setNumberFormat(this.getNumberFormat());
var bw=this.getChildControl(k);
bw.setFilter(this._getFilterRegExp());
bw.setValue(this.getNumberFormat().format(this.getValue()));
}},_onChangeNumberFormat:function(bx){var by=this.getChildControl(k);
by.setFilter(this._getFilterRegExp());
by.setValue(this.getNumberFormat().format(this.getValue()));
},_countUp:function(){if(this.__yR){var bA=this.getValue()+this.getPageStep();
}else{var bA=this.getValue()+this.getSingleStep();
}if(this.getWrap()){if(bA>this.getMaximum()){var bz=this.getMaximum()-bA;
bA=this.getMinimum()+bz;
}}this.gotoValue(bA);
},_countDown:function(){if(this.__yS){var bC=this.getValue()-this.getPageStep();
}else{var bC=this.getValue()-this.getSingleStep();
}if(this.getWrap()){if(bC<this.getMinimum()){var bB=this.getMinimum()+bC;
bC=this.getMaximum()-bB;
}}this.gotoValue(bC);
},gotoValue:function(bD){return this.setValue(Math.min(this.getMaximum(),Math.max(this.getMinimum(),bD)));
}},destruct:function(){if(qx.core.Environment.get(E)){qx.locale.Manager.getInstance().removeListener(F,this._onChangeLocale,this);
}}});
})();
(function(){var c="password",b="qx.ui.form.PasswordField",a="input";
qx.Class.define(b,{extend:qx.ui.form.TextField,members:{_createInputElement:function(){var d=new qx.html.Input(c);
d.addListener(a,this._onHtmlInput,this);
return d;
}}});
})();

});