qx.$$packageData['029416cbbe84']={"locales":{"C":{"alternateQuotationEnd":"’","alternateQuotationStart":"‘","cldr_am":"AM","cldr_date_format_full":"EEEE, MMMM d, y","cldr_date_format_long":"MMMM d, y","cldr_date_format_medium":"MMM d, y","cldr_date_format_short":"M/d/yy","cldr_date_time_format_EEEd":"d EEE","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_Hms":"H:mm:ss","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, M/d","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E, MMM d","cldr_date_time_format_MMMMEd":"E, MMMM d","cldr_date_time_format_MMMMd":"MMMM d","cldr_date_time_format_MMMd":"MMM d","cldr_date_time_format_Md":"M/d","cldr_date_time_format_d":"d","cldr_date_time_format_hm":"h:mm a","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"M/yyyy","cldr_date_time_format_yMEd":"EEE, M/d/yyyy","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, MMM d, y","cldr_date_time_format_yMMMM":"MMMM y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ y","cldr_day_format_abbreviated_fri":"Fri","cldr_day_format_abbreviated_mon":"Mon","cldr_day_format_abbreviated_sat":"Sat","cldr_day_format_abbreviated_sun":"Sun","cldr_day_format_abbreviated_thu":"Thu","cldr_day_format_abbreviated_tue":"Tue","cldr_day_format_abbreviated_wed":"Wed","cldr_day_format_narrow_fri":"F","cldr_day_format_narrow_mon":"M","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"S","cldr_day_format_narrow_thu":"T","cldr_day_format_narrow_tue":"T","cldr_day_format_narrow_wed":"W","cldr_day_format_wide_fri":"Friday","cldr_day_format_wide_mon":"Monday","cldr_day_format_wide_sat":"Saturday","cldr_day_format_wide_sun":"Sunday","cldr_day_format_wide_thu":"Thursday","cldr_day_format_wide_tue":"Tuesday","cldr_day_format_wide_wed":"Wednesday","cldr_day_stand-alone_abbreviated_fri":"Fri","cldr_day_stand-alone_abbreviated_mon":"Mon","cldr_day_stand-alone_abbreviated_sat":"Sat","cldr_day_stand-alone_abbreviated_sun":"Sun","cldr_day_stand-alone_abbreviated_thu":"Thu","cldr_day_stand-alone_abbreviated_tue":"Tue","cldr_day_stand-alone_abbreviated_wed":"Wed","cldr_day_stand-alone_narrow_fri":"F","cldr_day_stand-alone_narrow_mon":"M","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"S","cldr_day_stand-alone_narrow_thu":"T","cldr_day_stand-alone_narrow_tue":"T","cldr_day_stand-alone_narrow_wed":"W","cldr_day_stand-alone_wide_fri":"Friday","cldr_day_stand-alone_wide_mon":"Monday","cldr_day_stand-alone_wide_sat":"Saturday","cldr_day_stand-alone_wide_sun":"Sunday","cldr_day_stand-alone_wide_thu":"Thursday","cldr_day_stand-alone_wide_tue":"Tuesday","cldr_day_stand-alone_wide_wed":"Wednesday","cldr_month_format_abbreviated_1":"Jan","cldr_month_format_abbreviated_10":"Oct","cldr_month_format_abbreviated_11":"Nov","cldr_month_format_abbreviated_12":"Dec","cldr_month_format_abbreviated_2":"Feb","cldr_month_format_abbreviated_3":"Mar","cldr_month_format_abbreviated_4":"Apr","cldr_month_format_abbreviated_5":"May","cldr_month_format_abbreviated_6":"Jun","cldr_month_format_abbreviated_7":"Jul","cldr_month_format_abbreviated_8":"Aug","cldr_month_format_abbreviated_9":"Sep","cldr_month_format_wide_1":"January","cldr_month_format_wide_10":"October","cldr_month_format_wide_11":"November","cldr_month_format_wide_12":"December","cldr_month_format_wide_2":"February","cldr_month_format_wide_3":"March","cldr_month_format_wide_4":"April","cldr_month_format_wide_5":"May","cldr_month_format_wide_6":"June","cldr_month_format_wide_7":"July","cldr_month_format_wide_8":"August","cldr_month_format_wide_9":"September","cldr_month_stand-alone_narrow_1":"J","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":".","cldr_number_group_separator":",","cldr_number_percent_format":"#,##0%","cldr_pm":"PM","cldr_time_format_full":"h:mm:ss a zzzz","cldr_time_format_long":"h:mm:ss a z","cldr_time_format_medium":"h:mm:ss a","cldr_time_format_short":"h:mm a","quotationEnd":"”","quotationStart":"“"},"de":{"alternateQuotationEnd":"‘","alternateQuotationStart":"‚","cldr_am":"vorm.","cldr_date_format_full":"EEEE, d. MMMM y","cldr_date_format_long":"d. MMMM y","cldr_date_format_medium":"dd.MM.yyyy","cldr_date_format_short":"dd.MM.yy","cldr_date_time_format_EEEd":"d. EEE","cldr_date_time_format_Ed":"E d.","cldr_date_time_format_H":"H","cldr_date_time_format_HHmm":"HH:mm","cldr_date_time_format_HHmmss":"HH:mm:ss","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, d.M.","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E d. MMM","cldr_date_time_format_MMMMEd":"E d. MMMM","cldr_date_time_format_MMMMd":"d. MMMM","cldr_date_time_format_MMMMdd":"dd. MMMM","cldr_date_time_format_MMMd":"d. MMM","cldr_date_time_format_MMd":"d.MM.","cldr_date_time_format_MMdd":"dd.MM.","cldr_date_time_format_Md":"d.M.","cldr_date_time_format_d":"d","cldr_date_time_format_mmss":"mm:ss","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"yyyy-M","cldr_date_time_format_yMEd":"EEE, yyyy-M-d","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, d. MMM y","cldr_date_time_format_yMMMM":"MMMM y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ y","cldr_date_time_format_yyMM":"MM.yy","cldr_date_time_format_yyMMM":"MMM yy","cldr_date_time_format_yyMMdd":"dd.MM.yy","cldr_date_time_format_yyQ":"Q yy","cldr_date_time_format_yyQQQQ":"QQQQ yy","cldr_date_time_format_yyyy":"y","cldr_date_time_format_yyyyMMMM":"MMMM y","cldr_day_format_abbreviated_fri":"Fr.","cldr_day_format_abbreviated_mon":"Mo.","cldr_day_format_abbreviated_sat":"Sa.","cldr_day_format_abbreviated_sun":"So.","cldr_day_format_abbreviated_thu":"Do.","cldr_day_format_abbreviated_tue":"Di.","cldr_day_format_abbreviated_wed":"Mi.","cldr_day_format_narrow_fri":"F","cldr_day_format_narrow_mon":"M","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"S","cldr_day_format_narrow_thu":"D","cldr_day_format_narrow_tue":"D","cldr_day_format_narrow_wed":"M","cldr_day_format_wide_fri":"Freitag","cldr_day_format_wide_mon":"Montag","cldr_day_format_wide_sat":"Samstag","cldr_day_format_wide_sun":"Sonntag","cldr_day_format_wide_thu":"Donnerstag","cldr_day_format_wide_tue":"Dienstag","cldr_day_format_wide_wed":"Mittwoch","cldr_day_stand-alone_abbreviated_fri":"Fr.","cldr_day_stand-alone_abbreviated_mon":"Mo.","cldr_day_stand-alone_abbreviated_sat":"Sa.","cldr_day_stand-alone_abbreviated_sun":"So.","cldr_day_stand-alone_abbreviated_thu":"Do.","cldr_day_stand-alone_abbreviated_tue":"Di.","cldr_day_stand-alone_abbreviated_wed":"Mi.","cldr_day_stand-alone_narrow_fri":"F","cldr_day_stand-alone_narrow_mon":"M","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"S","cldr_day_stand-alone_narrow_thu":"D","cldr_day_stand-alone_narrow_tue":"D","cldr_day_stand-alone_narrow_wed":"M","cldr_day_stand-alone_wide_fri":"Freitag","cldr_day_stand-alone_wide_mon":"Montag","cldr_day_stand-alone_wide_sat":"Samstag","cldr_day_stand-alone_wide_sun":"Sonntag","cldr_day_stand-alone_wide_thu":"Donnerstag","cldr_day_stand-alone_wide_tue":"Dienstag","cldr_day_stand-alone_wide_wed":"Mittwoch","cldr_month_format_abbreviated_1":"Jan","cldr_month_format_abbreviated_10":"Okt","cldr_month_format_abbreviated_11":"Nov","cldr_month_format_abbreviated_12":"Dez","cldr_month_format_abbreviated_2":"Feb","cldr_month_format_abbreviated_3":"Mär","cldr_month_format_abbreviated_4":"Apr","cldr_month_format_abbreviated_5":"Mai","cldr_month_format_abbreviated_6":"Jun","cldr_month_format_abbreviated_7":"Jul","cldr_month_format_abbreviated_8":"Aug","cldr_month_format_abbreviated_9":"Sep","cldr_month_format_wide_1":"Januar","cldr_month_format_wide_10":"Oktober","cldr_month_format_wide_11":"November","cldr_month_format_wide_12":"Dezember","cldr_month_format_wide_2":"Februar","cldr_month_format_wide_3":"März","cldr_month_format_wide_4":"April","cldr_month_format_wide_5":"Mai","cldr_month_format_wide_6":"Juni","cldr_month_format_wide_7":"Juli","cldr_month_format_wide_8":"August","cldr_month_format_wide_9":"September","cldr_month_stand-alone_abbreviated_10":"Okt","cldr_month_stand-alone_abbreviated_11":"Nov","cldr_month_stand-alone_abbreviated_12":"Dez","cldr_month_stand-alone_abbreviated_3":"Mär","cldr_month_stand-alone_abbreviated_7":"Jul","cldr_month_stand-alone_abbreviated_8":"Aug","cldr_month_stand-alone_abbreviated_9":"Sep","cldr_month_stand-alone_narrow_1":"J","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":",","cldr_number_group_separator":".","cldr_number_percent_format":"#,##0 %","cldr_pm":"nachm.","cldr_time_format_full":"HH:mm:ss zzzz","cldr_time_format_long":"HH:mm:ss z","cldr_time_format_medium":"HH:mm:ss","cldr_time_format_short":"HH:mm","quotationEnd":"“","quotationStart":"„"},"de_AT":{"cldr_date_format_full":"EEEE, dd. MMMM y","cldr_date_format_long":"dd. MMMM y","cldr_month_format_abbreviated_1":"Jän","cldr_month_format_wide_1":"Jänner"},"de_DE":{},"en":{"alternateQuotationEnd":"’","alternateQuotationStart":"‘","cldr_am":"AM","cldr_date_format_full":"EEEE, MMMM d, y","cldr_date_format_long":"MMMM d, y","cldr_date_format_medium":"MMM d, y","cldr_date_format_short":"M/d/yy","cldr_date_time_format_EEEd":"d EEE","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_Hms":"H:mm:ss","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, M/d","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E, MMM d","cldr_date_time_format_MMMMEd":"E, MMMM d","cldr_date_time_format_MMMMd":"MMMM d","cldr_date_time_format_MMMd":"MMM d","cldr_date_time_format_Md":"M/d","cldr_date_time_format_d":"d","cldr_date_time_format_hm":"h:mm a","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"M/yyyy","cldr_date_time_format_yMEd":"EEE, M/d/yyyy","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, MMM d, y","cldr_date_time_format_yMMMM":"MMMM y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ y","cldr_day_format_abbreviated_fri":"Fri","cldr_day_format_abbreviated_mon":"Mon","cldr_day_format_abbreviated_sat":"Sat","cldr_day_format_abbreviated_sun":"Sun","cldr_day_format_abbreviated_thu":"Thu","cldr_day_format_abbreviated_tue":"Tue","cldr_day_format_abbreviated_wed":"Wed","cldr_day_format_narrow_fri":"F","cldr_day_format_narrow_mon":"M","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"S","cldr_day_format_narrow_thu":"T","cldr_day_format_narrow_tue":"T","cldr_day_format_narrow_wed":"W","cldr_day_format_wide_fri":"Friday","cldr_day_format_wide_mon":"Monday","cldr_day_format_wide_sat":"Saturday","cldr_day_format_wide_sun":"Sunday","cldr_day_format_wide_thu":"Thursday","cldr_day_format_wide_tue":"Tuesday","cldr_day_format_wide_wed":"Wednesday","cldr_day_stand-alone_abbreviated_fri":"Fri","cldr_day_stand-alone_abbreviated_mon":"Mon","cldr_day_stand-alone_abbreviated_sat":"Sat","cldr_day_stand-alone_abbreviated_sun":"Sun","cldr_day_stand-alone_abbreviated_thu":"Thu","cldr_day_stand-alone_abbreviated_tue":"Tue","cldr_day_stand-alone_abbreviated_wed":"Wed","cldr_day_stand-alone_narrow_fri":"F","cldr_day_stand-alone_narrow_mon":"M","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"S","cldr_day_stand-alone_narrow_thu":"T","cldr_day_stand-alone_narrow_tue":"T","cldr_day_stand-alone_narrow_wed":"W","cldr_day_stand-alone_wide_fri":"Friday","cldr_day_stand-alone_wide_mon":"Monday","cldr_day_stand-alone_wide_sat":"Saturday","cldr_day_stand-alone_wide_sun":"Sunday","cldr_day_stand-alone_wide_thu":"Thursday","cldr_day_stand-alone_wide_tue":"Tuesday","cldr_day_stand-alone_wide_wed":"Wednesday","cldr_month_format_abbreviated_1":"Jan","cldr_month_format_abbreviated_10":"Oct","cldr_month_format_abbreviated_11":"Nov","cldr_month_format_abbreviated_12":"Dec","cldr_month_format_abbreviated_2":"Feb","cldr_month_format_abbreviated_3":"Mar","cldr_month_format_abbreviated_4":"Apr","cldr_month_format_abbreviated_5":"May","cldr_month_format_abbreviated_6":"Jun","cldr_month_format_abbreviated_7":"Jul","cldr_month_format_abbreviated_8":"Aug","cldr_month_format_abbreviated_9":"Sep","cldr_month_format_wide_1":"January","cldr_month_format_wide_10":"October","cldr_month_format_wide_11":"November","cldr_month_format_wide_12":"December","cldr_month_format_wide_2":"February","cldr_month_format_wide_3":"March","cldr_month_format_wide_4":"April","cldr_month_format_wide_5":"May","cldr_month_format_wide_6":"June","cldr_month_format_wide_7":"July","cldr_month_format_wide_8":"August","cldr_month_format_wide_9":"September","cldr_month_stand-alone_narrow_1":"J","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":".","cldr_number_group_separator":",","cldr_number_percent_format":"#,##0%","cldr_pm":"PM","cldr_time_format_full":"h:mm:ss a zzzz","cldr_time_format_long":"h:mm:ss a z","cldr_time_format_medium":"h:mm:ss a","cldr_time_format_short":"h:mm a","quotationEnd":"”","quotationStart":"“"},"en_GB":{"alternateQuotationEnd":"”","alternateQuotationStart":"“","cldr_date_format_full":"EEEE, d MMMM y","cldr_date_format_long":"d MMMM y","cldr_date_format_medium":"d MMM y","cldr_date_format_short":"dd/MM/yyyy","cldr_date_time_format_MEd":"E, d/M","cldr_date_time_format_MMMEd":"E d MMM","cldr_date_time_format_MMMMd":"d MMMM","cldr_date_time_format_MMdd":"dd/MM","cldr_date_time_format_Md":"d/M","cldr_date_time_format_yMEd":"EEE, d/M/yyyy","cldr_date_time_format_yyMMM":"MMM yy","cldr_date_time_format_yyyyMM":"MM/yyyy","cldr_date_time_format_yyyyMMMM":"MMMM y","cldr_time_format_full":"HH:mm:ss zzzz","cldr_time_format_long":"HH:mm:ss z","cldr_time_format_medium":"HH:mm:ss","cldr_time_format_short":"HH:mm","quotationEnd":"’","quotationStart":"‘"},"en_US":{},"es":{"alternateQuotationEnd":"”","alternateQuotationStart":"“","cldr_am":"a.m.","cldr_date_format_full":"EEEE d 'de' MMMM 'de' y","cldr_date_format_long":"d 'de' MMMM 'de' y","cldr_date_format_medium":"dd/MM/yyyy","cldr_date_format_short":"dd/MM/yy","cldr_date_time_format_EEEd":"EEE d","cldr_date_time_format_HHmm":"HH:mm","cldr_date_time_format_HHmmss":"HH:mm:ss","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, d-M","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E d MMM","cldr_date_time_format_MMMMEd":"E d MMMM","cldr_date_time_format_MMMMd":"d 'de' MMMM","cldr_date_time_format_MMMd":"d MMM","cldr_date_time_format_MMMdd":"dd-MMM","cldr_date_time_format_MMd":"d/MM","cldr_date_time_format_MMdd":"MM/dd","cldr_date_time_format_Md":"d/M","cldr_date_time_format_d":"d","cldr_date_time_format_hhmm":"hh:mm a","cldr_date_time_format_hhmmss":"hh:mm:ss a","cldr_date_time_format_mmss":"mm:ss","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"M/yyyy","cldr_date_time_format_yMEd":"EEE d/M/yyyy","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, d MMM y","cldr_date_time_format_yMMMM":"MMMM 'de' y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ yyyy","cldr_date_time_format_yyMM":"MM/yy","cldr_date_time_format_yyMMM":"MMM-yy","cldr_date_time_format_yyQ":"Q yy","cldr_date_time_format_yyQQQQ":"QQQQ 'de' yy","cldr_date_time_format_yyyyMM":"MM/yyyy","cldr_day_format_abbreviated_fri":"vie","cldr_day_format_abbreviated_mon":"lun","cldr_day_format_abbreviated_sat":"sáb","cldr_day_format_abbreviated_sun":"dom","cldr_day_format_abbreviated_thu":"jue","cldr_day_format_abbreviated_tue":"mar","cldr_day_format_abbreviated_wed":"mié","cldr_day_format_narrow_fri":"V","cldr_day_format_narrow_mon":"L","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"D","cldr_day_format_narrow_thu":"J","cldr_day_format_narrow_tue":"M","cldr_day_format_narrow_wed":"M","cldr_day_format_wide_fri":"viernes","cldr_day_format_wide_mon":"lunes","cldr_day_format_wide_sat":"sábado","cldr_day_format_wide_sun":"domingo","cldr_day_format_wide_thu":"jueves","cldr_day_format_wide_tue":"martes","cldr_day_format_wide_wed":"miércoles","cldr_day_stand-alone_abbreviated_fri":"vie","cldr_day_stand-alone_abbreviated_mon":"lun","cldr_day_stand-alone_abbreviated_sat":"sáb","cldr_day_stand-alone_abbreviated_sun":"dom","cldr_day_stand-alone_abbreviated_thu":"jue","cldr_day_stand-alone_abbreviated_tue":"mar","cldr_day_stand-alone_abbreviated_wed":"mié","cldr_day_stand-alone_narrow_fri":"V","cldr_day_stand-alone_narrow_mon":"L","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"D","cldr_day_stand-alone_narrow_thu":"J","cldr_day_stand-alone_narrow_tue":"M","cldr_day_stand-alone_narrow_wed":"M","cldr_day_stand-alone_wide_fri":"viernes","cldr_day_stand-alone_wide_mon":"lunes","cldr_day_stand-alone_wide_sat":"sábado","cldr_day_stand-alone_wide_sun":"domingo","cldr_day_stand-alone_wide_thu":"jueves","cldr_day_stand-alone_wide_tue":"martes","cldr_day_stand-alone_wide_wed":"miércoles","cldr_month_format_abbreviated_1":"ene","cldr_month_format_abbreviated_10":"oct","cldr_month_format_abbreviated_11":"nov","cldr_month_format_abbreviated_12":"dic","cldr_month_format_abbreviated_2":"feb","cldr_month_format_abbreviated_3":"mar","cldr_month_format_abbreviated_4":"abr","cldr_month_format_abbreviated_5":"may","cldr_month_format_abbreviated_6":"jun","cldr_month_format_abbreviated_7":"jul","cldr_month_format_abbreviated_8":"ago","cldr_month_format_abbreviated_9":"sep","cldr_month_format_wide_1":"enero","cldr_month_format_wide_10":"octubre","cldr_month_format_wide_11":"noviembre","cldr_month_format_wide_12":"diciembre","cldr_month_format_wide_2":"febrero","cldr_month_format_wide_3":"marzo","cldr_month_format_wide_4":"abril","cldr_month_format_wide_5":"mayo","cldr_month_format_wide_6":"junio","cldr_month_format_wide_7":"julio","cldr_month_format_wide_8":"agosto","cldr_month_format_wide_9":"septiembre","cldr_month_stand-alone_narrow_1":"E","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":",","cldr_number_group_separator":".","cldr_number_percent_format":"#,##0%","cldr_pm":"p.m.","cldr_time_format_full":"HH:mm:ss zzzz","cldr_time_format_long":"HH:mm:ss z","cldr_time_format_medium":"HH:mm:ss","cldr_time_format_short":"HH:mm","quotationEnd":"’","quotationStart":"‘"},"es_ES":{},"es_MX":{"cldr_number_decimal_separator":".","cldr_number_group_separator":","}},"resources":{"qx/icon/Tango/16/actions/edit-clear.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-copy.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-cut.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-delete.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-find.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-paste.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-redo.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-select-all.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-undo.png":[16,16,"png","qx"]},"translations":{"C":{},"de":{"A date:":"Datum:","Command Menu (keyboard shortcuts)":"Command-Menü (Tastenkürzel)","Copy":"Kopieren","Cut":"Aussschneiden","Date format full:":"Vollständiges Datumsformat:","Date format long:":"Langes Datumsformat:","Date format medium:":"Mittellanges Datumsformat:","Date format short:":"kurzes Zeitformat:","Date full:":"Vollständiges Datum:","Date long:":"Langes Datum:","Date medium:":"Mittellanges Datum:","Date short:":"Zeit (kurz):","Delete":"Löschen","Form Elements":"Formular Widgets","Format of %1:":"Format von %1:","Locale Information":"Lokalisierungsinformationen","Locale:":"Sprachkennung:","Localized ComboBox:":"Lokalisierte ComboBox:","Paste":"Einfügen","Redo":"Wiederholen","Search":"Suchen","Search Again":"Weiter suchen","Select All":"Alles auswählen","Territory code:":"Landeskennung:","Time format long:":"Langes Zeitformat:","Time format short:":"kurzes Zeitformat:","Time long:":"Zeit (lang):","Time short:":"Zeit (kurz):","Undo":"Rückgängig","Week start:":"Wochenanfang:"},"de_AT":{},"de_DE":{},"en":{},"en_GB":{},"en_US":{},"es":{"A date:":"Una fecha:","Command Menu (keyboard shortcuts)":"Menú de comando (claves del teclado)","Copy":"Copiar","Cut":"Cortar","Date format full:":"Formato de fecha completo:","Date format long:":"Formato de fecha largo:","Date format medium:":"Formato de fecha mediano:","Date format short:":"Formato de hora corto:","Date full:":"Fecha completo:","Date long:":"Fecha largo:","Date medium:":"Fecha mediano:","Date short:":"Hora corto:","Delete":"Borrar","Format of %1:":"Formato de %1:","Locale Information":"Información de la localisación","Locale:":"Localisación:","Localized ComboBox:":"ComboBox:","Paste":"Pegar","Redo":"Rehacer","Search":"Búsqueda","Search Again":"Buscar otra vez","Select All":"Seleccionar todo","Territory code:":"Código regional:","Time format long:":"Formato de hora largo:","Time format short:":"Formato de hora corto:","Time long:":"Hora largo:","Time short:":"Hora corto:","Undo":"Deshacer","Week start:":"Inicio de semana:"},"es_ES":{},"es_MX":{}}};

qx.Part.$$notifyLoad("029416cbbe84", function() {
(function(){var d="cldr_number_decimal_separator",c="cldr_number_percent_format",b="qx.locale.Number",a="cldr_number_group_separator";
qx.Class.define(b,{statics:{getDecimalSeparator:function(e){return qx.locale.Manager.getInstance().localize(d,[],e);
},getGroupSeparator:function(f){return qx.locale.Manager.getInstance().localize(a,[],f);
},getPercentFormat:function(g){return qx.locale.Manager.getInstance().localize(c,[],g);
}}});
})();
(function(){var a="qx.util.format.IFormat";
qx.Interface.define(a,{members:{format:function(b){},parse:function(c){}}});
})();
(function(){var D="_",C="format",B="thu",A="sat",z="cldr_day_",y="cldr_month_",x="wed",w="fri",v="tue",u="mon",U="sun",T="short",S="HH:mm",R="HHmmsszz",Q="HHmm",P="HHmmss",O="cldr_date_format_",N="HH:mm:ss zz",M="full",L="cldr_pm",J="long",K="medium",H="cldr_am",I="qx.locale.Date",F="cldr_date_time_format_",G="cldr_time_format_",E="HH:mm:ss";
qx.Class.define(I,{statics:{__lS:qx.locale.Manager.getInstance(),getAmMarker:function(j){return this.__lS.localize(H,[],j);
},getPmMarker:function(bb){return this.__lS.localize(L,[],bb);
},getDayNames:function(length,p,q){var q=q?q:C;
{};
var s=[U,u,v,x,B,w,A];
var t=[];

for(var i=0;i<s.length;i++){var r=z+q+D+length+D+s[i];
t.push(this.__lS.localize(r,[],p));
}return t;
},getDayName:function(length,k,l,m){var m=m?m:C;
{};
var o=[U,u,v,x,B,w,A];
var n=z+m+D+length+D+o[k];
return this.__lS.localize(n,[],l);
},getMonthNames:function(length,bk,bl){var bl=bl?bl:C;
{};
var bn=[];

for(var i=0;i<12;i++){var bm=y+bl+D+length+D+(i+1);
bn.push(this.__lS.localize(bm,[],bk));
}return bn;
},getMonthName:function(length,bc,bd,be){var be=be?be:C;
{};
var bf=y+be+D+length+D+(bc+1);
return this.__lS.localize(bf,[],bd);
},getDateFormat:function(a,b){{};
var c=O+a;
return this.__lS.localize(c,[],b);
},getDateTimeFormat:function(V,W,X){var ba=F+V;
var Y=this.__lS.localize(ba,[],X);

if(Y==ba){Y=W;
}return Y;
},getTimeFormat:function(bo,bp){{};
var br=G+bo;
var bq=this.__lS.localize(br,[],bp);

if(bq!=br){return bq;
}
switch(bo){case T:case K:return qx.locale.Date.getDateTimeFormat(Q,S);
case J:return qx.locale.Date.getDateTimeFormat(P,E);
case M:return qx.locale.Date.getDateTimeFormat(R,N);
default:throw new Error("This case should never happen.");
}},getWeekStart:function(bv){var bw={"MV":5,"AE":6,"AF":6,"BH":6,"DJ":6,"DZ":6,"EG":6,"ER":6,"ET":6,"IQ":6,"IR":6,"JO":6,"KE":6,"KW":6,"LB":6,"LY":6,"MA":6,"OM":6,"QA":6,"SA":6,"SD":6,"SO":6,"TN":6,"YE":6,"AS":0,"AU":0,"AZ":0,"BW":0,"CA":0,"CN":0,"FO":0,"GE":0,"GL":0,"GU":0,"HK":0,"IE":0,"IL":0,"IS":0,"JM":0,"JP":0,"KG":0,"KR":0,"LA":0,"MH":0,"MN":0,"MO":0,"MP":0,"MT":0,"NZ":0,"PH":0,"PK":0,"SG":0,"TH":0,"TT":0,"TW":0,"UM":0,"US":0,"UZ":0,"VI":0,"ZA":0,"ZW":0,"MW":0,"NG":0,"TJ":0};
var bx=qx.locale.Date._getTerritory(bv);
return bw[bx]!=null?bw[bx]:1;
},getWeekendStart:function(f){var h={"EG":5,"IL":5,"SY":5,"IN":0,"AE":4,"BH":4,"DZ":4,"IQ":4,"JO":4,"KW":4,"LB":4,"LY":4,"MA":4,"OM":4,"QA":4,"SA":4,"SD":4,"TN":4,"YE":4};
var g=qx.locale.Date._getTerritory(f);
return h[g]!=null?h[g]:6;
},getWeekendEnd:function(bs){var bt={"AE":5,"BH":5,"DZ":5,"IQ":5,"JO":5,"KW":5,"LB":5,"LY":5,"MA":5,"OM":5,"QA":5,"SA":5,"SD":5,"TN":5,"YE":5,"AF":5,"IR":5,"EG":6,"IL":6,"SY":6};
var bu=qx.locale.Date._getTerritory(bs);
return bt[bu]!=null?bt[bu]:0;
},isWeekend:function(bg,bh){var bj=qx.locale.Date.getWeekendStart(bh);
var bi=qx.locale.Date.getWeekendEnd(bh);

if(bi>bj){return ((bg>=bj)&&(bg<=bi));
}else{return ((bg>=bj)||(bg<=bi));
}},_getTerritory:function(d){if(d){var e=d.split(D)[1]||d;
}else{e=this.__lS.getTerritory()||this.__lS.getLanguage();
}return e.toUpperCase();
}}});
})();
(function(){var dn="(\\d\\d?)",dm="format",dl="",dk="abbreviated",dj="wide",di="(",dh=")",dg="|",df="stand-alone",de="wildcard",cS="default",cR="literal",cQ="'",cP="hour",cO="(\\d\\d?\\d?)",cN="ms",cM="narrow",cL="-",cK="quoted_literal",cJ='a',dv="HH:mm:ss",dw="+",dt="HHmmss",du="long",dr='z',ds="0",dp="sec",dq="day",dx='Z',dy=" ",cW="min",cV="mm",cY="(\\d+)",cX="h",db="KK",da='L',dd="Z",dc="(\\d\\d+)",cU="EEEE",cT="^",bK=":",bL='y',bM="K",bN="a",bO="([\\+\\-]\\d\\d:?\\d\\d)",bP="GMT",bQ="dd",bR="qx.util.format.DateFormat",bS="yyy",bT="H",dC="YYYY",dB="y",dA="HH",dz="EE",dG='h',dF="S",dE='s',dD='A',dI="yyyyyy",dH="kk",ct="ss",cu='H',cr='S',cs="MMMM",cx='c',cy="d",cv="([a-zA-Z]+)",cw='k',cp="m",cq='Y',cc='D',cb="yyyyy",ce='K',cd="hh",bX="SSS",bW="MM",ca="yy",bY="(\\d\\d\\d\\d\\d\\d+)",bV="yyyy-MM-dd HH:mm:ss",bU="(\\d\\d\\d\\d\\d+)",cD="short",cE='d',cF="unkown",cG='m',cz="(\\d\\d\\d\\d)",cA="(\\d\\d\\d+)",cB="k",cC='M',cH="(\\d\\d\\d\\d+)",cI="SS",cm="MMM",cl="s",ck="M",cj='w',ci="EEE",ch="$",cg="?",cf='E',co="z",cn="yyyy";
qx.Class.define(bR,{extend:qx.core.Object,implement:qx.util.format.IFormat,construct:function(bE,bF){qx.core.Object.call(this);

if(!bF){this.__lG=qx.locale.Manager.getInstance().getLocale();
}else{this.__lG=bF;
}
if(bE!=null){this.__lH=bE.toString();
}else{this.__lH=qx.locale.Date.getDateFormat(du,this.__lG)+dy+qx.locale.Date.getDateTimeFormat(dt,dv,this.__lG);
}},statics:{getDateTimeInstance:function(){var bD=qx.util.format.DateFormat;
var bC=qx.locale.Date.getDateFormat(du)+dy+qx.locale.Date.getDateTimeFormat(dt,dv);

if(bD._dateInstance==null||bD._dateInstance.__lH!=bC){bD._dateTimeInstance=new bD();
}return bD._dateTimeInstance;
},getDateInstance:function(){var bH=qx.util.format.DateFormat;
var bG=qx.locale.Date.getDateFormat(cD)+dl;

if(bH._dateInstance==null||bH._dateInstance.__lH!=bG){bH._dateInstance=new bH(bG);
}return bH._dateInstance;
},ASSUME_YEAR_2000_THRESHOLD:30,LOGGING_DATE_TIME__format:bV,AM_MARKER:"am",PM_MARKER:"pm",MEDIUM_TIMEZONE_NAMES:["GMT"],FULL_TIMEZONE_NAMES:["Greenwich Mean Time"]},members:{__lG:null,__lH:null,__lI:null,__lJ:null,__lK:null,__lL:function(dJ,dK){var dL=dl+dJ;

while(dL.length<dK){dL=ds+dL;
}return dL;
},__lM:function(a){var b=new Date(a.getTime());
var c=b.getDate();

while(b.getMonth()!=0){b.setDate(-1);
c+=b.getDate()+1;
}return c;
},__lN:function(ea){return new Date(ea.getTime()+(3-((ea.getDay()+6)%7))*86400000);
},__lO:function(G){var I=this.__lN(G);
var J=I.getFullYear();
var H=this.__lN(new Date(J,0,4));
return Math.floor(1.5+(I.getTime()-H.getTime())/86400000/7);
},format:function(bi){if(bi==null){return null;
}var bo=qx.util.format.DateFormat;
var bp=this.__lG;
var bz=bi.getFullYear();
var bt=bi.getMonth();
var bB=bi.getDate();
var bj=bi.getDay();
var bu=bi.getHours();
var bq=bi.getMinutes();
var bv=bi.getSeconds();
var bx=bi.getMilliseconds();
var bA=bi.getTimezoneOffset();
var bm=bA>0?1:-1;
var bk=Math.floor(Math.abs(bA)/60);
var br=Math.abs(bA)%60;
this.__lP();
var by=dl;

for(var i=0;i<this.__lK.length;i++){var bw=this.__lK[i];

if(bw.type==cR){by+=bw.text;
}else{var bn=bw.character;
var bs=bw.size;
var bl=cg;

switch(bn){case bL:case cq:if(bs==2){bl=this.__lL(bz%100,2);
}else{bl=bz+dl;

if(bs>bl.length){for(var i=bl.length;i<bs;i++){bl=ds+bl;
}}}break;
case cc:bl=this.__lL(this.__lM(bi),bs);
break;
case cE:bl=this.__lL(bB,bs);
break;
case cj:bl=this.__lL(this.__lO(bi),bs);
break;
case cf:if(bs==2){bl=qx.locale.Date.getDayName(cM,bj,bp,dm);
}else if(bs==3){bl=qx.locale.Date.getDayName(dk,bj,bp,dm);
}else if(bs==4){bl=qx.locale.Date.getDayName(dj,bj,bp,dm);
}break;
case cx:if(bs==2){bl=qx.locale.Date.getDayName(cM,bj,bp,df);
}else if(bs==3){bl=qx.locale.Date.getDayName(dk,bj,bp,df);
}else if(bs==4){bl=qx.locale.Date.getDayName(dj,bj,bp,df);
}break;
case cC:if(bs==1||bs==2){bl=this.__lL(bt+1,bs);
}else if(bs==3){bl=qx.locale.Date.getMonthName(dk,bt,bp,dm);
}else if(bs==4){bl=qx.locale.Date.getMonthName(dj,bt,bp,dm);
}break;
case da:if(bs==1||bs==2){bl=this.__lL(bt+1,bs);
}else if(bs==3){bl=qx.locale.Date.getMonthName(dk,bt,bp,df);
}else if(bs==4){bl=qx.locale.Date.getMonthName(dj,bt,bp,df);
}break;
case cJ:bl=(bu<12)?qx.locale.Date.getAmMarker(bp):qx.locale.Date.getPmMarker(bp);
break;
case cu:bl=this.__lL(bu,bs);
break;
case cw:bl=this.__lL((bu==0)?24:bu,bs);
break;
case ce:bl=this.__lL(bu%12,bs);
break;
case dG:bl=this.__lL(((bu%12)==0)?12:(bu%12),bs);
break;
case cG:bl=this.__lL(bq,bs);
break;
case dE:bl=this.__lL(bv,bs);
break;
case cr:bl=this.__lL(bx,bs);
break;
case dr:if(bs==1){bl=bP+((bm>0)?cL:dw)+this.__lL(Math.abs(bk))+bK+this.__lL(br,2);
}else if(bs==2){bl=bo.MEDIUM_TIMEZONE_NAMES[bk];
}else if(bs==3){bl=bo.FULL_TIMEZONE_NAMES[bk];
}break;
case dx:bl=((bm>0)?cL:dw)+this.__lL(Math.abs(bk),2)+this.__lL(br,2);
break;
}by+=bl;
}}return by;
},parse:function(dM){this.__lQ();
var dS=this.__lI.regex.exec(dM);

if(dS==null){throw new Error("Date string '"+dM+"' does not match the date format: "+this.__lH);
}var dN={year:1970,month:0,day:1,hour:0,ispm:false,min:0,sec:0,ms:0};
var dO=1;

for(var i=0;i<this.__lI.usedRules.length;i++){var dQ=this.__lI.usedRules[i];
var dP=dS[dO];

if(dQ.field!=null){dN[dQ.field]=parseInt(dP,10);
}else{dQ.manipulator(dN,dP);
}dO+=(dQ.groups==null)?1:dQ.groups;
}var dR=new Date(dN.year,dN.month,dN.day,(dN.ispm)?(dN.hour+12):dN.hour,dN.min,dN.sec,dN.ms);

if(dN.month!=dR.getMonth()||dN.year!=dR.getFullYear()){throw new Error("Error parsing date '"+dM+"': the value for day or month is too large");
}return dR;
},__lP:function(){if(this.__lK!=null){return;
}this.__lK=[];
var D;
var B=0;
var F=dl;
var z=this.__lH;
var C=cS;
var i=0;

while(i<z.length){var E=z.charAt(i);

switch(C){case cK:if(E==cQ){if(i+1>=z.length){i++;
break;
}var A=z.charAt(i+1);

if(A==cQ){F+=E;
i++;
}else{i++;
C=cF;
}}else{F+=E;
i++;
}break;
case de:if(E==D){B++;
i++;
}else{this.__lK.push({type:de,character:D,size:B});
D=null;
B=0;
C=cS;
}break;
default:if((E>=cJ&&E<=dr)||(E>=dD&&E<=dx)){D=E;
C=de;
}else if(E==cQ){if(i+1>=z.length){F+=E;
i++;
break;
}var A=z.charAt(i+1);

if(A==cQ){F+=E;
i++;
}i++;
C=cK;
}else{C=cS;
}
if(C!=cS){if(F.length>0){this.__lK.push({type:cR,text:F});
F=dl;
}}else{F+=E;
i++;
}break;
}}if(D!=null){this.__lK.push({type:de,character:D,size:B});
}else if(F.length>0){this.__lK.push({type:cR,text:F});
}},__lQ:function(){if(this.__lI!=null){return ;
}var W=this.__lH;
this.__lR();
this.__lP();
var bd=[];
var Y=cT;

for(var U=0;U<this.__lK.length;U++){var be=this.__lK[U];

if(be.type==cR){Y+=qx.lang.String.escapeRegexpChars(be.text);
}else{var V=be.character;
var ba=be.size;
var X;

for(var bf=0;bf<this.__lJ.length;bf++){var bb=this.__lJ[bf];

if(V==bb.pattern.charAt(0)&&ba==bb.pattern.length){X=bb;
break;
}}if(X==null){var bc=dl;

for(var i=0;i<ba;i++){bc+=V;
}throw new Error("Malformed date format: "+W+". Wildcard "+bc+" is not supported");
}else{bd.push(X);
Y+=X.regex;
}}}Y+=ch;
var T;

try{T=new RegExp(Y);
}catch(M){throw new Error("Malformed date format: "+W);
}this.__lI={regex:T,"usedRules":bd,pattern:Y};
},__lR:function(){var j=qx.util.format.DateFormat;
var p=qx.lang.String;

if(this.__lJ!=null){return ;
}var k=this.__lJ=[];
var w=function(eb,ec){ec=parseInt(ec,10);

if(ec<j.ASSUME_YEAR_2000_THRESHOLD){ec+=2000;
}else if(ec<100){ec+=1900;
}eb.year=ec;
};
var q=function(x,y){x.month=parseInt(y,10)-1;
};
var n=function(R,S){R.ispm=(S==j.PM_MARKER);
};
var m=function(dX,dY){dX.hour=parseInt(dY,10)%24;
};
var l=function(dV,dW){dV.hour=parseInt(dW,10)%12;
};
var t=function(N,O){return;
};
var r=qx.locale.Date.getMonthNames(dk,this.__lG,dm);

for(var i=0;i<r.length;i++){r[i]=p.escapeRegexpChars(r[i].toString());
}var s=function(K,L){L=p.escapeRegexpChars(L);
K.month=r.indexOf(L);
};
var f=qx.locale.Date.getMonthNames(dj,this.__lG,dm);

for(var i=0;i<f.length;i++){f[i]=p.escapeRegexpChars(f[i].toString());
}var e=function(dT,dU){dU=p.escapeRegexpChars(dU);
dT.month=f.indexOf(dU);
};
var h=qx.locale.Date.getDayNames(cM,this.__lG,dm);

for(var i=0;i<h.length;i++){h[i]=p.escapeRegexpChars(h[i].toString());
}var d=function(P,Q){Q=p.escapeRegexpChars(Q);
P.month=h.indexOf(Q);
};
var u=qx.locale.Date.getDayNames(dk,this.__lG,dm);

for(var i=0;i<u.length;i++){u[i]=p.escapeRegexpChars(u[i].toString());
}var o=function(bI,bJ){bJ=p.escapeRegexpChars(bJ);
bI.month=u.indexOf(bJ);
};
var v=qx.locale.Date.getDayNames(dj,this.__lG,dm);

for(var i=0;i<v.length;i++){v[i]=p.escapeRegexpChars(v[i].toString());
}var g=function(bg,bh){bh=p.escapeRegexpChars(bh);
bg.month=v.indexOf(bh);
};
k.push({pattern:dC,regex:cz,manipulator:w});
k.push({pattern:dB,regex:cY,manipulator:w});
k.push({pattern:ca,regex:dc,manipulator:w});
k.push({pattern:bS,regex:cA,manipulator:w});
k.push({pattern:cn,regex:cH,manipulator:w});
k.push({pattern:cb,regex:bU,manipulator:w});
k.push({pattern:dI,regex:bY,manipulator:w});
k.push({pattern:ck,regex:dn,manipulator:q});
k.push({pattern:bW,regex:dn,manipulator:q});
k.push({pattern:cm,regex:di+r.join(dg)+dh,manipulator:s});
k.push({pattern:cs,regex:di+f.join(dg)+dh,manipulator:e});
k.push({pattern:bQ,regex:dn,field:dq});
k.push({pattern:cy,regex:dn,field:dq});
k.push({pattern:dz,regex:di+h.join(dg)+dh,manipulator:d});
k.push({pattern:ci,regex:di+u.join(dg)+dh,manipulator:o});
k.push({pattern:cU,regex:di+v.join(dg)+dh,manipulator:g});
k.push({pattern:bN,regex:di+j.AM_MARKER+dg+j.PM_MARKER+dh,manipulator:n});
k.push({pattern:dA,regex:dn,field:cP});
k.push({pattern:bT,regex:dn,field:cP});
k.push({pattern:dH,regex:dn,manipulator:m});
k.push({pattern:cB,regex:dn,manipulator:m});
k.push({pattern:db,regex:dn,field:cP});
k.push({pattern:bM,regex:dn,field:cP});
k.push({pattern:cd,regex:dn,manipulator:l});
k.push({pattern:cX,regex:dn,manipulator:l});
k.push({pattern:cV,regex:dn,field:cW});
k.push({pattern:cp,regex:dn,field:cW});
k.push({pattern:ct,regex:dn,field:dp});
k.push({pattern:cl,regex:dn,field:dp});
k.push({pattern:bX,regex:cO,field:cN});
k.push({pattern:cI,regex:cO,field:cN});
k.push({pattern:dF,regex:cO,field:cN});
k.push({pattern:dd,regex:bO,manipulator:t});
k.push({pattern:co,regex:cv,manipulator:t});
}},destruct:function(){this.__lK=this.__lI=this.__lJ=null;
}});
})();
(function(){var u="",t="Number",s="-",r="0",q="String",p="changeNumberFormat",o='(',n="g",m="Boolean",l="$",e="NaN",k='([0-9]{1,3}(?:',h='{0,1}[0-9]{3}){0,})',d='\\d+){0,1}',c="qx.util.format.NumberFormat",g="Infinity",f="^",i=".",b="-Infinity",j='([-+]){0,1}';
qx.Class.define(c,{extend:qx.core.Object,implement:qx.util.format.IFormat,construct:function(a){qx.core.Object.call(this);
this.__lF=a;
},statics:{getIntegerInstance:function(){var H=qx.util.format.NumberFormat;

if(H._integerInstance==null){H._integerInstance=new H();
H._integerInstance.setMaximumFractionDigits(0);
}return H._integerInstance;
},getInstance:function(){if(!this._instance){this._instance=new this;
}return this._instance;
}},properties:{minimumIntegerDigits:{check:t,init:0},maximumIntegerDigits:{check:t,nullable:true},minimumFractionDigits:{check:t,init:0},maximumFractionDigits:{check:t,nullable:true},groupingUsed:{check:m,init:true},prefix:{check:q,init:u,event:p},postfix:{check:q,init:u,event:p}},members:{__lF:null,format:function(v){switch(v){case Infinity:return g;
case -Infinity:return b;
case NaN:return e;
}var z=(v<0);

if(z){v=-v;
}
if(this.getMaximumFractionDigits()!=null){var G=Math.pow(10,this.getMaximumFractionDigits());
v=Math.round(v*G)/G;
}var F=String(Math.floor(v)).length;
var w=u+v;
var C=w.substring(0,F);

while(C.length<this.getMinimumIntegerDigits()){C=r+C;
}
if(this.getMaximumIntegerDigits()!=null&&C.length>this.getMaximumIntegerDigits()){C=C.substring(C.length-this.getMaximumIntegerDigits());
}var B=w.substring(F+1);

while(B.length<this.getMinimumFractionDigits()){B+=r;
}
if(this.getMaximumFractionDigits()!=null&&B.length>this.getMaximumFractionDigits()){B=B.substring(0,this.getMaximumFractionDigits());
}if(this.getGroupingUsed()){var y=C;
C=u;
var E;

for(E=y.length;E>3;E-=3){C=u+qx.locale.Number.getGroupSeparator(this.__lF)+y.substring(E-3,E)+C;
}C=y.substring(0,E)+C;
}var A=this.getPrefix()?this.getPrefix():u;
var x=this.getPostfix()?this.getPostfix():u;
var D=A+(z?s:u)+C;

if(B.length>0){D+=u+qx.locale.Number.getDecimalSeparator(this.__lF)+B;
}D+=x;
return D;
},parse:function(I){var N=qx.lang.String.escapeRegexpChars(qx.locale.Number.getGroupSeparator(this.__lF)+u);
var L=qx.lang.String.escapeRegexpChars(qx.locale.Number.getDecimalSeparator(this.__lF)+u);
var J=new RegExp(f+qx.lang.String.escapeRegexpChars(this.getPrefix())+j+k+N+h+o+L+d+qx.lang.String.escapeRegexpChars(this.getPostfix())+l);
var M=J.exec(I);

if(M==null){throw new Error("Number string '"+I+"' does not match the number format");
}var O=(M[1]==s);
var Q=M[2];
var P=M[3];
Q=Q.replace(new RegExp(N,n),u);
var K=(O?s:u)+Q;

if(P!=null&&P.length!=0){P=P.replace(new RegExp(L),u);
K+=i+P;
}return parseFloat(K);
}}});
})();
(function(){var s="short",r="long",q="selection[0]",p="medium",o="Cut",n="Copy",m="language",l="Paste",k="full",j="selection[0].selected",bK="Territory code:",bJ="icon/16/actions/edit-find.png",bI="Time format short:",bH="Ctrl+V",bG="icon/16/actions/edit-delete.png",bF="icon/16/actions/edit-cut.png",bE="United States",bD="Date medium:",bC=".png",bB="Date long:",z="DE",A="en",x="Time format long:",y="Mexico",v="button",w="Locale:",t="AT",u="Undo",H="Date short:",I="Austria",bc="Format of %1:",X="Date format short:",bk="changeLocale",bf="Search",bw="MX",bq="center",Q="Ctrl+X",bA="wide",by="es",bx="US",O="middle",T="Time short:",V="A date:",ba="name",bd="GB",bg="icon",bm="ES",bs="Germany",B="_",C="Date format medium:",S="de",bj="F3",bi="Date format full:",bh="Week start:",bo="Ctrl+F",bn="icon/16/actions/edit-paste.png",be="Del",bl="showcase.page.i18n.Content",f="Date format long:",br="right",D="icon/16/actions/edit-copy.png",E="country",Y="selection[0].countries",g="Spain",h="selection[0].selected.code",N="Locale Information",F="Redo",G="Delete",M="model",bb="Ctrl+C",bu="Date full:",bt="Ctrl+A",U="Search Again",bv="Localized ComboBox:",P="Select All",bp="Ctrl+Z",J="Time long:",L="Ctrl+Y",R="Command Menu (keyboard shortcuts)",W="showcase/i18n/",K="Form Elements",bz="Great Britain";
qx.Class.define(bl,{extend:showcase.AbstractContent,include:qx.locale.MTranslation,construct:function(d){showcase.AbstractContent.call(this,d);
this.setView(this._createView());
},members:{__sk:null,__sl:null,_createView:function(){var ci=new qx.ui.layout.Grid(10,15);
ci.setColumnFlex(0,1);
ci.setColumnFlex(1,1);
var ch=new qx.ui.container.Composite(ci).set({padding:10});
ch.add(this.__sm(),{row:0,column:0,colSpan:2});
ch.add(this.__sn(),{row:1,column:0});
ch.add(this.__so(),{row:1,column:1});
return ch;
},__sm:function(){var ck=new qx.ui.form.RadioButtonGroup(new qx.ui.layout.HBox(10).set({alignX:bq}));
var cl=this.__sk=qx.data.marshal.Json.createModel([{language:A,selected:null,countries:[{code:bx,name:bE},{code:bd,name:bz}]},{language:by,selected:null,countries:[{code:bm,name:g},{code:bw,name:y}]},{language:S,selected:null,countries:[{code:z,name:bs},{code:t,name:I}]}]);

for(var i=0;i<cl.getLength();i++){cl.getItem(i).setSelected(cl.getItem(i).getCountries().getItem(0));
}var cj=new qx.data.controller.List(null,ck,m);
this.__sl=cj;
cj.setDelegate({createItem:function(){return new qx.ui.form.RadioButton().set({show:bg,appearance:v});
}});
cj.setIconPath(m);
cj.setIconOptions({converter:function(e){return W+e+bC;
}});
cj.setModel(cl);
cj.getSelection().push(cl.getItem(0));
this.__sl.bind(h,this,E);
return ck;
},setCountry:function(cf){if(cf){var cg=this.__sl.getSelection().getItem(0).getLanguage();
qx.locale.Manager.getInstance().setLocale(cg+B+cf);
}},__sn:function(){var bW=new qx.ui.layout.Grid(10,10);
bW.setColumnFlex(0,1);
bW.setColumnFlex(1,1);
bW.setColumnAlign(0,br,O);
var bT=new qx.ui.groupbox.GroupBox(this.tr(K)).set({width:0,minWidth:0});
bT.setLayout(bW);
bT.add(new qx.ui.basic.Label(this.tr(bK)),{row:0,column:0});
var bP=new qx.ui.form.SelectBox();
var bV=new qx.data.controller.List(null,bP,ba);
this.__sl.bind(Y,bV,M);
this.__sl.bind(j,bV,q);
bV.bind(q,this.__sl,j);
bT.add(bP,{row:0,column:1});
bT.add(new qx.ui.basic.Label(this.tr(bv)),{row:1,column:0});
var bL=new qx.ui.form.ComboBox();
bL.add(new qx.ui.form.ListItem(this.tr(o)));
bL.add(new qx.ui.form.ListItem(this.tr(l)));
bL.add(new qx.ui.form.ListItem(this.tr(n)));
bT.add(bL,{row:1,column:1});
var bY=new qx.ui.basic.Label(this.tr(V));
bT.add(bY,{row:2,column:0});
var cc=new qx.ui.form.DateField();
cc.setValue(new Date);
bT.add(cc,{row:2,column:1});
var bS=new qx.ui.control.DateChooser;
bT.add(bS,{row:3,column:0,colSpan:2});
var bR=new qx.ui.core.Command(bp);
var bU=new qx.ui.core.Command(L);
var bM=new qx.ui.core.Command(Q);
var bQ=new qx.ui.core.Command(bb);
var cd=new qx.ui.core.Command(bH);
var ce=new qx.ui.core.Command(be);
var cb=new qx.ui.core.Command(bt);
var bN=new qx.ui.core.Command(bo);
var ca=new qx.ui.core.Command(bj);
var bO=new qx.ui.menu.Menu;
bO.add(new qx.ui.menu.Button(this.tr(u),null,bR));
bO.add(new qx.ui.menu.Button(this.tr(F),null,bU));
bO.add(new qx.ui.menu.Separator());
bO.add(new qx.ui.menu.Button(this.tr(o),bF,bM));
bO.add(new qx.ui.menu.Button(this.tr(n),D,bQ));
bO.add(new qx.ui.menu.Button(this.tr(l),bn,cd));
bO.add(new qx.ui.menu.Button(this.tr(G),bG,ce));
bO.add(new qx.ui.menu.Button(this.tr(P),null,cb));
bO.add(new qx.ui.menu.Separator());
bO.add(new qx.ui.menu.Button(this.tr(bf),null,bN));
bO.add(new qx.ui.menu.Button(this.tr(U),null,ca));
var bX=new qx.ui.form.MenuButton(this.tr(R),null,bO);
bT.add(bX,{row:4,column:0,colSpan:2});
return bT;
},__so:function(){var b=new qx.ui.groupbox.GroupBox(this.tr(N),bJ).set({width:0,minWidth:0,allowGrowY:true});
b.setLayout(new qx.ui.layout.Grow());
var c=new qx.ui.basic.Label().set({rich:true,allowGrowX:true,allowGrowY:true});
b.add(c);
var a=[];
a.push("<table id='i18n'><tr><td>");

for(var i=0;i<15;i++){a.push("");
a.push("</td><td>");
a.push("");
a.push("</td></tr><td>");
}a.push("");
a.push("</td><td>");
a.push("");
a.push("</td></tr></table>");
this.updateLocaleInformation=function(){var i=0;
a[(i++*2)+1]=this.tr(w);
a[(i++*2)+1]=qx.locale.Manager.getInstance().getLocale();
a[(i++*2)+1]=this.tr(bK);
a[(i++*2)+1]=qx.locale.Manager.getInstance().getTerritory();
a[(i++*2)+1]=this.tr(X);
a[(i++*2)+1]=qx.locale.Date.getDateFormat(s);
a[(i++*2)+1]=this.tr(H);
a[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(s))).format(new Date());
a[(i++*2)+1]=this.tr(C);
a[(i++*2)+1]=qx.locale.Date.getDateFormat(p);
a[(i++*2)+1]=this.tr(bD);
a[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(p))).format(new Date());
a[(i++*2)+1]=this.tr(f);
a[(i++*2)+1]=qx.locale.Date.getDateFormat(r);
a[(i++*2)+1]=this.tr(bB);
a[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(r))).format(new Date());
a[(i++*2)+1]=this.tr(bi);
a[(i++*2)+1]=qx.locale.Date.getDateFormat(k);
a[(i++*2)+1]=this.tr(bu);
a[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(k))).format(new Date());
a[(i++*2)+1]=this.tr(bI);
a[(i++*2)+1]=qx.locale.Date.getTimeFormat(s);
a[(i++*2)+1]=this.tr(T);
a[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(s))).format(new Date());
a[(i++*2)+1]=this.tr(x);
a[(i++*2)+1]=qx.locale.Date.getTimeFormat(r);
a[(i++*2)+1]=this.tr(J);
a[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(r))).format(new Date());
a[(i++*2)+1]=this.tr(bh);
a[(i++*2)+1]=qx.locale.Date.getDayName(bA,qx.locale.Date.getWeekStart());
a[(i++*2)+1]=this.tr(bc,10000.12);
a[(i++*2)+1]=qx.util.format.NumberFormat.getInstance().format(10000.12);
c.setValue(a.join(""));
};
qx.locale.Manager.getInstance().addListener(bk,this.updateLocaleInformation,this);
this.updateLocaleInformation();
return b;
}}});
})();

});