qx.$$packageData['d5b3b83cf2a9']={"locales":{"C":{"alternateQuotationEnd":"’","alternateQuotationStart":"‘","cldr_am":"AM","cldr_date_format_full":"EEEE, MMMM d, y","cldr_date_format_long":"MMMM d, y","cldr_date_format_medium":"MMM d, y","cldr_date_format_short":"M/d/yy","cldr_date_time_format_EEEd":"d EEE","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_Hms":"H:mm:ss","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, M/d","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E, MMM d","cldr_date_time_format_MMMMEd":"E, MMMM d","cldr_date_time_format_MMMMd":"MMMM d","cldr_date_time_format_MMMd":"MMM d","cldr_date_time_format_Md":"M/d","cldr_date_time_format_d":"d","cldr_date_time_format_hm":"h:mm a","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"M/yyyy","cldr_date_time_format_yMEd":"EEE, M/d/yyyy","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, MMM d, y","cldr_date_time_format_yMMMM":"MMMM y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ y","cldr_day_format_abbreviated_fri":"Fri","cldr_day_format_abbreviated_mon":"Mon","cldr_day_format_abbreviated_sat":"Sat","cldr_day_format_abbreviated_sun":"Sun","cldr_day_format_abbreviated_thu":"Thu","cldr_day_format_abbreviated_tue":"Tue","cldr_day_format_abbreviated_wed":"Wed","cldr_day_format_narrow_fri":"F","cldr_day_format_narrow_mon":"M","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"S","cldr_day_format_narrow_thu":"T","cldr_day_format_narrow_tue":"T","cldr_day_format_narrow_wed":"W","cldr_day_format_wide_fri":"Friday","cldr_day_format_wide_mon":"Monday","cldr_day_format_wide_sat":"Saturday","cldr_day_format_wide_sun":"Sunday","cldr_day_format_wide_thu":"Thursday","cldr_day_format_wide_tue":"Tuesday","cldr_day_format_wide_wed":"Wednesday","cldr_day_stand-alone_abbreviated_fri":"Fri","cldr_day_stand-alone_abbreviated_mon":"Mon","cldr_day_stand-alone_abbreviated_sat":"Sat","cldr_day_stand-alone_abbreviated_sun":"Sun","cldr_day_stand-alone_abbreviated_thu":"Thu","cldr_day_stand-alone_abbreviated_tue":"Tue","cldr_day_stand-alone_abbreviated_wed":"Wed","cldr_day_stand-alone_narrow_fri":"F","cldr_day_stand-alone_narrow_mon":"M","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"S","cldr_day_stand-alone_narrow_thu":"T","cldr_day_stand-alone_narrow_tue":"T","cldr_day_stand-alone_narrow_wed":"W","cldr_day_stand-alone_wide_fri":"Friday","cldr_day_stand-alone_wide_mon":"Monday","cldr_day_stand-alone_wide_sat":"Saturday","cldr_day_stand-alone_wide_sun":"Sunday","cldr_day_stand-alone_wide_thu":"Thursday","cldr_day_stand-alone_wide_tue":"Tuesday","cldr_day_stand-alone_wide_wed":"Wednesday","cldr_month_format_abbreviated_1":"Jan","cldr_month_format_abbreviated_10":"Oct","cldr_month_format_abbreviated_11":"Nov","cldr_month_format_abbreviated_12":"Dec","cldr_month_format_abbreviated_2":"Feb","cldr_month_format_abbreviated_3":"Mar","cldr_month_format_abbreviated_4":"Apr","cldr_month_format_abbreviated_5":"May","cldr_month_format_abbreviated_6":"Jun","cldr_month_format_abbreviated_7":"Jul","cldr_month_format_abbreviated_8":"Aug","cldr_month_format_abbreviated_9":"Sep","cldr_month_format_wide_1":"January","cldr_month_format_wide_10":"October","cldr_month_format_wide_11":"November","cldr_month_format_wide_12":"December","cldr_month_format_wide_2":"February","cldr_month_format_wide_3":"March","cldr_month_format_wide_4":"April","cldr_month_format_wide_5":"May","cldr_month_format_wide_6":"June","cldr_month_format_wide_7":"July","cldr_month_format_wide_8":"August","cldr_month_format_wide_9":"September","cldr_month_stand-alone_narrow_1":"J","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":".","cldr_number_group_separator":",","cldr_number_percent_format":"#,##0%","cldr_pm":"PM","cldr_time_format_full":"h:mm:ss a zzzz","cldr_time_format_long":"h:mm:ss a z","cldr_time_format_medium":"h:mm:ss a","cldr_time_format_short":"h:mm a","quotationEnd":"”","quotationStart":"“"},"de":{"alternateQuotationEnd":"‘","alternateQuotationStart":"‚","cldr_am":"vorm.","cldr_date_format_full":"EEEE, d. MMMM y","cldr_date_format_long":"d. MMMM y","cldr_date_format_medium":"dd.MM.yyyy","cldr_date_format_short":"dd.MM.yy","cldr_date_time_format_EEEd":"d. EEE","cldr_date_time_format_Ed":"E d.","cldr_date_time_format_H":"H","cldr_date_time_format_HHmm":"HH:mm","cldr_date_time_format_HHmmss":"HH:mm:ss","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, d.M.","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E d. MMM","cldr_date_time_format_MMMMEd":"E d. MMMM","cldr_date_time_format_MMMMd":"d. MMMM","cldr_date_time_format_MMMMdd":"dd. MMMM","cldr_date_time_format_MMMd":"d. MMM","cldr_date_time_format_MMd":"d.MM.","cldr_date_time_format_MMdd":"dd.MM.","cldr_date_time_format_Md":"d.M.","cldr_date_time_format_d":"d","cldr_date_time_format_mmss":"mm:ss","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"yyyy-M","cldr_date_time_format_yMEd":"EEE, yyyy-M-d","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, d. MMM y","cldr_date_time_format_yMMMM":"MMMM y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ y","cldr_date_time_format_yyMM":"MM.yy","cldr_date_time_format_yyMMM":"MMM yy","cldr_date_time_format_yyMMdd":"dd.MM.yy","cldr_date_time_format_yyQ":"Q yy","cldr_date_time_format_yyQQQQ":"QQQQ yy","cldr_date_time_format_yyyy":"y","cldr_date_time_format_yyyyMMMM":"MMMM y","cldr_day_format_abbreviated_fri":"Fr.","cldr_day_format_abbreviated_mon":"Mo.","cldr_day_format_abbreviated_sat":"Sa.","cldr_day_format_abbreviated_sun":"So.","cldr_day_format_abbreviated_thu":"Do.","cldr_day_format_abbreviated_tue":"Di.","cldr_day_format_abbreviated_wed":"Mi.","cldr_day_format_narrow_fri":"F","cldr_day_format_narrow_mon":"M","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"S","cldr_day_format_narrow_thu":"D","cldr_day_format_narrow_tue":"D","cldr_day_format_narrow_wed":"M","cldr_day_format_wide_fri":"Freitag","cldr_day_format_wide_mon":"Montag","cldr_day_format_wide_sat":"Samstag","cldr_day_format_wide_sun":"Sonntag","cldr_day_format_wide_thu":"Donnerstag","cldr_day_format_wide_tue":"Dienstag","cldr_day_format_wide_wed":"Mittwoch","cldr_day_stand-alone_abbreviated_fri":"Fr.","cldr_day_stand-alone_abbreviated_mon":"Mo.","cldr_day_stand-alone_abbreviated_sat":"Sa.","cldr_day_stand-alone_abbreviated_sun":"So.","cldr_day_stand-alone_abbreviated_thu":"Do.","cldr_day_stand-alone_abbreviated_tue":"Di.","cldr_day_stand-alone_abbreviated_wed":"Mi.","cldr_day_stand-alone_narrow_fri":"F","cldr_day_stand-alone_narrow_mon":"M","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"S","cldr_day_stand-alone_narrow_thu":"D","cldr_day_stand-alone_narrow_tue":"D","cldr_day_stand-alone_narrow_wed":"M","cldr_day_stand-alone_wide_fri":"Freitag","cldr_day_stand-alone_wide_mon":"Montag","cldr_day_stand-alone_wide_sat":"Samstag","cldr_day_stand-alone_wide_sun":"Sonntag","cldr_day_stand-alone_wide_thu":"Donnerstag","cldr_day_stand-alone_wide_tue":"Dienstag","cldr_day_stand-alone_wide_wed":"Mittwoch","cldr_month_format_abbreviated_1":"Jan","cldr_month_format_abbreviated_10":"Okt","cldr_month_format_abbreviated_11":"Nov","cldr_month_format_abbreviated_12":"Dez","cldr_month_format_abbreviated_2":"Feb","cldr_month_format_abbreviated_3":"Mär","cldr_month_format_abbreviated_4":"Apr","cldr_month_format_abbreviated_5":"Mai","cldr_month_format_abbreviated_6":"Jun","cldr_month_format_abbreviated_7":"Jul","cldr_month_format_abbreviated_8":"Aug","cldr_month_format_abbreviated_9":"Sep","cldr_month_format_wide_1":"Januar","cldr_month_format_wide_10":"Oktober","cldr_month_format_wide_11":"November","cldr_month_format_wide_12":"Dezember","cldr_month_format_wide_2":"Februar","cldr_month_format_wide_3":"März","cldr_month_format_wide_4":"April","cldr_month_format_wide_5":"Mai","cldr_month_format_wide_6":"Juni","cldr_month_format_wide_7":"Juli","cldr_month_format_wide_8":"August","cldr_month_format_wide_9":"September","cldr_month_stand-alone_abbreviated_10":"Okt","cldr_month_stand-alone_abbreviated_11":"Nov","cldr_month_stand-alone_abbreviated_12":"Dez","cldr_month_stand-alone_abbreviated_3":"Mär","cldr_month_stand-alone_abbreviated_7":"Jul","cldr_month_stand-alone_abbreviated_8":"Aug","cldr_month_stand-alone_abbreviated_9":"Sep","cldr_month_stand-alone_narrow_1":"J","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":",","cldr_number_group_separator":".","cldr_number_percent_format":"#,##0 %","cldr_pm":"nachm.","cldr_time_format_full":"HH:mm:ss zzzz","cldr_time_format_long":"HH:mm:ss z","cldr_time_format_medium":"HH:mm:ss","cldr_time_format_short":"HH:mm","quotationEnd":"“","quotationStart":"„"},"de_AT":{"cldr_date_format_full":"EEEE, dd. MMMM y","cldr_date_format_long":"dd. MMMM y","cldr_month_format_abbreviated_1":"Jän","cldr_month_format_wide_1":"Jänner"},"de_DE":{},"en":{"alternateQuotationEnd":"’","alternateQuotationStart":"‘","cldr_am":"AM","cldr_date_format_full":"EEEE, MMMM d, y","cldr_date_format_long":"MMMM d, y","cldr_date_format_medium":"MMM d, y","cldr_date_format_short":"M/d/yy","cldr_date_time_format_EEEd":"d EEE","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_Hms":"H:mm:ss","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, M/d","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E, MMM d","cldr_date_time_format_MMMMEd":"E, MMMM d","cldr_date_time_format_MMMMd":"MMMM d","cldr_date_time_format_MMMd":"MMM d","cldr_date_time_format_Md":"M/d","cldr_date_time_format_d":"d","cldr_date_time_format_hm":"h:mm a","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"M/yyyy","cldr_date_time_format_yMEd":"EEE, M/d/yyyy","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, MMM d, y","cldr_date_time_format_yMMMM":"MMMM y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ y","cldr_day_format_abbreviated_fri":"Fri","cldr_day_format_abbreviated_mon":"Mon","cldr_day_format_abbreviated_sat":"Sat","cldr_day_format_abbreviated_sun":"Sun","cldr_day_format_abbreviated_thu":"Thu","cldr_day_format_abbreviated_tue":"Tue","cldr_day_format_abbreviated_wed":"Wed","cldr_day_format_narrow_fri":"F","cldr_day_format_narrow_mon":"M","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"S","cldr_day_format_narrow_thu":"T","cldr_day_format_narrow_tue":"T","cldr_day_format_narrow_wed":"W","cldr_day_format_wide_fri":"Friday","cldr_day_format_wide_mon":"Monday","cldr_day_format_wide_sat":"Saturday","cldr_day_format_wide_sun":"Sunday","cldr_day_format_wide_thu":"Thursday","cldr_day_format_wide_tue":"Tuesday","cldr_day_format_wide_wed":"Wednesday","cldr_day_stand-alone_abbreviated_fri":"Fri","cldr_day_stand-alone_abbreviated_mon":"Mon","cldr_day_stand-alone_abbreviated_sat":"Sat","cldr_day_stand-alone_abbreviated_sun":"Sun","cldr_day_stand-alone_abbreviated_thu":"Thu","cldr_day_stand-alone_abbreviated_tue":"Tue","cldr_day_stand-alone_abbreviated_wed":"Wed","cldr_day_stand-alone_narrow_fri":"F","cldr_day_stand-alone_narrow_mon":"M","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"S","cldr_day_stand-alone_narrow_thu":"T","cldr_day_stand-alone_narrow_tue":"T","cldr_day_stand-alone_narrow_wed":"W","cldr_day_stand-alone_wide_fri":"Friday","cldr_day_stand-alone_wide_mon":"Monday","cldr_day_stand-alone_wide_sat":"Saturday","cldr_day_stand-alone_wide_sun":"Sunday","cldr_day_stand-alone_wide_thu":"Thursday","cldr_day_stand-alone_wide_tue":"Tuesday","cldr_day_stand-alone_wide_wed":"Wednesday","cldr_month_format_abbreviated_1":"Jan","cldr_month_format_abbreviated_10":"Oct","cldr_month_format_abbreviated_11":"Nov","cldr_month_format_abbreviated_12":"Dec","cldr_month_format_abbreviated_2":"Feb","cldr_month_format_abbreviated_3":"Mar","cldr_month_format_abbreviated_4":"Apr","cldr_month_format_abbreviated_5":"May","cldr_month_format_abbreviated_6":"Jun","cldr_month_format_abbreviated_7":"Jul","cldr_month_format_abbreviated_8":"Aug","cldr_month_format_abbreviated_9":"Sep","cldr_month_format_wide_1":"January","cldr_month_format_wide_10":"October","cldr_month_format_wide_11":"November","cldr_month_format_wide_12":"December","cldr_month_format_wide_2":"February","cldr_month_format_wide_3":"March","cldr_month_format_wide_4":"April","cldr_month_format_wide_5":"May","cldr_month_format_wide_6":"June","cldr_month_format_wide_7":"July","cldr_month_format_wide_8":"August","cldr_month_format_wide_9":"September","cldr_month_stand-alone_narrow_1":"J","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":".","cldr_number_group_separator":",","cldr_number_percent_format":"#,##0%","cldr_pm":"PM","cldr_time_format_full":"h:mm:ss a zzzz","cldr_time_format_long":"h:mm:ss a z","cldr_time_format_medium":"h:mm:ss a","cldr_time_format_short":"h:mm a","quotationEnd":"”","quotationStart":"“"},"en_GB":{"alternateQuotationEnd":"”","alternateQuotationStart":"“","cldr_date_format_full":"EEEE, d MMMM y","cldr_date_format_long":"d MMMM y","cldr_date_format_medium":"d MMM y","cldr_date_format_short":"dd/MM/yyyy","cldr_date_time_format_MEd":"E, d/M","cldr_date_time_format_MMMEd":"E d MMM","cldr_date_time_format_MMMMd":"d MMMM","cldr_date_time_format_MMdd":"dd/MM","cldr_date_time_format_Md":"d/M","cldr_date_time_format_yMEd":"EEE, d/M/yyyy","cldr_date_time_format_yyMMM":"MMM yy","cldr_date_time_format_yyyyMM":"MM/yyyy","cldr_date_time_format_yyyyMMMM":"MMMM y","cldr_time_format_full":"HH:mm:ss zzzz","cldr_time_format_long":"HH:mm:ss z","cldr_time_format_medium":"HH:mm:ss","cldr_time_format_short":"HH:mm","quotationEnd":"’","quotationStart":"‘"},"en_US":{},"es":{"alternateQuotationEnd":"”","alternateQuotationStart":"“","cldr_am":"a.m.","cldr_date_format_full":"EEEE d 'de' MMMM 'de' y","cldr_date_format_long":"d 'de' MMMM 'de' y","cldr_date_format_medium":"dd/MM/yyyy","cldr_date_format_short":"dd/MM/yy","cldr_date_time_format_EEEd":"EEE d","cldr_date_time_format_HHmm":"HH:mm","cldr_date_time_format_HHmmss":"HH:mm:ss","cldr_date_time_format_Hm":"H:mm","cldr_date_time_format_M":"L","cldr_date_time_format_MEd":"E, d-M","cldr_date_time_format_MMM":"LLL","cldr_date_time_format_MMMEd":"E d MMM","cldr_date_time_format_MMMMEd":"E d MMMM","cldr_date_time_format_MMMMd":"d 'de' MMMM","cldr_date_time_format_MMMd":"d MMM","cldr_date_time_format_MMMdd":"dd-MMM","cldr_date_time_format_MMd":"d/MM","cldr_date_time_format_MMdd":"MM/dd","cldr_date_time_format_Md":"d/M","cldr_date_time_format_d":"d","cldr_date_time_format_hhmm":"hh:mm a","cldr_date_time_format_hhmmss":"hh:mm:ss a","cldr_date_time_format_mmss":"mm:ss","cldr_date_time_format_ms":"mm:ss","cldr_date_time_format_y":"y","cldr_date_time_format_yM":"M/yyyy","cldr_date_time_format_yMEd":"EEE d/M/yyyy","cldr_date_time_format_yMMM":"MMM y","cldr_date_time_format_yMMMEd":"EEE, d MMM y","cldr_date_time_format_yMMMM":"MMMM 'de' y","cldr_date_time_format_yQ":"Q yyyy","cldr_date_time_format_yQQQ":"QQQ yyyy","cldr_date_time_format_yyMM":"MM/yy","cldr_date_time_format_yyMMM":"MMM-yy","cldr_date_time_format_yyQ":"Q yy","cldr_date_time_format_yyQQQQ":"QQQQ 'de' yy","cldr_date_time_format_yyyyMM":"MM/yyyy","cldr_day_format_abbreviated_fri":"vie","cldr_day_format_abbreviated_mon":"lun","cldr_day_format_abbreviated_sat":"sáb","cldr_day_format_abbreviated_sun":"dom","cldr_day_format_abbreviated_thu":"jue","cldr_day_format_abbreviated_tue":"mar","cldr_day_format_abbreviated_wed":"mié","cldr_day_format_narrow_fri":"V","cldr_day_format_narrow_mon":"L","cldr_day_format_narrow_sat":"S","cldr_day_format_narrow_sun":"D","cldr_day_format_narrow_thu":"J","cldr_day_format_narrow_tue":"M","cldr_day_format_narrow_wed":"M","cldr_day_format_wide_fri":"viernes","cldr_day_format_wide_mon":"lunes","cldr_day_format_wide_sat":"sábado","cldr_day_format_wide_sun":"domingo","cldr_day_format_wide_thu":"jueves","cldr_day_format_wide_tue":"martes","cldr_day_format_wide_wed":"miércoles","cldr_day_stand-alone_abbreviated_fri":"vie","cldr_day_stand-alone_abbreviated_mon":"lun","cldr_day_stand-alone_abbreviated_sat":"sáb","cldr_day_stand-alone_abbreviated_sun":"dom","cldr_day_stand-alone_abbreviated_thu":"jue","cldr_day_stand-alone_abbreviated_tue":"mar","cldr_day_stand-alone_abbreviated_wed":"mié","cldr_day_stand-alone_narrow_fri":"V","cldr_day_stand-alone_narrow_mon":"L","cldr_day_stand-alone_narrow_sat":"S","cldr_day_stand-alone_narrow_sun":"D","cldr_day_stand-alone_narrow_thu":"J","cldr_day_stand-alone_narrow_tue":"M","cldr_day_stand-alone_narrow_wed":"M","cldr_day_stand-alone_wide_fri":"viernes","cldr_day_stand-alone_wide_mon":"lunes","cldr_day_stand-alone_wide_sat":"sábado","cldr_day_stand-alone_wide_sun":"domingo","cldr_day_stand-alone_wide_thu":"jueves","cldr_day_stand-alone_wide_tue":"martes","cldr_day_stand-alone_wide_wed":"miércoles","cldr_month_format_abbreviated_1":"ene","cldr_month_format_abbreviated_10":"oct","cldr_month_format_abbreviated_11":"nov","cldr_month_format_abbreviated_12":"dic","cldr_month_format_abbreviated_2":"feb","cldr_month_format_abbreviated_3":"mar","cldr_month_format_abbreviated_4":"abr","cldr_month_format_abbreviated_5":"may","cldr_month_format_abbreviated_6":"jun","cldr_month_format_abbreviated_7":"jul","cldr_month_format_abbreviated_8":"ago","cldr_month_format_abbreviated_9":"sep","cldr_month_format_wide_1":"enero","cldr_month_format_wide_10":"octubre","cldr_month_format_wide_11":"noviembre","cldr_month_format_wide_12":"diciembre","cldr_month_format_wide_2":"febrero","cldr_month_format_wide_3":"marzo","cldr_month_format_wide_4":"abril","cldr_month_format_wide_5":"mayo","cldr_month_format_wide_6":"junio","cldr_month_format_wide_7":"julio","cldr_month_format_wide_8":"agosto","cldr_month_format_wide_9":"septiembre","cldr_month_stand-alone_narrow_1":"E","cldr_month_stand-alone_narrow_10":"O","cldr_month_stand-alone_narrow_11":"N","cldr_month_stand-alone_narrow_12":"D","cldr_month_stand-alone_narrow_2":"F","cldr_month_stand-alone_narrow_3":"M","cldr_month_stand-alone_narrow_4":"A","cldr_month_stand-alone_narrow_5":"M","cldr_month_stand-alone_narrow_6":"J","cldr_month_stand-alone_narrow_7":"J","cldr_month_stand-alone_narrow_8":"A","cldr_month_stand-alone_narrow_9":"S","cldr_number_decimal_separator":",","cldr_number_group_separator":".","cldr_number_percent_format":"#,##0%","cldr_pm":"p.m.","cldr_time_format_full":"HH:mm:ss zzzz","cldr_time_format_long":"HH:mm:ss z","cldr_time_format_medium":"HH:mm:ss","cldr_time_format_short":"HH:mm","quotationEnd":"’","quotationStart":"‘"},"es_ES":{},"es_MX":{"cldr_number_decimal_separator":".","cldr_number_group_separator":","}},"resources":{},"translations":{}};

qx.Part.$$notifyLoad("d5b3b83cf2a9", function() {
(function(){var r="move",q="Boolean",p="__ou",o="mouseup",n="mousedown",m="losecapture",l="__ov",k="qx.ui.core.MMovable",j="mousemove",i="maximized",h="move-frame";
qx.Mixin.define(k,{properties:{movable:{check:q,init:true},useMoveFrame:{check:q,init:false}},members:{__ou:null,__ov:null,__ow:null,__ox:null,__oy:null,__oz:null,__oA:null,__oB:false,__oC:null,__oD:0,_activateMoveHandle:function(z){if(this.__ou){throw new Error("The move handle could not be redefined!");
}this.__ou=z;
z.addListener(n,this._onMoveMouseDown,this);
z.addListener(o,this._onMoveMouseUp,this);
z.addListener(j,this._onMoveMouseMove,this);
z.addListener(m,this.__oH,this);
},__oE:function(){var c=this.__ov;

if(!c){c=this.__ov=new qx.ui.core.Widget();
c.setAppearance(h);
c.exclude();
qx.core.Init.getApplication().getRoot().add(c);
}return c;
},__oF:function(){var location=this.getContainerLocation();
var b=this.getBounds();
var a=this.__oE();
a.setUserBounds(location.left,location.top,b.width,b.height);
a.show();
a.setZIndex(this.getZIndex()+1);
},__oG:function(e){var t=this.__ow;
var w=Math.max(t.left,Math.min(t.right,e.getDocumentLeft()));
var v=Math.max(t.top,Math.min(t.bottom,e.getDocumentTop()));
var s=this.__ox+w;
var u=this.__oy+v;
return {viewportLeft:s,viewportTop:u,parentLeft:s-this.__oz,parentTop:u-this.__oA};
},_onMoveMouseDown:function(e){if(!this.getMovable()||this.hasState(i)){return;
}var parent=this.getLayoutParent();
var f=parent.getContentLocation();
var g=parent.getBounds();
if(qx.Class.implementsInterface(parent,qx.ui.window.IDesktop)){if(!parent.isContentBlocked()){this.__oB=true;
this.__oC=parent.getBlockerColor();
this.__oD=parent.getBlockerOpacity();
parent.setBlockerColor(null);
parent.setBlockerOpacity(1);
parent.blockContent(this.getZIndex()-1);
}}this.__ow={left:f.left,top:f.top,right:f.left+g.width,bottom:f.top+g.height};
var d=this.getContainerLocation();
this.__oz=f.left;
this.__oA=f.top;
this.__ox=d.left-e.getDocumentLeft();
this.__oy=d.top-e.getDocumentTop();
this.addState(r);
this.__ou.capture();
if(this.getUseMoveFrame()){this.__oF();
}e.stop();
},_onMoveMouseMove:function(e){if(!this.hasState(r)){return;
}var x=this.__oG(e);

if(this.getUseMoveFrame()){this.__oE().setDomPosition(x.viewportLeft,x.viewportTop);
}else{this.setDomPosition(x.parentLeft,x.parentTop);
}e.stopPropagation();
},_onMoveMouseUp:function(e){if(!this.hasState(r)){return;
}this.removeState(r);
var parent=this.getLayoutParent();

if(qx.Class.implementsInterface(parent,qx.ui.window.IDesktop)){if(this.__oB){parent.unblockContent();
parent.setBlockerColor(this.__oC);
parent.setBlockerOpacity(this.__oD);
this.__oC=null;
this.__oD=0;
}}this.__ou.releaseCapture();
var y=this.__oG(e);
this.setLayoutProperties({left:y.parentLeft,top:y.parentTop});
if(this.getUseMoveFrame()){this.__oE().exclude();
}e.stopPropagation();
},__oH:function(e){if(!this.hasState(r)){return;
}this.removeState(r);
if(this.getUseMoveFrame()){this.__oE().exclude();
}}},destruct:function(){this._disposeObjects(l,p);
this.__ow=null;
}});
})();
(function(){var E="Boolean",D="resize",C="mousedown",B="w-resize",A="sw-resize",z="n-resize",y="resizableRight",x="ne-resize",w="se-resize",v="Integer",T="e-resize",S="resizableLeft",R="mousemove",Q="move",P="shorthand",O="maximized",N="nw-resize",M="mouseout",L="qx.ui.core.MResizable",K="mouseup",I="losecapture",J="resize-frame",G="resizableBottom",H="s-resize",F="resizableTop";
qx.Mixin.define(L,{construct:function(){this.addListener(C,this.__op,this,true);
this.addListener(K,this.__oq,this);
this.addListener(R,this.__os,this);
this.addListener(M,this.__ot,this);
this.addListener(I,this.__or,this);
var V=this.getContainerElement().getDomElement();

if(V==null){V=window;
}this.__oe=qx.event.Registration.getManager(V).getHandler(qx.event.handler.DragDrop);
},properties:{resizableTop:{check:E,init:true},resizableRight:{check:E,init:true},resizableBottom:{check:E,init:true},resizableLeft:{check:E,init:true},resizable:{group:[F,y,G,S],mode:P},resizeSensitivity:{check:v,init:5},useResizeFrame:{check:E,init:true}},members:{__oe:null,__of:null,__og:null,__oh:null,__oi:null,__oj:null,RESIZE_TOP:1,RESIZE_BOTTOM:2,RESIZE_LEFT:4,RESIZE_RIGHT:8,__ok:function(){var U=this.__of;

if(!U){U=this.__of=new qx.ui.core.Widget();
U.setAppearance(J);
U.exclude();
qx.core.Init.getApplication().getRoot().add(U);
}return U;
},__ol:function(){var n=this.__oj;
var m=this.__ok();
m.setUserBounds(n.left,n.top,n.width,n.height);
m.show();
m.setZIndex(this.getZIndex()+1);
},__om:function(e){var p=this.__og;
var q=this.getSizeHint();
var s=this.__oj;
var o=s.width;
var r=s.height;
var u=s.left;
var top=s.top;
var t;

if((p&this.RESIZE_TOP)||(p&this.RESIZE_BOTTOM)){t=e.getDocumentTop()-this.__oi;

if(p&this.RESIZE_TOP){r-=t;
}else{r+=t;
}
if(r<q.minHeight){r=q.minHeight;
}else if(r>q.maxHeight){r=q.maxHeight;
}
if(p&this.RESIZE_TOP){top+=s.height-r;
}}
if((p&this.RESIZE_LEFT)||(p&this.RESIZE_RIGHT)){t=e.getDocumentLeft()-this.__oh;

if(p&this.RESIZE_LEFT){o-=t;
}else{o+=t;
}
if(o<q.minWidth){o=q.minWidth;
}else if(o>q.maxWidth){o=q.maxWidth;
}
if(p&this.RESIZE_LEFT){u+=s.width-o;
}}return {viewportLeft:u,viewportTop:top,parentLeft:s.bounds.left+u-s.left,parentTop:s.bounds.top+top-s.top,width:o,height:r};
},__on:{1:z,2:H,4:B,8:T,5:N,6:A,9:x,10:w},__oo:function(e){var c=this.getContentLocation();
var a=this.getResizeSensitivity();
var f=e.getDocumentLeft();
var d=e.getDocumentTop();
var b=0;

if(this.getResizableTop()&&Math.abs(c.top-d)<a){b+=this.RESIZE_TOP;
}else if(this.getResizableBottom()&&Math.abs(c.bottom-d)<a){b+=this.RESIZE_BOTTOM;
}
if(this.getResizableLeft()&&Math.abs(c.left-f)<a){b+=this.RESIZE_LEFT;
}else if(this.getResizableRight()&&Math.abs(c.right-f)<a){b+=this.RESIZE_RIGHT;
}this.__og=b;
},__op:function(e){if(!this.__og){return;
}this.addState(D);
this.__oh=e.getDocumentLeft();
this.__oi=e.getDocumentTop();
var location=this.getContainerLocation();
var W=this.getBounds();
this.__oj={top:location.top,left:location.left,width:W.width,height:W.height,bounds:qx.lang.Object.clone(W)};
if(this.getUseResizeFrame()){this.__ol();
}this.capture();
e.stop();
},__oq:function(e){if(!this.hasState(D)){return;
}if(this.getUseResizeFrame()){this.__ok().exclude();
}var g=this.__om(e);
this.setWidth(g.width);
this.setHeight(g.height);
if(this.getResizableLeft()||this.getResizableTop()){this.setLayoutProperties({left:g.parentLeft,top:g.parentTop});
}this.__og=0;
this.removeState(D);
this.resetCursor();
this.getApplicationRoot().resetGlobalCursor();
this.releaseCapture();
e.stopPropagation();
},__or:function(e){if(!this.__og){return;
}this.resetCursor();
this.getApplicationRoot().resetGlobalCursor();
this.removeState(Q);
if(this.getUseResizeFrame()){this.__ok().exclude();
}},__os:function(e){if(this.hasState(D)){var k=this.__om(e);
if(this.getUseResizeFrame()){var i=this.__ok();
i.setUserBounds(k.viewportLeft,k.viewportTop,k.width,k.height);
}else{this.setWidth(k.width);
this.setHeight(k.height);
if(this.getResizableLeft()||this.getResizableTop()){this.setLayoutProperties({left:k.parentLeft,top:k.parentTop});
}}e.stopPropagation();
}else if(!this.hasState(O)&&!this.__oe.isSessionActive()){this.__oo(e);
var l=this.__og;
var j=this.getApplicationRoot();

if(l){var h=this.__on[l];
this.setCursor(h);
j.setGlobalCursor(h);
}else if(this.getCursor()){this.resetCursor();
j.resetGlobalCursor();
}}},__ot:function(e){if(this.getCursor()&&!this.hasState(D)){this.resetCursor();
this.getApplicationRoot().resetGlobalCursor();
}}},destruct:function(){if(this.__of!=null&&!qx.core.ObjectRegistry.inShutDown){this.__of.destroy();
this.__of=null;
}this.__oe=null;
}});
})();
(function(){var c="qx.ui.window.IWindowManager";
qx.Interface.define(c,{members:{setDesktop:function(f){this.assertInterface(f,qx.ui.window.IDesktop);
},changeActiveWindow:function(d,e){},updateStack:function(){},bringToFront:function(b){this.assertInstance(b,qx.ui.window.Window);
},sendToBack:function(a){this.assertInstance(a,qx.ui.window.Window);
}}});
})();
(function(){var b="__oI",a="qx.ui.window.Manager";
qx.Class.define(a,{extend:qx.core.Object,implement:qx.ui.window.IWindowManager,members:{__oI:null,setDesktop:function(c){this.__oI=c;
this.updateStack();
},getDesktop:function(){return this.__oI;
},changeActiveWindow:function(d,e){if(d){this.bringToFront(d);
}},_minZIndex:1e5,updateStack:function(){qx.ui.core.queue.Widget.add(this);
},syncWidget:function(){this.__oI.forceUnblockContent();
var k=this.__oI.getWindows();
var o=this._minZIndex-1;
var n=false;
var m,j=null;

for(var i=0,l=k.length;i<l;i++){m=k[i];

if(!m.isVisible()){continue;
}o+=2;
m.setZIndex(o);
if(m.getModal()){this.__oI.blockContent(o-1);
}n=n||m.isActive();
j=m;
}
if(!n){this.__oI.setActiveWindow(j);
}},bringToFront:function(f){var g=this.__oI.getWindows();
var h=qx.lang.Array.remove(g,f);

if(h){g.push(f);
this.updateStack();
}},sendToBack:function(p){var q=this.__oI.getWindows();
var r=qx.lang.Array.remove(q,p);

if(r){q.unshift(p);
this.updateStack();
}}},destruct:function(){this._disposeObjects(b);
}});
})();
(function(){var k="Boolean",j="qx.event.type.Event",i="captionbar",h="_applyCaptionBarChange",g="maximize-button",f="restore-button",d="minimize-button",c="close-button",b="title",a="icon",P="maximized",O="execute",N="pane",M="statusbar-text",L="statusbar",K="String",J="normal",I="active",H="beforeClose",G="beforeMinimize",r="mousedown",s="changeStatus",p="changeIcon",q="excluded",n="dblclick",o="_applyActive",l="beforeRestore",m="minimize",t="changeModal",u="_applyShowStatusbar",y="_applyStatus",x="qx.ui.window.Window",A="changeCaption",z="focusout",C="beforeMaximize",B="maximize",w="restore",F="window",E="close",D="changeActive",v="minimized";
qx.Class.define(x,{extend:qx.ui.core.Widget,include:[qx.ui.core.MRemoteChildrenHandling,qx.ui.core.MRemoteLayoutHandling,qx.ui.core.MResizable,qx.ui.core.MMovable,qx.ui.core.MContentPadding],construct:function(br,bs){qx.ui.core.Widget.call(this);
this._setLayout(new qx.ui.layout.VBox());
this._createChildControl(i);
this._createChildControl(N);
if(bs!=null){this.setIcon(bs);
}
if(br!=null){this.setCaption(br);
}this._updateCaptionBar();
this.addListener(r,this._onWindowMouseDown,this,true);
this.addListener(z,this._onWindowFocusOut,this);
qx.core.Init.getApplication().getRoot().add(this);
this.initVisibility();
qx.ui.core.FocusHandler.getInstance().addRoot(this);
{};
},statics:{DEFAULT_MANAGER_CLASS:qx.ui.window.Manager},events:{"beforeClose":j,"close":j,"beforeMinimize":j,"minimize":j,"beforeMaximize":j,"maximize":j,"beforeRestore":j,"restore":j},properties:{appearance:{refine:true,init:F},visibility:{refine:true,init:q},focusable:{refine:true,init:true},active:{check:k,init:false,apply:o,event:D},modal:{check:k,init:false,event:t},caption:{apply:h,event:A,nullable:true},icon:{check:K,nullable:true,apply:h,event:p,themeable:true},status:{check:K,nullable:true,apply:y,event:s},showClose:{check:k,init:true,apply:h,themeable:true},showMaximize:{check:k,init:true,apply:h,themeable:true},showMinimize:{check:k,init:true,apply:h,themeable:true},allowClose:{check:k,init:true,apply:h},allowMaximize:{check:k,init:true,apply:h},allowMinimize:{check:k,init:true,apply:h},showStatusbar:{check:k,init:false,apply:u}},members:{__oJ:null,__oK:null,getChildrenContainer:function(){return this.getChildControl(N);
},_forwardStates:{active:true,maximized:true},setLayoutParent:function(parent){{};
qx.ui.core.Widget.prototype.setLayoutParent.call(this,parent);
},_createChildControlImpl:function(bn){var bo;

switch(bn){case L:bo=new qx.ui.container.Composite(new qx.ui.layout.HBox());
this._add(bo);
bo.add(this.getChildControl(M));
break;
case M:bo=new qx.ui.basic.Label();
bo.setValue(this.getStatus());
break;
case N:bo=new qx.ui.container.Composite();
this._add(bo,{flex:1});
break;
case i:var bq=new qx.ui.layout.Grid();
bq.setRowFlex(0,1);
bq.setColumnFlex(1,1);
bo=new qx.ui.container.Composite(bq);
this._add(bo);
bo.addListener(n,this._onCaptionMouseDblClick,this);
this._activateMoveHandle(bo);
break;
case a:bo=new qx.ui.basic.Image(this.getIcon());
this.getChildControl(i).add(bo,{row:0,column:0});
break;
case b:bo=new qx.ui.basic.Label(this.getCaption());
bo.setWidth(0);
bo.setAllowGrowX(true);
var bp=this.getChildControl(i);
bp.add(bo,{row:0,column:1});
break;
case d:bo=new qx.ui.form.Button();
bo.setFocusable(false);
bo.addListener(O,this._onMinimizeButtonClick,this);
this.getChildControl(i).add(bo,{row:0,column:2});
break;
case f:bo=new qx.ui.form.Button();
bo.setFocusable(false);
bo.addListener(O,this._onRestoreButtonClick,this);
this.getChildControl(i).add(bo,{row:0,column:3});
break;
case g:bo=new qx.ui.form.Button();
bo.setFocusable(false);
bo.addListener(O,this._onMaximizeButtonClick,this);
this.getChildControl(i).add(bo,{row:0,column:4});
break;
case c:bo=new qx.ui.form.Button();
bo.setFocusable(false);
bo.addListener(O,this._onCloseButtonClick,this);
this.getChildControl(i).add(bo,{row:0,column:6});
break;
}return bo||qx.ui.core.Widget.prototype._createChildControlImpl.call(this,bn);
},_updateCaptionBar:function(){var bl;
var bm=this.getIcon();

if(bm){this.getChildControl(a).setSource(bm);
this._showChildControl(a);
}else{this._excludeChildControl(a);
}var bk=this.getCaption();

if(bk){this.getChildControl(b).setValue(bk);
this._showChildControl(b);
}else{this._excludeChildControl(b);
}
if(this.getShowMinimize()){this._showChildControl(d);
bl=this.getChildControl(d);
this.getAllowMinimize()?bl.resetEnabled():bl.setEnabled(false);
}else{this._excludeChildControl(d);
}
if(this.getShowMaximize()){if(this.isMaximized()){this._showChildControl(f);
this._excludeChildControl(g);
}else{this._showChildControl(g);
this._excludeChildControl(f);
}bl=this.getChildControl(g);
this.getAllowMaximize()?bl.resetEnabled():bl.setEnabled(false);
}else{this._excludeChildControl(g);
this._excludeChildControl(f);
}
if(this.getShowClose()){this._showChildControl(c);
bl=this.getChildControl(c);
this.getAllowClose()?bl.resetEnabled():bl.setEnabled(false);
}else{this._excludeChildControl(c);
}},close:function(){if(!this.isVisible()){return;
}
if(this.fireNonBubblingEvent(H,qx.event.type.Event,[false,true])){this.hide();
this.fireEvent(E);
}},open:function(){this.show();
this.setActive(true);
this.focus();
},center:function(){var parent=this.getLayoutParent();

if(parent){var bg=parent.getBounds();

if(bg){var bh=this.getSizeHint();
var bf=Math.round((bg.width-bh.width)/2);
var top=Math.round((bg.height-bh.height)/2);

if(top<0){top=0;
}this.moveTo(bf,top);
return;
}}{};
},maximize:function(){if(this.isMaximized()){return;
}var parent=this.getLayoutParent();

if(parent!=null&&parent.supportsMaximize()){if(this.fireNonBubblingEvent(C,qx.event.type.Event,[false,true])){if(!this.isVisible()){this.open();
}var V=this.getLayoutProperties();
this.__oK=V.left===undefined?0:V.left;
this.__oJ=V.top===undefined?0:V.top;
this.setLayoutProperties({left:null,top:null,edge:0});
this.addState(P);
this._updateCaptionBar();
this.fireEvent(B);
}}},minimize:function(){if(!this.isVisible()){return;
}
if(this.fireNonBubblingEvent(G,qx.event.type.Event,[false,true])){var T=this.getLayoutProperties();
this.__oK=T.left===undefined?0:T.left;
this.__oJ=T.top===undefined?0:T.top;
this.removeState(P);
this.hide();
this.fireEvent(m);
}},restore:function(){if(this.getMode()===J){return;
}
if(this.fireNonBubblingEvent(l,qx.event.type.Event,[false,true])){if(!this.isVisible()){this.open();
}var W=this.__oK;
var top=this.__oJ;
this.setLayoutProperties({edge:null,left:W,top:top});
this.removeState(P);
this._updateCaptionBar();
this.fireEvent(w);
}},moveTo:function(Q,top){if(this.isMaximized()){return;
}this.setLayoutProperties({left:Q,top:top});
},isMaximized:function(){return this.hasState(P);
},getMode:function(){if(!this.isVisible()){return v;
}else{if(this.isMaximized()){return P;
}else{return J;
}}},_applyActive:function(bt,bu){if(bu){this.removeState(I);
}else{this.addState(I);
}},_getContentPaddingTarget:function(){return this.getChildControl(N);
},_applyShowStatusbar:function(bi,bj){if(bi){this._showChildControl(L);
}else{this._excludeChildControl(L);
}},_applyCaptionBarChange:function(bd,be){this._updateCaptionBar();
},_applyStatus:function(ba,bb){var bc=this.getChildControl(M,true);

if(bc){bc.setValue(ba);
}},_applyCaption:function(X,Y){{};
this.getChildControl(b).setValue(X);
},_applyIcon:function(R,S){{};
this.getChildControl(a).setSource(R);
},_onWindowEventStop:function(e){e.stopPropagation();
},_onWindowMouseDown:function(e){this.setActive(true);
},_onWindowFocusOut:function(e){if(this.getModal()){return;
}var U=e.getRelatedTarget();

if(U!=null&&!qx.ui.core.Widget.contains(this,U)){this.setActive(false);
}},_onCaptionMouseDblClick:function(e){if(this.getAllowMaximize()){this.isMaximized()?this.restore():this.maximize();
}},_onMinimizeButtonClick:function(e){this.minimize();
this.getChildControl(d).reset();
},_onRestoreButtonClick:function(e){this.restore();
this.getChildControl(f).reset();
},_onMaximizeButtonClick:function(e){this.maximize();
this.getChildControl(g).reset();
},_onCloseButtonClick:function(e){this.close();
this.getChildControl(c).reset();
}}});
})();
(function(){var b="qx.ui.window.IDesktop";
qx.Interface.define(b,{members:{setWindowManager:function(a){this.assertInterface(a,qx.ui.window.IWindowManager);
},getWindows:function(){},supportsMaximize:function(){},blockContent:function(c){this.assertInteger(c);
},unblockContent:function(){},isContentBlocked:function(){}}});
})();
(function(){var a="qx.ui.window.Desktop";
qx.Class.define(a,{extend:qx.ui.core.Widget,include:[qx.ui.core.MChildrenHandling,qx.ui.window.MDesktop,qx.ui.core.MBlocker],implement:qx.ui.window.IDesktop,construct:function(b){qx.ui.core.Widget.call(this);
this.getContentElement().disableScrolling();
this._setLayout(new qx.ui.layout.Canvas());
this.setWindowManager(b);
}});
})();
(function(){var c="showcase.page.AbstractDesktopContent";
qx.Class.define(c,{extend:showcase.AbstractContent,construct:function(d){showcase.AbstractContent.call(this,d);
this.setView(this._createView());
},members:{_createView:function(){var b=new qx.ui.window.Desktop(new qx.ui.window.Manager());
var a=new qx.ui.window.Window();
a.set({showClose:false,showMinimize:false,contentPadding:0});
this._addWindowContent(a);
b.add(a);
a.moveTo(30,20);
a.open();
return b;
},_addWindowContent:function(e){throw new Error("Abstract method call!");
}}});
})();
(function(){var h="checked",g="menu-checkbox",f="Boolean",d="_applyValue",c="changeValue",b="qx.ui.menu.CheckBox",a="execute";
qx.Class.define(b,{extend:qx.ui.menu.AbstractButton,implement:[qx.ui.form.IBooleanForm],construct:function(i,j){qx.ui.menu.AbstractButton.call(this);
if(i!=null){if(i.translate){this.setLabel(i.translate());
}else{this.setLabel(i);
}}
if(j!=null){this.setMenu(j);
}this.addListener(a,this._onExecute,this);
},properties:{appearance:{refine:true,init:g},value:{check:f,init:false,apply:d,event:c,nullable:true}},members:{_applyValue:function(k,l){k?this.addState(h):this.removeState(h);
},_onExecute:function(e){this.toggleValue();
},_onMouseUp:function(e){if(e.isLeftPressed()){this.execute();
}qx.ui.menu.Manager.getInstance().hideAll();
},_onKeyPress:function(e){this.execute();
}}});
})();

});