qx.$$packageData['2b1a1bde23db']={"resources":{}};
(function(){var s="pressed",r="abandoned",q="hovered",p="checked",o="Space",n="Enter",m="mouseup",l="mousedown",k="Boolean",j="_applyValue",c="mouseover",i="mouseout",g="qx.ui.form.ToggleButton",b="keydown",a="changeValue",f="button",d="keyup",h="execute";
qx.Class.define(g,{extend:qx.ui.basic.Atom,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IBooleanForm,qx.ui.form.IExecutable],construct:function(t,u){arguments.callee.base.call(this,t,u);
this.addListener(c,this._onMouseOver);
this.addListener(i,this._onMouseOut);
this.addListener(l,this._onMouseDown);
this.addListener(m,this._onMouseUp);
this.addListener(b,this._onKeyDown);
this.addListener(d,this._onKeyUp);
this.addListener(h,this._onExecute,this);
},properties:{appearance:{refine:true,init:f},focusable:{refine:true,init:true},value:{check:k,nullable:true,event:a,apply:j,init:false}},members:{_applyValue:function(v,w){v?this.addState(p):this.removeState(p);
},_onExecute:function(e){this.toggleValue();
},_onMouseOver:function(e){if(e.getTarget()!==this){return;
}this.addState(q);

if(this.hasState(r)){this.removeState(r);
this.addState(s);
}},_onMouseOut:function(e){if(e.getTarget()!==this){return;
}this.removeState(q);

if(this.hasState(s)){if(!this.getValue()){this.removeState(s);
}this.addState(r);
}},_onMouseDown:function(e){if(!e.isLeftPressed()){return;
}this.capture();
this.removeState(r);
this.addState(s);
e.stopPropagation();
},_onMouseUp:function(e){this.releaseCapture();

if(this.hasState(r)){this.removeState(r);
}else if(this.hasState(s)){this.execute();
}this.removeState(s);
e.stopPropagation();
},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case n:case o:this.removeState(r);
this.addState(s);
e.stopPropagation();
}},_onKeyUp:function(e){if(!this.hasState(s)){return;
}
switch(e.getKeyIdentifier()){case n:case o:this.removeState(r);
this.execute();
this.removeState(s);
e.stopPropagation();
}}}});
})();
(function(){var b="checkbox",a="qx.ui.form.CheckBox";
qx.Class.define(a,{extend:qx.ui.form.ToggleButton,include:[qx.ui.form.MForm,qx.ui.form.MModelProperty],implement:[qx.ui.form.IForm,qx.ui.form.IModel],construct:function(c){{};
arguments.callee.base.call(this,c);
this.setValue(false);
},properties:{appearance:{refine:true,init:b},allowGrowX:{refine:true,init:false}}});
})();
(function(){var f="textarea",e="qx.ui.form.TextArea",d="_applyWrap",c="Boolean";
qx.Class.define(e,{extend:qx.ui.form.AbstractField,construct:function(h){arguments.callee.base.call(this,h);
this.initWrap();
},properties:{wrap:{check:c,init:true,apply:d},appearance:{refine:true,init:f}},members:{_createInputElement:function(){return new qx.html.Input(f);
},_applyWrap:function(a,b){this.getContentElement().setWrap(a);
},_getContentHint:function(){var g=arguments.callee.base.call(this);
g.height=g.height*4;
g.width=this._getTextSize().width*20;
return g;
}}});
})();
(function(){var k="value",j="placeholder",h="CheckBox:",g="TextArea:",f="Boolean",e="RepeatButton:",d="execute",c="Text",b="ToggleButton",a="password",M="RadioButton 3",L="showcase.page.form.Content",K="Button:",J="ComboBox:",I="ToggleButton:",H="RadioButton",G="0",F="MenuButton:",E="Button",D="PasswordField:",r="SplitButton",s="Buttons",p="RadioButtons:",q="dd.mm.YYYY",n="List:",o="SplitButton:",l="RadioButton 1",m="Spinner:",t="Selection",u="DateField:",x="RadioButton 2",w="Number",z="CheckBox",y="SelectBox:",B="MenuButton",A="Slider:",v="TextField:",C="RadioButtonGroup:";
qx.Class.define(L,{extend:showcase.AbstractContent,construct:function(bs){arguments.callee.base.call(this,bs);
this.setView(this._createView());
},members:{_createView:function(){var bd=new qx.ui.layout.Grid(20,5);
bd.setColumnFlex(0,1);
bd.setColumnFlex(1,1);
var bn=new qx.ui.container.Composite(bd);
bn.setPadding(10);
var U=1;
var N=new qx.ui.groupbox.GroupBox(c);
N.setLayout(new qx.ui.layout.Grid(8,8));
N.setWidth(290);
bn.add(N,{row:0,column:0});
var bm=new qx.ui.form.TextField();
bm.setPlaceholder(j);
bm.setTabIndex(U++);
var W=new qx.ui.basic.Label(v);
W.setBuddy(bm);
N.add(W,{row:0,column:0});
N.add(bm,{row:0,column:1});
var T=new qx.ui.form.PasswordField();
T.setTabIndex(U++);
T.setPlaceholder(a);
W=new qx.ui.basic.Label(D);
W.setBuddy(T);
N.add(W,{row:1,column:0});
N.add(T,{row:1,column:1});
var O=new qx.ui.form.TextArea();
O.setTabIndex(U++);
O.setPlaceholder(j);
W=new qx.ui.basic.Label(g);
W.setBuddy(O);
N.add(W,{row:2,column:0});
N.add(O,{row:2,column:1});
var P=new qx.ui.form.ComboBox();
P.setTabIndex(U++);
P.setPlaceholder(j);
W=new qx.ui.basic.Label(J);
W.setBuddy(P);
N.add(W,{row:3,column:0});
N.add(P,{row:3,column:1});
this.__GV(P);
var bf=new qx.ui.form.DateField();
bf.setTabIndex(U++);
bf.setPlaceholder(q);
W=new qx.ui.basic.Label(u);
W.setBuddy(bf);
N.add(W,{row:4,column:0});
N.add(bf,{row:4,column:1});
var V=new qx.ui.groupbox.GroupBox(t);
V.setLayout(new qx.ui.layout.Grid(8,8));
V.setWidth(290);
bn.add(V,{row:1,column:0,rowSpan:2});
var bg=new qx.ui.form.SelectBox();
bg.setTabIndex(U++);
W=new qx.ui.basic.Label(y);
W.setBuddy(bg);
V.add(W,{row:0,column:0});
V.add(bg,{row:0,column:1});
this.__GV(bg);
var bl=new qx.ui.form.List();
bl.setTabIndex(U++);
bl.setHeight(60);
bl.setWidth(155);
W=new qx.ui.basic.Label(n);
W.setBuddy(bl);
V.add(W,{row:1,column:0});
V.add(bl,{row:1,column:1});
this.__GV(bl);
var be=new qx.ui.form.RadioButtonGroup();
be.add(new qx.ui.form.RadioButton(l).set({tabIndex:U++}));
be.add(new qx.ui.form.RadioButton(x).set({tabIndex:U++}));
be.add(new qx.ui.form.RadioButton(M).set({tabIndex:U++}));
W=new qx.ui.basic.Label(C);
W.setBuddy(be);
V.add(W,{row:2,column:0});
V.add(be,{row:2,column:1});
var bj=new qx.ui.groupbox.GroupBox(s);
bj.setLayout(new qx.ui.layout.Grid(8,8));
bj.setWidth(250);
bn.add(bj,{row:0,column:1});
var bk=new qx.ui.form.Button(E).set({tabIndex:U++});
W=new qx.ui.basic.Label(K);
W.setBuddy(bk);
bj.add(W,{row:0,column:0});
bj.add(bk,{row:0,column:1});
var R=new qx.ui.form.ToggleButton(b).set({tabIndex:U++});
W=new qx.ui.basic.Label(I);
W.setBuddy(R);
bj.add(W,{row:1,column:0});
bj.add(R,{row:1,column:1});
var ba=new qx.ui.form.RepeatButton(G).set({tabIndex:U++});
W=new qx.ui.basic.Label(e);
W.setBuddy(ba);
bj.add(W,{row:2,column:0});
bj.add(ba,{row:2,column:1});
var bb=new qx.ui.form.MenuButton(B,null,this.__GW()).set({tabIndex:U++});
W=new qx.ui.basic.Label(F);
W.setBuddy(bb);
bj.add(W,{row:3,column:0});
bj.add(bb,{row:3,column:1});
var S=new qx.ui.form.SplitButton(r,null,this.__GX()).set({tabIndex:U++});
W=new qx.ui.basic.Label(o);
W.setBuddy(S);
bj.add(W,{row:4,column:0});
bj.add(S,{row:4,column:1});
ba.addListener(d,function(){var bA=parseInt(ba.getLabel())+1;
ba.setLabel(bA.toString());
});
var Q=new qx.ui.groupbox.GroupBox(f);
Q.setLayout(new qx.ui.layout.Grid(8,8));
Q.setWidth(250);
bn.add(Q,{row:1,column:1});
var bh=new qx.ui.form.CheckBox(z).set({tabIndex:U++});
W=new qx.ui.basic.Label(h);
W.setBuddy(bh);
Q.add(W,{row:0,column:0});
Q.add(bh,{row:0,column:1});
var Y=new qx.ui.form.RadioButton(H).set({tabIndex:U++});
Q.add(new qx.ui.basic.Label(p),{row:1,column:0});
Q.add(Y,{row:1,column:1});
var bi=new qx.ui.groupbox.GroupBox(w);
bi.setLayout(new qx.ui.layout.Grid(8,8));
bi.setWidth(250);
bn.add(bi,{row:2,column:1});
var X=new qx.ui.form.Spinner(0,50,100).set({tabIndex:U++});
W=new qx.ui.basic.Label(m);
W.setBuddy(X);
bi.add(W,{row:0,column:0});
bi.add(X,{row:0,column:1});
var bc=new qx.ui.form.Slider().set({tabIndex:U++});
bc.setWidth(130);
W=new qx.ui.basic.Label(A);
W.setBuddy(bc);
bi.add(W,{row:1,column:0});
bi.add(bc,{row:1,column:1});
bc.bind(k,X,k);
X.bind(k,bc,k);
return bn;
},__GV:function(by){for(var i=0;i<10;i++){var bz=new qx.ui.form.ListItem("Item "+i);
by.add(bz);
}},__GW:function(){var bt=new qx.ui.menu.Menu;

for(var i=0;i<3;i++){bt.add(new qx.ui.menu.RadioButton("Option"+i));
}var bw=new qx.ui.form.RadioGroup;
bw.add.apply(bw,bt.getChildren());
var bv=new qx.ui.menu.Menu();

for(var i=0;i<3;i++){var bx=new qx.ui.menu.Button("Button"+i);
bv.add(bx);
}var bu=new qx.ui.menu.Button("Options","",null,bt);
bv.addSeparator();
bv.add(bu);
return bv;
},__GX:function(){var bo=new qx.ui.menu.Menu;
var br=new qx.ui.menu.Button("Website 1");
var bp=new qx.ui.menu.Button("Website 2");
var bq=new qx.ui.menu.Button("Website 3");
bo.add(br);
bo.add(bp);
bo.add(bq);
return bo;
}}});
})();
(function(){var o="button",n="hovered",m="pressed",l="arrow",k="Enter",j="Space",i="abandoned",h="both",g="String",f="changeVisibility",E="splitbutton",D="changeShow",C="mouseout",B="keydown",A="execute",z="_applyMenu",y="icon",x="mouseover",w="keyup",v="qx.ui.menu.Menu",t="_applyIcon",u="label",r="_applyShow",s="changeMenu",p="_applyLabel",q="qx.ui.form.SplitButton";
qx.Class.define(q,{extend:qx.ui.core.Widget,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IExecutable],construct:function(I,J,K,L){arguments.callee.base.call(this);
this._setLayout(new qx.ui.layout.HBox);
this._createChildControl(l);
this.addListener(x,this._onMouseOver,this,true);
this.addListener(C,this._onMouseOut,this,true);
this.addListener(B,this._onKeyDown);
this.addListener(w,this._onKeyUp);
if(I!=null){this.setLabel(I);
}
if(J!=null){this.setIcon(J);
}
if(K!=null){this.setMenu(K);
}
if(L!=null){this.setCommand(L);
}},properties:{appearance:{refine:true,init:E},focusable:{refine:true,init:true},label:{apply:p,nullable:true,check:g},icon:{check:g,apply:t,nullable:true,themeable:true},show:{init:h,check:[h,u,y],themeable:true,inheritable:true,apply:r,event:D},menu:{check:v,nullable:true,apply:z,event:s}},members:{__un:null,_createChildControlImpl:function(a){var b;

switch(a){case o:b=new qx.ui.form.Button;
b.addListener(A,this._onButtonExecute,this);
b.setFocusable(false);
this._addAt(b,0,{flex:1});
break;
case l:b=new qx.ui.form.MenuButton;
b.setFocusable(false);
this._addAt(b,1);
break;
}return b||arguments.callee.base.call(this,a);
},_forwardStates:{hovered:1,focused:1},_applyLabel:function(T,U){var V=this.getChildControl(o);
T==null?V.resetLabel():V.setLabel(T);
},_applyIcon:function(N,O){var P=this.getChildControl(o);
N==null?P.resetIcon():P.setIcon(N);
},_applyMenu:function(F,G){var H=this.getChildControl(l);

if(F){H.resetEnabled();
H.setMenu(F);
F.setOpener(this);
F.addListener(f,this._onChangeMenuVisibility,this);
}else{H.setEnabled(false);
H.resetMenu();
}
if(G){G.removeListener(f,this._onChangeMenuVisibility,this);
G.resetOpener();
}},_applyShow:function(c,d){},_onMouseOver:function(e){e.stopPropagation();
this.addState(n);
delete this.__un;
},_onMouseOut:function(e){e.stopPropagation();
if(!this.hasState(n)){return;
}var R=e.getRelatedTarget();

if(qx.ui.core.Widget.contains(this,R)){return;
}var Q=this.getMenu();

if(Q&&Q.isVisible()){this.__un=true;
return;
}this.removeState(n);
},_onKeyDown:function(e){var M=this.getChildControl(o);

switch(e.getKeyIdentifier()){case k:case j:M.removeState(i);
M.addState(m);
}},_onKeyUp:function(e){var S=this.getChildControl(o);

switch(e.getKeyIdentifier()){case k:case j:if(S.hasState(m)){S.removeState(i);
S.removeState(m);
S.execute();
}}},_onButtonExecute:function(e){this.execute();
},_onChangeMenuVisibility:function(e){if(!this.getMenu().isVisible()&&this.__un){this.removeState(n);
}}}});
})();
(function(){var bd="textfield",bc="",bb="downbutton",ba="upbutton",Y="Number",X="inner",W="PageUp",V="Boolean",U="changeValue",T="Down",bA="Up",bz="execute",by="PageDown",bx="changeLocale",bw="qx.dynlocale",bv="on",bu="_applyEditable",bt="_applyWrap",bs="keydown",br="\-]",bk="mousewheel",bl="_applyValue",bi="number",bj="_applyMinimum",bg="qx.util.format.NumberFormat",bh="[0-9",be="keyup",bf="spinner",bm="this._checkValue(value)",bn="_applyMaximum",bp="changeNumberFormat",bo="_applyNumberFormat",bq="qx.ui.form.Spinner";
qx.Class.define(bq,{extend:qx.ui.core.Widget,implement:[qx.ui.form.INumberForm,qx.ui.form.IRange,qx.ui.form.IForm],include:[qx.ui.core.MContentPadding,qx.ui.form.MForm],construct:function(v,w,x){arguments.callee.base.call(this);
var y=new qx.ui.layout.Grid();
y.setColumnFlex(0,1);
y.setRowFlex(0,1);
y.setRowFlex(1,1);
this._setLayout(y);
this.addListener(bs,this._onKeyDown,this);
this.addListener(be,this._onKeyUp,this);
this.addListener(bk,this._onMouseWheel,this);

if(qx.core.Variant.isSet(bw,bv)){qx.locale.Manager.getInstance().addListener(bx,this._onChangeLocale,this);
}this._createChildControl(bd);
this._createChildControl(ba);
this._createChildControl(bb);
if(v!=null){this.setMinimum(v);
}
if(x!=null){this.setMaximum(x);
}
if(w!==undefined){this.setValue(w);
}else{this.initValue();
}},properties:{appearance:{refine:true,init:bf},focusable:{refine:true,init:true},singleStep:{check:Y,init:1},pageStep:{check:Y,init:10},minimum:{check:Y,apply:bj,init:0},value:{check:bm,nullable:true,apply:bl,init:0,event:U},maximum:{check:Y,apply:bn,init:100},wrap:{check:V,init:false,apply:bt},editable:{check:V,init:true,apply:bu},numberFormat:{check:bg,apply:bo,nullable:true},allowShrinkY:{refine:true,init:false}},members:{__tx:null,__ty:false,__tz:false,_createChildControlImpl:function(R){var S;

switch(R){case bd:S=new qx.ui.form.TextField();
S.setFilter(this._getFilterRegExp());
S.addState(X);
S.setWidth(40);
S.setFocusable(false);
S.addListener(U,this._onTextChange,this);
this._add(S,{column:0,row:0,rowSpan:2});
break;
case ba:S=new qx.ui.form.RepeatButton();
S.addState(X);
S.setFocusable(false);
S.addListener(bz,this._countUp,this);
this._add(S,{column:1,row:0});
break;
case bb:S=new qx.ui.form.RepeatButton();
S.addState(X);
S.setFocusable(false);
S.addListener(bz,this._countDown,this);
this._add(S,{column:1,row:1});
break;
}return S||arguments.callee.base.call(this,R);
},_getFilterRegExp:function(){var K=qx.locale.Number.getDecimalSeparator(qx.locale.Manager.getInstance().getLocale());
var J=qx.locale.Number.getGroupSeparator(qx.locale.Manager.getInstance().getLocale());
var I=bc;
var G=bc;

if(this.getNumberFormat()!==null){I=this.getNumberFormat().getPrefix()||bc;
G=this.getNumberFormat().getPostfix()||bc;
}var H=new RegExp(bh+qx.lang.String.escapeRegexpChars(K)+qx.lang.String.escapeRegexpChars(J)+qx.lang.String.escapeRegexpChars(I)+qx.lang.String.escapeRegexpChars(G)+br);
return H;
},_forwardStates:{focused:true,invalid:true},tabFocus:function(){var r=this.getChildControl(bd);
r.getFocusElement().focus();
r.selectAllText();
},_applyMinimum:function(N,O){if(this.getMaximum()<N){this.setMaximum(N);
}
if(this.getValue()<N){this.setValue(N);
}else{this._updateButtons();
}},_applyMaximum:function(d,f){if(this.getMinimum()>d){this.setMin(d);
}
if(this.getValue()>d){this.setValue(d);
}else{this._updateButtons();
}},_applyEnabled:function(P,Q){arguments.callee.base.call(this,P,Q);
this._updateButtons();
},_checkValue:function(z){return typeof z===bi&&z>=this.getMinimum()&&z<=this.getMaximum();
},_applyValue:function(a,b){var c=this.getChildControl(bd);
this._updateButtons();
this.__tx=a;
if(a!==null){if(this.getNumberFormat()){c.setValue(this.getNumberFormat().format(a));
}else{c.setValue(a+bc);
}}else{c.setValue(bc);
}},_applyEditable:function(o,p){var q=this.getChildControl(bd);

if(q){q.setReadOnly(!o);
}},_applyWrap:function(E,F){this._updateButtons();
},_applyNumberFormat:function(j,k){var l=this.getChildControl(bd);
l.setFilter(this._getFilterRegExp());
this.getNumberFormat().addListener(bp,this._onChangeNumberFormat,this);
this._applyValue(this.__tx,undefined);
},_getContentPaddingTarget:function(){return this.getChildControl(bd);
},_updateButtons:function(){var t=this.getChildControl(ba);
var s=this.getChildControl(bb);
var u=this.getValue();

if(!this.getEnabled()){t.setEnabled(false);
s.setEnabled(false);
}else{if(this.getWrap()){t.setEnabled(true);
s.setEnabled(true);
}else{if(u!==null&&u<this.getMaximum()){t.setEnabled(true);
}else{t.setEnabled(false);
}if(u!==null&&u>this.getMinimum()){s.setEnabled(true);
}else{s.setEnabled(false);
}}}},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case W:this.__ty=true;
case bA:this.getChildControl(ba).press();
break;
case by:this.__tz=true;
case T:this.getChildControl(bb).press();
break;
default:return ;
}e.stopPropagation();
e.preventDefault();
},_onKeyUp:function(e){switch(e.getKeyIdentifier()){case W:this.getChildControl(ba).release();
this.__ty=false;
break;
case bA:this.getChildControl(ba).release();
break;
case by:this.getChildControl(bb).release();
this.__tz=false;
break;
case T:this.getChildControl(bb).release();
break;
}},_onMouseWheel:function(e){if(e.getWheelDelta()>0){this._countDown();
}else{this._countUp();
}e.stop();
},_onTextChange:function(e){var A=this.getChildControl(bd);
var B;
if(this.getNumberFormat()){try{B=this.getNumberFormat().parse(A.getValue());
}catch(g){}}if(B===undefined){B=parseFloat(A.getValue(),10);
}if(!isNaN(B)){if(B>this.getMaximum()){A.setValue(this.getMaximum()+bc);
return;
}else if(B<this.getMinimum()){A.setValue(this.getMinimum()+bc);
return;
}this.setValue(B);
}else{this._applyValue(this.__tx,undefined);
}},_onChangeLocale:function(m){if(this.getNumberFormat()!==null){this.setNumberFormat(this.getNumberFormat());
var n=this.getChildControl(bd);
n.setFilter(this._getFilterRegExp());
n.setValue(this.getNumberFormat().format(this.getValue()));
}},_onChangeNumberFormat:function(L){var M=this.getChildControl(bd);
M.setFilter(this._getFilterRegExp());
M.setValue(this.getNumberFormat().format(this.getValue()));
},_countUp:function(){if(this.__ty){var i=this.getValue()+this.getPageStep();
}else{var i=this.getValue()+this.getSingleStep();
}if(this.getWrap()){if(i>this.getMaximum()){var h=this.getMaximum()-i;
i=this.getMinimum()+h;
}}this.gotoValue(i);
},_countDown:function(){if(this.__tz){var D=this.getValue()-this.getPageStep();
}else{var D=this.getValue()-this.getSingleStep();
}if(this.getWrap()){if(D<this.getMinimum()){var C=this.getMinimum()+D;
D=this.getMaximum()-C;
}}this.gotoValue(D);
},gotoValue:function(bB){return this.setValue(Math.min(this.getMaximum(),Math.max(this.getMinimum(),bB)));
}},destruct:function(){if(qx.core.Variant.isSet(bw,bv)){qx.locale.Manager.getInstance().removeListener(bx,this._onChangeLocale,this);
}}});
})();
(function(){var d="password",c="qx.ui.form.PasswordField",b="input";
qx.Class.define(c,{extend:qx.ui.form.TextField,members:{_createInputElement:function(){var a=new qx.html.Input(d);
a.addListener(b,this._onHtmlInput,this);
return a;
}}});
})();
