qx.$$packageData['5696dd6345b3']={"resources":{"qx/icon/Tango/16/actions/edit-clear.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-copy.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-cut.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-delete.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-find.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-paste.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-redo.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-select-all.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-undo.png":[16,16,"png","qx"]}};
(function(){var d="cldr_number_decimal_separator",c="cldr_number_percent_format",b="qx.locale.Number",a="cldr_number_group_separator";
qx.Class.define(b,{statics:{getDecimalSeparator:function(f){return qx.locale.Manager.getInstance().localize(d,[],f);
},getGroupSeparator:function(e){return qx.locale.Manager.getInstance().localize(a,[],e);
},getPercentFormat:function(g){return qx.locale.Manager.getInstance().localize(c,[],g);
}}});
})();
(function(){var a="qx.util.format.IFormat";
qx.Interface.define(a,{members:{format:function(b){},parse:function(c){}}});
})();
(function(){var C="_",B="format",A="thu",z="sat",y="cldr_day_",x="cldr_month_",w="wed",v="fri",u="tue",t="mon",T="sun",S="short",R="HH:mm",Q="HHmmsszz",P="HHmm",O="HHmmss",N="cldr_date_format_",M="HH:mm:ss zz",L="full",K="cldr_pm",I="long",J="medium",G="cldr_am",H="qx.locale.Date",E="cldr_date_time_format_",F="cldr_time_format_",D="HH:mm:ss";
qx.Class.define(H,{statics:{__pa:qx.locale.Manager.getInstance(),getAmMarker:function(bs){return this.__pa.localize(G,[],bs);
},getPmMarker:function(U){return this.__pa.localize(K,[],U);
},getDayNames:function(length,V,W){var W=W?W:B;
{};
var Y=[T,t,u,w,A,v,z];
var ba=[];

for(var i=0;i<Y.length;i++){var X=y+W+C+length+C+Y[i];
ba.push(this.__pa.localize(X,[],V));
}return ba;
},getDayName:function(length,bt,bu,bv){var bv=bv?bv:B;
{};
var bx=[T,t,u,w,A,v,z];
var bw=y+bv+C+length+C+bx[bt];
return this.__pa.localize(bw,[],bu);
},getMonthNames:function(length,a,b){var b=b?b:B;
{};
var d=[];

for(var i=0;i<12;i++){var c=x+b+C+length+C+(i+1);
d.push(this.__pa.localize(c,[],a));
}return d;
},getMonthName:function(length,bh,bi,bj){var bj=bj?bj:B;
{};
var bk=x+bj+C+length+C+(bh+1);
return this.__pa.localize(bk,[],bi);
},getDateFormat:function(e,f){{};
var g=N+e;
return this.__pa.localize(g,[],f);
},getDateTimeFormat:function(h,j,k){var m=E+h;
var l=this.__pa.localize(m,[],k);

if(l==m){l=j;
}return l;
},getTimeFormat:function(bd,be){{};
var bg=F+bd;
var bf=this.__pa.localize(bg,[],be);

if(bf!=bg){return bf;
}
switch(bd){case S:case J:return qx.locale.Date.getDateTimeFormat(P,R);
case I:return qx.locale.Date.getDateTimeFormat(O,D);
case L:return qx.locale.Date.getDateTimeFormat(Q,M);
default:throw new Error("This case should never happen.");
}},getWeekStart:function(q){var r={"MV":5,"AE":6,"AF":6,"BH":6,"DJ":6,"DZ":6,"EG":6,"ER":6,"ET":6,"IQ":6,"IR":6,"JO":6,"KE":6,"KW":6,"LB":6,"LY":6,"MA":6,"OM":6,"QA":6,"SA":6,"SD":6,"SO":6,"TN":6,"YE":6,"AS":0,"AU":0,"AZ":0,"BW":0,"CA":0,"CN":0,"FO":0,"GE":0,"GL":0,"GU":0,"HK":0,"IE":0,"IL":0,"IS":0,"JM":0,"JP":0,"KG":0,"KR":0,"LA":0,"MH":0,"MN":0,"MO":0,"MP":0,"MT":0,"NZ":0,"PH":0,"PK":0,"SG":0,"TH":0,"TT":0,"TW":0,"UM":0,"US":0,"UZ":0,"VI":0,"ZA":0,"ZW":0,"MW":0,"NG":0,"TJ":0};
var s=qx.locale.Date._getTerritory(q);
return r[s]!=null?r[s]:1;
},getWeekendStart:function(n){var p={"EG":5,"IL":5,"SY":5,"IN":0,"AE":4,"BH":4,"DZ":4,"IQ":4,"JO":4,"KW":4,"LB":4,"LY":4,"MA":4,"OM":4,"QA":4,"SA":4,"SD":4,"TN":4,"YE":4};
var o=qx.locale.Date._getTerritory(n);
return p[o]!=null?p[o]:6;
},getWeekendEnd:function(bl){var bm={"AE":5,"BH":5,"DZ":5,"IQ":5,"JO":5,"KW":5,"LB":5,"LY":5,"MA":5,"OM":5,"QA":5,"SA":5,"SD":5,"TN":5,"YE":5,"AF":5,"IR":5,"EG":6,"IL":6,"SY":6};
var bn=qx.locale.Date._getTerritory(bl);
return bm[bn]!=null?bm[bn]:0;
},isWeekend:function(bo,bp){var br=qx.locale.Date.getWeekendStart(bp);
var bq=qx.locale.Date.getWeekendEnd(bp);

if(bq>br){return ((bo>=br)&&(bo<=bq));
}else{return ((bo>=br)||(bo<=bq));
}},_getTerritory:function(bb){if(bb){var bc=bb.split(C)[1]||bb;
}else{bc=this.__pa.getTerritory()||this.__pa.getLanguage();
}return bc.toUpperCase();
}}});
})();
(function(){var cX="(\\d\\d?)",cW="format",cV="",cU="abbreviated",cT="wide",cS="(",cR=")",cQ="|",cP="stand-alone",cO="wildcard",cD="default",cC="literal",cB="'",cA="hour",cz="(\\d\\d?\\d?)",cy="ms",cx="narrow",cw="-",cv="quoted_literal",cu='a',df="HH:mm:ss",dg="+",dd="HHmmss",de="long",db='z',dc="0",cY="sec",da="day",dh='Z',di=" ",cH="min",cG="mm",cJ="(\\d+)",cI="h",cL="KK",cK='L',cN="Z",cM="(\\d\\d+)",cF="EEEE",cE="^",bv=":",bw='y',bx="K",by="a",bz="([\\+\\-]\\d\\d:?\\d\\d)",bA="GMT",bB="dd",bC="qx.util.format.DateFormat",bD="yyy",bE="H",dm="YYYY",dl="y",dk="HH",dj="EE",dr='h',dq="S",dp='s',dn='A',dt="yyyyyy",ds="kk",ce="ss",cf='H',cc='S',cd="MMMM",ci='c',cj="d",cg="([a-zA-Z]+)",ch='k',ca="m",cb='Y',bM='D',bL="yyyyy",bO='K',bN="hh",bI="SSS",bH="MM",bK="yy",bJ="(\\d\\d\\d\\d\\d\\d+)",bG="yyyy-MM-dd HH:mm:ss",bF="(\\d\\d\\d\\d\\d+)",co="short",cp='d',cq="unkown",cr='m',ck="(\\d\\d\\d\\d)",cl="(\\d\\d\\d+)",cm="k",cn='M',cs="(\\d\\d\\d\\d+)",ct="SS",bW="MMM",bV="s",bU="M",bT='w',bS="EEE",bR="$",bQ="?",bP='E',bY="z",bX="yyyy";
qx.Class.define(bC,{extend:qx.core.Object,implement:qx.util.format.IFormat,construct:function(bh,bi){arguments.callee.base.call(this);

if(!bi){this.__pp=qx.locale.Manager.getInstance().getLocale();
}else{this.__pp=bi;
}
if(bh!=null){this.__pq=bh.toString();
}else{this.__pq=qx.locale.Date.getDateFormat(de,this.__pp)+di+qx.locale.Date.getDateTimeFormat(dd,df,this.__pp);
}},statics:{getDateTimeInstance:function(){var dH=qx.util.format.DateFormat;
var dG=qx.locale.Date.getDateFormat(de)+di+qx.locale.Date.getDateTimeFormat(dd,df);

if(dH._dateInstance==null||dH._dateInstance.__pq!=dG){dH._dateTimeInstance=new dH();
}return dH._dateTimeInstance;
},getDateInstance:function(){var dz=qx.util.format.DateFormat;
var dy=qx.locale.Date.getDateFormat(co)+cV;

if(dz._dateInstance==null||dz._dateInstance.__pq!=dy){dz._dateInstance=new dz(dy);
}return dz._dateInstance;
},ASSUME_YEAR_2000_THRESHOLD:30,LOGGING_DATE_TIME__format:bG,AM_MARKER:"am",PM_MARKER:"pm",MEDIUM_TIMEZONE_NAMES:["GMT"],FULL_TIMEZONE_NAMES:["Greenwich Mean Time"]},members:{__pp:null,__pq:null,__pr:null,__ps:null,__pt:null,__pu:function(c,d){var e=cV+c;

while(e.length<d){e=dc+e;
}return e;
},__pv:function(be){var bf=new Date(be.getTime());
var bg=bf.getDate();

while(bf.getMonth()!=0){bf.setDate(-1);
bg+=bf.getDate()+1;
}return bg;
},__pw:function(dI){return new Date(dI.getTime()+(3-((dI.getDay()+6)%7))*86400000);
},__px:function(dC){var dE=this.__pw(dC);
var dF=dE.getFullYear();
var dD=this.__pw(new Date(dF,0,4));
return Math.floor(1.5+(dE.getTime()-dD.getTime())/86400000/7);
},format:function(h){if(h==null){return null;
}var o=qx.util.format.DateFormat;
var p=this.__pp;
var z=h.getFullYear();
var t=h.getMonth();
var B=h.getDate();
var j=h.getDay();
var u=h.getHours();
var q=h.getMinutes();
var v=h.getSeconds();
var x=h.getMilliseconds();
var A=h.getTimezoneOffset();
var m=A>0?1:-1;
var k=Math.floor(Math.abs(A)/60);
var r=Math.abs(A)%60;
this.__py();
var y=cV;

for(var i=0;i<this.__pt.length;i++){var w=this.__pt[i];

if(w.type==cC){y+=w.text;
}else{var n=w.character;
var s=w.size;
var l=bQ;

switch(n){case bw:case cb:if(s==2){l=this.__pu(z%100,2);
}else{l=z+cV;

if(s>l.length){for(var i=l.length;i<s;i++){l=dc+l;
}}}break;
case bM:l=this.__pu(this.__pv(h),s);
break;
case cp:l=this.__pu(B,s);
break;
case bT:l=this.__pu(this.__px(h),s);
break;
case bP:if(s==2){l=qx.locale.Date.getDayName(cx,j,p,cW);
}else if(s==3){l=qx.locale.Date.getDayName(cU,j,p,cW);
}else if(s==4){l=qx.locale.Date.getDayName(cT,j,p,cW);
}break;
case ci:if(s==2){l=qx.locale.Date.getDayName(cx,j,p,cP);
}else if(s==3){l=qx.locale.Date.getDayName(cU,j,p,cP);
}else if(s==4){l=qx.locale.Date.getDayName(cT,j,p,cP);
}break;
case cn:if(s==1||s==2){l=this.__pu(t+1,s);
}else if(s==3){l=qx.locale.Date.getMonthName(cU,t,p,cW);
}else if(s==4){l=qx.locale.Date.getMonthName(cT,t,p,cW);
}break;
case cK:if(s==1||s==2){l=this.__pu(t+1,s);
}else if(s==3){l=qx.locale.Date.getMonthName(cU,t,p,cP);
}else if(s==4){l=qx.locale.Date.getMonthName(cT,t,p,cP);
}break;
case cu:l=(u<12)?qx.locale.Date.getAmMarker(p):qx.locale.Date.getPmMarker(p);
break;
case cf:l=this.__pu(u,s);
break;
case ch:l=this.__pu((u==0)?24:u,s);
break;
case bO:l=this.__pu(u%12,s);
break;
case dr:l=this.__pu(((u%12)==0)?12:(u%12),s);
break;
case cr:l=this.__pu(q,s);
break;
case dp:l=this.__pu(v,s);
break;
case cc:l=this.__pu(x,s);
break;
case db:if(s==1){l=bA+((m>0)?cw:dg)+this.__pu(Math.abs(k))+bv+this.__pu(r,2);
}else if(s==2){l=o.MEDIUM_TIMEZONE_NAMES[k];
}else if(s==3){l=o.FULL_TIMEZONE_NAMES[k];
}break;
case dh:l=((m>0)?cw:dg)+this.__pu(Math.abs(k),2)+this.__pu(r,2);
break;
}y+=l;
}}return y;
},parse:function(bj){this.__pz();
var bp=this.__pr.regex.exec(bj);

if(bp==null){throw new Error("Date string '"+bj+"' does not match the date format: "+this.__pq);
}var bk={year:1970,month:0,day:1,hour:0,ispm:false,min:0,sec:0,ms:0};
var bl=1;

for(var i=0;i<this.__pr.usedRules.length;i++){var bn=this.__pr.usedRules[i];
var bm=bp[bl];

if(bn.field!=null){bk[bn.field]=parseInt(bm,10);
}else{bn.manipulator(bk,bm);
}bl+=(bn.groups==null)?1:bn.groups;
}var bo=new Date(bk.year,bk.month,bk.day,(bk.ispm)?(bk.hour+12):bk.hour,bk.min,bk.sec,bk.ms);

if(bk.month!=bo.getMonth()||bk.year!=bo.getFullYear()){throw new Error("Error parsing date '"+bj+"': the value for day or month is too large");
}return bo;
},__py:function(){if(this.__pt!=null){return;
}this.__pt=[];
var ea;
var dX=0;
var ec=cV;
var dV=this.__pq;
var dY=cD;
var i=0;

while(i<dV.length){var eb=dV.charAt(i);

switch(dY){case cv:if(eb==cB){if(i+1>=dV.length){i++;
break;
}var dW=dV.charAt(i+1);

if(dW==cB){ec+=eb;
i++;
}else{i++;
dY=cq;
}}else{ec+=eb;
i++;
}break;
case cO:if(eb==ea){dX++;
i++;
}else{this.__pt.push({type:cO,character:ea,size:dX});
ea=null;
dX=0;
dY=cD;
}break;
default:if((eb>=cu&&eb<=db)||(eb>=dn&&eb<=dh)){ea=eb;
dY=cO;
}else if(eb==cB){if(i+1>=dV.length){ec+=eb;
i++;
break;
}var dW=dV.charAt(i+1);

if(dW==cB){ec+=eb;
i++;
}i++;
dY=cv;
}else{dY=cD;
}
if(dY!=cD){if(ec.length>0){this.__pt.push({type:cC,text:ec});
ec=cV;
}}else{ec+=eb;
i++;
}break;
}}if(ea!=null){this.__pt.push({type:cO,character:ea,size:dX});
}else if(ec.length>0){this.__pt.push({type:cC,text:ec});
}},__pz:function(){if(this.__pr!=null){return ;
}var dM=this.__pq;
this.__pA();
this.__py();
var dS=[];
var dO=cE;

for(var dK=0;dK<this.__pt.length;dK++){var dT=this.__pt[dK];

if(dT.type==cC){dO+=qx.lang.String.escapeRegexpChars(dT.text);
}else{var dL=dT.character;
var dP=dT.size;
var dN;

for(var dU=0;dU<this.__ps.length;dU++){var dQ=this.__ps[dU];

if(dL==dQ.pattern.charAt(0)&&dP==dQ.pattern.length){dN=dQ;
break;
}}if(dN==null){var dR=cV;

for(var i=0;i<dP;i++){dR+=dL;
}throw new Error("Malformed date format: "+dM+". Wildcard "+dR+" is not supported");
}else{dS.push(dN);
dO+=dN.regex;
}}}dO+=bR;
var dJ;

try{dJ=new RegExp(dO);
}catch(bu){throw new Error("Malformed date format: "+dM);
}this.__pr={regex:dJ,"usedRules":dS,pattern:dO};
},__pA:function(){var L=qx.util.format.DateFormat;
var R=qx.lang.String;

if(this.__ps!=null){return ;
}var M=this.__ps=[];
var Y=function(bc,bd){bd=parseInt(bd,10);

if(bd<L.ASSUME_YEAR_2000_THRESHOLD){bd+=2000;
}else if(bd<100){bd+=1900;
}bc.year=bd;
};
var S=function(du,dv){du.month=parseInt(dv,10)-1;
};
var P=function(dw,dx){dw.ispm=(dx==L.PM_MARKER);
};
var O=function(dA,dB){dA.hour=parseInt(dB,10)%24;
};
var N=function(f,g){f.hour=parseInt(g,10)%12;
};
var V=function(C,D){return;
};
var T=qx.locale.Date.getMonthNames(cU,this.__pp,cW);

for(var i=0;i<T.length;i++){T[i]=R.escapeRegexpChars(T[i].toString());
}var U=function(a,b){b=R.escapeRegexpChars(b);
a.month=T.indexOf(b);
};
var I=qx.locale.Date.getMonthNames(cT,this.__pp,cW);

for(var i=0;i<I.length;i++){I[i]=R.escapeRegexpChars(I[i].toString());
}var H=function(bs,bt){bt=R.escapeRegexpChars(bt);
bs.month=I.indexOf(bt);
};
var K=qx.locale.Date.getDayNames(cx,this.__pp,cW);

for(var i=0;i<K.length;i++){K[i]=R.escapeRegexpChars(K[i].toString());
}var G=function(bq,br){br=R.escapeRegexpChars(br);
bq.month=K.indexOf(br);
};
var W=qx.locale.Date.getDayNames(cU,this.__pp,cW);

for(var i=0;i<W.length;i++){W[i]=R.escapeRegexpChars(W[i].toString());
}var Q=function(E,F){F=R.escapeRegexpChars(F);
E.month=W.indexOf(F);
};
var X=qx.locale.Date.getDayNames(cT,this.__pp,cW);

for(var i=0;i<X.length;i++){X[i]=R.escapeRegexpChars(X[i].toString());
}var J=function(ba,bb){bb=R.escapeRegexpChars(bb);
ba.month=X.indexOf(bb);
};
M.push({pattern:dm,regex:ck,manipulator:Y});
M.push({pattern:dl,regex:cJ,manipulator:Y});
M.push({pattern:bK,regex:cM,manipulator:Y});
M.push({pattern:bD,regex:cl,manipulator:Y});
M.push({pattern:bX,regex:cs,manipulator:Y});
M.push({pattern:bL,regex:bF,manipulator:Y});
M.push({pattern:dt,regex:bJ,manipulator:Y});
M.push({pattern:bU,regex:cX,manipulator:S});
M.push({pattern:bH,regex:cX,manipulator:S});
M.push({pattern:bW,regex:cS+T.join(cQ)+cR,manipulator:U});
M.push({pattern:cd,regex:cS+I.join(cQ)+cR,manipulator:H});
M.push({pattern:bB,regex:cX,field:da});
M.push({pattern:cj,regex:cX,field:da});
M.push({pattern:dj,regex:cS+K.join(cQ)+cR,manipulator:G});
M.push({pattern:bS,regex:cS+W.join(cQ)+cR,manipulator:Q});
M.push({pattern:cF,regex:cS+X.join(cQ)+cR,manipulator:J});
M.push({pattern:by,regex:cS+L.AM_MARKER+cQ+L.PM_MARKER+cR,manipulator:P});
M.push({pattern:dk,regex:cX,field:cA});
M.push({pattern:bE,regex:cX,field:cA});
M.push({pattern:ds,regex:cX,manipulator:O});
M.push({pattern:cm,regex:cX,manipulator:O});
M.push({pattern:cL,regex:cX,field:cA});
M.push({pattern:bx,regex:cX,field:cA});
M.push({pattern:bN,regex:cX,manipulator:N});
M.push({pattern:cI,regex:cX,manipulator:N});
M.push({pattern:cG,regex:cX,field:cH});
M.push({pattern:ca,regex:cX,field:cH});
M.push({pattern:ce,regex:cX,field:cY});
M.push({pattern:bV,regex:cX,field:cY});
M.push({pattern:bI,regex:cz,field:cy});
M.push({pattern:ct,regex:cz,field:cy});
M.push({pattern:dq,regex:cz,field:cy});
M.push({pattern:cN,regex:bz,manipulator:V});
M.push({pattern:bY,regex:cg,manipulator:V});
}},destruct:function(){this.__pt=this.__pr=this.__ps=null;
}});
})();
(function(){var t="",s="Number",r="-",q="0",p="String",o="changeNumberFormat",n='(',m="g",l="Boolean",k="$",d="NaN",j='([0-9]{1,3}(?:',g='{0,1}[0-9]{3}){0,})',c='\\d+){0,1}',b="qx.util.format.NumberFormat",f="Infinity",e="^",h=".",a="-Infinity",i='([-+]){0,1}';
qx.Class.define(b,{extend:qx.core.Object,implement:qx.util.format.IFormat,construct:function(G){arguments.callee.base.call(this);
this.__sw=G;
},statics:{getIntegerInstance:function(){var H=qx.util.format.NumberFormat;

if(H._integerInstance==null){H._integerInstance=new H();
H._integerInstance.setMaximumFractionDigits(0);
}return H._integerInstance;
},getInstance:function(){if(!this._instance){this._instance=new this;
}return this._instance;
}},properties:{minimumIntegerDigits:{check:s,init:0},maximumIntegerDigits:{check:s,nullable:true},minimumFractionDigits:{check:s,init:0},maximumFractionDigits:{check:s,nullable:true},groupingUsed:{check:l,init:true},prefix:{check:p,init:t,event:o},postfix:{check:p,init:t,event:o}},members:{__sw:null,format:function(u){switch(u){case Infinity:return f;
case -Infinity:return a;
case NaN:return d;
}var y=(u<0);

if(y){u=-u;
}
if(this.getMaximumFractionDigits()!=null){var F=Math.pow(10,this.getMaximumFractionDigits());
u=Math.round(u*F)/F;
}var E=String(Math.floor(u)).length;
var v=t+u;
var B=v.substring(0,E);

while(B.length<this.getMinimumIntegerDigits()){B=q+B;
}
if(this.getMaximumIntegerDigits()!=null&&B.length>this.getMaximumIntegerDigits()){B=B.substring(B.length-this.getMaximumIntegerDigits());
}var A=v.substring(E+1);

while(A.length<this.getMinimumFractionDigits()){A+=q;
}
if(this.getMaximumFractionDigits()!=null&&A.length>this.getMaximumFractionDigits()){A=A.substring(0,this.getMaximumFractionDigits());
}if(this.getGroupingUsed()){var x=B;
B=t;
var D;

for(D=x.length;D>3;D-=3){B=t+qx.locale.Number.getGroupSeparator(this.__sw)+x.substring(D-3,D)+B;
}B=x.substring(0,D)+B;
}var z=this.getPrefix()?this.getPrefix():t;
var w=this.getPostfix()?this.getPostfix():t;
var C=z+(y?r:t)+B;

if(A.length>0){C+=t+qx.locale.Number.getDecimalSeparator(this.__sw)+A;
}C+=w;
return C;
},parse:function(I){var N=qx.lang.String.escapeRegexpChars(qx.locale.Number.getGroupSeparator(this.__sw)+t);
var L=qx.lang.String.escapeRegexpChars(qx.locale.Number.getDecimalSeparator(this.__sw)+t);
var J=new RegExp(e+qx.lang.String.escapeRegexpChars(this.getPrefix())+i+j+N+g+n+L+c+qx.lang.String.escapeRegexpChars(this.getPostfix())+k);
var M=J.exec(I);

if(M==null){throw new Error("Number string '"+I+"' does not match the number format");
}var O=(M[1]==r);
var Q=M[2];
var P=M[3];
Q=Q.replace(new RegExp(N,m),t);
var K=(O?r:t)+Q;

if(P!=null&&P.length!=0){P=P.replace(new RegExp(L),t);
K+=h+P;
}return parseFloat(K);
}}});
})();
(function(){var S="short",R="long",Q="selection[0]",P="medium",O="Cut",N="Copy",M="language",L="Paste",K="full",J="selection[0].selected",cl="Territory code:",ck="icon/16/actions/edit-find.png",cj="Time format short:",ci="Ctrl+V",ch="icon/16/actions/edit-delete.png",cg="icon/16/actions/edit-cut.png",cf="United States",ce="Date medium:",cd=".png",cc="Date long:",ba="DE",bb="en",X="Time format long:",Y="Mexico",V="button",W="Locale:",T="AT",U="Undo",bi="Date short:",bj="Austria",bC="Format of %1:",by="Date format short:",bK="changeLocale",bF="Search",bW="MX",bQ="center",br="Ctrl+X",cb="wide",bY="es",bX="US",bp="middle",bu="Time short:",bw="A date:",bA="name",bD="GB",bG="icon",bM="ES",bS="Germany",bc="_",bd="Date format medium:",bt="de",bJ="F3",bI="Date format full:",bH="Week start:",bO="Ctrl+F",bN="icon/16/actions/edit-paste.png",bE="Del",bL="showcase.page.i18n.Content",G="Date format long:",bR="right",be="icon/16/actions/edit-copy.png",bf="country",bz="selection[0].countries",H="Spain",I="selection[0].selected.code",bo="Locale Information",bg="Redo",bh="Delete",bn="model",bB="Ctrl+C",bU="Date full:",bT="Ctrl+A",bv="Search Again",bV="Localized ComboBox:",bq="Select All",bP="Ctrl+Z",bk="Time long:",bm="Ctrl+Y",bs="Command Menu (keyboard shortcuts)",bx="showcase/i18n/",bl="Form Elements",ca="Great Britain";
qx.Class.define(bL,{extend:showcase.AbstractContent,include:qx.locale.MTranslation,construct:function(v){arguments.callee.base.call(this,v);
this.setView(this._createView());
},members:{_createView:function(){var C=new qx.ui.layout.Grid(10,15);
C.setColumnFlex(0,1);
C.setColumnFlex(1,1);
var B=new qx.ui.container.Composite(C).set({padding:10});
B.add(this.__Gj(),{row:0,column:0,colSpan:2});
B.add(this.__Gm(),{row:1,column:0});
B.add(this.__Gn(),{row:1,column:1});
return B;
},__Gj:function(){var x=new qx.ui.form.RadioButtonGroup(new qx.ui.layout.HBox(10).set({alignX:bQ}));
var y=this.__Gk=qx.data.marshal.Json.createModel([{language:bb,selected:null,countries:[{code:bX,name:cf},{code:bD,name:ca}]},{language:bY,selected:null,countries:[{code:bM,name:H},{code:bW,name:Y}]},{language:bt,selected:null,countries:[{code:ba,name:bS},{code:T,name:bj}]}]);

for(var i=0;i<y.getLength();i++){y.getItem(i).setSelected(y.getItem(i).getCountries().getItem(0));
}var w=new qx.data.controller.List(null,x,M);
this.__Gl=w;
w.setDelegate({createItem:function(){return new qx.ui.form.RadioButton().set({show:bG,appearance:V});
}});
w.setIconPath(M);
w.setIconOptions({converter:function(a){return bx+a+cd;
}});
w.setModel(y);
w.getSelection().push(y.getItem(0));
this.__Gl.bind(I,this,bf);
return x;
},setCountry:function(z){if(z){var A=this.__Gl.getSelection().getItem(0).getLanguage();
qx.locale.Manager.getInstance().setLocale(A+bc+z);
}},__Gm:function(){var n=new qx.ui.layout.Grid(10,10);
n.setColumnFlex(0,1);
n.setColumnFlex(1,1);
n.setColumnAlign(0,bR,bp);
var k=new qx.ui.groupbox.GroupBox(this.tr(bl)).set({width:0,minWidth:0});
k.setLayout(n);
k.add(new qx.ui.basic.Label(this.tr(cl)),{row:0,column:0});
var f=new qx.ui.form.SelectBox();
var m=new qx.data.controller.List(null,f,bA);
this.__Gl.bind(bz,m,bn);
this.__Gl.bind(J,m,Q);
m.bind(Q,this.__Gl,J);
k.add(f,{row:0,column:1});
k.add(new qx.ui.basic.Label(this.tr(bV)),{row:1,column:0});
var b=new qx.ui.form.ComboBox();
b.add(new qx.ui.form.ListItem(this.tr(O)));
b.add(new qx.ui.form.ListItem(this.tr(L)));
b.add(new qx.ui.form.ListItem(this.tr(N)));
k.add(b,{row:1,column:1});
var p=new qx.ui.basic.Label(this.tr(bw));
k.add(p,{row:2,column:0});
var s=new qx.ui.form.DateField();
s.setValue(new Date);
k.add(s,{row:2,column:1});
var j=new qx.ui.control.DateChooser;
k.add(j,{row:3,column:0,colSpan:2});
var h=new qx.ui.core.Command(bP);
var l=new qx.ui.core.Command(bm);
var c=new qx.ui.core.Command(br);
var g=new qx.ui.core.Command(bB);
var t=new qx.ui.core.Command(ci);
var u=new qx.ui.core.Command(bE);
var r=new qx.ui.core.Command(bT);
var d=new qx.ui.core.Command(bO);
var q=new qx.ui.core.Command(bJ);
var e=new qx.ui.menu.Menu;
e.add(new qx.ui.menu.Button(this.tr(U),null,h));
e.add(new qx.ui.menu.Button(this.tr(bg),null,l));
e.add(new qx.ui.menu.Separator());
e.add(new qx.ui.menu.Button(this.tr(O),cg,c));
e.add(new qx.ui.menu.Button(this.tr(N),be,g));
e.add(new qx.ui.menu.Button(this.tr(L),bN,t));
e.add(new qx.ui.menu.Button(this.tr(bh),ch,u));
e.add(new qx.ui.menu.Button(this.tr(bq),null,r));
e.add(new qx.ui.menu.Separator());
e.add(new qx.ui.menu.Button(this.tr(bF),null,d));
e.add(new qx.ui.menu.Button(this.tr(bv),null,q));
var o=new qx.ui.form.MenuButton(this.tr(bs),null,e);
k.add(o,{row:4,column:0,colSpan:2});
return k;
},__Gn:function(){var E=new qx.ui.groupbox.GroupBox(this.tr(bo),ck).set({width:0,minWidth:0,allowGrowY:true});
E.setLayout(new qx.ui.layout.Grow());
var F=new qx.ui.basic.Label().set({rich:true,allowGrowX:true,allowGrowY:true});
E.add(F);
var D=[];
D.push("<table id='i18n'><tr><td>");

for(var i=0;i<15;i++){D.push("");
D.push("</td><td>");
D.push("");
D.push("</td></tr><td>");
}D.push("");
D.push("</td><td>");
D.push("");
D.push("</td></tr></table>");
this.updateLocaleInformation=function(){var i=0;
D[(i++*2)+1]=this.tr(W);
D[(i++*2)+1]=qx.locale.Manager.getInstance().getLocale();
D[(i++*2)+1]=this.tr(cl);
D[(i++*2)+1]=qx.locale.Manager.getInstance().getTerritory();
D[(i++*2)+1]=this.tr(by);
D[(i++*2)+1]=qx.locale.Date.getDateFormat(S);
D[(i++*2)+1]=this.tr(bi);
D[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(S))).format(new Date());
D[(i++*2)+1]=this.tr(bd);
D[(i++*2)+1]=qx.locale.Date.getDateFormat(P);
D[(i++*2)+1]=this.tr(ce);
D[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(P))).format(new Date());
D[(i++*2)+1]=this.tr(G);
D[(i++*2)+1]=qx.locale.Date.getDateFormat(R);
D[(i++*2)+1]=this.tr(cc);
D[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(R))).format(new Date());
D[(i++*2)+1]=this.tr(bI);
D[(i++*2)+1]=qx.locale.Date.getDateFormat(K);
D[(i++*2)+1]=this.tr(bU);
D[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(K))).format(new Date());
D[(i++*2)+1]=this.tr(cj);
D[(i++*2)+1]=qx.locale.Date.getTimeFormat(S);
D[(i++*2)+1]=this.tr(bu);
D[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(S))).format(new Date());
D[(i++*2)+1]=this.tr(X);
D[(i++*2)+1]=qx.locale.Date.getTimeFormat(R);
D[(i++*2)+1]=this.tr(bk);
D[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(R))).format(new Date());
D[(i++*2)+1]=this.tr(bH);
D[(i++*2)+1]=qx.locale.Date.getDayName(cb,qx.locale.Date.getWeekStart());
D[(i++*2)+1]=this.tr(bC,10000.12);
D[(i++*2)+1]=qx.util.format.NumberFormat.getInstance().format(10000.12);
F.setValue(D.join(""));
};
qx.locale.Manager.getInstance().addListener(bK,this.updateLocaleInformation,this);
this.updateLocaleInformation();
return E;
}}});
})();
