(function(){var w="move",v="Boolean",u="__md",t="mouseup",s="mousedown",r="losecapture",q="__mb",p="qx.ui.core.MMovable",o="__mc",n="mousemove",l="maximized",m="move-frame";
qx.Mixin.define(p,{properties:{movable:{check:v,init:true},useMoveFrame:{check:v,init:false}},members:{__mb:null,__mc:null,__md:null,__me:null,__mf:null,__mg:null,__mh:null,_activateMoveHandle:function(A){if(this.__mb){throw new Error("The move handle could not be redefined!");
}this.__mb=A;
A.addListener(s,this._onMoveMouseDown,this);
A.addListener(t,this._onMoveMouseUp,this);
A.addListener(n,this._onMoveMouseMove,this);
A.addListener(r,this.__ml,this);
},__mi:function(){var a=this.__mc;

if(!a){a=this.__mc=new qx.ui.core.Widget();
a.setAppearance(m);
a.exclude();
qx.core.Init.getApplication().getRoot().add(a);
}return a;
},__mj:function(){var d=this.getBounds();
var c=this.__mi();
c.setUserBounds(d.left,d.top,d.width,d.height);
c.show();
c.setZIndex(this.getZIndex()+1);
},__mk:function(e){var h=this.__md;
var k=Math.max(h.left,Math.min(h.right,e.getDocumentLeft()));
var j=Math.max(h.top,Math.min(h.bottom,e.getDocumentTop()));
var g=this.__me+k;
var i=this.__mf+j;
return {viewportLeft:g,viewportTop:i,parentLeft:g-this.__mg,parentTop:i-this.__mh};
},_onMoveMouseDown:function(e){if(!this.getMovable()||this.hasState(l)){return;
}var parent=this.getLayoutParent();
var y=parent.getContentLocation();
var z=parent.getBounds();
this.__md={left:y.left,top:y.top,right:y.left+z.width,bottom:y.top+z.height};
var x=this.getContainerLocation();
this.__mg=y.left;
this.__mh=y.top;
this.__me=x.left-e.getDocumentLeft();
this.__mf=x.top-e.getDocumentTop();
this.addState(w);
this.__mb.capture();
if(this.getUseMoveFrame()){this.__mj();
}e.stop();
},_onMoveMouseMove:function(e){if(!this.hasState(w)){return;
}var b=this.__mk(e);

if(this.getUseMoveFrame()){this.__mi().setDomPosition(b.viewportLeft,b.viewportTop);
}else{this.setDomPosition(b.parentLeft,b.parentTop);
}},_onMoveMouseUp:function(e){if(!this.hasState(w)){return;
}this.removeState(w);
this.__mb.releaseCapture();
var f=this.__mk(e);
this.setLayoutProperties({left:f.parentLeft,top:f.parentTop});
if(this.getUseMoveFrame()){this.__mi().exclude();
}},__ml:function(e){if(!this.hasState(w)){return;
}this.removeState(w);
if(this.getUseMoveFrame()){this.__mi().exclude();
}}},destruct:function(){this._disposeObjects(o,q);
this._disposeFields(u);
}});
})();
(function(){var b="qx.ui.core.MRemoteLayoutHandling";
qx.Mixin.define(b,{members:{setLayout:function(a){return this.getChildrenContainer().setLayout(a);
},getLayout:function(){return this.getChildrenContainer().getLayout();
}}});
})();
(function(){var b="qx.ui.window.IDesktop";
qx.Interface.define(b,{members:{setWindowManager:function(c){this.assertInterface(c,qx.ui.window.IWindowManager);
},getWindows:function(){},supportsMaximize:function(){},blockContent:function(a){this.assertInteger(a);
},unblockContent:function(){}}});
})();
(function(){var G="resize",F="Boolean",E="nw-resize",D="mouseup",C="mousedown",B="w-resize",A="losecapture",z="se-resize",y="resize-frame",x="ne-resize",q="n-resize",w="sw-resize",t="mouseout",o="__lL",n="s-resize",s="mousemove",r="move",u="maximized",m="Integer",v="e-resize",p="qx.ui.core.MResizable";
qx.Mixin.define(p,{construct:function(){this.addListener(C,this.__lV,this,true);
this.addListener(D,this.__lW,this);
this.addListener(s,this.__lY,this);
this.addListener(t,this.__ma,this);
this.addListener(A,this.__lX,this);
},properties:{resizable:{check:F,init:true},resizeAllEdges:{check:F,init:true},resizeSensitivity:{check:m,init:5},useResizeFrame:{check:F,init:true}},members:{__lL:null,__lM:null,__lN:null,__lO:null,__lP:null,__lQ:function(){var P=this.__lL;

if(!P){P=this.__lL=new qx.ui.core.Widget();
P.setAppearance(y);
P.exclude();
qx.core.Init.getApplication().getRoot().add(P);
}return P;
},__lR:function(){var S=this.__lP;
var R=this.__lQ();
R.setUserBounds(S.left,S.top,S.width,S.height);
R.show();
R.setZIndex(this.getZIndex()+1);
},__lS:function(e){var I=this.__lM;
var J=this.getSizeHint();
var M=this.__lP;
var H=M.width;
var L=M.height;
var O=M.left;
var top=M.top;
var N;
if(I&1||I&2){N=e.getDocumentTop()-this.__lO;

if(I&1){L-=N;
}else{L+=N;
}
if(L<J.minHeight){L=J.minHeight;
}else if(L>J.maxHeight){L=J.maxHeight;
}
if(I&1){top+=M.height-L;
}}if(I&4||I&8){N=e.getDocumentLeft()-this.__lN;

if(I&4){H-=N;
}else{H+=N;
}
if(H<J.minWidth){H=J.minWidth;
}else if(H>J.maxWidth){H=J.maxWidth;
}
if(I&4){O+=M.width-H;
}}var K=this.getBounds();
return {viewportLeft:O,viewportTop:top,parentLeft:K.left+O-M.left,parentTop:K.top+top-M.top,width:H,height:L};
},__lT:{1:q,2:n,4:B,8:v,5:E,6:w,9:x,10:z},__lU:function(e){if(!this.getResizable()){return;
}var k=this.getContentLocation();
var g=this.getResizeAllEdges();
var j=this.getResizeSensitivity();
var l=e.getDocumentLeft();
var i=e.getDocumentTop();
var h=0;

if(g&&Math.abs(k.top-i)<j){h+=1;
}else if(Math.abs(k.bottom-i)<j){h+=2;
}
if(g&&Math.abs(k.left-l)<j){h+=4;
}else if(Math.abs(k.right-l)<j){h+=8;
}this.__lM=h;
},__lV:function(e){if(!this.__lM){return;
}this.addState(G);
this.capture();
this.__lN=e.getDocumentLeft();
this.__lO=e.getDocumentTop();
var location=this.getContainerLocation();
var T=this.getBounds();
this.__lP={top:location.top,left:location.left,width:T.width,height:T.height};
if(this.getUseResizeFrame()){this.__lR();
}e.stop();
},__lW:function(e){if(!this.__lM){return;
}if(this.getUseResizeFrame()){this.__lQ().exclude();
}var Q=this.__lS(e);
this.setWidth(Q.width);
this.setHeight(Q.height);
if(this.getResizeAllEdges()){this.setLayoutProperties({left:Q.parentLeft,top:Q.parentTop});
}this.__lM=0;
this.removeState(G);
this.resetCursor();
this.getApplicationRoot().resetGlobalCursor();
this.releaseCapture();
},__lX:function(e){if(!this.__lM){return;
}this.resetCursor();
this.getApplicationRoot().resetGlobalCursor();
this.removeState(r);
if(this.getUseResizeFrame()){this.__lQ().exclude();
}},__lY:function(e){if(this.hasState(G)){var d=this.__lS(e);
if(this.getUseResizeFrame()){var b=this.__lQ();
b.setUserBounds(d.viewportLeft,d.viewportTop,d.width,d.height);
}else{this.setWidth(d.width);
this.setHeight(d.height);
if(this.getResizeAllEdges()){this.setLayoutProperties({left:d.parentLeft,top:d.parentTop});
}}e.stop();
}else if(!this.hasState(u)){this.__lU(e);
var f=this.__lM;
var c=this.getApplicationRoot();

if(f){var a=this.__lT[f];
this.setCursor(a);
c.setGlobalCursor(a);
}else if(this.getCursor()){this.resetCursor();
c.resetGlobalCursor();
}}},__ma:function(e){if(this.getCursor()&&!this.hasState(G)){this.resetCursor();
this.getApplicationRoot().resetGlobalCursor();
}}},destruct:function(){this._disposeObjects(o);
}});
})();
(function(){var b="qx.ui.window.IWindowManager";
qx.Interface.define(b,{members:{setDesktop:function(e){this.assertInterface(e,qx.ui.window.IDesktop);
},changeActiveWindow:function(c,d){},updateStack:function(){},bringToFront:function(a){this.assertInstance(a,qx.ui.window.Window);
},sendToBack:function(f){this.assertInstance(f,qx.ui.window.Window);
}}});
})();
(function(){var k="qx.ui.window.Manager",j="__mm";
qx.Class.define(k,{extend:qx.core.Object,implement:qx.ui.window.IWindowManager,members:{__mm:null,setDesktop:function(m){this.__mm=m;
this.updateStack();
},changeActiveWindow:function(n,o){this.bringToFront(n);
},_minZIndex:1e5,updateStack:function(){qx.ui.core.queue.Widget.add(this);
},syncWidget:function(){this.__mm.unblockContent();
var e=this.__mm.getWindows();
var h=this._minZIndex-1;
var g=false;
var f,d;

for(var i=0,l=e.length;i<l;i++){f=e[i];

if(!f.isVisible()){continue;
}h+=2;
f.setZIndex(h);
if(f.getModal()){this.__mm.blockContent(h-1);
}g=g||f.isActive();
d=f;
}
if(!g&&d){d.setActive(true);
}},bringToFront:function(p){var q=this.__mm.getWindows();
var r=qx.lang.Array.remove(q,p);

if(r){q.push(p);
this.updateStack();
}},sendToBack:function(a){var b=this.__mm.getWindows();
var c=qx.lang.Array.remove(b,a);

if(c){b.unshift(a);
this.updateStack();
}}},destruct:function(){this._disposeObjects(j);
}});
})();
(function(){var m="Boolean",l="qx.event.type.Event",k="captionbar",j="maximize-button",i="_applyCaptionBarChange",h="restore-button",g="minimize-button",f="close-button",d="execute",c="pane",T="title",S="icon",R="maximized",Q="statusbar-text",P="statusbar",O="String",N="active",M="beforeClose",L="beforeMinimize",K="mousedown",t="changeStatus",u="changeIcon",r="excluded",s="_applyCaption",p="_applyActive",q="beforeRestore",n="normal",o="minimize",v="dblclick",w="changeModal",C="_applyShowStatusbar",B="_applyStatus",E="qx.ui.window.Window",D="changeCaption",G="_applyIcon",F="focusout",y="beforeMaximize",J="maximize",I="restore",H="window",x="close",z="changeActive",A="minimized";
qx.Class.define(E,{extend:qx.ui.core.Widget,include:[qx.ui.core.MRemoteChildrenHandling,qx.ui.core.MRemoteLayoutHandling,qx.ui.core.MResizable,qx.ui.core.MMovable,qx.ui.core.MContentPadding],construct:function(bo,bp){arguments.callee.base.call(this);
this._setLayout(new qx.ui.layout.VBox());
this._createChildControl(k);
this._createChildControl(c);
if(bp!=null){this.setIcon(bp);
}
if(bo!=null){this.setCaption(bo);
}this._updateCaptionBar();
this.addListener(K,this._onWindowMouseDown,this,true);
this.addListener(F,this._onWindowFocusOut,this);
qx.core.Init.getApplication().getRoot().add(this);
this.initVisibility();
qx.ui.core.FocusHandler.getInstance().addRoot(this);
},statics:{DEFAULT_MANAGER_CLASS:qx.ui.window.Manager},events:{"beforeClose":l,"close":l,"beforeMinimize":l,"minimize":l,"beforeMaximize":l,"maximize":l,"beforeRestore":l,"restore":l},properties:{appearance:{refine:true,init:H},visibility:{refine:true,init:r},focusable:{refine:true,init:true},active:{check:m,init:false,apply:p,event:z},modal:{check:m,init:false,event:w},caption:{apply:s,event:D,nullable:true},icon:{check:O,nullable:true,apply:G,event:u,themeable:true},status:{check:O,nullable:true,apply:B,event:t},showClose:{check:m,init:true,apply:i,themeable:true},showMaximize:{check:m,init:true,apply:i,themeable:true},showMinimize:{check:m,init:true,apply:i,themeable:true},allowClose:{check:m,init:true,apply:i},allowMaximize:{check:m,init:true,apply:i},allowMinimize:{check:m,init:true,apply:i},showStatusbar:{check:m,init:false,apply:C}},members:{__mn:null,__mo:null,getChildrenContainer:function(){return this.getChildControl(c);
},_forwardStates:{active:true,maximized:true},setLayoutParent:function(parent){{};
arguments.callee.base.call(this,parent);
},_createChildControlImpl:function(U){var V;

switch(U){case P:V=new qx.ui.container.Composite(new qx.ui.layout.HBox());
this._add(V);
V.add(this.getChildControl(Q));
break;
case Q:V=new qx.ui.basic.Label();
V.setContent(this.getStatus());
break;
case c:V=new qx.ui.container.Composite();
this._add(V,{flex:1});
break;
case k:var X=new qx.ui.layout.Grid();
X.setRowFlex(0,1);
X.setColumnFlex(1,1);
V=new qx.ui.container.Composite(X);
this._add(V);
V.addListener(v,this._onCaptionMouseDblClick,this);
this._activateMoveHandle(V);
break;
case S:V=new qx.ui.basic.Image(this.getIcon());
this.getChildControl(k).add(V,{row:0,column:0});
break;
case T:V=new qx.ui.basic.Label(this.getCaption());
V.setWidth(0);
V.setAllowGrowX(true);
var W=this.getChildControl(k);
W.add(V,{row:0,column:1});
break;
case g:V=new qx.ui.form.Button();
V.setFocusable(false);
V.addListener(d,this._onMinimizeButtonClick,this);
this.getChildControl(k).add(V,{row:0,column:2});
break;
case h:V=new qx.ui.form.Button();
V.setFocusable(false);
V.addListener(d,this._onRestoreButtonClick,this);
this.getChildControl(k).add(V,{row:0,column:3});
break;
case j:V=new qx.ui.form.Button();
V.setFocusable(false);
V.addListener(d,this._onMaximizeButtonClick,this);
this.getChildControl(k).add(V,{row:0,column:4});
break;
case f:V=new qx.ui.form.Button();
V.setFocusable(false);
V.addListener(d,this._onCloseButtonClick,this);
this.getChildControl(k).add(V,{row:0,column:6});
break;
}return V||arguments.callee.base.call(this,U);
},_updateCaptionBar:function(){var bd;

if(this.getIcon()){this._showChildControl(S);
}else{this._excludeChildControl(S);
}
if(this.getCaption()){this._showChildControl(T);
}else{this._excludeChildControl(T);
}
if(this.getShowMinimize()){this._showChildControl(g);
bd=this.getChildControl(g);
this.getAllowMinimize()?bd.resetEnabled():bd.setEnabled(false);
}else{this._excludeChildControl(g);
}
if(this.getShowMaximize()){if(this.isMaximized()){this._showChildControl(h);
this._excludeChildControl(j);
}else{this._showChildControl(j);
this._excludeChildControl(h);
}bd=this.getChildControl(j);
this.getAllowMaximize()?bd.resetEnabled():bd.setEnabled(false);
}else{this._excludeChildControl(j);
this._excludeChildControl(h);
}
if(this.getShowClose()){this._showChildControl(f);
bd=this.getChildControl(f);
this.getAllowClose()?bd.resetEnabled():bd.setEnabled(false);
}else{this._excludeChildControl(f);
}},close:function(){if(this.fireNonBubblingEvent(M,qx.event.type.Event,[false,true])){this.hide();
this.fireEvent(x);
}},open:function(){this.show();
this.setActive(true);
this.focus();
},center:function(){var parent=this.getLayoutParent();

if(parent){var bh=parent.getBounds();

if(bh){var bi=this.getSizeHint();
var bg=Math.round((bh.width-bi.width)/2);
var top=Math.round((bh.height-bi.height)/2);

if(top<0){top=0;
}this.moveTo(bg,top);
return;
}}{};
},maximize:function(){if(this.isMaximized()){return;
}var parent=this.getLayoutParent();

if(!parent){return;
}
if(parent.supportsMaximize()){if(this.fireNonBubblingEvent(y,qx.event.type.Event,[false,true])){var bt=this.getLayoutProperties();
this.__mo=bt.left===undefined?0:bt.left;
this.__mn=bt.top===undefined?0:bt.top;
this.setLayoutProperties({left:null,top:null,edge:0});
this.addState(R);
this._updateCaptionBar();
this.fireEvent(J);
}}},minimize:function(){if(this.fireNonBubblingEvent(L,qx.event.type.Event,[false,true])){this.hide();
this.fireEvent(o);
}},restore:function(){if(!this.isMaximized()){return;
}
if(this.fireNonBubblingEvent(q,qx.event.type.Event,[false,true])){var bs=this.__mo;
var top=this.__mn;
this.setLayoutProperties({edge:null,left:bs,top:top});
this.removeState(R);
this._updateCaptionBar();
this.fireEvent(I);
}},moveTo:function(a,top){if(this.isMaximized()){return;
}this.setLayoutProperties({left:a,top:top});
},isMaximized:function(){return this.hasState(R);
},getMode:function(){if(!this.isVisible()){return A;
}else{if(this.isMaximized()){return R;
}else{return n;
}}},_applyActive:function(bq,br){if(br){this.removeState(N);
}else{this.addState(N);
}},_getContentPaddingTarget:function(){return this.getChildControl(c);
},_applyShowStatusbar:function(Y,ba){if(Y){this._showChildControl(P);
}else{this._excludeChildControl(P);
}},_applyCaptionBarChange:function(be,bf){this._updateCaptionBar();
},_applyStatus:function(bj,bk){var bl=this.getChildControl(Q,true);

if(bl){bl.setContent(bj);
}},_applyCaption:function(bb,bc){this.getChildControl(T).setContent(bb);
},_applyIcon:function(bm,bn){this.getChildControl(S).setSource(bm);
},_onWindowEventStop:function(e){e.stopPropagation();
},_onWindowMouseDown:function(e){this.setActive(true);
},_onWindowFocusOut:function(e){if(this.getModal()){return;
}var b=e.getRelatedTarget();

if(b!=null&&!qx.ui.core.Widget.contains(this,b)){this.setActive(false);
}},_onCaptionMouseDblClick:function(e){if(this.getAllowMaximize()){this.isMaximized()?this.restore():this.maximize();
}},_onMinimizeButtonClick:function(e){this.minimize();
this.getChildControl(g).reset();
},_onRestoreButtonClick:function(e){this.restore();
this.getChildControl(h).reset();
},_onMaximizeButtonClick:function(e){this.maximize();
this.getChildControl(j).reset();
},_onCloseButtonClick:function(e){this.close();
this.getChildControl(f).reset();
}}});
})();
(function(){var i="legend",h="frame",g="middle",f="top",e="resize",d="qx.ui.groupbox.GroupBox",c="groupbox",b="_applyLegendPosition";
qx.Class.define(d,{extend:qx.ui.core.Widget,include:[qx.ui.core.MRemoteChildrenHandling,qx.ui.core.MRemoteLayoutHandling,qx.ui.core.MContentPadding],construct:function(q,r){arguments.callee.base.call(this);
this._setLayout(new qx.ui.layout.Canvas);
this._createChildControl(h);
this._createChildControl(i);
if(q!=null){this.setLegend(q);
}
if(r!=null){this.setIcon(r);
}},properties:{appearance:{refine:true,init:c},legendPosition:{check:[f,g],init:g,apply:b,themeable:true}},members:{_createChildControlImpl:function(o){var p;

switch(o){case h:p=new qx.ui.container.Composite();
this._add(p,{left:0,top:6,right:0,bottom:0});
break;
case i:p=new qx.ui.basic.Atom();
p.addListener(e,this._repositionFrame,this);
this._add(p);
break;
}return p||arguments.callee.base.call(this,o);
},_getContentPaddingTarget:function(){return this.getChildControl(h);
},_applyLegendPosition:function(e){if(this.getChildControl(i).getBounds()){this._repositionFrame();
}},_repositionFrame:function(){var k=this.getChildControl(i);
var j=this.getChildControl(h);
var l=k.getBounds().height;
if(this.getLegendPosition()==g){j.setLayoutProperties({"top":Math.round(l/2)});
}else if(this.getLegendPosition()==f){j.setLayoutProperties({"top":l});
}},getChildrenContainer:function(){return this.getChildControl(h);
},setLegend:function(m){var n=this.getChildControl(i);

if(m!==null){n.setLabel(m);
n.show();
}else{n.exclude();
}},getLegend:function(){return this.getChildControl(i).getLabel();
},setIcon:function(a){this.getChildControl(i).setIcon(a);
},getIcon:function(){this.getChildControl(i).getIcon();
}}});
})();
