qx.$$packageData['255e75f7523c']={"locales":{},"resources":{"qx/icon/Tango/16/actions/edit-clear.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-copy.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-cut.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-delete.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-find.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-paste.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-redo.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-select-all.png":[16,16,"png","qx"],"qx/icon/Tango/16/actions/edit-undo.png":[16,16,"png","qx"]},"translations":{"C":{},"de":{"A date:":"Datum:","Command Menu (keyboard shortcuts)":"Command-Menü (Tastenkürzel)","Copy":"Kopieren","Cut":"Aussschneiden","Date format full:":"Vollständiges Datumsformat:","Date format long:":"Langes Datumsformat:","Date format medium:":"Mittellanges Datumsformat:","Date format short:":"kurzes Zeitformat:","Date full:":"Vollständiges Datum:","Date long:":"Langes Datum:","Date medium:":"Mittellanges Datum:","Date short:":"Zeit (kurz):","Delete":"Löschen","Form Elements":"Formular Widgets","Format of %1:":"Format von %1:","Locale Information":"Lokalisierungsinformationen","Locale:":"Sprachkennung:","Localized ComboBox:":"Lokalisierte ComboBox:","Paste":"Einfügen","Redo":"Wiederholen","Search":"Suchen","Search Again":"Weiter suchen","Select All":"Alles auswählen","Territory code:":"Landeskennung:","Time format long:":"Langes Zeitformat:","Time format short:":"kurzes Zeitformat:","Time long:":"Zeit (lang):","Time short:":"Zeit (kurz):","Undo":"Rückgängig","Week start:":"Wochenanfang:","key_full_Alt":"Alt","key_full_Apps":"Kontextmenü","key_full_Backspace":"Rücktaste","key_full_CapsLock":"Feststelltaste","key_full_Control":"Steuerung","key_full_Delete":"Entfernen","key_full_Down":"Pfeil runter","key_full_End":"Ende","key_full_Enter":"Enter","key_full_Escape":"Escape","key_full_Home":"Position 1","key_full_Insert":"Einfügen","key_full_Left":"Pfeil links","key_full_Meta":"Meta","key_full_NumLock":"NumLock","key_full_PageDown":"Bild runter ","key_full_PageUp":"Bild hoch","key_full_Pause":"Pause","key_full_PrintScreen":"Drucken","key_full_Right":"Pfeil rechts","key_full_Scroll":"Rollen","key_full_Shift":"Umschalttaste","key_full_Space":"Leertaste","key_full_Tab":"Tabulator","key_full_Up":"Pfeil hoch","key_full_Win":"Windowstaste","key_short_Alt":"Alt","key_short_Apps":"Kontext","key_short_Backspace":"Rück","key_short_CapsLock":"Feststell","key_short_Control":"Strg","key_short_Delete":"Entf","key_short_Down":"Runter","key_short_End":"Ende","key_short_Enter":"Enter","key_short_Escape":"Esc","key_short_Home":"Pos1","key_short_Insert":"Einfg","key_short_Left":"Links","key_short_Meta":"Meta","key_short_NumLock":"Num","key_short_PageDown":"Bild runter","key_short_PageUp":"Bild hoch","key_short_Pause":"Pause","key_short_PrintScreen":"Druck","key_short_Right":"Rechts ","key_short_Scroll":"Rollen","key_short_Shift":"Umschalt","key_short_Space":"Leer","key_short_Tab":"Tab","key_short_Up":"Hoch","key_short_Win":"Win"},"de_AT":{},"de_DE":{},"en":{},"en_GB":{},"en_US":{},"es":{"A date:":"Una fecha:","Command Menu (keyboard shortcuts)":"Menú de comando (claves del teclado)","Copy":"Copiar","Cut":"Cortar","Date format full:":"Formato de fecha completo:","Date format long:":"Formato de fecha largo:","Date format medium:":"Formato de fecha mediano:","Date format short:":"Formato de hora corto:","Date full:":"Fecha completo:","Date long:":"Fecha largo:","Date medium:":"Fecha mediano:","Date short:":"Hora corto:","Delete":"Borrar","Format of %1:":"Formato de %1:","Locale Information":"Información de la localisación","Locale:":"Localisación:","Localized ComboBox:":"ComboBox:","Paste":"Pegar","Redo":"Rehacer","Search":"Búsqueda","Search Again":"Buscar otra vez","Select All":"Seleccionar todo","Territory code:":"Código regional:","Time format long:":"Formato de hora largo:","Time format short:":"Formato de hora corto:","Time long:":"Hora largo:","Time short:":"Hora corto:","Undo":"Deshacer","Week start:":"Inicio de semana:","key_full_Alt":"Alt","key_full_Apps":"Aplicaciones","key_full_Backspace":"Retroceso","key_full_CapsLock":"Bloqueo Mayúsculas","key_full_Control":"Control","key_full_Delete":"Suprimir","key_full_Down":"Flecha abajo","key_full_End":"Fin","key_full_Enter":"Intro","key_full_Escape":"Escape","key_full_Home":"Inicio","key_full_Insert":"Insertar","key_full_Left":"Flecha izquierda","key_full_Meta":"Meta","key_full_NumLock":"Bloqueo Numérico","key_full_PageDown":"Avanzar Página","key_full_PageUp":"Retroceder Página","key_full_Pause":"Pausa","key_full_PrintScreen":"Imprimir Pantalla","key_full_Right":"Flecha derecha","key_full_Scroll":"Bloq. Despl.","key_full_Shift":"Mayúscula","key_full_Space":"Espacio","key_full_Tab":"Tabulador","key_full_Up":"Flecha arriba","key_full_Win":"Windows","key_short_Alt":"Alt","key_short_Apps":"Aplic","key_short_Backspace":"Retroceso","key_short_CapsLock":"BloqMayús","key_short_Control":"Ctrl","key_short_Control_Mac":"Ctrl","key_short_Delete":"Supr","key_short_Down":"Abajo","key_short_End":"Fin","key_short_Enter":"Intro","key_short_Escape":"Esc","key_short_Home":"Inicio","key_short_Insert":"Insert","key_short_Left":"Izquierda","key_short_Meta":"Meta","key_short_NumLock":"BloqNum","key_short_PageDown":"AvPág","key_short_PageUp":"RePág","key_short_Pause":"Pausa","key_short_PrintScreen":"ImprPant","key_short_Right":"Derecha","key_short_Scroll":"BloqDespl","key_short_Shift":"Mayús","key_short_Space":"Espacio","key_short_Tab":"Tab","key_short_Up":"Arriba","key_short_Win":"Win"},"es_ES":{},"es_MX":{}}};

qx.Part.$$notifyLoad("255e75f7523c", function() {
(function(){var p="String",o="execute",n="qx.ui.menu.Menu",m="_shortcut",l="changeEnabled",k="changeToolTipText",j="Boolean",i="qx.ui.core.Command",h="changeLabel",g="changeMenu",d="changeIcon",f="changeValue",e="_applyShortcut",c="_applyEnabled",b="qx.event.type.Data";
qx.Class.define(i,{extend:qx.core.Object,construct:function(a){qx.core.Object.call(this);
this._shortcut=new qx.bom.Shortcut(a);
this._shortcut.addListener(o,this.execute,this);
},events:{"execute":b},properties:{enabled:{init:true,check:j,event:l,apply:c},shortcut:{check:p,apply:e,nullable:true},label:{check:p,nullable:true,event:h},icon:{check:p,nullable:true,event:d},toolTipText:{check:p,nullable:true,event:k},value:{nullable:true,event:f},menu:{check:n,nullable:true,event:g}},members:{_shortcut:null,_applyEnabled:function(s){this._shortcut.setEnabled(s);
},_applyShortcut:function(r){this._shortcut.setShortcut(r);
},execute:function(q){this.fireDataEvent(o,q);
},toString:function(){return this._shortcut.toString();
}},destruct:function(){this._disposeObjects(m);
}});
})();
(function(){var p="Unidentified",o="Boolean",n="+",m="short",l="keydown",k="",j="Control",h="keypress",g="-",f="PageUp",V="Escape",U="qx.event.type.Data",T="_applyShortcut",S="PrintScreen",R="NumLock",Q="5",P="8",O="execute",N="Meta",M="0",w="2",x="Shift",u="You can only specify one non modifier key!",v="3",s="/",t="Delete",q="String",r="changeEnabled",y="*",z="qx.bom.Shortcut",E="6",D="4",G="1",F="Alt",I="Not a valid key name for a shortcut: ",H="PageDown",B="Whitespaces are not allowed within shortcuts",L="_applyEnabled",K="7",J="a",A="z",C="9";
qx.Class.define(z,{extend:qx.core.Object,construct:function(X){qx.core.Object.call(this);
this.__pc={};
this.__pd=null;

if(X!=null){this.setShortcut(X);
}this.initEnabled();
},events:{"execute":U},properties:{enabled:{init:true,check:o,event:r,apply:L},shortcut:{check:q,apply:T,nullable:true},autoRepeat:{check:o,init:false}},members:{__pc:k,__pd:k,execute:function(bk){this.fireDataEvent(O,bk);
},__pe:function(event){if(this.getEnabled()&&this.__pg(event)){if(!this.isAutoRepeat()){this.execute(event.getTarget());
}event.stop();
}},__pf:function(event){if(this.getEnabled()&&this.__pg(event)){if(this.isAutoRepeat()){this.execute(event.getTarget());
}event.stop();
}},_applyEnabled:function(bi,bj){if(bi){qx.event.Registration.addListener(document.documentElement,l,this.__pe,this);
qx.event.Registration.addListener(document.documentElement,h,this.__pf,this);
}else{qx.event.Registration.removeListener(document.documentElement,l,this.__pe,this);
qx.event.Registration.removeListener(document.documentElement,h,this.__pf,this);
}},_applyShortcut:function(Y,ba){if(Y){if(Y.search(/[\s]+/)!=-1){var bd=B;
this.error(bd);
throw new Error(bd);
}this.__pc={"Control":false,"Shift":false,"Meta":false,"Alt":false};
this.__pd=null;
var bb;
var a=[];

while(Y.length>0&&bb!=-1){bb=Y.search(/[-+]+/);
a.push((Y.length==1||bb==-1)?Y:Y.substring(0,bb));
Y=Y.substring(bb+1);
}var bc=a.length;

for(var i=0;i<bc;i++){var be=this.__pi(a[i]);

switch(be){case j:case x:case N:case F:this.__pc[be]=true;
break;
case p:var bd=I+a[i];
this.error(bd);
throw bd;
default:if(this.__pd){var bd=u;
this.error(bd);
throw bd;
}this.__pd=be;
}}}return true;
},__pg:function(e){var W=this.__pd;

if(!W){return ;
}if((!this.__pc.Shift&&e.isShiftPressed())||(this.__pc.Shift&&!e.isShiftPressed())||(!this.__pc.Control&&e.isCtrlPressed())||(this.__pc.Control&&!e.isCtrlPressed())||(!this.__pc.Meta&&e.isMetaPressed())||(this.__pc.Meta&&!e.isMetaPressed())||(!this.__pc.Alt&&e.isAltPressed())||(this.__pc.Alt&&!e.isAltPressed())){return false;
}
if(W==e.getKeyIdentifier()){return true;
}return false;
},__ph:{esc:V,ctrl:j,print:S,del:t,pageup:f,pagedown:H,numlock:R,numpad_0:M,numpad_1:G,numpad_2:w,numpad_3:v,numpad_4:D,numpad_5:Q,numpad_6:E,numpad_7:K,numpad_8:P,numpad_9:C,numpad_divide:s,numpad_multiply:y,numpad_minus:g,numpad_plus:n},__pi:function(b){var c=qx.event.handler.Keyboard;
var d=p;

if(c.isValidKeyIdentifier(b)){return b;
}
if(b.length==1&&b>=J&&b<=A){return b.toUpperCase();
}b=b.toLowerCase();
var d=this.__ph[b]||qx.lang.String.firstUp(b);

if(c.isValidKeyIdentifier(d)){return d;
}else{return p;
}},toString:function(){var bh=this.__pd;
var bg=[];

for(var bf in this.__pc){if(this.__pc[bf]){bg.push(qx.locale.Key.getKeyName(m,bf));
}}
if(bh){bg.push(qx.locale.Key.getKeyName(m,bh));
}return bg.join(n);
}},destruct:function(){this.setEnabled(false);
this.__pc=this.__pd=null;
}});
})();
(function(){var bw="Control",bv="Left",bu="Meta",bt="Pause",bs="End",br="Down",bq="Ctrl",bp="Home",bo="Apps",bn="Win",bc="Right",bb="Backspace",ba="Space",Y="Up",X="Shift",W="Enter",V="Scroll",U="Alt",T="Escape",S="key_full_Meta",bD="PrintScreen",bE="NumLock",bB="key_short_Alt",bC="key_short_Control_Mac",bz="key_short_Insert",bA="Del",bx="key_full_Enter",by="key_full_Control",bF="qx.locale.Key",bG="Tabulator",bg="key_full_Space",bf="key_short_Meta",bi="key_short_PageUp",bh="key_short_Pause",bk="key_full_Down",bj="key_short_Apps",bm="key_short_Win",bl="key_full_Right",be="key_short_Up",bd="key_full_PageDown",a="key_full_Alt",b="PgDn",c="Esc",d="key_full_Insert",e="key_short_Space",f="key_short_Backspace",g="key_short_Home",h="key_short_Down",i="PgUp",j="_Mac",bK="key_short_CapsLock",bJ="PageUp",bI="key_full_Up",bH="key_full_Home",bO="key_full_Backspace",bN="PageDown",bM="CapsLock",bL="Ins",bQ="key_short_PrintScreen",bP="Tab",C="key_full_Apps",D="key_short_Tab",A="key_short_End",B="_",G="Caps",H="key_short_NumLock",E="Num",F="key_full_Scroll",y="key_short_Left",z="key_short_Scroll",r="key_",q="key_full_Pause",t="key_short_Right",s="key_full_PrintScreen",n="key_full_Win",m="key_full_Control_Mac",p="key_short_Shift",o="key_short_PageDown",l="key_short_Enter",k="key_short_Control",M="Insert",N="key_short_Escape",O="key_full_Tab",P="Print",I="Delete",J="key_full_CapsLock",K="key_full_Escape",L="key_short_Delete",Q="key_full_PageUp",R="key_full_Shift",x="key_full_NumLock",w="key_full_Delete",v="key_full_End",u="key_full_Left";
qx.Class.define(bF,{statics:{getKeyName:function(bR,bS,bT){{};
var bV=r+bR+B+bS;
if(qx.bom.client.Platform.MAC&&bS==bw){bV+=j;
}var bU=qx.locale.Manager.getInstance().translate(bV,[],bT);

if(bU==bV){return qx.locale.Key._keyNames[bV]||bS;
}else{return bU;
}}},defer:function(bW){var bY={};
var bX=qx.locale.Manager;
bY[bX.marktr(f)]=bb;
bY[bX.marktr(D)]=bP;
bY[bX.marktr(e)]=ba;
bY[bX.marktr(l)]=W;
bY[bX.marktr(p)]=X;
bY[bX.marktr(k)]=bq;
bY[bX.marktr(bC)]=bq;
bY[bX.marktr(bB)]=U;
bY[bX.marktr(bK)]=G;
bY[bX.marktr(bf)]=bu;
bY[bX.marktr(N)]=c;
bY[bX.marktr(y)]=bv;
bY[bX.marktr(be)]=Y;
bY[bX.marktr(t)]=bc;
bY[bX.marktr(h)]=br;
bY[bX.marktr(bi)]=i;
bY[bX.marktr(o)]=b;
bY[bX.marktr(A)]=bs;
bY[bX.marktr(g)]=bp;
bY[bX.marktr(bz)]=bL;
bY[bX.marktr(L)]=bA;
bY[bX.marktr(H)]=E;
bY[bX.marktr(bQ)]=P;
bY[bX.marktr(z)]=V;
bY[bX.marktr(bh)]=bt;
bY[bX.marktr(bm)]=bn;
bY[bX.marktr(bj)]=bo;
bY[bX.marktr(bO)]=bb;
bY[bX.marktr(O)]=bG;
bY[bX.marktr(bg)]=ba;
bY[bX.marktr(bx)]=W;
bY[bX.marktr(R)]=X;
bY[bX.marktr(by)]=bw;
bY[bX.marktr(m)]=bw;
bY[bX.marktr(a)]=U;
bY[bX.marktr(J)]=bM;
bY[bX.marktr(S)]=bu;
bY[bX.marktr(K)]=T;
bY[bX.marktr(u)]=bv;
bY[bX.marktr(bI)]=Y;
bY[bX.marktr(bl)]=bc;
bY[bX.marktr(bk)]=br;
bY[bX.marktr(Q)]=bJ;
bY[bX.marktr(bd)]=bN;
bY[bX.marktr(v)]=bs;
bY[bX.marktr(bH)]=bp;
bY[bX.marktr(d)]=M;
bY[bX.marktr(w)]=I;
bY[bX.marktr(x)]=bE;
bY[bX.marktr(s)]=bD;
bY[bX.marktr(F)]=V;
bY[bX.marktr(q)]=bt;
bY[bX.marktr(n)]=bn;
bY[bX.marktr(C)]=bo;
bW._keyNames=bY;
}});
})();
(function(){var o="short",n="long",m="selection[0]",l="medium",k="Cut",j="Copy",h="language",g="Paste",f="full",e="selection[0].selected",bF="Territory code:",bE="icon/16/actions/edit-find.png",bD="Time format short:",bC="Ctrl+V",bB="icon/16/actions/edit-delete.png",bA="icon/16/actions/edit-cut.png",bz="United States",by="Date medium:",bx=".png",bw="Date long:",v="DE",w="en",t="Time format long:",u="Mexico",r="button",s="Locale:",p="AT",q="Undo",D="Date short:",E="Austria",W="Format of %1:",S="Date format short:",bf="changeLocale",ba="Search",br="MX",bl="center",L="Ctrl+X",bv="wide",bt="es",bs="US",J="middle",O="Time short:",Q="A date:",U="name",X="GB",bb="icon",bh="ES",bn="Germany",x="_",y="Date format medium:",N="de",be="F3",bd="Date format full:",bc="Week start:",bj="Ctrl+F",bi="icon/16/actions/edit-paste.png",Y="Del",bg="showcase.page.i18n.Content",a="Date format long:",bm="right",z="icon/16/actions/edit-copy.png",A="country",T="selection[0].countries",b="Spain",d="selection[0].selected.code",I="Locale Information",B="Redo",C="Delete",G="model",V="Ctrl+C",bp="Date full:",bo="Ctrl+A",P="Search Again",bq="Localized ComboBox:",K="Select All",bk="Ctrl+Z",F="Time long:",H="Ctrl+Y",c="Command Menu (keyboard shortcuts)",R="showcase/i18n/",M="Form Elements",bu="Great Britain";
qx.Class.define(bg,{extend:showcase.AbstractContent,include:qx.locale.MTranslation,construct:function(bO){showcase.AbstractContent.call(this,bO);
this.setView(this._createView());
},members:{__Io:null,__Ip:null,_createView:function(){var bQ=new qx.ui.layout.Grid(10,15);
bQ.setColumnFlex(0,1);
bQ.setColumnFlex(1,1);
var bP=new qx.ui.container.Composite(bQ).set({padding:10});
bP.add(this.__Iq(),{row:0,column:0,colSpan:2});
bP.add(this.__Ir(),{row:1,column:0});
bP.add(this.__Is(),{row:1,column:1});
return bP;
},__Iq:function(){var bJ=new qx.ui.form.RadioButtonGroup(new qx.ui.layout.HBox(10).set({alignX:bl}));
var bK=this.__Io=qx.data.marshal.Json.createModel([{language:w,selected:null,countries:[{code:bs,name:bz},{code:X,name:bu}]},{language:bt,selected:null,countries:[{code:bh,name:b},{code:br,name:u}]},{language:N,selected:null,countries:[{code:v,name:bn},{code:p,name:E}]}]);

for(var i=0;i<bK.getLength();i++){bK.getItem(i).setSelected(bK.getItem(i).getCountries().getItem(0));
}var bI=new qx.data.controller.List(null,bJ,h);
this.__Ip=bI;
bI.setDelegate({createItem:function(){return new qx.ui.form.RadioButton().set({show:bb,appearance:r});
}});
bI.setIconPath(h);
bI.setIconOptions({converter:function(bR){return R+bR+bx;
}});
bI.setModel(bK);
bI.getSelection().push(bK.getItem(0));
this.__Ip.bind(d,this,A);
return bJ;
},setCountry:function(bG){if(bG){var bH=this.__Ip.getSelection().getItem(0).getLanguage();
qx.locale.Manager.getInstance().setLocale(bH+x+bG);
}},__Ir:function(){var ce=new qx.ui.layout.Grid(10,10);
ce.setColumnFlex(0,1);
ce.setColumnFlex(1,1);
ce.setColumnAlign(0,bm,J);
var cb=new qx.ui.groupbox.GroupBox(this.tr(M)).set({width:0,minWidth:0});
cb.setLayout(ce);
cb.add(new qx.ui.basic.Label(this.tr(bF)),{row:0,column:0});
var bW=new qx.ui.form.SelectBox();
var cd=new qx.data.controller.List(null,bW,U);
this.__Ip.bind(T,cd,G);
this.__Ip.bind(e,cd,m);
cd.bind(m,this.__Ip,e);
cb.add(bW,{row:0,column:1});
cb.add(new qx.ui.basic.Label(this.tr(bq)),{row:1,column:0});
var bS=new qx.ui.form.ComboBox();
bS.add(new qx.ui.form.ListItem(this.tr(k)));
bS.add(new qx.ui.form.ListItem(this.tr(g)));
bS.add(new qx.ui.form.ListItem(this.tr(j)));
cb.add(bS,{row:1,column:1});
var cg=new qx.ui.basic.Label(this.tr(Q));
cb.add(cg,{row:2,column:0});
var cj=new qx.ui.form.DateField();
cj.setValue(new Date);
cb.add(cj,{row:2,column:1});
var ca=new qx.ui.control.DateChooser;
cb.add(ca,{row:3,column:0,colSpan:2});
var bY=new qx.ui.core.Command(bk);
var cc=new qx.ui.core.Command(H);
var bT=new qx.ui.core.Command(L);
var bX=new qx.ui.core.Command(V);
var ck=new qx.ui.core.Command(bC);
var cl=new qx.ui.core.Command(Y);
var ci=new qx.ui.core.Command(bo);
var bU=new qx.ui.core.Command(bj);
var ch=new qx.ui.core.Command(be);
var bV=new qx.ui.menu.Menu;
bV.add(new qx.ui.menu.Button(this.tr(q),null,bY));
bV.add(new qx.ui.menu.Button(this.tr(B),null,cc));
bV.add(new qx.ui.menu.Separator());
bV.add(new qx.ui.menu.Button(this.tr(k),bA,bT));
bV.add(new qx.ui.menu.Button(this.tr(j),z,bX));
bV.add(new qx.ui.menu.Button(this.tr(g),bi,ck));
bV.add(new qx.ui.menu.Button(this.tr(C),bB,cl));
bV.add(new qx.ui.menu.Button(this.tr(K),null,ci));
bV.add(new qx.ui.menu.Separator());
bV.add(new qx.ui.menu.Button(this.tr(ba),null,bU));
bV.add(new qx.ui.menu.Button(this.tr(P),null,ch));
var cf=new qx.ui.form.MenuButton(this.tr(c),null,bV);
cb.add(cf,{row:4,column:0,colSpan:2});
return cb;
},__Is:function(){var bM=new qx.ui.groupbox.GroupBox(this.tr(I),bE).set({width:0,minWidth:0,allowGrowY:true});
bM.setLayout(new qx.ui.layout.Grow());
var bN=new qx.ui.basic.Label().set({rich:true,allowGrowX:true,allowGrowY:true});
bM.add(bN);
var bL=[];
bL.push("<table id='i18n'><tr><td>");

for(var i=0;i<15;i++){bL.push("");
bL.push("</td><td>");
bL.push("");
bL.push("</td></tr><td>");
}bL.push("");
bL.push("</td><td>");
bL.push("");
bL.push("</td></tr></table>");
this.updateLocaleInformation=function(){var i=0;
bL[(i++*2)+1]=this.tr(s);
bL[(i++*2)+1]=qx.locale.Manager.getInstance().getLocale();
bL[(i++*2)+1]=this.tr(bF);
bL[(i++*2)+1]=qx.locale.Manager.getInstance().getTerritory();
bL[(i++*2)+1]=this.tr(S);
bL[(i++*2)+1]=qx.locale.Date.getDateFormat(o);
bL[(i++*2)+1]=this.tr(D);
bL[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(o))).format(new Date());
bL[(i++*2)+1]=this.tr(y);
bL[(i++*2)+1]=qx.locale.Date.getDateFormat(l);
bL[(i++*2)+1]=this.tr(by);
bL[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(l))).format(new Date());
bL[(i++*2)+1]=this.tr(a);
bL[(i++*2)+1]=qx.locale.Date.getDateFormat(n);
bL[(i++*2)+1]=this.tr(bw);
bL[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(n))).format(new Date());
bL[(i++*2)+1]=this.tr(bd);
bL[(i++*2)+1]=qx.locale.Date.getDateFormat(f);
bL[(i++*2)+1]=this.tr(bp);
bL[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getDateFormat(f))).format(new Date());
bL[(i++*2)+1]=this.tr(bD);
bL[(i++*2)+1]=qx.locale.Date.getTimeFormat(o);
bL[(i++*2)+1]=this.tr(O);
bL[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(o))).format(new Date());
bL[(i++*2)+1]=this.tr(t);
bL[(i++*2)+1]=qx.locale.Date.getTimeFormat(n);
bL[(i++*2)+1]=this.tr(F);
bL[(i++*2)+1]=(new qx.util.format.DateFormat(qx.locale.Date.getTimeFormat(n))).format(new Date());
bL[(i++*2)+1]=this.tr(bc);
bL[(i++*2)+1]=qx.locale.Date.getDayName(bv,qx.locale.Date.getWeekStart());
bL[(i++*2)+1]=this.tr(W,10000.12);
bL[(i++*2)+1]=qx.util.format.NumberFormat.getInstance().format(10000.12);
bN.setValue(bL.join(""));
};
qx.locale.Manager.getInstance().addListener(bf,this.updateLocaleInformation,this);
this.updateLocaleInformation();
return bM;
}}});
})();

});