qx.$$packageData['3b43ba73526b']={"locales":{},"resources":{},"translations":{}};

qx.Part.$$notifyLoad("3b43ba73526b", function() {
(function(){var s="pressed",r="abandoned",q="hovered",p="checked",o="Space",n="Enter",m="mouseup",l="mousedown",k="Boolean",j="_applyValue",c="mouseover",i="mouseout",g="qx.ui.form.ToggleButton",b="keydown",a="changeValue",f="button",d="keyup",h="execute";
qx.Class.define(g,{extend:qx.ui.basic.Atom,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IBooleanForm,qx.ui.form.IExecutable],construct:function(t,u){qx.ui.basic.Atom.call(this,t,u);
this.addListener(c,this._onMouseOver);
this.addListener(i,this._onMouseOut);
this.addListener(l,this._onMouseDown);
this.addListener(m,this._onMouseUp);
this.addListener(b,this._onKeyDown);
this.addListener(d,this._onKeyUp);
this.addListener(h,this._onExecute,this);
},properties:{appearance:{refine:true,init:f},focusable:{refine:true,init:true},value:{check:k,nullable:true,event:a,apply:j,init:false}},members:{_applyValue:function(v,w){v?this.addState(p):this.removeState(p);
},_onExecute:function(e){this.toggleValue();
},_onMouseOver:function(e){if(e.getTarget()!==this){return;
}this.addState(q);

if(this.hasState(r)){this.removeState(r);
this.addState(s);
}},_onMouseOut:function(e){if(e.getTarget()!==this){return;
}this.removeState(q);

if(this.hasState(s)){if(!this.getValue()){this.removeState(s);
}this.addState(r);
}},_onMouseDown:function(e){if(!e.isLeftPressed()){return;
}this.capture();
this.removeState(r);
this.addState(s);
e.stopPropagation();
},_onMouseUp:function(e){this.releaseCapture();

if(this.hasState(r)){this.removeState(r);
}else if(this.hasState(s)){this.execute();
}this.removeState(s);
e.stopPropagation();
},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case n:case o:this.removeState(r);
this.addState(s);
e.stopPropagation();
}},_onKeyUp:function(e){if(!this.hasState(s)){return;
}
switch(e.getKeyIdentifier()){case n:case o:this.removeState(r);
this.execute();
this.removeState(s);
e.stopPropagation();
}}}});
})();
(function(){var b="checkbox",a="qx.ui.form.CheckBox";
qx.Class.define(a,{extend:qx.ui.form.ToggleButton,include:[qx.ui.form.MForm,qx.ui.form.MModelProperty],implement:[qx.ui.form.IForm,qx.ui.form.IModel],construct:function(c){{};
qx.ui.form.ToggleButton.call(this,c);
this.setValue(false);
},properties:{appearance:{refine:true,init:b},allowGrowX:{refine:true,init:false}}});
})();
(function(){var h="auto",g="textarea",f="Boolean",d="qx.ui.form.TextArea",c="_applyWrap",b="Integer",a="mousewheel";
qx.Class.define(d,{extend:qx.ui.form.AbstractField,construct:function(n){qx.ui.form.AbstractField.call(this,n);
this.initWrap();
this.addListener(a,this._onMousewheel,this);
},properties:{wrap:{check:f,init:true,apply:c},appearance:{refine:true,init:g},singleStep:{check:b,init:20}},members:{_onMousewheel:function(e){var i=this.getContentElement();
var scrollY=i.getScrollY();
i.scrollToY(scrollY+e.getWheelDelta()*this.getSingleStep());
var j=i.getScrollY();

if(j!=scrollY){e.stop();
}},_createInputElement:function(){return new qx.html.Input(g,{overflowX:h,overflowY:h});
},_applyWrap:function(l,m){this.getContentElement().setWrap(l);
},_getContentHint:function(){var k=qx.ui.form.AbstractField.prototype._getContentHint.call(this);
k.height=k.height*4;
k.width=this._getTextSize().width*20;
return k;
}}});
})();
(function(){var k="value",j="placeholder",h="Button",g="CheckBox:",f="TextArea:",e="Boolean",d="RepeatButton:",c="execute",b="Website 2",a="Text",T="ToggleButton",S="password",R="RadioButton 3",Q="showcase.page.form.Content",P="Button:",O="ComboBox:",N="ToggleButton:",M="Options",L="RadioButton",K="0",r="MenuButton:",s="PasswordField:",p="SplitButton",q="Buttons",n="",o="RadioButtons:",l="dd.mm.YYYY",m="List:",t="SplitButton:",u="Option",B="RadioButton 1",z="Spinner:",E="Selection",D="DateField:",G="RadioButton 2",F="Number",w="CheckBox",J="SelectBox:",I="Website 3",H="MenuButton",v="Website 1",x="Slider:",y="TextField:",A="Item ",C="RadioButtonGroup:";
qx.Class.define(Q,{extend:showcase.AbstractContent,construct:function(U){showcase.AbstractContent.call(this,U);
this.setView(this._createView());
},members:{_createView:function(){var bu=new qx.ui.layout.Grid(20,5);
bu.setColumnFlex(0,1);
bu.setColumnFlex(1,1);
var bE=new qx.ui.container.Composite(bu);
bE.setPadding(10);
var bm=1;
var bf=new qx.ui.groupbox.GroupBox(a);
bf.setLayout(new qx.ui.layout.Grid(8,8));
bf.setWidth(290);
bE.add(bf,{row:0,column:0});
var bD=new qx.ui.form.TextField();
bD.setPlaceholder(j);
bD.setTabIndex(bm++);
var bo=new qx.ui.basic.Label(y);
bo.setBuddy(bD);
bf.add(bo,{row:0,column:0});
bf.add(bD,{row:0,column:1});
var bl=new qx.ui.form.PasswordField();
bl.setTabIndex(bm++);
bl.setPlaceholder(S);
bo=new qx.ui.basic.Label(s);
bo.setBuddy(bl);
bf.add(bo,{row:1,column:0});
bf.add(bl,{row:1,column:1});
var bg=new qx.ui.form.TextArea();
bg.setTabIndex(bm++);
bg.setPlaceholder(j);
bo=new qx.ui.basic.Label(f);
bo.setBuddy(bg);
bf.add(bo,{row:2,column:0});
bf.add(bg,{row:2,column:1});
var bh=new qx.ui.form.ComboBox();
bh.setTabIndex(bm++);
bh.setPlaceholder(j);
bo=new qx.ui.basic.Label(O);
bo.setBuddy(bh);
bf.add(bo,{row:3,column:0});
bf.add(bh,{row:3,column:1});
this.__Jc(bh);
var bw=new qx.ui.form.DateField();
bw.setTabIndex(bm++);
bw.setPlaceholder(l);
bo=new qx.ui.basic.Label(D);
bo.setBuddy(bw);
bf.add(bo,{row:4,column:0});
bf.add(bw,{row:4,column:1});
var bn=new qx.ui.groupbox.GroupBox(E);
bn.setLayout(new qx.ui.layout.Grid(8,8));
bn.setWidth(290);
bE.add(bn,{row:1,column:0,rowSpan:2});
var bx=new qx.ui.form.SelectBox();
bx.setTabIndex(bm++);
bo=new qx.ui.basic.Label(J);
bo.setBuddy(bx);
bn.add(bo,{row:0,column:0});
bn.add(bx,{row:0,column:1});
this.__Jc(bx);
var bC=new qx.ui.form.List();
bC.setTabIndex(bm++);
bC.setHeight(60);
bC.setWidth(155);
bo=new qx.ui.basic.Label(m);
bo.setBuddy(bC);
bn.add(bo,{row:1,column:0});
bn.add(bC,{row:1,column:1});
this.__Jc(bC);
var bv=new qx.ui.form.RadioButtonGroup();
bv.add(new qx.ui.form.RadioButton(B).set({tabIndex:bm++}));
bv.add(new qx.ui.form.RadioButton(G).set({tabIndex:bm++}));
bv.add(new qx.ui.form.RadioButton(R).set({tabIndex:bm++}));
bo=new qx.ui.basic.Label(C);
bo.setBuddy(bv);
bn.add(bo,{row:2,column:0});
bn.add(bv,{row:2,column:1});
var bA=new qx.ui.groupbox.GroupBox(q);
bA.setLayout(new qx.ui.layout.Grid(8,8));
bA.setWidth(250);
bE.add(bA,{row:0,column:1});
var bB=new qx.ui.form.Button(h).set({tabIndex:bm++});
bo=new qx.ui.basic.Label(P);
bo.setBuddy(bB);
bA.add(bo,{row:0,column:0});
bA.add(bB,{row:0,column:1});
var bj=new qx.ui.form.ToggleButton(T).set({tabIndex:bm++});
bo=new qx.ui.basic.Label(N);
bo.setBuddy(bj);
bA.add(bo,{row:1,column:0});
bA.add(bj,{row:1,column:1});
var br=new qx.ui.form.RepeatButton(K).set({tabIndex:bm++});
bo=new qx.ui.basic.Label(d);
bo.setBuddy(br);
bA.add(bo,{row:2,column:0});
bA.add(br,{row:2,column:1});
var bs=new qx.ui.form.MenuButton(H,null,this.__Jd()).set({tabIndex:bm++});
bo=new qx.ui.basic.Label(r);
bo.setBuddy(bs);
bA.add(bo,{row:3,column:0});
bA.add(bs,{row:3,column:1});
var bk=new qx.ui.form.SplitButton(p,null,this.__Je()).set({tabIndex:bm++});
bo=new qx.ui.basic.Label(t);
bo.setBuddy(bk);
bA.add(bo,{row:4,column:0});
bA.add(bk,{row:4,column:1});
br.addListener(c,function(){var bH=parseInt(br.getLabel())+1;
br.setLabel(bH.toString());
});
var bi=new qx.ui.groupbox.GroupBox(e);
bi.setLayout(new qx.ui.layout.Grid(8,8));
bi.setWidth(250);
bE.add(bi,{row:1,column:1});
var by=new qx.ui.form.CheckBox(w).set({tabIndex:bm++});
bo=new qx.ui.basic.Label(g);
bo.setBuddy(by);
bi.add(bo,{row:0,column:0});
bi.add(by,{row:0,column:1});
var bq=new qx.ui.form.RadioButton(L).set({tabIndex:bm++});
bi.add(new qx.ui.basic.Label(o),{row:1,column:0});
bi.add(bq,{row:1,column:1});
var bz=new qx.ui.groupbox.GroupBox(F);
bz.setLayout(new qx.ui.layout.Grid(8,8));
bz.setWidth(250);
bE.add(bz,{row:2,column:1});
var bp=new qx.ui.form.Spinner(0,50,100).set({tabIndex:bm++});
bo=new qx.ui.basic.Label(z);
bo.setBuddy(bp);
bz.add(bo,{row:0,column:0});
bz.add(bp,{row:0,column:1});
var bt=new qx.ui.form.Slider().set({tabIndex:bm++});
bt.setWidth(130);
bo=new qx.ui.basic.Label(x);
bo.setBuddy(bt);
bz.add(bo,{row:1,column:0});
bz.add(bt,{row:1,column:1});
bt.bind(k,bp,k);
bp.bind(k,bt,k);
return bE;
},__Jc:function(bF){for(var i=0;i<10;i++){var bG=new qx.ui.form.ListItem(A+i);
bF.add(bG);
}},__Jd:function(){var ba=new qx.ui.menu.Menu;

for(var i=0;i<3;i++){ba.add(new qx.ui.menu.RadioButton(u+i));
}var bd=new qx.ui.form.RadioGroup;
bd.add.apply(bd,ba.getChildren());
var bc=new qx.ui.menu.Menu();

for(var i=0;i<3;i++){var be=new qx.ui.menu.Button(h+i);
bc.add(be);
}var bb=new qx.ui.menu.Button(M,n,null,ba);
bc.addSeparator();
bc.add(bb);
return bc;
},__Je:function(){var V=new qx.ui.menu.Menu;
var Y=new qx.ui.menu.Button(v);
var W=new qx.ui.menu.Button(b);
var X=new qx.ui.menu.Button(I);
V.add(Y);
V.add(W);
V.add(X);
return V;
}}});
})();
(function(){var k="button",j="hovered",i="pressed",h="arrow",g="Enter",f="Space",d="abandoned",c="both",b="String",a="changeVisibility",A="splitbutton",z="changeShow",y="mouseout",x="keydown",w="execute",v="_applyMenu",u="icon",t="mouseover",s="keyup",r="qx.ui.menu.Menu",p="_applyIcon",q="label",n="_applyShow",o="changeMenu",l="_applyLabel",m="qx.ui.form.SplitButton";
qx.Class.define(m,{extend:qx.ui.core.Widget,include:[qx.ui.core.MExecutable],implement:[qx.ui.form.IExecutable],construct:function(N,O,P,Q){qx.ui.core.Widget.call(this);
this._setLayout(new qx.ui.layout.HBox);
this._createChildControl(h);
this.addListener(t,this._onMouseOver,this,true);
this.addListener(y,this._onMouseOut,this,true);
this.addListener(x,this._onKeyDown);
this.addListener(s,this._onKeyUp);
if(N!=null){this.setLabel(N);
}
if(O!=null){this.setIcon(O);
}
if(P!=null){this.setMenu(P);
}
if(Q!=null){this.setCommand(Q);
}},properties:{appearance:{refine:true,init:A},focusable:{refine:true,init:true},label:{apply:l,nullable:true,check:b},icon:{check:b,apply:p,nullable:true,themeable:true},show:{init:c,check:[c,q,u],themeable:true,inheritable:true,apply:n,event:z},menu:{check:r,nullable:true,apply:v,event:o}},members:{__zi:null,_createChildControlImpl:function(R){var S;

switch(R){case k:S=new qx.ui.form.Button;
S.addListener(w,this._onButtonExecute,this);
S.setFocusable(false);
this._addAt(S,0,{flex:1});
break;
case h:S=new qx.ui.form.MenuButton;
S.setFocusable(false);
this._addAt(S,1);
break;
}return S||qx.ui.core.Widget.prototype._createChildControlImpl.call(this,R);
},_forwardStates:{hovered:1,focused:1},_applyLabel:function(G,H){var I=this.getChildControl(k);
G==null?I.resetLabel():I.setLabel(G);
},_applyIcon:function(J,K){var L=this.getChildControl(k);
J==null?L.resetIcon():L.setIcon(J);
},_applyMenu:function(B,C){var D=this.getChildControl(h);

if(B){D.resetEnabled();
D.setMenu(B);
B.setOpener(this);
B.addListener(a,this._onChangeMenuVisibility,this);
}else{D.setEnabled(false);
D.resetMenu();
}
if(C){C.removeListener(a,this._onChangeMenuVisibility,this);
C.resetOpener();
}},_applyShow:function(T,U){},_onMouseOver:function(e){e.stopPropagation();
this.addState(j);
delete this.__zi;
},_onMouseOut:function(e){e.stopPropagation();
if(!this.hasState(j)){return;
}var F=e.getRelatedTarget();

if(qx.ui.core.Widget.contains(this,F)){return;
}var E=this.getMenu();

if(E&&E.isVisible()){this.__zi=true;
return;
}this.removeState(j);
},_onKeyDown:function(e){var V=this.getChildControl(k);

switch(e.getKeyIdentifier()){case g:case f:V.removeState(d);
V.addState(i);
}},_onKeyUp:function(e){var M=this.getChildControl(k);

switch(e.getKeyIdentifier()){case g:case f:if(M.hasState(i)){M.removeState(d);
M.removeState(i);
M.execute();
}}},_onButtonExecute:function(e){this.execute();
},_onChangeMenuVisibility:function(e){if(!this.getMenu().isVisible()&&this.__zi){this.removeState(j);
}}}});
})();
(function(){var bb="textfield",ba="",Y="downbutton",X="upbutton",W="Number",V="inner",U="PageUp",T="Boolean",S="changeValue",R="Down",bA="Up",bz="execute",by="PageDown",bx="changeLocale",bw="qx.dynlocale",bv="on",bu="_applyEditable",bt="_applyWrap",bs="keydown",br="\-]",bi="mousewheel",bj="_applyValue",bg="number",bh="_applyMinimum",be="qx.util.format.NumberFormat",bf="[0-9",bc="keyup",bd="spinner",bk="this._checkValue(value)",bl="_applyMaximum",bn="changeNumberFormat",bm="changeMaximum",bp="changeMinimum",bo="_applyNumberFormat",bq="qx.ui.form.Spinner";
qx.Class.define(bq,{extend:qx.ui.core.Widget,implement:[qx.ui.form.INumberForm,qx.ui.form.IRange,qx.ui.form.IForm],include:[qx.ui.core.MContentPadding,qx.ui.form.MForm],construct:function(x,y,z){qx.ui.core.Widget.call(this);
var A=new qx.ui.layout.Grid();
A.setColumnFlex(0,1);
A.setRowFlex(0,1);
A.setRowFlex(1,1);
this._setLayout(A);
this.addListener(bs,this._onKeyDown,this);
this.addListener(bc,this._onKeyUp,this);
this.addListener(bi,this._onMouseWheel,this);

if(qx.core.Variant.isSet(bw,bv)){qx.locale.Manager.getInstance().addListener(bx,this._onChangeLocale,this);
}this._createChildControl(bb);
this._createChildControl(X);
this._createChildControl(Y);
if(x!=null){this.setMinimum(x);
}
if(z!=null){this.setMaximum(z);
}
if(y!==undefined){this.setValue(y);
}else{this.initValue();
}},properties:{appearance:{refine:true,init:bd},focusable:{refine:true,init:true},singleStep:{check:W,init:1},pageStep:{check:W,init:10},minimum:{check:W,apply:bh,init:0,event:bp},value:{check:bk,nullable:true,apply:bj,init:0,event:S},maximum:{check:W,apply:bl,init:100,event:bm},wrap:{check:T,init:false,apply:bt},editable:{check:T,init:true,apply:bu},numberFormat:{check:be,apply:bo,nullable:true},allowShrinkY:{refine:true,init:false}},members:{__yt:null,__yu:false,__yv:false,_createChildControlImpl:function(H){var I;

switch(H){case bb:I=new qx.ui.form.TextField();
I.setFilter(this._getFilterRegExp());
I.addState(V);
I.setWidth(40);
I.setFocusable(false);
I.addListener(S,this._onTextChange,this);
this._add(I,{column:0,row:0,rowSpan:2});
break;
case X:I=new qx.ui.form.RepeatButton();
I.addState(V);
I.setFocusable(false);
I.addListener(bz,this._countUp,this);
this._add(I,{column:1,row:0});
break;
case Y:I=new qx.ui.form.RepeatButton();
I.addState(V);
I.setFocusable(false);
I.addListener(bz,this._countDown,this);
this._add(I,{column:1,row:1});
break;
}return I||qx.ui.core.Widget.prototype._createChildControlImpl.call(this,H);
},_getFilterRegExp:function(){var q=qx.locale.Number.getDecimalSeparator(qx.locale.Manager.getInstance().getLocale());
var p=qx.locale.Number.getGroupSeparator(qx.locale.Manager.getInstance().getLocale());
var o=ba;
var m=ba;

if(this.getNumberFormat()!==null){o=this.getNumberFormat().getPrefix()||ba;
m=this.getNumberFormat().getPostfix()||ba;
}var n=new RegExp(bf+qx.lang.String.escapeRegexpChars(q)+qx.lang.String.escapeRegexpChars(p)+qx.lang.String.escapeRegexpChars(o)+qx.lang.String.escapeRegexpChars(m)+br);
return n;
},_forwardStates:{focused:true,invalid:true},tabFocus:function(){var g=this.getChildControl(bb);
g.getFocusElement().focus();
g.selectAllText();
},_applyMinimum:function(bC,bD){if(this.getMaximum()<bC){this.setMaximum(bC);
}
if(this.getValue()<bC){this.setValue(bC);
}else{this._updateButtons();
}},_applyMaximum:function(s,t){if(this.getMinimum()>s){this.setMin(s);
}
if(this.getValue()>s){this.setValue(s);
}else{this._updateButtons();
}},_applyEnabled:function(P,Q){qx.ui.core.Widget.prototype._applyEnabled.call(this,P,Q);
this._updateButtons();
},_checkValue:function(L){return typeof L===bg&&L>=this.getMinimum()&&L<=this.getMaximum();
},_applyValue:function(u,v){var w=this.getChildControl(bb);
this._updateButtons();
this.__yt=u;
if(u!==null){if(this.getNumberFormat()){w.setValue(this.getNumberFormat().format(u));
}else{w.setValue(u+ba);
}}else{w.setValue(ba);
}},_applyEditable:function(a,b){var c=this.getChildControl(bb);

if(c){c.setReadOnly(!a);
}},_applyWrap:function(B,C){this._updateButtons();
},_applyNumberFormat:function(M,N){var O=this.getChildControl(bb);
O.setFilter(this._getFilterRegExp());
this.getNumberFormat().addListener(bn,this._onChangeNumberFormat,this);
this._applyValue(this.__yt,undefined);
},_getContentPaddingTarget:function(){return this.getChildControl(bb);
},_updateButtons:function(){var k=this.getChildControl(X);
var j=this.getChildControl(Y);
var l=this.getValue();

if(!this.getEnabled()){k.setEnabled(false);
j.setEnabled(false);
}else{if(this.getWrap()){k.setEnabled(true);
j.setEnabled(true);
}else{if(l!==null&&l<this.getMaximum()){k.setEnabled(true);
}else{k.setEnabled(false);
}if(l!==null&&l>this.getMinimum()){j.setEnabled(true);
}else{j.setEnabled(false);
}}}},_onKeyDown:function(e){switch(e.getKeyIdentifier()){case U:this.__yu=true;
case bA:this.getChildControl(X).press();
break;
case by:this.__yv=true;
case R:this.getChildControl(Y).press();
break;
default:return ;
}e.stopPropagation();
e.preventDefault();
},_onKeyUp:function(e){switch(e.getKeyIdentifier()){case U:this.getChildControl(X).release();
this.__yu=false;
break;
case bA:this.getChildControl(X).release();
break;
case by:this.getChildControl(Y).release();
this.__yv=false;
break;
case R:this.getChildControl(Y).release();
break;
}},_onMouseWheel:function(e){if(e.getWheelDelta()>0){this._countDown();
}else{this._countUp();
}e.stop();
},_onTextChange:function(e){var J=this.getChildControl(bb);
var K;
if(this.getNumberFormat()){try{K=this.getNumberFormat().parse(J.getValue());
}catch(bB){}}if(K===undefined){K=parseFloat(J.getValue(),10);
}if(!isNaN(K)){if(K>this.getMaximum()){J.setValue(this.getMaximum()+ba);
return;
}else if(K<this.getMinimum()){J.setValue(this.getMinimum()+ba);
return;
}this.setValue(K);
}else{this._applyValue(this.__yt,undefined);
}},_onChangeLocale:function(F){if(this.getNumberFormat()!==null){this.setNumberFormat(this.getNumberFormat());
var G=this.getChildControl(bb);
G.setFilter(this._getFilterRegExp());
G.setValue(this.getNumberFormat().format(this.getValue()));
}},_onChangeNumberFormat:function(h){var i=this.getChildControl(bb);
i.setFilter(this._getFilterRegExp());
i.setValue(this.getNumberFormat().format(this.getValue()));
},_countUp:function(){if(this.__yu){var f=this.getValue()+this.getPageStep();
}else{var f=this.getValue()+this.getSingleStep();
}if(this.getWrap()){if(f>this.getMaximum()){var d=this.getMaximum()-f;
f=this.getMinimum()+d;
}}this.gotoValue(f);
},_countDown:function(){if(this.__yv){var E=this.getValue()-this.getPageStep();
}else{var E=this.getValue()-this.getSingleStep();
}if(this.getWrap()){if(E<this.getMinimum()){var D=this.getMinimum()+E;
E=this.getMaximum()-D;
}}this.gotoValue(E);
},gotoValue:function(r){return this.setValue(Math.min(this.getMaximum(),Math.max(this.getMinimum(),r)));
}},destruct:function(){if(qx.core.Variant.isSet(bw,bv)){qx.locale.Manager.getInstance().removeListener(bx,this._onChangeLocale,this);
}}});
})();
(function(){var c="password",b="qx.ui.form.PasswordField",a="input";
qx.Class.define(b,{extend:qx.ui.form.TextField,members:{_createInputElement:function(){var d=new qx.html.Input(c);
d.addListener(a,this._onHtmlInput,this);
return d;
}}});
})();

});